import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const YAOCAOYU_SECTION_TITLE = "藥草喻品第五";

export const T0264_JUAN_3_YAOCAOYU_REMAINDER_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-003-073",
    category: "調伏平等",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如來於諸眾生調伏平等。迦葉！譬如日月光明照於世間，若作善、若作不善，若高處住、若下處住，若香、若臭，諸處平等光照無偏。",
    anchorText: "如來於諸眾生調伏平等",
    note: "经文以日月光明无偏，说明如来调伏众生平等。",
    occurrence: 1,
  },
  {
    id: "t0264-003-074",
    category: "平等轉法",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如來、應、正遍知一切種智心之光明，於諸五趣眾生受生之中，如其信解大乘、緣覺乘、聲聞乘中，為說正法平等而轉，如來智慧亦無增減，如其福智聚集而生。",
    anchorText: "為說正法平等而轉",
    note: "如来随众生信解说法，正法平等而转，佛智无有增减。",
    occurrence: 1,
  },
  {
    id: "t0264-003-075",
    category: "唯一佛乘",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "迦葉！無有三乘，唯彼眾生別異行故，施設三乘。",
    anchorText: "無有三乘，唯彼眾生別異行故",
    note: "本段明说三乘是随众生行相差别而施设，究竟并无三乘差别。",
    occurrence: 1,
  },
  {
    id: "t0264-003-076",
    category: "唯一大乘",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如是，迦葉！此唯一乘所謂大乘，無有二乘及以三乘。",
    anchorText: "此唯一乘所謂大乘",
    note: "瓦器譬喻之后，经文归结为唯一大乘，无二乘三乘。",
    occurrence: 1,
  },
  {
    id: "t0264-003-077",
    category: "一涅槃義",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "若覺諸法體等涅槃，彼亦唯一無有二、三。",
    anchorText: "若覺諸法體等涅槃",
    note: "若觉诸法体等涅槃，即知涅槃唯一，无二无三。",
    occurrence: 1,
  },
  {
    id: "t0264-003-078",
    category: "有智解義",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "迦葉！以彼義故，我當為汝作喻，以此喻故有智丈夫則當解我所說之義。",
    anchorText: "有智丈夫則當解我所說之義",
    note: "佛以譬喻说明深义，使有智慧者能理解所说义理。",
    occurrence: 1,
  },
  {
    id: "t0264-003-079",
    category: "良醫悲愍",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "時彼良醫，於生盲所發生悲愍，興起如是方便思惟，以彼方便詣雪山王，到已上頂，或下入、或傍行，周遍觀察，既觀察已，得四種藥，",
    anchorText: "於生盲所發生悲愍",
    note: "良医为生盲起悲愍、求药疗治，譬喻如来以悲方便救治众生。",
    occurrence: 1,
  },
  {
    id: "t0264-003-080",
    category: "盲者得眼",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "時彼生盲，以方便相應故即時得眼，彼得眼已，內、外、遠、近、日、月、光明、星宿諸色皆悉得見，",
    anchorText: "以方便相應故即時得眼",
    note: "生盲因方便疗治即得眼见，譬喻众生因佛方便得见真实。",
    occurrence: 1,
  },
  {
    id: "t0264-003-081",
    category: "思法斷惑",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "若欲如是，汝應當住空閑山窟，坐思念法及斷煩惱，當得神通，具足功德。",
    anchorText: "坐思念法及斷煩惱",
    note: "仙人劝其住空闲处、思念法、断烦恼，得神通并具足功德。",
    occurrence: 1,
  },
  {
    id: "t0264-003-082",
    category: "悲愍眾生",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如是無明闇冥眾生流轉中住，唯有如來超出三界，發生悲愍，亦如慈父愛念一子，發悲愍已下入三界，見彼眾生，於流轉輪中行，不如實知出離流轉。",
    anchorText: "唯有如來超出三界，發生悲愍",
    note: "经文说明如来超出三界而悲愍流转众生，如慈父念独子。",
    occurrence: 1,
  },
  {
    id: "t0264-003-083",
    category: "方便三乘",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "佛以佛眼而觀見之，見已了知此等眾生，先世作善，少瞋厚欲，少欲厚瞋，或有少智，或有巧慧，或有成熟清淨，或有邪見，彼等眾生，佛為方便巧說三乘；",
    anchorText: "彼等眾生，佛為方便巧說三乘",
    note: "佛以佛眼了知众生差别，故方便善巧说三乘。",
    occurrence: 1,
  },
  {
    id: "t0264-003-084",
    category: "四門滅苦",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如四種藥，即是空、無相、無願、涅槃門；當如是見。隨所服藥，其病隨滅，即是空、無相、無願、解脫門，正修念已，無明當滅，無明滅故行滅，乃至唯有大苦聚滅。",
    anchorText: "隨所服藥，其病隨滅",
    note: "以四药譬四门，正修念时无明灭，乃至大苦聚灭。",
    occurrence: 1,
  },
  {
    id: "t0264-003-085",
    category: "解脫繫縛",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "割斷流轉煩惱繫縛，解脫煩惱，解脫六趣及以三界，",
    anchorText: "割斷流轉煩惱繫縛",
    note: "经文以割断流转烦恼系缚，说明声闻缘觉解脱烦恼、六趣与三界。",
    occurrence: 1,
  },
  {
    id: "t0264-003-086",
    category: "菩提教化",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "爾時如來為彼說法，若於諸法未能悉到，何處彼有究竟涅槃？彼等，佛以菩提教化，發菩提心，不住流轉，不到涅槃，",
    anchorText: "佛以菩提教化，發菩提心",
    note: "如来进一步以菩提教化，使其发菩提心，不住流转也不停于小涅槃。",
    occurrence: 1,
  },
  {
    id: "t0264-003-087",
    category: "見甚深法",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "彼悟三界十方空寂，皆如化夢及以焰響，觀見諸法不生、不滅，不縛、不解、不闇、不明，如是見甚深法，",
    anchorText: "彼悟三界十方空寂",
    note: "经文说明悟三界十方空寂、诸法不生不灭，即见甚深法。",
    occurrence: 1,
  },
  {
    id: "t0264-003-088",
    category: "智光平等",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如來智慧光，平等如日月，教化諸眾生，無增亦無減。",
    anchorText: "如來智慧光，平等如日月",
    note: "偈颂重申如来智慧光平等如日月，教化众生无增无减。",
    occurrence: 1,
  },
  {
    id: "t0264-003-089",
    category: "決定佛乘",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如眾生無餘，如來隨別欲，雖說乘差別，決定唯佛乘；",
    anchorText: "雖說乘差別，決定唯佛乘",
    note: "佛虽随众生别欲说乘差别，究竟决定唯佛乘。",
    occurrence: 1,
  },
  {
    id: "t0264-003-090",
    category: "遠離法我",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "若人能知空，遠離於法我；彼知佛世尊，所得正真覺。",
    anchorText: "若人能知空，遠離於法我",
    note: "能知空、远离法我者，能知佛所得正真觉。",
    occurrence: 1,
  },
  {
    id: "t0264-003-091",
    category: "覺諸法者",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "安置處中智，說名緣覺者；空智教化已，顯名為聲聞；若能覺諸法，說名正遍知。",
    anchorText: "若能覺諸法，說名正遍知",
    note: "偈颂以中智、空智与觉诸法说明不同名相，归向正遍知。",
    occurrence: 1,
  },
  {
    id: "t0264-003-092",
    category: "良醫療盲",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "大醫於生盲，為其入慈愍，往詣雪山已，上下及傍行；求得於良藥，順入色味處，如是等四種，和合而療治；",
    anchorText: "大醫於生盲，為其入慈愍",
    note: "偈颂以大医慈愍生盲、求药疗治，重显如来悲智方便。",
    occurrence: 1,
  },
  {
    id: "t0264-003-093",
    category: "大良醫說法",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如來大良醫，出生悲愍體，彼以善方便，演說寂正法。無上佛覺智，演說最勝乘，",
    anchorText: "如來大良醫，出生悲愍體",
    note: "偈颂直接称如来为大良医，以善方便演说寂正法与最胜乘。",
    occurrence: 1,
  },
  {
    id: "t0264-003-094",
    category: "思惟得通",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "汝欲一切智，出生於神通，若住空閑處，神通則可出，思惟清淨法，則當得神通。",
    anchorText: "思惟清淨法，則當得神通",
    note: "偈颂明示住空闲处、思惟清净法，则能得神通。",
    occurrence: 1,
  },
  {
    id: "t0264-003-095",
    category: "具足功德",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "受義詣空閑，思惟入靜室，得五神通已，不久具功德；",
    anchorText: "得五神通已，不久具功德",
    note: "受义后至空闲静室思惟，得五神通，不久具足功德。",
    occurrence: 1,
  },
  {
    id: "t0264-003-096",
    category: "方便說道",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "諸佛說彼時，小息非涅槃，是諸佛方便，為說如此道。",
    anchorText: "小息非涅槃，是諸佛方便",
    note: "诸佛说明小息并非究竟涅槃，这是诸佛方便所说之道。",
    occurrence: 1,
  },
  {
    id: "t0264-003-097",
    category: "教化眾生",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "若離一切智，無有發涅槃，三世智無邊，六度行清淨；空寂及無相，作願亦除捨，及以菩提心，別法向涅槃。及四種梵行，四攝亦讚說，為教化眾生，勝仙而說此。",
    anchorText: "為教化眾生，勝仙而說此",
    note: "偈中连说一切智、六度、菩提心、四梵行、四摄，皆为教化众生而说。",
    occurrence: 1,
  },
  {
    id: "t0264-003-098",
    category: "如幻法觀",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "若復知諸法，自性如幻夢，不實似芭蕉，亦與音響等。及知彼自性，三界無餘殘，不縛亦不解，不知於滅度。",
    anchorText: "若復知諸法，自性如幻夢",
    note: "偈颂以幻梦、芭蕉、音响譬诸法自性，示深观诸法之义。",
    occurrence: 1,
  },
  {
    id: "t0264-003-099",
    category: "一乘平等",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "諸法皆平等空，無有異體者，此亦無所見，不觀於一法。彼見大智者，法身無餘殘，無有於三乘，一乘此中有。諸法皆平等，平等常等等，知如是智已，涅槃甘露安。",
    anchorText: "無有於三乘，一乘此中有",
    note: "结偈归于诸法平等空、无三乘而有一乘，知此智已得涅槃甘露安。",
    occurrence: 1,
  },
];