import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const CONGDIYONGCHU_SECTION_TITLE = "從地踊出品第十四";

export const T0264_JUAN_5_CONGDIYONGCHU_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-005-030",
    category: "灭后护持广说此经",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "世尊！若聽我等，於佛滅後，在此娑婆世界，勤加精進，護持、讀誦、書寫、供養是經典者，當於此土而廣說之。",
    anchorText: "勤加精進，護持、讀誦、書寫、供養是經典者",
    note: "他方菩萨发愿佛灭后在娑婆世界护持、读诵、书写、供养并广说此经。",
  },
  {
    id: "t0264-005-031",
    category: "娑婆菩萨能护此经",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "我娑婆世界，自有六萬恒河沙等菩薩摩訶薩，一一菩薩，各有六萬恒河沙眷屬，是諸人等，能於我滅後護持、讀誦、廣說此經。",
    anchorText: "能於我滅後護持、讀誦、廣說此經",
    note: "佛明示娑婆世界自有无量菩萨，能于佛灭后护持、读诵、广说此经。",
  },
  {
    id: "t0264-005-032",
    category: "地涌菩萨相好光明",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "有無量千萬億菩薩摩訶薩同時踊出，是諸菩薩身皆金色，三十二相，無量光明，先盡在此娑婆世界之下此界虛空中住。",
    anchorText: "身皆金色，三十二相，無量光明",
    note: "地涌菩萨以金色身、三十二相、无量光明显示其深厚德相。",
  },
  {
    id: "t0264-005-033",
    category: "无量唱导眷属",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "一一菩薩，皆是大眾唱導之首，各將六萬恒河沙眷屬，況將五萬、四萬、三萬、二萬、一萬恒河沙等眷屬者，況復乃至一恒河沙，半恒河沙，四分之一，乃至千萬億那由他分之一；況復千萬億那由他眷屬，況復億萬眷屬，況復千萬、百萬乃至一萬，況復一千一百乃至一十，況復將五、四、三、二、一弟子者，況復單己，樂遠離行，如是等比，無量無邊，算數譬喻所不能知。",
    anchorText: "皆是大眾唱導之首",
    note: "经文以无量眷属与唱导之首赞显地涌菩萨众的广大不可思议。",
  },
  {
    id: "t0264-005-034",
    category: "礼佛赞佛欣乐瞻仰",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "是諸菩薩從地出已，各詣虛空七寶妙塔，多寶如來、釋迦牟尼佛所，到已向二世尊，頭面禮足，及至諸寶樹下師子座上佛所，亦皆作禮右遶三匝，合掌恭敬，以諸菩薩種種讚法而以讚歎，住在一面，欣樂瞻仰於二世尊。",
    anchorText: "合掌恭敬，以諸菩薩種種讚法而以讚歎",
    note: "地涌菩萨出已礼拜二世尊，合掌恭敬，以种种赞法赞叹。",
  },
  {
    id: "t0264-005-035",
    category: "佛神力令久如暂",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "是諸菩薩摩訶薩，從初踊出，以諸菩薩種種讚法，而讚於佛，如是時間，經五十小劫；是時釋迦牟尼佛默然而坐，及諸四眾亦皆默然，五十小劫，佛神力故，令諸大眾謂如半日。",
    anchorText: "五十小劫，佛神力故，令諸大眾謂如半日",
    note: "地涌菩萨长时赞佛，佛神力令大众感受五十小劫如半日。",
  },
  {
    id: "t0264-005-036",
    category: "四导师为上首",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "是菩薩眾中，有四導師：一名上行，二名無邊行，三名淨行，四名安立行，是四菩薩，於其眾中，最為上首唱導之師",
    anchorText: "最為上首唱導之師",
    note: "上行、无边行、净行、安立行四菩萨为地涌众中上首唱导。",
  },
  {
    id: "t0264-005-037",
    category: "众生信受入如来慧",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "此諸眾生，始見我身，聞我所說，即皆信受，入如來慧，除先修習，學小乘者，如是之人，我今亦令得聞是經，入於佛慧。",
    anchorText: "聞我所說，即皆信受，入如來慧",
    note: "佛说众生闻佛所说即能信受入如来慧；修学小乘者也令闻此经入佛慧。",
  },
  {
    id: "t0264-005-038",
    category: "闻深智信行随喜",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "善哉善哉！大雄世尊！諸眾生等，易可化度。能問諸佛，甚深智慧，聞已信行，我等隨喜。",
    anchorText: "聞已信行，我等隨喜",
    note: "菩萨赞叹众生能问诸佛甚深智慧，闻已信行，菩萨随喜。",
  },
  {
    id: "t0264-005-039",
    category: "如来赞随喜心",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "於時世尊讚歎上首諸大菩薩：「善哉，善哉！善男子！汝等能於如來發隨喜心。」",
    anchorText: "汝等能於如來發隨喜心",
    note: "佛亲自赞叹上首菩萨能于如来发随喜心。",
  },
  {
    id: "t0264-005-040",
    category: "地涌众一心求佛道",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "如是諸大眾，一心求佛道，是諸大師等，六萬恒河沙，俱來供養佛，及護持是經。",
    anchorText: "一心求佛道",
    note: "弥勒偈中赞地涌大众一心求佛道，并来供养佛、护持此经。",
  },
  {
    id: "t0264-005-041",
    category: "护持此经供养佛",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "俱來供養佛，及護持是經。",
    anchorText: "俱來供養佛，及護持是經",
    note: "偈文明说地涌菩萨俱来供养佛，并护持此经。",
  },
  {
    id: "t0264-005-042",
    category: "大威德精进菩萨",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "是諸大威德，精進菩薩眾，誰為其說法，教化而成就？從誰初發心？稱揚何佛法？受持行誰經？修習何佛道？",
    anchorText: "是諸大威德，精進菩薩眾",
    note: "弥勒以大威德、精进赞叹地涌菩萨，并追问其受持修行因缘。",
  },
  {
    id: "t0264-005-043",
    category: "问大事显佛智慧",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "善哉，善哉！阿逸多！乃能問佛如是大事，汝等當共一心，被精進鎧，發堅固意，如來今欲顯發宣示諸佛智慧，諸佛自在神通之力，諸佛師子奮迅之力，諸佛威猛大勢之力。",
    anchorText: "如來今欲顯發宣示諸佛智慧",
    note: "佛赞弥勒能问大事，并劝大众一心精进，欲宣示诸佛智慧与神通力。",
  },
  {
    id: "t0264-005-044",
    category: "昔未闻法今当得闻",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "當精進一心，我欲說此事，勿得有疑悔，佛智叵思議。汝今出信力，住於忍善中，昔所未聞法，今皆當得聞。",
    anchorText: "昔所未聞法，今皆當得聞",
    note: "佛劝大众精进一心、出信力、住忍善中，未闻之法今将得闻。",
  },
  {
    id: "t0264-005-045",
    category: "佛语真实智慧难量",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "我今安慰汝，勿得懷疑懼，佛無不實語，智慧不可量，所得第一法，甚深叵分別；如是今當說，汝等一心聽。",
    anchorText: "佛無不實語，智慧不可量",
    note: "佛安慰大众勿疑惧，明示佛语真实、智慧不可量，劝一心听受。",
  },
  {
    id: "t0264-005-046",
    category: "地涌菩萨读诵通利",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "此諸菩薩皆於是娑婆世界之下此界虛空中住，於諸經典讀誦、通利、思惟、分別、正憶念。",
    anchorText: "於諸經典讀誦、通利、思惟、分別、正憶念",
    note: "佛说明地涌菩萨久住娑婆界下，读诵通利、思惟分别、正忆念诸经典。",
  },
  {
    id: "t0264-005-047",
    category: "静处精进求无上慧",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "阿逸多！是諸善男子等，不樂在眾多有所說，常樂靜處，勤行精進，未曾休息，亦不依止人、天而住，常樂深智，無有障礙，亦常樂於諸佛之法，一心精進求無上慧。",
    anchorText: "常樂靜處，勤行精進，未曾休息",
    note: "地涌菩萨常乐静处、勤行精进、乐深智与诸佛法，一心求无上慧。",
  },
  {
    id: "t0264-005-048",
    category: "久修佛慧住不退",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "是諸大菩薩，從無數劫來，修習佛智慧，悉是我所化，令發大道心。",
    anchorText: "從無數劫來，修習佛智慧",
    note: "佛偈说明地涌菩萨从无数劫来修习佛智慧，由佛教化而发大道心。",
  },
  {
    id: "t0264-005-049",
    category: "精进求慧说法无畏",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "如是諸子等，學習我道法，晝夜常精進，為求佛道故，在娑婆世界，下方空中住，志念力堅固，常勤求智慧，說種種妙法，其心無所畏。",
    anchorText: "志念力堅固，常勤求智慧",
    note: "佛赞地涌诸子学习佛道，昼夜精进、志念坚固、勤求智慧，说种种妙法无所畏。",
  },
  {
    id: "t0264-005-050",
    category: "发心不退悉当成佛",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "得成最正覺，轉無上法輪，爾乃教化之，令初發道心，今皆住不退，悉當得成佛。",
    anchorText: "令初發道心，今皆住不退，悉當得成佛",
    note: "佛明说地涌菩萨由其教化初发道心，今皆住不退，悉当成佛。",
  },
  {
    id: "t0264-005-051",
    category: "久远教化真实可信",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "我今說實語，汝等一心信，我從久遠來，教化是等眾。",
    anchorText: "我從久遠來，教化是等眾",
    note: "佛以实语说明久远以来教化地涌菩萨，劝大众一心信受。",
  },
  {
    id: "t0264-005-052",
    category: "久修菩萨道人中希有",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "如此大眾諸菩薩等，已於無量千萬億劫，為佛道故，勤行精進，善入出住無量百千萬億三昧，得大神通，久修梵行，善能次第集諸善法，巧於問答，人中之寶，一切世間甚為希有。",
    anchorText: "已於無量千萬億劫，為佛道故，勤行精進",
    note: "弥勒赞叹地涌菩萨久远勤行精进、善入三昧、得大神通，是人中之宝。",
  },
  {
    id: "t0264-005-053",
    category: "解疑令未来不生疑",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "唯然世尊，願為解說除我等疑，及未來世諸善男子，聞此事已亦不生疑。",
    anchorText: "聞此事已亦不生疑",
    note: "弥勒请佛解说，以除当会与未来善男子闻此事后的疑惑。",
  },
  {
    id: "t0264-005-054",
    category: "疑不信者堕恶道警策",
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    text: "若有於此經，生疑不信者，即當墮惡道，願今為解說，是無量菩薩，云何於少時，教化令發心，而住不退地？",
    anchorText: "若有於此經，生疑不信者，即當墮惡道",
    note: "品末偈以疑不信此经的恶道果报作警策，并请求佛解说令众开解。",
  },
];