import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const ANLEXING_SECTION_TITLE = "安樂行品第十三";

export const T0264_JUAN_5_ANLEXING_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-005-001",
    category: "恶世护持读诵说经",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "世尊！是諸菩薩，甚為難有，敬順佛故，發大誓願，於後惡世護持、讀誦、說是《法華經》。",
    anchorText: "於後惡世護持、讀誦、說是《法華經》",
    note: "文殊赞叹诸菩萨因敬顺佛而发愿，在后恶世护持、读诵、宣说此经。",
  },
  {
    id: "t0264-005-002",
    category: "安住四法能说此经",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "若菩薩摩訶薩，於後惡世欲說是經，當安住四法：一者、安住菩薩行處、親近處，能為眾生演說是經。",
    anchorText: "於後惡世欲說是經，當安住四法",
    note: "佛明示后恶世欲说此经者，应安住四法，方能为众生演说。",
  },
  {
    id: "t0264-005-003",
    category: "忍辱柔和安住行处",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "若菩薩摩訶薩，住忍辱地，柔和善順，而不卒暴，心亦不驚；又復於法無所行，而觀諸法如實相，亦不行不分別，是名菩薩摩訶薩行處。",
    anchorText: "住忍辱地，柔和善順",
    note: "以忍辱、柔和、善顺及观诸法实相为菩萨行处。",
  },
  {
    id: "t0264-005-004",
    category: "无怖畏心说经",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "若有菩薩，於後惡世，無怖畏心，欲說是經；應入行處，及親近處。",
    anchorText: "於後惡世，無怖畏心，欲說是經",
    note: "经文指出后恶世欲说此经，应入行处与亲近处，以成无怖畏心。",
  },
  {
    id: "t0264-005-005",
    category: "无所希求而为说法",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "若是人等，以好心來，到菩薩所，為聞佛道；菩薩則以，無所畏心，不懷悕望，而為說法。",
    anchorText: "菩薩則以，無所畏心",
    note: "对好心来求闻佛道者，菩萨无所畏惧、不怀希求而为说法。",
  },
  {
    id: "t0264-005-006",
    category: "入行处近处说经无怯",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "若有比丘，於我滅後，入是行處，及親近處，說斯經時，無有怯弱。",
    anchorText: "入是行處，及親近處，說斯經時",
    note: "灭后能入行处与亲近处者，说此经时无有怯弱。",
  },
  {
    id: "t0264-005-007",
    category: "禅定观法安隐演说",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "菩薩有時，入於靜室，以正憶念，隨義觀法；從禪定起，為諸國王，王子臣民，婆羅門等，開化演暢，說斯經典，其心安隱，無有怯弱。",
    anchorText: "開化演暢，說斯經典，其心安隱",
    note: "由静室正念观法、从禅定起而开化演说，心安隐无怯弱。",
  },
  {
    id: "t0264-005-008",
    category: "大乘解说令得一切种智",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "諸有聽者不逆其意，有所難問，不以小乘法答，但以大乘而為解說，令得一切種智。",
    anchorText: "但以大乘而為解說",
    note: "面对难问不以小乘作答，而以大乘解说，令得一切种智。",
  },
  {
    id: "t0264-005-009",
    category: "方便譬喻使众发心入道",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "若有難問，隨義而答，因緣譬喻，敷演分別；以是方便，皆使發心，漸漸增益，入於佛道。",
    anchorText: "以是方便，皆使發心",
    note: "以因缘譬喻随义回答，使听众发心、渐增益而入佛道。",
  },
  {
    id: "t0264-005-010",
    category: "愿成佛道令众亦尔为大利",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "但一心念，說法因緣，願成佛道，令眾亦爾，是則大利，安樂供養。",
    anchorText: "願成佛道，令眾亦爾",
    note: "一心念说法因缘，愿自他同成佛道，经中称为大利、安乐供养。",
  },
  {
    id: "t0264-005-011",
    category: "演说妙法无忧无怖",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "我滅度後，若有比丘，能演說斯，《妙法華經》，心無嫉恚，諸惱障礙，亦無憂愁，及罵詈者；又無怖畏，加刀杖等，亦無擯出，安住忍故。",
    anchorText: "能演說斯，《妙法華經》",
    note: "灭后能演说此经并安住忍者，心无嫉恚障碍、无忧愁罵詈怖畏等。",
  },
  {
    id: "t0264-005-012",
    category: "安乐行功德说不能尽",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "智者如是，善修其心，能住安樂，如我上說；其人功德，千億萬劫。算數譬喻，說不能盡。",
    anchorText: "其人功德，千億萬劫",
    note: "善修其心而住安乐者，其功德经千亿万劫以算数譬喻也说不能尽。",
  },
  {
    id: "t0264-005-013",
    category: "末世受持读诵离嫉诳",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "又文殊師利！菩薩摩訶薩，於後末世法欲滅時，受持、讀誦斯經典者，無懷嫉妬、諂誑之心，亦勿輕罵學佛道者，求其長短。",
    anchorText: "於後末世法欲滅時，受持、讀誦斯經典者",
    note: "后末世法欲灭时受持读诵此经，应离嫉妒谄诳与轻骂求短。",
  },
  {
    id: "t0264-005-014",
    category: "平等说法顺法不偏",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "於一切眾生平等說法，以順法故，不多、不少，乃至深愛法者，亦不為多說。",
    anchorText: "於一切眾生平等說法",
    note: "依顺正法，于一切众生平等说法，不因亲疏爱憎而增减。",
  },
  {
    id: "t0264-005-015",
    category: "第三安乐行得同学大众听受",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "文殊師利！是菩薩摩訶薩，於後末世法欲滅時，有成就是第三安樂行者，說是法時，無能惱亂得好同學，共讀誦是經，亦得大眾而來聽受，聽已能持，持已能誦，誦已能說，說已能書；若使人書，供養經卷，恭敬尊重讚歎。",
    anchorText: "說是法時，無能惱亂得好同學",
    note: "成就第三安乐行者，说法无能恼乱，得善同学与大众听受，并能持诵说写、供养经卷。",
  },
  {
    id: "t0264-005-016",
    category: "一心安乐行为众所敬",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "第三法如是，智者應守護；一心安樂行，無量眾所敬。",
    anchorText: "一心安樂行，無量眾所敬",
    note: "偈中劝智者守护第三法，一心安乐行，为无量众所敬。",
  },
  {
    id: "t0264-005-017",
    category: "慈悲引导令住此法",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "其人雖不問、不信、不解是經，我得阿耨多羅三藐三菩提時，隨在何地，以神通力、智慧力，引之令得住是法中。",
    anchorText: "以神通力、智慧力，引之令得住是法中",
    note: "持经菩萨对不信不解者起悲愿，将来以神通力、智慧力引导令住此法。",
  },
  {
    id: "t0264-005-018",
    category: "第四安乐行说法无过诸天卫护",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "文殊師利！是菩薩摩訶薩，於如來滅後有成就此第四法者，說是法時無有過失，常為比丘、比丘尼、優婆塞、優婆夷，國王、王子、大臣、人民、婆羅門、居士等，供養、恭敬、尊重、讚歎；虛空諸天為聽法故，亦常隨侍，若在聚落、城邑、空閑、林中，有人來欲難問者，諸天晝、夜常為法故，而衛護之；能令聽者皆得歡喜。",
    anchorText: "說是法時無有過失",
    note: "成就第四法者说法无过，受四众国王人民等供养赞叹，诸天随侍卫护，令听者欢喜。",
  },
  {
    id: "t0264-005-019",
    category: "诸佛神力所护",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "所以者何？此經是一切過去、未來、現在諸佛神力所護故。",
    anchorText: "此經是一切過去、未來、現在諸佛神力所護",
    note: "经文说明此经为过去、未来、现在一切诸佛神力所护。",
  },
  {
    id: "t0264-005-020",
    category: "名字难闻见持更难",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "文殊師利！是《法華經》，於無量國中，乃至名字不可得聞，何況得見受持、讀誦。",
    anchorText: "於無量國中，乃至名字不可得聞",
    note: "此经在无量国中连名字尚难闻，何况得见、受持、读诵。",
  },
  {
    id: "t0264-005-021",
    category: "能令众生至一切智",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "此《法華經》，能令眾生至一切智，一切世間多怨難信，先所未說而今說之。",
    anchorText: "能令眾生至一切智",
    note: "此经能令众生至一切智，虽世间难信，佛今宣说。",
  },
  {
    id: "t0264-005-022",
    category: "如来第一甚深之说",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "文殊師利！此《法華經》，是諸如來第一之說，於諸說中最為甚深，末後賜與，如彼強力之王，久護明珠，今乃與之。",
    anchorText: "是諸如來第一之說",
    note: "佛称此经为诸如来第一之说，于诸说中最为甚深，如王末后赐明珠。",
  },
  {
    id: "t0264-005-023",
    category: "诸佛秘密之藏经中最上",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "文殊師利！此《法華經》，諸佛如來祕密之藏，於諸經中最在其上，長夜守護不妄宣說，始於今日乃與汝等而敷演之。",
    anchorText: "諸佛如來祕密之藏",
    note: "此经为诸佛如来秘密之藏，于诸经中最上，长夜守护，今乃敷演。",
  },
  {
    id: "t0264-005-024",
    category: "忍辱哀愍能说佛赞经",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "常行忍辱，哀愍一切；乃能演說，佛所讚經。",
    anchorText: "乃能演說，佛所讚經",
    note: "偈中以常行忍辱、哀愍一切为能演说佛所赞经的条件。",
  },
  {
    id: "t0264-005-025",
    category: "读经者现世安稳众生乐见",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "我滅度後，求佛道者，欲得安隱，演說斯經，應當親近，如是四法，讀是經者，常無憂惱，又無病痛，顏色鮮白；不生貧窮，卑賤醜陋，眾生樂見，如慕賢聖；天諸童子，以為給使；刀杖不加，毒不能害；若人惡罵，口則閉塞，遊行無畏，如師子王。",
    anchorText: "欲得安隱，演說斯經",
    note: "欲安稳演说此经者应亲近四法；读经者得无忧恼病痛、众生乐见、天童给使、刀毒不害、游行无畏等益。",
  },
  {
    id: "t0264-005-026",
    category: "智慧光明梦见妙事",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "智慧光明，如日之照；若於夢中，但見妙事，見諸如來，坐師子座；諸比丘眾，圍遶說法；又見龍神，阿脩羅等，數如恒沙，恭敬合掌，自見其身，而為說法；",
    anchorText: "智慧光明，如日之照",
    note: "读持说经者智慧光明如日，梦中见诸如来、比丘围绕说法，乃至自见为众说法。",
  },
  {
    id: "t0264-005-027",
    category: "闻法欢喜得陀罗尼不退智",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "佛為四眾，說無上法，見身處中，合掌讚佛，聞法歡喜，而為供養；得陀羅尼，證不退智。佛知其心，深入佛道，即為授記，成最正覺。",
    anchorText: "聞法歡喜，而為供養",
    note: "梦中闻佛说无上法而欢喜供养，得陀罗尼、证不退智，并蒙佛授记成正觉。",
  },
  {
    id: "t0264-005-028",
    category: "山林修善证实相见十方佛",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "又見自身，在山林中，修習善法，證諸實相，深入禪定，見十方佛。",
    anchorText: "修習善法，證諸實相",
    note: "善梦中见自身山林修习善法、证诸实相、深入禅定、见十方佛。",
  },
  {
    id: "t0264-005-029",
    category: "恶世说第一法得大利",
    sectionTitle: ANLEXING_SECTION_TITLE,
    text: "若後惡世中，說是第一法，是人得大利，如上諸功德。",
    anchorText: "說是第一法，是人得大利",
    note: "本品结偈总摄：后恶世中说此第一法者，得大利，如上诸功德。",
  },
];
