import type { FaliuMeritBenefit } from "./faliu-merit-benefits";
import { T0263_JUAN_9_MIAOHOU_MERIT_BENEFITS } from "./faliu-merit-benefits-t0263-juan9-miaohou";
import { T0263_JUAN_9_YAOWANG_MERIT_BENEFITS } from "./faliu-merit-benefits-t0263-juan9-yaowang";

const CHANGBEIQINGMAN_SECTION_TITLE = "常被輕慢品第十九";
const RULAISHENZU_SECTION_TITLE = "如來神足行品第二十";

const T0263_JUAN_9_BASE_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-001",
    category: "持經福德",
    text: "設復有人，聞是經卷受持諷誦，為他人說廣解其誼，獲上妙福。如斯疇類，佛所諮嗟，眼耳鼻口身意清淨，而無蔽礙。",
    anchorText: "聞是經卷受持諷誦，為他人說廣解其誼",
    note: "本品开端直接说明闻经、受持、讽诵、为人解说所得上妙福与六根清净。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-002",
    category: "護經警策",
    text: "其有比丘、比丘尼、清信士、清信女，持斯經典，假使四部罵詈誹謗，出麁獷辭訶制止之，罪不可限。",
    anchorText: "持斯經典，假使四部罵詈誹謗",
    note: "经文明示毁谤持经者罪不可限，显示护持此经的严肃性。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-003",
    category: "不輕眾生",
    text: "我身終不輕慢諸賢人，普當學菩薩高行，得至如來、至真、等正覺。",
    anchorText: "我身終不輕慢諸賢人",
    note: "常被轻慢菩萨的核心劝修，是不轻众生并劝入菩萨高行、趣向正觉。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-004",
    category: "忍辱發心",
    text: "勿行輕慢，修忍辱心、發菩薩意。",
    anchorText: "勿行輕慢，修忍辱心",
    note: "面对诃骂时仍劝人修忍辱心、发菩萨意，是本品清楚的修行要点。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-005",
    category: "聞經增益",
    text: "斯一大士臨欲壽終，得聞寂趣音王如來講《正法華經》二十頌本深妙之誼億百千事。",
    anchorText: "得聞寂趣音王如來講《正法華經》",
    note: "常被轻慢菩萨临终得闻《正法华经》深义，成为后文功德转起的关键。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-006",
    category: "受經功德",
    text: "仁當受經，亦當逮得如前淨眼，耳鼻口身意亦清淨，已獲斯淨，更即增益二十億姟壽，逮得定意，復為眾人講是經典。",
    anchorText: "仁當受經，亦當逮得如前淨眼",
    note: "经中赞受经者得六根清净、增益寿命、得定意，并能为众讲说经典。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-007",
    category: "聞法發心",
    text: "見此大士微妙神力、辯才慧力、善權道力，皆來歸伏敬宗為友，聽聞經法。是等輩類，餘不可計無數億人，便立無上正真道意。",
    anchorText: "皆來歸伏敬宗為友，聽聞經法",
    note: "昔日轻毁者见德归伏、听闻经法，无数人由此建立无上道意。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-008",
    category: "值佛聞經",
    text: "時彼大士壽沒之後，便值二十百千億如來正真，此諸世尊，皆為講說《正法華經》。",
    anchorText: "便值二十百千億如來正真",
    note: "受持此经的因缘续感值遇诸佛，诸佛皆为讲说《正法华经》。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-009",
    category: "六根清淨",
    text: "亦復從聞《正法華經》，受持諷誦為四輩說，在所生處，常自然獲眼淨耳淨鼻淨口淨身淨意淨，視聽洞徹，鼻通口辯，身能輕舉，意覩眾生心，普為四輩演斯經典分別其誼。",
    anchorText: "受持諷誦為四輩說，在所生處",
    note: "闻经、受持、讽诵、为四众说法，感得所生处六根清净并能继续宣说此经。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-010",
    category: "成佛因緣",
    text: "常被輕慢大士，供養奉事若干億百千數如來已，復更值無數億百千如來，亦復從受《正法華經》，以是德本，自致無上正真之道成最正覺。",
    anchorText: "亦復從受《正法華經》，以是德本",
    note: "经文把从诸佛受《正法华经》的德本，直接连到成就无上正觉。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-011",
    category: "速成正覺",
    text: "假使爾時設不受是《正法華經》，不持諷誦為人說者，不能疾逮無上正真道成最正覺。備從過去諸佛世尊，聞此經典，受持諷誦廣為人說致最正覺。",
    anchorText: "不受是《正法華經》，不持諷誦為人說者",
    note: "佛以自身因缘说明受持、讽诵、为人广说此经，是疾成正觉的重要因缘。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-012",
    category: "毀謗果報",
    text: "又諸四部輕彼大士罵詈形笑不自改者，二十億千劫所生之處，常不值佛不聞法聲，又萬劫中墮無可大地獄，拷掠燒炙痛不可言。",
    anchorText: "輕彼大士罵詈形笑不自改者",
    note: "本品以强烈果报警策轻毁持经菩萨与正法者。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-013",
    category: "教化得益",
    text: "罪已畢竟從地獄出，以彼大士教化之故，令發無上正真道意，皆得神通，慧無罣礙，今悉現在。",
    anchorText: "以彼大士教化之故",
    note: "即使曾轻毁者，罪毕之后仍因菩萨教化而发无上道意、得神通与无碍慧。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-014",
    category: "不退成佛",
    text: "今此會中颰陀和等五百菩薩，師子月等五百比丘、比丘尼，今在佛前五百清信士、五百清信女等，皆不退轉，當成無上正真之道。",
    anchorText: "皆不退轉，當成無上正真之道",
    note: "佛指出昔日被教化者今在会中，皆已不退转并当成无上正真之道。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-015",
    category: "經文總讚",
    text: "此《正法華經》其誼廣大，威神無量一切無慶，諸菩薩大士所當欽尚。",
    anchorText: "此《正法華經》其誼廣大",
    note: "佛总赞《正法华经》义理广大、威神无量，为诸菩萨大士所应尊尚。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-016",
    category: "滅後受持",
    text: "如來滅後其受斯經，持諷誦讀得福如是，逮成無上正真道。",
    anchorText: "如來滅後其受斯經",
    note: "佛明说灭后受持、讽诵、读此经得福如是，并至无上正真道。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-017",
    category: "講經教化",
    text: "處在虛空，講說經典，教化一切，悉發道慧。",
    anchorText: "處在虛空，講說經典",
    note: "偈颂总结常被轻慢菩萨讲说经典，教化众生皆发道慧。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-018",
    category: "聞經難遇",
    text: "於今佛身，滅度之後，數數當受，奉斯經卷。無數億億，而當思惟，未曾得聞，如是之法。假使有佛，億百千數，希聞講說，如斯等經。",
    anchorText: "滅度之後，數數當受，奉斯經卷",
    note: "偈中劝佛灭后数数受奉此经，并赞此法亿劫难闻、诸佛难值难说。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-019",
    category: "忍受奉經",
    text: "我滅度後，若有說此，頻數當忍，受《正法華》。",
    anchorText: "我滅度後，若有說此",
    note: "本品以佛灭后说此经者当忍、受《正法华》作结，承接常被轻慢的忍辱护法精神。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-020",
    category: "持經功德",
    text: "如來滅後，布露經典遍諸佛國，及世尊土滅度之處，於彼所在講說斯經，多所利益。若有受持此妙典要，講讀書寫為人說者，德不可量。",
    anchorText: "如來滅後，布露經典遍諸佛國",
    note: "本品开端由地涌菩萨发愿，明说灭后流布、讲说、受持、读写此经，多所利益、德不可量。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-021",
    category: "神足瑞應",
    text: "如來、至真、等正覺，為現瑞應，悉得柔順法忍，皆令書寫《正法華經》，化異世界億百千數諸菩薩等，各各坐于諸寶樹下師子座上。",
    anchorText: "為現瑞應，悉得柔順法忍",
    note: "如来神足瑞应令众得柔顺法忍，并令书写《正法华经》。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-022",
    category: "見瑞歡喜",
    text: "無數無限不可計會億百千姟菩薩大士及四部眾，見斯變化，心中愕然驚喜無量，得未曾有。",
    anchorText: "見斯變化，心中愕然驚喜無量",
    note: "大众见佛神足变化而惊喜无量，显示本品神足示现的摄受力。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-023",
    category: "諸佛護經",
    text: "為諸菩薩大士，講《正法華經》方等典詔，一切諸佛普護斯經，用救菩薩大士。",
    anchorText: "講《正法華經》方等典詔",
    note: "空中音声赞明能仁如来讲《正法华经》，一切诸佛普护此经以救菩萨大士。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-024",
    category: "勸讚供養",
    text: "以故諸賢，心當質直清淨，稽首歸命勸讚奉侍，供養彼能仁正覺。",
    anchorText: "心當質直清淨，稽首歸命",
    note: "本品以诸佛护经为因，劝众清净其心、归命赞叹供养佛。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-025",
    category: "供養瑞相",
    text: "於時眾生聞空中自然之音，有佛世尊，號曰能仁，這聞名稱，應時叉手，以若干種華香衣服幢幡雜香，舉手各散忍世界，瓔珞珠璣、諸貫真珠、如意寶珠而供養之。",
    anchorText: "這聞名稱，應時叉手",
    note: "众生闻佛名与空中法音，即合掌散华香珍宝供养，体现闻名闻法而起敬信。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-026",
    category: "經義深廣",
    text: "如來正覺功德威神，不可思議。諸族姓子，於無數億那術百千姟劫，說此經誼不可究竟，雖無央數若干種經，所不能及不可限盡，欲度彼岸難得邊際。",
    anchorText: "如來正覺功德威神，不可思議",
    note: "佛总赞此经义理与如来功德威神不可思议，诸经不能及。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-027",
    category: "經要所顯",
    text: "諸族姓子，舉要言之，假令有人欲了斯經要，悉佛威神普諸佛法，諸世尊界諸佛精進，諸佛閑居諸佛妙力，示現是經。",
    anchorText: "假令有人欲了斯經要",
    note: "佛说明欲了此经要义，即可从中见佛威神、诸佛法、精进、闲居与妙力。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-028",
    category: "滅後奉行",
    text: "故族姓子，佛滅度後，當以慇懃求此經典，受持書寫精進奉行，供養承事為他人說。",
    anchorText: "佛滅度後，當以慇懃求此經典",
    note: "本品直接劝佛灭后殷勤求经、受持书写、精进奉行、供养承事并为人说。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-029",
    category: "經所在處",
    text: "設使有人，齎此經行講讚書寫，思惟奉宣著於竹帛，若在精舍齋堂室宅，大林樹下若在水邊，當起塔廟。所以者何？則為如來所處之地，觀是道場佛所坐樹，則當察之，一切如來正覺所遊，群聖世雄轉法輪處，十方諸佛在中滅度，等無差特。",
    anchorText: "齎此經行講讚書寫",
    note: "经所在、讲赞书写奉宣之处，应起塔庙，等同如来所处、道场、转法轮与诸佛灭度之处。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-030",
    category: "入於大道",
    text: "諸群萌類，覩見神足，怪未曾有，皆入大道。",
    anchorText: "覩見神足，怪未曾有",
    note: "偈颂说明众生见佛神足，得未曾有，皆入大道。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-031",
    category: "奉經功德",
    text: "如來爾時，皆令歡喜，佛滅度後，奉是經卷，安住宣暢，功德之法，無央數劫，不可思議。",
    anchorText: "佛滅度後，奉是經卷",
    note: "偈中明说佛灭后奉持经卷、安住宣畅，其功德不可思议。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-032",
    category: "持經福祚",
    text: "持是經卷，福祚之限，導師諮嗟，若干無量。欲盡其限，不可邊崖，猶如虛空，不可窮極。",
    anchorText: "持是經卷，福祚之限",
    note: "佛以虚空为喻，赞持经者福祚无量、不可穷极。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-033",
    category: "持經見佛",
    text: "持是經者，淨德常然。則為見佛，大聖導師，及吾於世，滅度大通。",
    anchorText: "持是經者，淨德常然",
    note: "偈颂赞持经者净德常然，等同见佛与大圣导师。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-034",
    category: "值遇此經",
    text: "其有值遇，斯經典者，則為遭見，今日之會。",
    anchorText: "其有值遇，斯經典者",
    note: "能值遇此经，即如遭见今日佛会。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-035",
    category: "持經覩佛",
    text: "佛滅度後，亦復在此，及彼十方，諸佛世界，其有能持，此經卷者，則為覩覲，諸過去佛，及於十方，今現在佛。目自面見，供養奉持，悉當悅意，向人中上。",
    anchorText: "其有能持，此經卷者",
    note: "偈中说灭后持此经卷者，等同觐见过去诸佛与十方现在佛，并能供养奉持。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-036",
    category: "速當受持",
    text: "在於道場，所可思惟，當速受持，於此經典，自然辯才，無所罣礙。",
    anchorText: "當速受持，於此經典",
    note: "偈中劝应速受持此经，并赞其得自然辩才、无所挂碍。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-037",
    category: "曉了經義",
    text: "設本種命，不能長者，當分別曉，於斯經誼，便當受持，於此世尊，曉了諸經，次第所歸。",
    anchorText: "當分別曉，於斯經誼",
    note: "偈中说明应分别晓了此经义并受持，由此明了诸经次第所归。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-038",
    category: "說經利益",
    text: "大聖世尊，滅度之後，假使有人，至誠說者。分別此經，議理所趣，則講審諦，諸經卷誼。其人光明，分別所覺，譬如日月，普照遠近。遊於天下，在所至到，勸化發起，無數菩薩。",
    anchorText: "滅度之後，假使有人，至誠說者",
    note: "佛灭后至诚说此经、分别义理者，其分明觉悟如日月照远近，并能劝化无数菩萨。",
  },
  {
    sectionTitle: RULAISHENZU_SECTION_TITLE,
    id: "t0263-009-039",
    category: "奉經不疑",
    text: "是故智慧，諸菩薩眾，聞如是像，經無等倫。我滅度後，奉此經典，其人不疑，於佛大道。",
    anchorText: "聞如是像，經無等倫",
    note: "本品结尾赞此经无等伦，并劝灭后奉持此经者，于佛大道不疑。",
  },
];

export const T0263_JUAN_9_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  ...T0263_JUAN_9_BASE_MERIT_BENEFITS,
  ...T0263_JUAN_9_YAOWANG_MERIT_BENEFITS,
  ...T0263_JUAN_9_MIAOHOU_MERIT_BENEFITS,
];
