import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const QUANSHUO_SECTION_TITLE = "勸說品第十二";

export const T0263_JUAN_6_QUANSHUO_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0263-006-089",
    category: "滅後弘經",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "如來、至真滅度之後，我等當共分布此經講說示人。",
    anchorText: "如來、至真滅度之後，我等當共分布此經講說示人",
    note: "药王、大辩等二万菩萨发愿在如来灭后分布此经、讲说示人。",
  },
  {
    id: "t0263-006-090",
    category: "忍辱持經",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "我等世尊，興忍辱力在於彼世，受此經典書持誦說，供養奉事懷佩在身，除於吾我班宣斯經，報安住恩。",
    anchorText: "興忍辱力在於彼世，受此經典書持誦說",
    note: "本品以忍辱力受持、书写、诵说、供养、佩持此经，作为报佛恩的弘法行。",
  },
  {
    id: "t0263-006-091",
    category: "宣布此經",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "吾等堪任宣布此經。",
    anchorText: "吾等堪任宣布此經",
    note: "五百比丘学无学众在佛前自陈堪任宣布此经。",
  },
  {
    id: "t0263-006-092",
    category: "授決成道",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "他方世界如來聲聞諸學不學，佛悉授決，當成無上正真之道",
    anchorText: "他方世界如來聲聞諸學不學，佛悉授決",
    note: "经文重申诸声闻学无学已蒙佛授记，当成无上正真之道。",
  },
  {
    id: "t0263-006-093",
    category: "廣說經道",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "滅度之後，當廣解說傳此經道，亦當宣布他方世界。",
    anchorText: "滅度之後，當廣解說傳此經道",
    note: "八千比丘发愿于佛灭后广解说、传此经道，并宣布于他方世界。",
  },
  {
    id: "t0263-006-094",
    category: "道德讚佛",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "道德至尊巍巍無量，超絕虛空無能及者。",
    anchorText: "道德至尊巍巍無量",
    note: "大敬逵比丘尼赞佛道德至尊、巍巍无量，作为本品授记前的敬赞。",
  },
  {
    id: "t0263-006-095",
    category: "平等授決",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "一切眾會等共和同，爾乃演布授眾人決，當至無上正真之道，皆一等味味無有異。",
    anchorText: "一切眾會等共和同，爾乃演布授眾人決",
    note: "佛开示授记平等，一切众会皆当至无上正真之道，一味无异。",
  },
  {
    id: "t0263-006-096",
    category: "供佛法師",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "從是已往，汝當遭值三萬八千億諸佛之眾供養奉事，當為菩薩常為法師",
    anchorText: "汝當遭值三萬八千億諸佛之眾供養奉事",
    note: "佛授记瞿昙弥未来供养奉事诸佛，并常为菩萨法师。",
  },
  {
    id: "t0263-006-097",
    category: "成佛度眾",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "此學不學六千比丘尼，為諸眾生。菩薩法師次第具足菩薩行已，當成為佛，號曰一切眾生咸敬如來、至真、等正覺。成佛以後開化人民，各各展轉共相授決，當成為佛，度脫無數不可計人。",
    anchorText: "此學不學六千比丘尼，為諸眾生",
    note: "六千比丘尼被授记具足菩萨行后成佛，并开化人民、展转授记、度脱无量众生。",
  },
  {
    id: "t0263-006-098",
    category: "名聞授記",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "當於十萬億佛修道，常為法師奉菩薩行，所遵具足當得作佛，號具足百千光幢幡如來、至真、等正覺",
    anchorText: "當於十萬億佛修道，常為法師奉菩薩行",
    note: "名闻比丘尼蒙佛授记，将于十万亿佛所修道、常为法师，具足菩萨行而成佛。",
  },
  {
    id: "t0263-006-099",
    category: "聞記歡喜",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "時大敬逵及羅云母比丘尼等，得未曾有驚喜悅豫",
    anchorText: "時大敬逵及羅云母比丘尼等，得未曾有驚喜悅豫",
    note: "比丘尼众闻佛授记后得未曾有，惊喜悦豫。",
  },
  {
    id: "t0263-006-100",
    category: "佛為導師",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "世尊所開示，為眾之導師，開化於世界，并及於天人。",
    anchorText: "世尊所開示，為眾之導師",
    note: "比丘尼以偈赞佛为众导师，开化世间与天人。",
  },
  {
    id: "t0263-006-101",
    category: "信樂誦讀",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "我等信樂是佛法訓，堪任誦讀，又及餘人他方世界。",
    anchorText: "我等信樂是佛法訓",
    note: "比丘尼众表明信乐佛法训，堪任诵读，并能及于他人与他方世界。",
  },
  {
    id: "t0263-006-102",
    category: "付囑講說",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "唯願大聖，以斯經典付授我等講說宣布。得此經卷，專惟佛德。",
    anchorText: "以斯經典付授我等講說宣布",
    note: "八十亿菩萨请佛付嘱此经典，愿讲说宣布，并专念佛德。",
  },
  {
    id: "t0263-006-103",
    category: "受持顯化",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "如來滅度後，若此經法在於十方，我等書寫受持諷誦，思惟其誼分別布路，顯化餘人亦令如斯",
    anchorText: "如來滅度後，若此經法在於十方",
    note: "诸菩萨发愿灭后于十方书写、受持、讽诵、思惟义理，并显化余人同得其益。",
  },
  {
    id: "t0263-006-104",
    category: "末世班宣",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "佛滅度後，光闡影訓。然後末世，恐有患難，當普班宣，分別說之。",
    anchorText: "佛滅度後，光闡影訓",
    note: "菩萨偈中发愿佛灭后光阐教训，在末世患难中普遍宣说分别。",
  },
  {
    id: "t0263-006-105",
    category: "忍辱說經",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "謗毀說我惡，所行如邪道，吾當悉忍此，當奉侍大聖。",
    anchorText: "謗毀說我惡，所行如邪道",
    note: "面对诽谤与恶言，诸菩萨誓愿忍受，并以奉侍大圣之心护持弘经。",
  },
  {
    id: "t0263-006-106",
    category: "柔忍說經",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "在世行恭敬，皆令忍苦患，以順柔軟性，故當說此經。",
    anchorText: "在世行恭敬，皆令忍苦患",
    note: "本品以恭敬、忍苦患、柔软性作为末世说此经的重要德行。",
  },
  {
    id: "t0263-006-107",
    category: "奉持佛道",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "吾等不貪身，亦不惜壽命，當堪奉持此，志願於佛道。",
    anchorText: "吾等不貪身，亦不惜壽命",
    note: "诸菩萨明誓不贪身命，堪任奉持此经，志愿于佛道。",
  },
  {
    id: "t0263-006-108",
    category: "勇猛說經",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "假使今世雄，滅度後末世，在眾會勇猛，分別說是經。",
    anchorText: "滅度後末世，在眾會勇猛",
    note: "诸菩萨愿在佛灭后末世，于众会中勇猛分别说此经。",
  },
  {
    id: "t0263-006-109",
    category: "少欲寂滅",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "用愛樂世原，興修仁善心，少欲行節限，逮善寂滅度。",
    anchorText: "興修仁善心，少欲行節限",
    note: "偈末将弘经者的修行归于仁善心、少欲节限，并逮善寂灭度。",
  },
  {
    id: "t0263-006-110",
    category: "至誠護法",
    sectionTitle: QUANSHUO_SECTION_TITLE,
    text: "一切世光曜，十方悉來會，我當言至誠，悉見心不虛。",
    anchorText: "一切世光曜，十方悉來會",
    note: "诸菩萨以十方诸佛来会作证，宣明护持弘经之誓诚真实不虚。",
  },
];
