import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const RULAISHOULIANG_SECTION_TITLE = "如來壽量品第十五";

export const T0264_JUAN_5_RULAISHOULIANG_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-005-055",
    category: "信解如来诚谛",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "諸善男子！汝等當信解如來誠諦之語。",
    anchorText: "汝等當信解如來誠諦之語",
    note: "佛三告大众，应信解如来诚谛之语。",
  },
  {
    id: "t0264-005-056",
    category: "大众愿信受佛语",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "世尊！惟願說之，我等當信受佛語。",
    anchorText: "我等當信受佛語",
    note: "菩萨大众以弥勒为首，请佛宣说，并表明当信受佛语。",
  },
  {
    id: "t0264-005-057",
    category: "如来秘密神通之力",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "汝等諦聽！如來祕密神通之力，一切世間天、人及阿修羅，皆謂今釋迦牟尼佛，出釋氏宮，去伽耶城不遠，坐於道場，得阿耨多羅三藐三菩提。",
    anchorText: "如來祕密神通之力",
    note: "本品开示如来秘密神通之力，破除只见近成佛的浅解。",
  },
  {
    id: "t0264-005-058",
    category: "久远成佛",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "我實成佛已來，無量無邊百千萬億那由他劫",
    anchorText: "我實成佛已來",
    note: "如来自述实已久远成佛，非仅今生成道。",
  },
  {
    id: "t0264-005-059",
    category: "常在说法导利众生",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "自從是來，我常在此娑婆世界說法教化，亦於餘處百千萬億那由他阿僧祇國，導利眾生。",
    anchorText: "我常在此娑婆世界說法教化",
    note: "佛久远以来常在娑婆及他方国土说法教化、导利众生。",
  },
  {
    id: "t0264-005-060",
    category: "方便说法令生欢喜",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "又以種種方便說微妙法，能令眾生發歡喜心。",
    anchorText: "種種方便說微妙法",
    note: "如来随众生根机，以种种方便说微妙法，令生欢喜心。",
  },
  {
    id: "t0264-005-061",
    category: "方便教化令入佛道",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "然我實成佛已來久遠若斯，但以方便，教化眾生令入佛道，作如是說。",
    anchorText: "教化眾生令入佛道",
    note: "佛虽久远成佛，仍以方便示现近成，教化众生入佛道。",
  },
  {
    id: "t0264-005-062",
    category: "经教皆为度生",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "如來所演經典，皆為度脫眾生，或說己身，或說他身，或示己身，或示他身，或示己事，或示他事，諸所言說皆實不虛。",
    anchorText: "如來所演經典，皆為度脫眾生",
    note: "如来所说经典皆为度脱众生，所言真实不虚。",
  },
  {
    id: "t0264-005-063",
    category: "令生善根佛事不废",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "欲令生諸善根，以若干因緣，譬喻言辭，種種說法，所作佛事未曾暫廢。",
    anchorText: "欲令生諸善根",
    note: "如来随众生种种性欲，以因缘譬喻说法，令生善根，佛事不废。",
  },
  {
    id: "t0264-005-064",
    category: "寿命无量常住不灭",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "如是我成佛已來甚大久遠，壽命無量阿僧祇劫，常住不滅。",
    anchorText: "壽命無量阿僧祇劫，常住不滅",
    note: "本品正明如来寿命无量，常住不灭。",
  },
  {
    id: "t0264-005-065",
    category: "难遭想种善根",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "斯眾生等聞如是語，必當生於難遭之想，心懷戀慕渴仰於佛，便種善根。",
    anchorText: "生於難遭之想",
    note: "佛以方便说难得见，使众生恋慕渴仰而种善根。",
  },
  {
    id: "t0264-005-066",
    category: "诸佛为度众生真实不虚",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "諸佛如來法皆如是，為度眾生皆實不虛。",
    anchorText: "為度眾生皆實不虛",
    note: "诸佛如来方便示现，目的皆为度众生，真实不虚。",
  },
  {
    id: "t0264-005-067",
    category: "良药除苦无患",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "此大良藥，色、香、美味皆悉具足，汝等可服，速除苦惱無復眾患。",
    anchorText: "速除苦惱無復眾患",
    note: "良医譬喻中，以良药喻佛法能除众生苦恼诸患。",
  },
  {
    id: "t0264-005-068",
    category: "方便现灭不虚妄",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "我亦如是，成佛已來無量無邊百千萬億那由他阿僧祇劫，為眾生故，以方便力言當滅度，亦無有能如法說我虛妄過者。",
    anchorText: "為眾生故，以方便力言當滅度",
    note: "佛以良医譬喻说明，为众生故方便说灭度，并非虚妄。",
  },
  {
    id: "t0264-005-069",
    category: "常说法令入佛道",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "常說法教化，無數億眾生，令入於佛道",
    anchorText: "常說法教化，無數億眾生",
    note: "偈颂重申佛久远以来常说法教化无数众生，令入佛道。",
  },
  {
    id: "t0264-005-070",
    category: "实不灭度常住说法",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "為度眾生故，方便現涅槃，而實不滅度，常住此說法。",
    anchorText: "而實不滅度，常住此說法",
    note: "佛为度众生方便现涅槃，而实常住说法。",
  },
  {
    id: "t0264-005-071",
    category: "信伏柔软一心见佛",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "眾生既信伏，質直意柔軟，一心欲見佛，不自惜身命。",
    anchorText: "一心欲見佛，不自惜身命",
    note: "众生因恋慕渴仰而信伏柔软，一心欲见佛。",
  },
  {
    id: "t0264-005-072",
    category: "常在不灭方便示现",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "我時語眾生，常在此不滅，以方便力故，現有滅不滅；",
    anchorText: "常在此不滅",
    note: "佛明示常在不灭，但以方便力示现灭与不灭。",
  },
  {
    id: "t0264-005-073",
    category: "恭敬信乐闻无上法",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "餘國有眾生，恭敬信樂者，我復於彼中，為說無上法",
    anchorText: "恭敬信樂者，我復於彼中",
    note: "他方众生若恭敬信乐，佛亦为其说无上法。",
  },
  {
    id: "t0264-005-074",
    category: "常在灵鹫及余处",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "神通力如是，於阿僧祇劫，常在靈鷲山，及餘諸住處。",
    anchorText: "常在靈鷲山",
    note: "佛以神通力常在灵鹫山及余诸住处。",
  },
  {
    id: "t0264-005-075",
    category: "净土安隐",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "眾生見劫盡，大火所燒時，我此土安隱，天人常充滿，園林諸堂閣，種種寶莊嚴，寶樹多花果，眾生所遊樂；",
    anchorText: "我此土安隱，天人常充滿",
    note: "众生见劫火烧尽时，佛土实安隐庄严，天人充满。",
  },
  {
    id: "t0264-005-076",
    category: "修功德柔和见佛",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "諸有修功德，柔和質直者，則皆見我身，在此而說法；",
    anchorText: "諸有修功德，柔和質直者",
    note: "修功德、柔和质直者，得见佛身在此说法。",
  },
  {
    id: "t0264-005-077",
    category: "断疑信佛语实",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "汝等有智者，勿於此生疑，當斷令永盡，佛語實不虛。",
    anchorText: "佛語實不虛",
    note: "佛劝有智者断除疑惑，信佛语真实不虚。",
  },
  {
    id: "t0264-005-078",
    category: "世父救苦",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "我亦為世父，救諸苦患者，為凡夫顛倒，實在而言滅。",
    anchorText: "我亦為世父，救諸苦患者",
    note: "佛自喻为世间之父，为救诸苦患者而方便言灭。",
  },
  {
    id: "t0264-005-079",
    category: "随应所度说种种法",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "我常知眾生，行道不行道，隨應所可度，為說種種法。",
    anchorText: "隨應所可度，為說種種法",
    note: "佛常知众生行道与否，随所应度而说种种法。",
  },
  {
    id: "t0264-005-080",
    category: "令入无上道速成佛身",
    sectionTitle: RULAISHOULIANG_SECTION_TITLE,
    text: "每自作是意，以何令眾生，得入無上道，速成就佛身？",
    anchorText: "得入無上道，速成就佛身",
    note: "本品结偈显佛本怀：令众生入无上道，速成就佛身。",
  },
];
