import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const CHANGBEIQINGMAN_SECTION_TITLE = "常被輕慢品第十九";

export const T0263_JUAN_9_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-001",
    category: "持經福德",
    text: "設復有人，聞是經卷受持諷誦，為他人說廣解其誼，獲上妙福。如斯疇類，佛所諮嗟，眼耳鼻口身意清淨，而無蔽礙。",
    anchorText: "聞是經卷受持諷誦，為他人說廣解其誼",
    note: "本品开端直接说明闻经、受持、讽诵、为人解说所得上妙福与六根清净。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-002",
    category: "護經警策",
    text: "其有比丘、比丘尼、清信士、清信女，持斯經典，假使四部罵詈誹謗，出麁獷辭訶制止之，罪不可限。",
    anchorText: "持斯經典，假使四部罵詈誹謗",
    note: "经文明示毁谤持经者罪不可限，显示护持此经的严肃性。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-003",
    category: "不輕眾生",
    text: "我身終不輕慢諸賢人，普當學菩薩高行，得至如來、至真、等正覺。",
    anchorText: "我身終不輕慢諸賢人",
    note: "常被轻慢菩萨的核心劝修，是不轻众生并劝入菩萨高行、趣向正觉。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-004",
    category: "忍辱發心",
    text: "勿行輕慢，修忍辱心、發菩薩意。",
    anchorText: "勿行輕慢，修忍辱心",
    note: "面对诃骂时仍劝人修忍辱心、发菩萨意，是本品清楚的修行要点。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-005",
    category: "聞經增益",
    text: "斯一大士臨欲壽終，得聞寂趣音王如來講《正法華經》二十頌本深妙之誼億百千事。",
    anchorText: "得聞寂趣音王如來講《正法華經》",
    note: "常被轻慢菩萨临终得闻《正法华经》深义，成为后文功德转起的关键。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-006",
    category: "受經功德",
    text: "仁當受經，亦當逮得如前淨眼，耳鼻口身意亦清淨，已獲斯淨，更即增益二十億姟壽，逮得定意，復為眾人講是經典。",
    anchorText: "仁當受經，亦當逮得如前淨眼",
    note: "经中赞受经者得六根清净、增益寿命、得定意，并能为众讲说经典。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-007",
    category: "聞法發心",
    text: "見此大士微妙神力、辯才慧力、善權道力，皆來歸伏敬宗為友，聽聞經法。是等輩類，餘不可計無數億人，便立無上正真道意。",
    anchorText: "皆來歸伏敬宗為友，聽聞經法",
    note: "昔日轻毁者见德归伏、听闻经法，无数人由此建立无上道意。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-008",
    category: "值佛聞經",
    text: "時彼大士壽沒之後，便值二十百千億如來正真，此諸世尊，皆為講說《正法華經》。",
    anchorText: "便值二十百千億如來正真",
    note: "受持此经的因缘续感值遇诸佛，诸佛皆为讲说《正法华经》。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-009",
    category: "六根清淨",
    text: "亦復從聞《正法華經》，受持諷誦為四輩說，在所生處，常自然獲眼淨耳淨鼻淨口淨身淨意淨，視聽洞徹，鼻通口辯，身能輕舉，意覩眾生心，普為四輩演斯經典分別其誼。",
    anchorText: "受持諷誦為四輩說，在所生處",
    note: "闻经、受持、讽诵、为四众说法，感得所生处六根清净并能继续宣说此经。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-010",
    category: "成佛因緣",
    text: "常被輕慢大士，供養奉事若干億百千數如來已，復更值無數億百千如來，亦復從受《正法華經》，以是德本，自致無上正真之道成最正覺。",
    anchorText: "亦復從受《正法華經》，以是德本",
    note: "经文把从诸佛受《正法华经》的德本，直接连到成就无上正觉。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-011",
    category: "速成正覺",
    text: "假使爾時設不受是《正法華經》，不持諷誦為人說者，不能疾逮無上正真道成最正覺。備從過去諸佛世尊，聞此經典，受持諷誦廣為人說致最正覺。",
    anchorText: "不受是《正法華經》，不持諷誦為人說者",
    note: "佛以自身因缘说明受持、讽诵、为人广说此经，是疾成正觉的重要因缘。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-012",
    category: "毀謗果報",
    text: "又諸四部輕彼大士罵詈形笑不自改者，二十億千劫所生之處，常不值佛不聞法聲，又萬劫中墮無可大地獄，拷掠燒炙痛不可言。",
    anchorText: "輕彼大士罵詈形笑不自改者",
    note: "本品以强烈果报警策轻毁持经菩萨与正法者。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-013",
    category: "教化得益",
    text: "罪已畢竟從地獄出，以彼大士教化之故，令發無上正真道意，皆得神通，慧無罣礙，今悉現在。",
    anchorText: "以彼大士教化之故",
    note: "即使曾轻毁者，罪毕之后仍因菩萨教化而发无上道意、得神通与无碍慧。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-014",
    category: "不退成佛",
    text: "今此會中颰陀和等五百菩薩，師子月等五百比丘、比丘尼，今在佛前五百清信士、五百清信女等，皆不退轉，當成無上正真之道。",
    anchorText: "皆不退轉，當成無上正真之道",
    note: "佛指出昔日被教化者今在会中，皆已不退转并当成无上正真之道。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-015",
    category: "經文總讚",
    text: "此《正法華經》其誼廣大，威神無量一切無慶，諸菩薩大士所當欽尚。",
    anchorText: "此《正法華經》其誼廣大",
    note: "佛总赞《正法华经》义理广大、威神无量，为诸菩萨大士所应尊尚。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-016",
    category: "滅後受持",
    text: "如來滅後其受斯經，持諷誦讀得福如是，逮成無上正真道。",
    anchorText: "如來滅後其受斯經",
    note: "佛明说灭后受持、讽诵、读此经得福如是，并至无上正真道。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-017",
    category: "講經教化",
    text: "處在虛空，講說經典，教化一切，悉發道慧。",
    anchorText: "處在虛空，講說經典",
    note: "偈颂总结常被轻慢菩萨讲说经典，教化众生皆发道慧。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-018",
    category: "聞經難遇",
    text: "於今佛身，滅度之後，數數當受，奉斯經卷。無數億億，而當思惟，未曾得聞，如是之法。假使有佛，億百千數，希聞講說，如斯等經。",
    anchorText: "滅度之後，數數當受，奉斯經卷",
    note: "偈中劝佛灭后数数受奉此经，并赞此法亿劫难闻、诸佛难值难说。",
  },
  {
    sectionTitle: CHANGBEIQINGMAN_SECTION_TITLE,
    id: "t0263-009-019",
    category: "忍受奉經",
    text: "我滅度後，若有說此，頻數當忍，受《正法華》。",
    anchorText: "我滅度後，若有說此",
    note: "本品以佛灭后说此经者当忍、受《正法华》作结，承接常被轻慢的忍辱护法精神。",
  },
];
