import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const PUXIAN_SECTION_TITLE = "普賢菩薩勸發品第二十八";

export const T0262_JUAN_7_PUXIAN_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0262-007-069",
    category: "來聽法華",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "世尊。我於寶威德上王佛國。遙聞此娑婆世界說法華經。與無量無邊百千萬億諸菩薩眾。共來聽受。",
    anchorText: "遙聞此娑婆世界說法華經",
    note: "普賢菩薩從寶威德上王佛國遙聞娑婆說《法華經》，與無量菩薩共來聽受。",
  },
  {
    id: "t0262-007-070",
    category: "得法華經",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若善男子善女人。成就四法。於如來滅後。當得是法華經。一者為諸佛護念。二者植眾德本。三者入正定聚。四者發救一切眾生之心。善男子善女人。如是成就四法。於如來滅後。必得是經。",
    anchorText: "成就四法。於如來滅後。當得是法華經",
    note: "佛明說滅後得《法華經》的四法：諸佛護念、植眾德本、入正定聚、發救眾生心。",
  },
  {
    id: "t0262-007-071",
    category: "守護安隱",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "世尊。於後五百歲濁惡世中。其有受持是經典者。我當守護。除其衰患。令得安隱。使無伺求得其便者。",
    anchorText: "其有受持是經典者。我當守護",
    note: "普賢菩薩發願守護後五百歲受持此經者，除衰患、令安隱。",
  },
  {
    id: "t0262-007-072",
    category: "無能得便",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若魔。若魔子。若魔女。若魔民。若為魔所著者。若夜叉。若羅剎。若鳩槃荼。若毗舍闍。若吉蔗。若富單那。若韋陀羅等。諸惱人者。皆不得便。",
    anchorText: "諸惱人者。皆不得便",
    note: "普賢菩薩明說諸魔與惱人者，對受持此經者皆不得便。",
  },
  {
    id: "t0262-007-073",
    category: "現身守護",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "是人若行若立。讀誦此經。我爾時乘六牙白象王。與大菩薩眾俱詣其所。而自現身。供養守護。安慰其心。亦為供養法華經故。",
    anchorText: "是人若行若立。讀誦此經",
    note: "若行立讀誦此經，普賢菩薩乘六牙白象現身，供養守護、安慰其心。",
  },
  {
    id: "t0262-007-074",
    category: "教令通利",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "是人若坐。思惟此經。爾時我復乘白象王。現其人前。其人若於法華經。有所忘失一句一偈。我當教之。與共讀誦。還令通利。",
    anchorText: "思惟此經。爾時我復乘白象王",
    note: "若坐思惟此經而有所忘失，普賢菩薩現前教之、共讀誦，令其通利。",
  },
  {
    id: "t0262-007-075",
    category: "得三昧陀羅尼",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "爾時受持讀誦法華經者。得見我身。甚大歡喜。轉復精進。以見我故。即得三昧。及陀羅尼。名為旋陀羅尼。百千萬億旋陀羅尼。法音方便陀羅尼。得如是等陀羅尼。",
    anchorText: "受持讀誦法華經者。得見我身",
    note: "受持讀誦《法華經》者得見普賢身，歡喜精進，並得三昧與諸陀羅尼。",
  },
  {
    id: "t0262-007-076",
    category: "精進修習",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "世尊。若後世後五百歲濁惡世中。比丘比丘尼。優婆塞優婆夷。求索者。受持者。讀誦者。書寫者。欲修習是法華經。於三七日中應一心精進。",
    anchorText: "欲修習是法華經。於三七日中應一心精進",
    note: "普賢菩薩勸後五百歲欲修習《法華經》的四眾，三七日中一心精進。",
  },
  {
    id: "t0262-007-077",
    category: "現前說法",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "滿三七日已。我當乘六牙白象。與無量菩薩而自圍繞。以一切眾生所喜見身。現其人前而為說法。示教利喜。",
    anchorText: "滿三七日已。我當乘六牙白象",
    note: "一心精進滿三七日後，普賢菩薩現前為其說法、示教利喜。",
  },
  {
    id: "t0262-007-078",
    category: "陀羅尼護",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "亦復與其陀羅尼咒。得是陀羅尼故。無有非人能破壞者。亦不為女人之所惑亂。我身亦自常護是人。",
    anchorText: "得是陀羅尼故。無有非人能破壞者",
    note: "得普賢陀羅尼故，無非人能破壞，亦不為惑亂，普賢菩薩自常護持。",
  },
  {
    id: "t0262-007-079",
    category: "神通之力",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "世尊。若有菩薩得聞是陀羅尼者。當知普賢神通之力。若法華經行閻浮提。有受持者。應作此念。皆是普賢威神之力。",
    anchorText: "當知普賢神通之力",
    note: "聞此陀羅尼與《法華經》在閻浮提有受持者，皆被歸於普賢神通威神之力。",
  },
  {
    id: "t0262-007-080",
    category: "行普賢行",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若有受持讀誦。正憶念。解其義趣。如說修行。當知是人行普賢行。於無量無邊諸佛所。深種善根。為諸如來手摩其頭。",
    anchorText: "當知是人行普賢行",
    note: "受持讀誦、正憶念、解義如說修行者，即行普賢行，深種善根，為諸如來摩頂。",
  },
  {
    id: "t0262-007-081",
    category: "書寫生天",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若但書寫。是人命終。當生忉利天上。是時八萬四千天女。作眾伎樂而來迎之。其人即著七寶冠。於采女中娛樂快樂。",
    anchorText: "若但書寫。是人命終。當生忉利天上",
    note: "經文明說但能書寫此經，命終當生忉利天上，天女伎樂迎接。",
  },
  {
    id: "t0262-007-082",
    category: "千佛授手",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若有人受持讀誦解其義趣。是人命終。為千佛授手。令不恐怖。不墮惡趣。即往兜率天上彌勒菩薩所。",
    anchorText: "為千佛授手。令不恐怖",
    note: "受持讀誦並解義趣者，命終為千佛授手，不恐怖、不墮惡趣，往兜率天彌勒所。",
  },
  {
    id: "t0262-007-083",
    category: "功德利益",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "彌勒菩薩。有三十二相大菩薩眾所共圍繞。有百千萬億天女眷屬而於中生。有如是等功德利益。",
    anchorText: "有如是等功德利益",
    note: "經文以“有如是等功德利益”總結往生兜率天彌勒所的殊勝果報。",
  },
  {
    id: "t0262-007-084",
    category: "智者應修",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "是故智者。應當一心自書。若使人書。受持讀誦。正憶念。如說修行。",
    anchorText: "是故智者。應當一心自書",
    note: "經文據前述功德利益，勸智者一心自書、使人書、受持讀誦、正憶念、如說修行。",
  },
  {
    id: "t0262-007-085",
    category: "流布不絕",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "世尊。我今以神通力故。守護是經。於如來滅後。閻浮提內。廣令流布。使不斷絕。",
    anchorText: "守護是經。於如來滅後。閻浮提內",
    note: "普賢菩薩發願以神通力守護此經，使其於閻浮提廣為流布、不斷絕。",
  },
  {
    id: "t0262-007-086",
    category: "安樂利益",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "善哉善哉。普賢。汝能護助是經。令多所眾生。安樂利益。汝已成就不可思議功德。深大慈悲。從久遠來。發阿耨多羅三藐三菩提意。而能作是神通之願。守護是經。",
    anchorText: "汝能護助是經。令多所眾生。安樂利益",
    note: "佛讚普賢護助此經，令眾生安樂利益，並讚其不可思議功德與深大慈悲。",
  },
  {
    id: "t0262-007-087",
    category: "佛護其名",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "我當以神通力。守護能受持普賢菩薩名者。",
    anchorText: "守護能受持普賢菩薩名者",
    note: "佛明說將以神通力守護能受持普賢菩薩名者。",
  },
  {
    id: "t0262-007-088",
    category: "如見佛聞經",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "普賢。若有受持讀誦。正憶念。修習書寫是法華經者。當知是人則見釋迦牟尼佛。如從佛口聞此經典。",
    anchorText: "修習書寫是法華經者。當知是人則見釋迦牟尼佛",
    note: "受持讀誦、正憶念、修習書寫《法華經》者，如見釋迦佛、如從佛口聞此經。",
  },
  {
    id: "t0262-007-089",
    category: "佛所覆護",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "當知是人供養釋迦牟尼佛。當知是人。佛讚善哉。當知是人。為釋迦牟尼佛手摩其頭。當知是人。為釋迦牟尼佛衣之所覆。",
    anchorText: "當知是人供養釋迦牟尼佛",
    note: "經文將修習書寫受持者說為供養佛、佛讚善哉、佛摩頂與佛衣所覆。",
  },
  {
    id: "t0262-007-090",
    category: "離惱修行",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "是人心意質直。有正憶念。有福德力。是人不為三毒所惱。亦不為嫉妒我慢邪慢增上慢所惱。是人少欲知足。能修普賢之行。",
    anchorText: "是人心意質直。有正憶念。有福德力",
    note: "受持修習者心意質直、有正憶念與福德力，不為三毒慢心所惱，能修普賢行。",
  },
  {
    id: "t0262-007-091",
    category: "不久成佛",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "普賢。若如來滅後。後五百歲。若有人見受持讀誦法華經者。應作是念。此人不久當詣道場。破諸魔眾。得阿耨多羅三藐三菩提。轉法輪。擊法鼓。吹法螺。雨法雨。當坐天人大眾中獅子法座上。",
    anchorText: "此人不久當詣道場",
    note: "佛教人見受持讀誦《法華經》者，應念其不久詣道場、破魔、成菩提、轉法輪。",
  },
  {
    id: "t0262-007-092",
    category: "現世福報",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "普賢。若於後世。受持讀誦是經典者。是人不復貪著衣服臥具飲食資生之物。所願不虛。亦於現世得其福報。",
    anchorText: "受持讀誦是經典者。是人不復貪著",
    note: "後世受持讀誦此經者，不貪著資生之物，所願不虛，現世得其福報。",
  },
  {
    id: "t0262-007-093",
    category: "供養現報",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若有供養讚歎之者。當於今世得現果報。",
    anchorText: "供養讚歎之者。當於今世得現果報",
    note: "經文明說供養讚歎受持此經者，今世得現果報。",
  },
  {
    id: "t0262-007-094",
    category: "敬如佛",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "是故普賢。若見受持是經典者。當起遠迎。當如敬佛。",
    anchorText: "若見受持是經典者。當起遠迎",
    note: "佛以此勸見受持經典者應起遠迎，敬之如佛。",
  },
  {
    id: "t0262-007-095",
    category: "聞品證法",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "說是普賢勸發品時。恆河沙等無量無邊菩薩。得百千萬億旋陀羅尼。三千大千世界微塵等諸菩薩。具普賢道。",
    anchorText: "恆河沙等無量無邊菩薩",
    note: "說此品時，無量菩薩得旋陀羅尼，微塵等諸菩薩具普賢道。",
  },
  {
    id: "t0262-007-096",
    category: "歡喜受持",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "佛說是經時。普賢等諸菩薩。舍利弗等諸聲聞。及諸天龍人非人等。一切大會皆大歡喜。受持佛語。作禮而去。",
    anchorText: "一切大會皆大歡喜。受持佛語",
    note: "全經結尾以一切大會歡喜受持佛語、作禮而去收束。",
  },
];
