import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const FENBIEGONGDE_SECTION_TITLE = "分別功德品第十六";

export const T0264_JUAN_5_FENBIEGONGDE_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-005-081",
    category: "闻寿命得大饶益",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "爾時大會，聞佛說壽命劫數長遠如是，無量無邊阿僧祇眾生得大饒益。",
    anchorText: "聞佛說壽命劫數長遠如是",
    note: "大众闻佛寿命长远，获得无量大饶益。",
  },
  {
    id: "t0264-005-082",
    category: "得无生法忍",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "我說是如來壽命長遠時，六百八十萬億那由他恒河沙眾生得無生法忍；",
    anchorText: "得無生法忍",
    note: "佛说如来寿命长远时，众多众生得无生法忍。",
  },
  {
    id: "t0264-005-083",
    category: "得陀罗尼辩才",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "復有千倍菩薩摩訶薩，得聞持陀羅尼門；復有一世界微塵數菩薩摩訶薩，得樂說無礙辯才；",
    anchorText: "得聞持陀羅尼門",
    note: "有菩萨得闻持陀罗尼门，又有菩萨得乐说无碍辩才。",
  },
  {
    id: "t0264-005-084",
    category: "转不退与清净法轮",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "復有三千大千世界微塵數菩薩摩訶薩，能轉不退法輪；復有二千中國土微塵數菩薩摩訶薩，能轉清淨法輪；",
    anchorText: "能轉不退法輪",
    note: "闻佛寿量功德中，有菩萨能转不退法轮、清净法轮。",
  },
  {
    id: "t0264-005-085",
    category: "随数生成佛",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "復有小千國土微塵數菩薩摩訶薩，八生當得阿耨多羅三藐三菩提；復有四四天下微塵數菩薩摩訶薩，四生當得阿耨多羅三藐三菩提；復有三四天下微塵數菩薩摩訶薩，三生當得阿耨多羅三藐三菩提；復有二四天下微塵數菩薩摩訶薩，二生當得阿耨多羅三藐三菩提；復有一四天下微塵數菩薩摩訶薩，一生當得阿耨多羅三藐三菩提；",
    anchorText: "八生當得阿耨多羅三藐三菩提",
    note: "诸菩萨随八生乃至一生，当得无上正等正觉。",
  },
  {
    id: "t0264-005-086",
    category: "发无上心",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "復有八世界微塵數眾生，皆發阿耨多羅三藐三菩提心。",
    anchorText: "皆發阿耨多羅三藐三菩提心",
    note: "八世界微尘数众生，皆发无上菩提心。",
  },
  {
    id: "t0264-005-087",
    category: "得大法利感天供养",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "佛說是諸菩薩摩訶薩得大法利時，於虛空中，雨曼陀羅華、摩訶曼陀羅華，以散無量百千萬億眾寶樹下師子座上諸佛，并散七寶塔中師子座上釋迦牟尼佛，及久滅度多寶如來，亦散一切諸大菩薩及四部眾；",
    anchorText: "得大法利時",
    note: "诸菩萨得大法利时，天华雨下，供养诸佛、菩萨及四众。",
  },
  {
    id: "t0264-005-088",
    category: "希有法利欢喜",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "佛說希有法，昔所未曾聞；世尊有大力，壽命不可量。無數諸佛子，聞世尊分別，說得法利者，歡喜充遍身，",
    anchorText: "佛說希有法",
    note: "弥勒赞佛说昔未曾闻希有法，诸佛子闻得法利而欢喜。",
  },
  {
    id: "t0264-005-089",
    category: "清净果报",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "如是等眾生，聞佛壽長遠，得無量無漏，清淨之果報。",
    anchorText: "聞佛壽長遠",
    note: "闻佛寿命长远，得无量无漏清净果报。",
  },
  {
    id: "t0264-005-090",
    category: "无量饶益",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "世尊說無量，不可思議法，多有所饒益，如虛空無邊，",
    anchorText: "多有所饒益，如虛空無邊",
    note: "世尊所说不可思议法，饶益广大如虚空无边。",
  },
  {
    id: "t0264-005-091",
    category: "助无上心",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "佛名聞十方，廣饒益眾生，一切具善根，以助無上心。",
    anchorText: "廣饒益眾生",
    note: "佛名闻于十方，广饶益众生，令具善根助成无上心。",
  },
  {
    id: "t0264-005-092",
    category: "一念信解功德无量",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "其有眾生，聞佛壽命長遠如是，乃至能生一念信解，所得功德無有限量。",
    anchorText: "乃至能生一念信解",
    note: "闻佛寿命长远，乃至一念信解，所得功德无有限量。",
  },
  {
    id: "t0264-005-093",
    category: "胜过五波罗蜜功德",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "於八十萬億那由他劫，行五波羅蜜：檀波羅蜜、尸羅波羅蜜、羼提波羅蜜、毘梨耶波羅蜜、禪波羅蜜，除般若波羅蜜，以是功德比前功德，百分、千分、百千萬億分，不及其一，乃至算數譬喻所不能知。",
    anchorText: "以是功德比前功德",
    note: "一念信解佛寿长远之功德，胜过长劫行五波罗蜜的功德。",
  },
  {
    id: "t0264-005-094",
    category: "菩提不退",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "若善男子有如是功德，於阿耨多羅三藐三菩提退者，無有是處。",
    anchorText: "退者，無有是處",
    note: "具此功德者，于无上正等正觉退转，无有是处。",
  },
  {
    id: "t0264-005-095",
    category: "一念信福过彼",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "有善男女等，聞我說壽命，乃至一念信，其福過於彼。",
    anchorText: "乃至一念信，其福過於彼",
    note: "偈颂重申闻佛说寿命乃至一念信，其福胜过前述功德。",
  },
  {
    id: "t0264-005-096",
    category: "无疑信受顶受经典",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "其有諸菩薩，無量劫行道，聞我說壽命，是則能信受；如是諸人等，頂受此經典，願我於未來，長壽度眾生。",
    anchorText: "聞我說壽命，是則能信受",
    note: "无量劫行道的菩萨闻佛寿命能信受，并顶受经典，愿未来长寿度生。",
  },
  {
    id: "t0264-005-097",
    category: "深心解佛语无疑",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "若有深心者，清淨而質直，多聞能總持，隨義解佛語；如是之人等，於此無有疑。",
    anchorText: "隨義解佛語",
    note: "深心清净质直、多闻总持者，能随义解佛语，于此无疑。",
  },
  {
    id: "t0264-005-098",
    category: "解言趣起佛慧",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "若有聞佛壽命長遠，解其言趣，是人所得功德無有限量，能起如來無上之慧，",
    anchorText: "解其言趣",
    note: "闻佛寿命长远并解其言趣，功德无量，能起如来无上智慧。",
  },
  {
    id: "t0264-005-099",
    category: "闻持书供养生种智",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "何況廣聞是經，若教人聞，若自持，若教人持，若自書，若教人書，若以華香、瓔珞、幢幡、繒蓋、香油、穌燈供養經卷，是人功德無量無邊，能生一切種智。",
    anchorText: "是人功德無量無邊",
    note: "广闻此经、教人闻、自持教持、自书教书及供养经卷，功德无量，能生一切种智。",
  },
  {
    id: "t0264-005-100",
    category: "深心信解见佛净土",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "若善男子、善女人，聞我說壽命長遠，深心信解，則為見佛常在耆闍崛山共大菩薩、諸聲聞眾圍遶說法；又見此娑婆世界，其地琉璃，坦然平正，閻浮檀金以界八道，寶樹行列，諸臺樓觀皆悉寶成，其菩薩眾咸處其中，",
    anchorText: "深心信解，則為見佛常在耆闍崛山",
    note: "深心信解佛寿长远，即为见佛常在灵鹫山说法，并见娑婆净土庄严。",
  },
  {
    id: "t0264-005-101",
    category: "随喜为深信解相",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "又復如來滅後，若聞是經，而不毀呰，起隨喜心，當知已為深信解相，何況讀誦、受持之者，斯人則為頂戴如來。",
    anchorText: "起隨喜心，當知已為深信解相",
    note: "灭后闻经不毁而随喜，是深信解相；读诵受持者则为顶戴如来。",
  },
  {
    id: "t0264-005-102",
    category: "受持读诵等同供养",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "是善男子、善女人，受持、讀誦是經典者，為已起塔造立僧坊供養眾僧，則為以佛舍利起七寶塔，高廣漸小至于梵天，懸諸幡蓋及眾寶鈴，華香、瓔珞、末香、塗香、燒香，眾鼓伎樂，簫、笛、箜篌，種種舞戲，以妙音聲歌唄、讚誦，則為已於無量千萬億劫作是供養已。",
    anchorText: "受持、讀誦是經典者",
    note: "受持读诵此经，即等同已起塔造坊、长劫广修供养。",
  },
  {
    id: "t0264-005-103",
    category: "受持书写如供养佛僧",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "若我滅後，聞是經典有能受持，若自書，若教人書，則為起立僧坊，以赤栴檀作諸殿堂，三十有二，高八多羅樹，高廣嚴好，百千比丘於其中止，園林、浴池、經行、禪窟，衣服、飲食、床褥、湯藥，一切樂具充滿其中，如是僧坊堂閣若干百千萬億其數無量，以此現前供養於我及比丘僧。",
    anchorText: "聞是經典有能受持",
    note: "灭后闻经受持、自书教书，即如起立无量僧坊现前供养佛及僧。",
  },
  {
    id: "t0264-005-104",
    category: "持经兼六度德最胜",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "況復有人能持是經，兼行布施、持戒、忍辱、精進、一心、智慧，其德最勝無量無邊。",
    anchorText: "能持是經，兼行布施",
    note: "持此经并兼修布施、持戒、忍辱、精进、一心、智慧，其德最胜无量无边。",
  },
  {
    id: "t0264-005-105",
    category: "疾至一切种智",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "譬如虛空東、西、南、北、四維、上、下無量無邊，是人功德亦復如是無量無邊，疾至一切種智。",
    anchorText: "疾至一切種智",
    note: "持经兼修诸善者，功德如虚空无边，疾至一切种智。",
  },
  {
    id: "t0264-005-106",
    category: "已趣道场近菩提",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "若我滅後，諸善男子、善女人，受持、讀誦是經典者，復有如是諸善功德，當知是人已趣道場，近阿耨多羅三藐三菩提，坐道樹下。",
    anchorText: "已趣道場，近阿耨多羅三藐三菩提",
    note: "灭后受持读诵此经并具诸善功德者，已趣道场，近无上菩提。",
  },
  {
    id: "t0264-005-107",
    category: "所住处应起塔供养",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "是善男子若坐若立若經行處，是中便應起塔，一切天人皆應供養，如佛之塔。",
    anchorText: "一切天人皆應供養，如佛之塔",
    note: "持经者坐立经行之处，应起塔供养，如佛塔一般。",
  },
  {
    id: "t0264-005-108",
    category: "奉持此经福无量",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "若我滅度後，能奉持此經；斯人福無量，如上之所說。",
    anchorText: "能奉持此經",
    note: "偈颂重申佛灭后能奉持此经者，福德无量。",
  },
  {
    id: "t0264-005-109",
    category: "持经如佛现在",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "若能持此經，則如佛現在，",
    anchorText: "若能持此經，則如佛現在",
    note: "能持此经，则如佛现在。",
  },
  {
    id: "t0264-005-110",
    category: "供养持经福如虚空",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "若有信解心，受持讀誦書，若復教人書，及供養經卷；散華香末香，以須曼瞻蔔，阿提目多伽，薰油常然之；如是供養者，得無量功德，如虛空無邊，其福亦如是。",
    anchorText: "如是供養者，得無量功德",
    note: "以信解心受持读诵书写、教人书写并供养经卷，所得功德如虚空无边。",
  },
  {
    id: "t0264-005-111",
    category: "持经兼行功德不可量",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "況復持此經，兼布施持戒，忍辱樂禪定，不瞋不惡口；恭敬於塔廟，謙下諸比丘，遠離自高心，常思惟智慧；有問難不瞋，隨順為解說，若能行是行，功德不可量。",
    anchorText: "若能行是行，功德不可量",
    note: "持经并兼行布施、持戒、忍辱、禅定、谦下、智慧与随顺解说，功德不可量。",
  },
  {
    id: "t0264-005-112",
    category: "敬法师如佛想",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "若見此法師，成就如是德，應以天華散，天衣覆其身，頭面接足禮，生心如佛想。",
    anchorText: "生心如佛想",
    note: "见成就持经功德的法师，应以天华天衣供养礼敬，生如佛想。",
  },
  {
    id: "t0264-005-113",
    category: "不久道树广利人天",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "又應作是念，不久詣道樹，得無漏無為，廣利諸人天，",
    anchorText: "不久詣道樹",
    note: "对成就持经功德者，应念其不久诣道树，得无漏无为，广利人天。",
  },
  {
    id: "t0264-005-114",
    category: "佛子住地是佛受用",
    sectionTitle: FENBIEGONGDE_SECTION_TITLE,
    text: "其所住止處，經行若坐臥，乃至說一偈，是中應起塔，莊嚴令妙好，種種以供養；佛子住此地，則是佛受用，常在於其中，經行及坐臥。",
    anchorText: "乃至說一偈，是中應起塔",
    note: "持经佛子住止、经行、坐卧乃至说一偈处，应起塔供养，是佛受用之地。",
  },
];
