import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const JIANBAOTA_SECTION_TITLE = "見寶塔品第十一";

export const T0262_JUAN_5_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0262-005-148",
    category: "寶塔作證",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "善哉，善哉！釋迦牟尼世尊！能以平等大慧，教菩薩法，佛所護念，妙法華經，為大眾說。如是，如是！釋迦牟尼世尊！如所說者，皆是真實。",
    anchorText: "能以平等大慧，教菩薩法，佛所護念，妙法華經",
    note: "多寶塔中出聲讚歎，為釋迦說《法華經》作證，稱所說皆是真實。",
  },
  {
    id: "t0262-005-149",
    category: "聞聲法喜",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "爾時四眾，見大寶塔住在空中，又聞塔中所出音聲，皆得法喜，怪未曾有，從座而起，恭敬合掌，却住一面。",
    anchorText: "又聞塔中所出音聲，皆得法喜",
    note: "四眾見寶塔、聞塔中音聲，皆得法喜，生未曾有心。",
  },
  {
    id: "t0262-005-150",
    category: "為聽此經",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "若我成佛、滅度之後，於十方國土有說法華經處，我之塔廟，為聽是經故，踊現其前，為作證明，讚言善哉。",
    anchorText: "於十方國土有說法華經處，我之塔廟，為聽是經故",
    note: "多寶如來本願明示：凡十方有說《法華經》處，寶塔為聽此經而現前作證。",
  },
  {
    id: "t0262-005-151",
    category: "寶塔現前",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "十方世界，在在處處，若有說法華經者，彼之寶塔皆踊出其前，全身在於塔中，讚言：『善哉，善哉！』",
    anchorText: "若有說法華經者，彼之寶塔皆踊出其前",
    note: "經文明說在在處處有說《法華經》者，多寶寶塔皆現前讚歎。",
  },
  {
    id: "t0262-005-152",
    category: "聞經讚歎",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "今多寶如來塔，聞說法華經故，從地踊出，讚言：『善哉，善哉！』",
    anchorText: "聞說法華經故，從地踊出",
    note: "佛直接說明寶塔從地踊出的原因，是聞說《法華經》故。",
  },
  {
    id: "t0262-005-153",
    category: "分身來集",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "若我寶塔，為聽法華經故，出於諸佛前時，其有欲以我身示四眾者，彼佛分身諸佛——在於十方世界說法，盡還集一處，然後我身乃出現耳。",
    anchorText: "為聽法華經故，出於諸佛前時",
    note: "多寶佛深重願力，把寶塔現前、十方分身佛來集，皆與聽《法華經》相連。",
  },
  {
    id: "t0262-005-154",
    category: "供養寶塔",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "善男子！我今應往娑婆世界，釋迦牟尼佛所，并供養多寶如來寶塔。",
    anchorText: "我今應往娑婆世界，釋迦牟尼佛所，并供養多寶如來寶塔",
    note: "十方諸佛因寶塔與法華會集，皆往娑婆供養多寶如來寶塔。",
  },
  {
    id: "t0262-005-155",
    category: "為聽經故",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "善哉，善哉！釋迦牟尼佛！快說是法華經，我為聽是經故而來至此。",
    anchorText: "快說是法華經，我為聽是經故而來至此",
    note: "多寶如來現身後再次讚歎，明說自己為聽《法華經》而來。",
  },
  {
    id: "t0262-005-156",
    category: "付囑弘經",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "誰能於此娑婆國土廣說妙法華經，今正是時。如來不久當入涅槃，佛欲以此妙法華經付囑有在。",
    anchorText: "誰能於此娑婆國土廣說妙法華經，今正是時",
    note: "佛在二如來同坐寶塔後，正式付囑於娑婆廣說《妙法華經》。",
  },
  {
    id: "t0262-005-157",
    category: "勤為法故",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "聖主世尊，雖久滅度，在寶塔中，尚為法來。諸人云何不勤為法？",
    anchorText: "雖久滅度，在寶塔中，尚為法來",
    note: "偈頌以多寶如來久滅仍為法而來，勸眾勤為法。",
  },
  {
    id: "t0262-005-158",
    category: "令法久住",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "又我分身，無量諸佛，如恒沙等，來欲聽法。及見滅度，多寶如來，各捨妙土，及弟子眾、天人龍神、諸供養事，令法久住，故來至此。",
    anchorText: "令法久住，故來至此",
    note: "十方分身佛與多寶如來來集，旨在聽法並令法久住。",
  },
  {
    id: "t0262-005-159",
    category: "護持讀說",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "我滅度後，誰能護持、讀說斯經？今於佛前，自說誓言。",
    anchorText: "誰能護持、讀說斯經",
    note: "佛直接勸眾於佛前立誓，在滅後護持、讀說此經。",
  },
  {
    id: "t0262-005-160",
    category: "供養諸佛",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "其有能護，此經法者，則為供養，我及多寶。",
    anchorText: "其有能護，此經法者，則為供養，我及多寶",
    note: "能護持此經法者，經文明說即是供養釋迦佛與多寶佛。",
  },
  {
    id: "t0262-005-161",
    category: "見佛功德",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "若說此經，則為見我、多寶如來，及諸化佛。",
    anchorText: "若說此經，則為見我、多寶如來，及諸化佛",
    note: "偈中明說說此經者，即為見釋迦、多寶如來及諸化佛。",
  },
  {
    id: "t0262-005-162",
    category: "惡世說經",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "若佛滅後，於惡世中，能說此經，是則為難。",
    anchorText: "於惡世中，能說此經，是則為難",
    note: "佛以多重譬喻襯托，佛滅後惡世能說此經最為難得。",
  },
  {
    id: "t0262-005-163",
    category: "書持難得",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "於我滅後，若自書持，若使人書，是則為難。",
    anchorText: "若自書持，若使人書，是則為難",
    note: "佛明示滅後自行書持或使人書此經，皆屬難行難得。",
  },
  {
    id: "t0262-005-164",
    category: "暫讀難得",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "佛滅度後，於惡世中，暫讀此經，是則為難。",
    anchorText: "於惡世中，暫讀此經，是則為難",
    note: "即使暫讀此經，於佛滅後惡世中亦被佛標舉為難得。",
  },
  {
    id: "t0262-005-165",
    category: "為人說經",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "我滅度後，若持此經、為一人說，是則為難。",
    anchorText: "若持此經、為一人說，是則為難",
    note: "滅後受持此經並為一人說，也是本品反覆讚歎的難行。",
  },
  {
    id: "t0262-005-166",
    category: "聽受問義",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "於我滅後，聽受此經，問其義趣，是則為難。",
    anchorText: "聽受此經，問其義趣，是則為難",
    note: "滅後能聽受此經並詢問義趣，亦被佛列為難得之事。",
  },
  {
    id: "t0262-005-167",
    category: "奉持難得",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "於我滅後，若能奉持，如斯經典，是則為難。",
    anchorText: "若能奉持，如斯經典，是則為難",
    note: "佛總結滅後奉持此經典極為難得。",
  },
  {
    id: "t0262-005-168",
    category: "此經第一",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "我為佛道，於無量土，從始至今，廣說諸經，而於其中，此經第一。",
    anchorText: "廣說諸經，而於其中，此經第一",
    note: "佛親自總讚：從始至今廣說諸經，其中此經第一。",
  },
  {
    id: "t0262-005-169",
    category: "持佛身",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "若有能持，則持佛身。",
    anchorText: "若有能持，則持佛身",
    note: "本品以極簡重語讚歎持經者：能持此經，即持佛身。",
  },
  {
    id: "t0262-005-170",
    category: "諸佛歡喜",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "此經難持，若暫持者，我則歡喜，諸佛亦然。",
    anchorText: "此經難持，若暫持者，我則歡喜，諸佛亦然",
    note: "佛明說此經難持，若能暫持，釋迦與諸佛皆歡喜。",
  },
  {
    id: "t0262-005-171",
    category: "諸佛所歎",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "如是之人，諸佛所歎。是則勇猛，是則精進，是名持戒，行頭陀者，則為疾得，無上佛道。",
    anchorText: "如是之人，諸佛所歎",
    note: "能暫持此經者為諸佛所歎，經中稱為勇猛、精進、持戒，疾得無上佛道。",
  },
  {
    id: "t0262-005-172",
    category: "真佛子",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "能於來世，讀持此經，是真佛子，住淳善地。",
    anchorText: "能於來世，讀持此經，是真佛子",
    note: "來世能讀持此經者，經文明稱為真佛子，住淳善地。",
  },
  {
    id: "t0262-005-173",
    category: "世間之眼",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "佛滅度後，能解其義，是諸天人，世間之眼。",
    anchorText: "能解其義，是諸天人，世間之眼",
    note: "佛滅後能解此經義趣者，為諸天人、世間之眼。",
  },
  {
    id: "t0262-005-174",
    category: "天人供養",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "於恐畏世，能須臾說，一切天人，皆應供養。",
    anchorText: "於恐畏世，能須臾說，一切天人，皆應供養",
    note: "在恐畏惡世中能須臾說此經者，一切天人皆應供養。",
  },
];
