import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const HUACHENG_SECTION_TITLE = "化城喻品第七";

export const T0264_JUAN_3_HUACHENG_REMAINDER_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-003-139",
    category: "聞法信解",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "是十六菩薩，常樂說是《妙法華經》，一一菩薩所化六百萬億那由他恒河沙等眾生，世世所生與菩薩俱，從其聞法悉皆信解。以此因緣，得值四萬億諸佛世尊，于今不盡。",
    anchorText: "是十六菩薩，常樂說是《妙法華經》",
    note: "十六菩萨常说《妙法华经》，所化众生世世闻法信解，得值诸佛。",
    occurrence: 1,
  },
  {
    id: "t0264-003-140",
    category: "現在說法",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "彼佛弟子十六沙彌，今皆得阿耨多羅三藐三菩提，於十方國土現在說法，有無量百千萬億菩薩、聲聞，以為眷屬。",
    anchorText: "彼佛弟子十六沙彌，今皆得阿耨多羅三藐三菩提",
    note: "十六沙弥今皆成佛，在十方国土说法，菩萨声闻眷属无量。",
    occurrence: 1,
  },
  {
    id: "t0264-003-141",
    category: "漸入佛道",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "我等為沙彌時，各各教化無量百千萬億恒河沙等眾生，從我聞法，為阿耨多羅三藐三菩提。此諸眾生，于今有住聲聞地者，我常教化阿耨多羅三藐三菩提，是諸人等，應以是法漸入佛道。",
    anchorText: "我等為沙彌時，各各教化無量百千萬億恒河沙等眾生",
    note: "释迦牟尼佛说明宿世所化众生，虽有住声闻地者，仍以此法渐入佛道。",
    occurrence: 1,
  },
  {
    id: "t0264-003-142",
    category: "得聞此經",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "我滅度後，復有弟子不聞是經，不知、不覺菩薩所行，自於所得功德，生滅度想，當入涅槃。我於餘國作佛，更有異名，是人雖生滅度之想，入於涅槃，而於彼土求佛智慧，得聞是經；唯以佛乘而得滅度，更無餘乘，除諸如來方便說法。",
    anchorText: "而於彼土求佛智慧，得聞是經",
    note: "灭后弟子虽先作灭度想，仍于彼土求佛智慧、得闻此经，终归唯一佛乘。",
    occurrence: 1,
  },
  {
    id: "t0264-003-143",
    category: "唯一佛乘",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "若如來自知涅槃時到，眾又清淨信解堅固，了達空法深入禪定，便集諸菩薩及聲聞眾，為說是經。世間無有二乘而得滅度，唯一佛乘得滅度耳。",
    anchorText: "世間無有二乘而得滅度，唯一佛乘得滅度耳",
    note: "如来于众清净信解坚固时说此经，明唯有佛乘得灭度。",
    occurrence: 1,
  },
  {
    id: "t0264-003-144",
    category: "方便信受",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "如來方便，深入眾生之性，知其志樂小法，深著五慾，為是等故說於涅槃，是人若聞則便信受。",
    anchorText: "如來方便，深入眾生之性",
    note: "如来深入众生根性，以方便说涅槃，使志乐小法者闻而信受。",
    occurrence: 1,
  },
  {
    id: "t0264-003-145",
    category: "安隱止息",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "汝等勿怖，莫得退還，今此大城可於中止，隨意所作，若入是城，快得安隱，若能前至寶所，亦可得去。",
    anchorText: "汝等勿怖，莫得退還",
    note: "化城譬喻显示导师以方便令疲惫众生止息怖畏，安隐前进。",
    occurrence: 1,
  },
  {
    id: "t0264-003-146",
    category: "如來導師",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "如來亦復如是，今為汝等作大導師，知諸生死煩惱惡道，險難長遠應去應度。",
    anchorText: "如來亦復如是，今為汝等作大導師",
    note: "佛以大导师自喻，知生死烦恼险道长远，能导众生应去应度。",
    occurrence: 1,
  },
  {
    id: "t0264-003-147",
    category: "引入佛慧",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "汝等所作未辦，汝所住地近於佛慧，當觀察籌量，所得涅槃，非真實也，但是如來方便之力，於一佛乘分別說三。",
    anchorText: "汝等所作未辦，汝所住地近於佛慧",
    note: "佛明二乘涅槃非真实究竟，是如来方便，导向一佛乘与佛慧。",
    occurrence: 1,
  },
];
