import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const MIAOYIN_SECTION_TITLE = "妙音菩薩品第二十四";

export const T0262_JUAN_7_MIAOYIN_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0262-007-017",
    category: "久植德本",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "妙音。久已植眾德本。供養親近無量百千萬億諸佛。而悉成就甚深智慧。",
    anchorText: "久已植眾德本",
    note: "妙音菩薩久植德本、供養親近無量諸佛，成就甚深智慧。",
  },
  {
    id: "t0262-007-018",
    category: "諸大三昧",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "得妙幢相三昧。法華三昧。淨德三昧。宿王戲三昧。無緣三昧。智印三昧。解一切眾生語言三昧。集一切功德三昧。清淨三昧。神通遊戲三昧。慧炬三昧。莊嚴王三昧。淨光明三昧。淨藏三昧。不共三昧。日旋三昧。得如是等百千萬億恆河沙等諸大三昧。",
    anchorText: "得妙幢相三昧",
    note: "本品列舉妙音菩薩所得法華三昧、集一切功德三昧等無量三昧。",
  },
  {
    id: "t0262-007-019",
    category: "禮佛聽經",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "我當往詣娑婆世界。禮拜親近供養釋迦牟尼佛。及見文殊師利法王子菩薩。藥王菩薩。勇施菩薩。宿王華菩薩。上行意菩薩。莊嚴王菩薩。藥上菩薩。",
    anchorText: "禮拜親近供養釋迦牟尼佛",
    note: "妙音菩薩發願來娑婆，為禮拜親近供養釋迦牟尼佛並見諸大菩薩。",
  },
  {
    id: "t0262-007-020",
    category: "勿輕娑婆",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "是故汝往。莫輕彼國。若佛菩薩及國土。生下劣想。",
    anchorText: "莫輕彼國",
    note: "淨華宿王智佛告誡妙音勿輕娑婆國土、佛與菩薩，含有敬法敬土的勸修義。",
  },
  {
    id: "t0262-007-021",
    category: "如來力用",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "世尊。我今詣娑婆世界。皆是如來之力。如來神通遊戲。如來功德智慧莊嚴。",
    anchorText: "皆是如來之力",
    note: "妙音菩薩明說往詣娑婆皆依如來之力、神通遊戲與功德智慧莊嚴。",
  },
  {
    id: "t0262-007-022",
    category: "三昧現瑞",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "於是妙音菩薩。不起於座。身不動搖。而入三昧。以三昧力。於耆闍崛山。去法座不遠。化作八萬四千眾寶蓮華。",
    anchorText: "不起於座。身不動搖。而入三昧",
    note: "妙音菩薩不起於座而入三昧，以三昧力於靈鷲山化現眾寶蓮華。",
  },
  {
    id: "t0262-007-023",
    category: "供養聽經",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "是妙音菩薩摩訶薩。欲從淨華宿王智佛國。與八萬四千菩薩圍繞。而來至此娑婆世界。供養親近禮拜於我。亦欲供養聽法華經。",
    anchorText: "亦欲供養聽法華經",
    note: "佛明說妙音菩薩來娑婆，是為供養親近禮拜佛，也為供養聽《法華經》。",
  },
  {
    id: "t0262-007-024",
    category: "勤修三昧",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "世尊。是菩薩種何善本。修何功德。而能有是大神通力。行何三昧。願為我等說是三昧名字。我等亦欲勤修行之。",
    anchorText: "我等亦欲勤修行之",
    note: "文殊因見瑞相請問三昧名字，明說大眾亦欲勤修此三昧。",
  },
  {
    id: "t0262-007-025",
    category: "供佛聞法",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "善哉善哉。汝能為供養釋迦牟尼佛。及聽法華經。并見文殊師利等故來至此。",
    anchorText: "汝能為供養釋迦牟尼佛",
    note: "多寶佛讚妙音菩薩為供養釋迦牟尼佛、聽法華經並見文殊等而來。",
  },
  {
    id: "t0262-007-026",
    category: "供養果報",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "妙音菩薩於萬二千歲。以十萬種伎樂。供養雲雷音王佛。并奉上八萬四千七寶鉢。以是因緣果報。今生淨華宿王智佛國。有是神力。",
    anchorText: "以是因緣果報",
    note: "佛明示妙音菩薩昔日以伎樂、寶鉢供佛，因緣果報今生佛國並具神力。",
  },
  {
    id: "t0262-007-027",
    category: "供佛善根",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "華德。是妙音菩薩。已曾供養親近無量諸佛。久植德本。又值恆河沙等百千萬億那由他佛。",
    anchorText: "已曾供養親近無量諸佛",
    note: "佛再次說明妙音菩薩已曾供養親近無量諸佛，久植德本。",
  },
  {
    id: "t0262-007-028",
    category: "現身說經",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "而是菩薩。現種種身。處處為諸眾生說是經典。",
    anchorText: "現種種身。處處為諸眾生說是經典",
    note: "本品總說妙音菩薩能現種種身，處處為眾生說此經典。",
  },
  {
    id: "t0262-007-029",
    category: "救濟眾難",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "或現天龍。夜叉。乾闥婆。阿修羅。迦樓羅。緊那羅。摩睺羅伽。人非人等身而說是經。諸有地獄。餓鬼。畜生。及眾難處。皆能救濟。",
    anchorText: "諸有地獄。餓鬼。畜生。及眾難處。皆能救濟",
    note: "妙音菩薩隨類現身說經，地獄、餓鬼、畜生及眾難處皆能救濟。",
  },
  {
    id: "t0262-007-030",
    category: "救護娑婆",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "華德。是妙音菩薩。能救護娑婆世界諸眾生者。",
    anchorText: "能救護娑婆世界諸眾生",
    note: "佛明說妙音菩薩能救護娑婆世界諸眾生。",
  },
  {
    id: "t0262-007-031",
    category: "智慧明照",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "是菩薩以若干智慧。明照娑婆世界。令一切眾生。各得所知。",
    anchorText: "明照娑婆世界",
    note: "妙音菩薩以若干智慧明照娑婆世界，令一切眾生各得所知。",
  },
  {
    id: "t0262-007-032",
    category: "隨類度生",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "如是種種。隨所應度而為現形。乃至應以滅度而得度者。示現滅度。",
    anchorText: "隨所應度而為現形",
    note: "佛總結妙音菩薩隨所應度而現形，乃至示現滅度以度眾生。",
  },
  {
    id: "t0262-007-033",
    category: "三昧饒益",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "善男子。其三昧名現一切色身。妙音菩薩住是三昧中。能如是饒益無量眾生。",
    anchorText: "能如是饒益無量眾生",
    note: "佛說妙音菩薩住現一切色身三昧，能如是饒益無量眾生。",
  },
  {
    id: "t0262-007-034",
    category: "聞品得益",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "說是妙音菩薩品時。與妙音菩薩俱來者八萬四千人。皆得現一切色身三昧。此娑婆世界無量菩薩。亦得是三昧及陀羅尼。",
    anchorText: "皆得現一切色身三昧",
    note: "說此品時，俱來八萬四千人及娑婆無量菩薩皆得三昧，並得陀羅尼。",
  },
  {
    id: "t0262-007-035",
    category: "來往饒益",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "世尊。我到娑婆世界。饒益眾生。見釋迦牟尼佛。及見多寶佛塔。禮拜供養。",
    anchorText: "我到娑婆世界。饒益眾生",
    note: "妙音菩薩回本國自述到娑婆世界饒益眾生，並禮拜供養釋迦佛與多寶佛塔。",
  },
  {
    id: "t0262-007-036",
    category: "聞品證法",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "說是妙音菩薩來往品時。四萬二千天子。得無生法忍。華德菩薩。得法華三昧。",
    anchorText: "四萬二千天子。得無生法忍",
    note: "本品結尾明說說此來往品時，四萬二千天子得無生法忍，華德菩薩得法華三昧。",
  },
];
