import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const CHANGBUQING_SECTION_TITLE = "常不輕菩薩品第十九";

export const T0264_JUAN_6_CHANGBUQING_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-006-044",
    category: "持经功德与护敬警策",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "汝今當知！若比丘、比丘尼、優婆塞、優婆夷，持《法華經》者，若有惡口、罵詈、誹謗，獲大罪報如前所說；其所得功德，如向所說，眼、耳、鼻、舌、身、意清淨。",
    anchorText: "持《法華經》者，若有惡口、罵詈、誹謗",
    note: "佛先重申：对持《法华经》者恶口、毁谤有大罪报；持经所得功德则是六根清净。",
  },
  {
    id: "t0264-006-045",
    category: "三乘说法究竟佛慧",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "其威音王佛，於彼世中，為天、人、阿脩羅說法，為求聲聞者，說應四諦法，度生、老、病、死究竟涅槃。為求辟支佛者，說應十二因緣法。為諸菩薩，因阿耨多羅三藐三菩提，說應六波羅蜜法，究竟佛慧。",
    anchorText: "為諸菩薩，因阿耨多羅三藐三菩提",
    note: "本品以威音王佛说法开端，显示佛随三乘根机说法，最终导向究竟佛慧。",
  },
  {
    id: "t0264-006-046",
    category: "礼敬众生皆当作佛",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "是比丘凡有所見，若比丘、比丘尼、優婆塞、優婆夷，皆悉禮拜讚歎，而作是言：『我深敬汝等，不敢輕慢。所以者何？汝等皆行菩薩道，當得作佛。』",
    anchorText: "我深敬汝等，不敢輕慢",
    note: "常不轻菩萨见四众皆礼拜赞叹，以“一切皆当作佛”示人佛性与菩萨道。",
  },
  {
    id: "t0264-006-047",
    category: "忍辱不退",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "如此經歷多年，常被罵詈，不生瞋恚，常作是言：『汝當作佛。』說是語時，眾人或以杖木、瓦、石，而打擲之。避走遠住，猶高聲唱言：『我不敢輕汝，汝等皆當作佛。』",
    anchorText: "常被罵詈，不生瞋恚",
    note: "常不轻菩萨虽多年受骂詈打掷，仍不生瞋恚，继续宣说众生当作佛。",
  },
  {
    id: "t0264-006-048",
    category: "闻持法华六根清净",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "是比丘臨欲終時，於虛空中具聞威音王佛先所說《法華經》，二十千萬億偈，悉能受持，即得如上眼根清淨，耳、鼻、舌、身、意根清淨，得是六根清淨已，更增壽命二百萬億那由他歲，廣為人說是《法華經》。",
    anchorText: "於虛空中具聞威音王佛先所說《法華經》",
    note: "常不轻临终闻《法华经》并受持，得六根清净、增益寿命，进而广为人说。",
  },
  {
    id: "t0264-006-049",
    category: "闻法信伏随从",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "於時增上慢四眾——比丘、比丘尼、優婆塞、優婆夷，輕賤是人為作不輕名者，見其得大神通力、樂說辯力、大善寂力，聞其所說，皆信伏隨從。",
    anchorText: "見其得大神通力、樂說辯力、大善寂力",
    note: "昔日轻慢者见常不轻得神通、辩才与寂力，闻其说法，皆能信伏随从。",
  },
  {
    id: "t0264-006-050",
    category: "教化众生住菩提",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "是菩薩復化千萬億眾，令住阿耨多羅三藐三菩提，命終之後，得值二千億佛，皆號日月燈明，於其法中說是《法華經》，",
    anchorText: "復化千萬億眾，令住阿耨多羅三藐三菩提",
    note: "常不轻复教化千万亿众安住无上菩提，命终之后又值无量诸佛并说《法华经》。",
  },
  {
    id: "t0264-006-051",
    category: "说经得根净无畏",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "於此諸佛法中，受持讀誦，為諸四眾說此經典故，得是常眼清淨，耳、鼻、舌、身、意諸根清淨，於四眾中說法心無所畏。",
    anchorText: "受持讀誦，為諸四眾說此經典故",
    note: "于诸佛法中受持读诵、为四众说此经典，得诸根清净，说法无所畏。",
  },
  {
    id: "t0264-006-052",
    category: "供佛种善功德成就",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "是常不輕菩薩摩訶薩，供養如是若干諸佛，恭敬、尊重、讚歎，種諸善根，於後復值千萬億佛，亦於諸佛法中說是經典，功德成就當得作佛。",
    anchorText: "供養如是若干諸佛，恭敬、尊重、讚歎",
    note: "常不轻供养诸佛、种诸善根，并于诸佛法中说此经典，功德成就而当作佛。",
  },
  {
    id: "t0264-006-053",
    category: "受持说经疾得菩提",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "若我於宿世不受持讀誦此經為他人說者，不能疾得阿耨多羅三藐三菩提；我於先佛所，受持讀誦此經為他人說故，疾得阿耨多羅三藐三菩提。",
    anchorText: "受持讀誦此經為他人說故",
    note: "佛以自身宿因说明：受持读诵《法华经》并为人说，是疾得无上菩提的因缘。",
  },
  {
    id: "t0264-006-054",
    category: "轻贱罪报与终蒙教化",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "彼時四眾比丘、比丘尼、優婆塞、優婆夷，以瞋恚意輕賤我故，二百億劫，常不值佛、不聞法、不見僧，千劫於阿鼻地獄受大苦惱；畢是罪已，復遇常不輕菩薩教化阿耨多羅三藐三菩提。",
    anchorText: "以瞋恚意輕賤我故",
    note: "经文明示轻贱菩萨的严重果报，同时也说罪尽后仍蒙常不轻菩萨教化趣向菩提。",
  },
  {
    id: "t0264-006-055",
    category: "法华饶益诸菩萨",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "當知是《法華經》，大饒益諸菩薩摩訶薩，能令至於阿耨多羅三藐三菩提，是故諸菩薩摩訶薩，於如來滅後，常應受持、讀誦、解說、書寫是經。",
    anchorText: "大饒益諸菩薩摩訶薩",
    note: "佛总结《法华经》能大饶益菩萨，令至无上菩提，故灭后应常受持、读诵、解说、书写。",
  },
  {
    id: "t0264-006-056",
    category: "不轻菩萨能忍受之",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "不輕菩薩，往到其所，而語之言：『我不輕汝，汝等行道，皆當作佛。』諸人聞已，輕毀罵詈；不輕菩薩，能忍受之；",
    anchorText: "我不輕汝，汝等行道，皆當作佛",
    note: "偈颂重申常不轻的核心行持：以礼敬宣示众生当作佛，并能忍受轻毁骂詈。",
  },
  {
    id: "t0264-006-057",
    category: "闻经根净广说",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "其罪畢已，臨命終時，得聞此經，六根清淨，神通力故，增益壽命，復為諸人，廣說是經。",
    anchorText: "臨命終時，得聞此經，六根清淨",
    note: "偈颂概括常不轻得闻此经后，六根清净、增益寿命、广说此经。",
  },
  {
    id: "t0264-006-058",
    category: "说经得福疾成佛道",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "不輕命終，值無數佛，說是經故，得無量福；漸具功德，疾成佛道。",
    anchorText: "說是經故，得無量福",
    note: "偈颂说明常不轻命终后值无数佛，因说此经得无量福，渐具功德而疾成佛道。",
  },
  {
    id: "t0264-006-059",
    category: "闻经勿疑广说疾成佛道",
    sectionTitle: CHANGBUQING_SECTION_TITLE,
    text: "是故行者，於佛滅後，聞如是經，勿生疑惑；應當一心，廣說此經，世世值佛，疾成佛道。",
    anchorText: "聞如是經，勿生疑惑",
    note: "结偈劝行者于佛灭后闻此经不生疑惑，应一心广说，世世值佛，疾成佛道。",
  },
];
