import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const PUMEN_SECTION_TITLE = "觀世音菩薩普門品第二十四";

export const T0264_JUAN_7_PUMEN_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-007-021",
    category: "稱名解脫",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若有無量百千萬億眾生受諸苦惱，聞是觀世音菩薩，一心稱名觀世音菩薩，即時觀其音聲皆得解脫。",
    anchorText: "一心稱名觀世音菩薩",
    note: "佛明说受诸苦恼众生闻名一心称念，即时观其音声皆得解脱。",
  },
  {
    id: "t0264-007-022",
    category: "火難不燒",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若有持是觀世音菩薩名者，設入大火火不能燒，由是菩薩威神力故。",
    anchorText: "設入大火火不能燒",
    note: "受持观世音菩萨名者，入大火而火不能烧。",
  },
  {
    id: "t0264-007-023",
    category: "水難得濟",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若為大水所漂，稱其名號即得淺處。",
    anchorText: "稱其名號即得淺處",
    note: "遇大水漂流，称其名号即得浅处。",
  },
  {
    id: "t0264-007-024",
    category: "羅剎難解脫",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "其中若有乃至一人稱觀世音菩薩名者，是諸人等皆得解脫羅剎之難。",
    anchorText: "皆得解脫羅剎之難",
    note: "入海遇黑风堕罗刹鬼国，只要有人称名，众人皆得解脱罗刹之难。",
  },
  {
    id: "t0264-007-025",
    category: "刀杖解脫",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若復有人臨當被害，稱觀世音菩薩名者，彼所執刀杖尋段段壞而得解脫。",
    anchorText: "彼所執刀杖尋段段壞",
    note: "临当被害而称名，所执刀杖段段坏，得以解脱。",
  },
  {
    id: "t0264-007-026",
    category: "惡鬼不害",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "聞其稱觀世音菩薩名者，是諸惡鬼尚不能以惡眼視之，況復加害。",
    anchorText: "尚不能以惡眼視之",
    note: "夜叉罗刹闻人称名，尚不能以恶眼视之，何况加害。",
  },
  {
    id: "t0264-007-027",
    category: "繫縛解脫",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "設復有人，若有罪、若無罪，杻械枷鎖撿繫其身，稱觀世音菩薩名者，皆悉斷壞即得解脫。",
    anchorText: "皆悉斷壞即得解脫",
    note: "杻械枷锁系身，称观世音名，皆悉断坏而得解脱。",
  },
  {
    id: "t0264-007-028",
    category: "怨賊解脫",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "其中一人作是唱言：『諸善男子！勿得恐怖！汝等應當一心稱觀世音菩薩名號，是菩薩能以無畏施於眾生，汝等若稱名者，於此怨賊當得解脫。』眾商人聞俱發聲言：『南無觀世音菩薩！』稱其名故即得解脫。",
    anchorText: "稱其名故即得解脫",
    note: "商人遇怨贼险路，一心称名，称其名故即得解脱。",
  },
  {
    id: "t0264-007-029",
    category: "威神巍巍",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "觀世音菩薩摩訶薩威神之力，巍巍如是。",
    anchorText: "威神之力，巍巍如是",
    note: "佛总赞观世音菩萨威神之力巍巍如是。",
  },
  {
    id: "t0264-007-030",
    category: "離貪瞋癡",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若有眾生多於婬欲，常念恭敬觀世音菩薩，便得離欲。若多瞋恚，常念恭敬觀世音菩薩，便得離瞋。若多愚癡，常念恭敬觀世音菩薩，便得離癡。",
    anchorText: "常念恭敬觀世音菩薩",
    note: "多欲、多瞋、多痴众生，常念恭敬观世音菩萨，便得离欲、离瞋、离痴。",
  },
  {
    id: "t0264-007-031",
    category: "多所饒益",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "觀世音菩薩有如是等大威神力，多所饒益。是故眾生常應心念。",
    anchorText: "多所饒益",
    note: "佛劝众生常应心念观世音菩萨，因其大威神力多所饶益。",
  },
  {
    id: "t0264-007-032",
    category: "求子得益",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若有女人，設欲求男，禮拜恭敬觀世音菩薩，便生福德智慧之男；設欲求女，便生端正有相之女，宿殖德本，眾人愛敬。",
    anchorText: "便生福德智慧之男",
    note: "欲求男、女而礼拜恭敬观世音菩萨，得福德智慧之男或端正有相之女。",
  },
  {
    id: "t0264-007-033",
    category: "福不唐捐",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若有眾生恭敬禮拜觀世音菩薩，福不唐捐。是故眾生皆應受持觀世音菩薩名號。",
    anchorText: "福不唐捐",
    note: "恭敬礼拜观世音菩萨，福不唐捐，故众生皆应受持名号。",
  },
  {
    id: "t0264-007-034",
    category: "福德無邊",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若復有人，受持觀世音菩薩名號，乃至一時禮拜供養，是二人福正等無異，於百千萬億劫不可窮盡。",
    anchorText: "於百千萬億劫不可窮盡",
    note: "受持观世音菩萨名号乃至一时礼拜供养，其福百千万亿劫不可穷尽。",
  },
  {
    id: "t0264-007-035",
    category: "福德之利",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "受持觀世音菩薩名號，得如是無量無邊福德之利。",
    anchorText: "無量無邊福德之利",
    note: "佛总结受持观世音菩萨名号，得无量无边福德之利。",
  },
  {
    id: "t0264-007-036",
    category: "隨類說法",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若有國土眾生應以佛身得度者，觀世音菩薩即現佛身而為說法。",
    anchorText: "即現佛身而為說法",
    note: "观世音菩萨随众生所应得度，乃至现佛身而为说法。",
  },
  {
    id: "t0264-007-037",
    category: "遊國度生",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "觀世音菩薩成就如是功德，以種種形遊諸國土，度脫眾生。",
    anchorText: "以種種形遊諸國土",
    note: "佛总结观世音菩萨成就功德，以种种形游诸国土度脱众生。",
  },
  {
    id: "t0264-007-038",
    category: "施無畏者",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "是觀世音菩薩摩訶薩於怖畏急難之中能施無畏，是故此娑婆世界皆號之為施無畏者。",
    anchorText: "怖畏急難之中能施無畏",
    note: "观世音菩萨于怖畏急难中能施无畏，故号施无畏者。",
  },
  {
    id: "t0264-007-039",
    category: "愍眾受供",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "即時觀世音菩薩愍諸四眾及於天、龍、人非人等故，受其瓔珞，分作二分，一分奉釋迦牟尼佛，一分奉多寶佛塔。",
    anchorText: "愍諸四眾及於天、龍、人非人等",
    note: "观世音菩萨愍念四众及天龙人非人等，受供后分奉二佛。",
  },
  {
    id: "t0264-007-040",
    category: "願海深廣",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "汝聽觀音行，善應諸方所，弘誓深如海，歷劫不思議，侍多千億佛，發大清淨願。",
    anchorText: "弘誓深如海",
    note: "偈颂赞观音行善应诸方，弘誓深如海，历劫不思议。",
  },
  {
    id: "t0264-007-041",
    category: "滅諸有苦",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "我為汝略說，聞名及見身，心念不空過，能滅諸有苦。",
    anchorText: "心念不空過",
    note: "闻名、见身、心念观音不空过，能灭诸有苦。",
  },
  {
    id: "t0264-007-042",
    category: "念力救難",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "假使興害意，推落大火坑；念彼觀音力，火坑變成池。",
    anchorText: "念彼觀音力，火坑變成池",
    note: "偈颂以火坑变池赞念观音力能救火难。",
  },
  {
    id: "t0264-007-043",
    category: "眾難不害",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "或值怨賊繞，各執刀加害；念彼觀音力，咸即起慈心。",
    anchorText: "咸即起慈心",
    note: "遇怨贼围绕执刀加害，念观音力，怨贼即起慈心。",
  },
  {
    id: "t0264-007-044",
    category: "救苦滅惡趣",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "眾生被困厄，無量苦逼身；觀音妙智力，能救世間苦。具足神通力，廣修智方便，十方諸國土，無剎不現身。種種諸惡趣，地獄鬼畜生；生老病死苦，以漸悉令滅。",
    anchorText: "觀音妙智力，能救世間苦",
    note: "偈颂总赞观音妙智力能救世间苦，并令恶趣、生老病死苦渐灭。",
  },
  {
    id: "t0264-007-045",
    category: "法雨滅惱",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "無垢清淨光，慧日破諸闇；能伏災風火，普明照世間。悲體戒雷震，慈意妙大雲；澍甘露法雨，滅除煩惱焰。",
    anchorText: "澍甘露法雨，滅除煩惱焰",
    note: "偈颂赞观音慧日破暗、法雨灭除烦恼焰。",
  },
  {
    id: "t0264-007-046",
    category: "依怙頂禮",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "念念勿生疑，觀世音淨聖；於苦惱死厄，能為作依怙。具一切功德，慈眼視眾生；福聚海無量，是故應頂禮。",
    anchorText: "於苦惱死厄，能為作依怙",
    note: "偈颂劝念念勿疑，观世音于苦恼死厄能作依怙，福聚海无量，应顶礼。",
  },
  {
    id: "t0264-007-047",
    category: "聞品功德",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若有眾生，聞是〈觀世音菩薩品〉自在之業普門示現神通力者，當知是人功德不少。",
    anchorText: "當知是人功德不少",
    note: "持地菩萨明说闻此品自在之业、普门示现神通力者，功德不少。",
  },
  {
    id: "t0264-007-048",
    category: "聞品發心",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "佛說是〈普門品〉時，眾中八萬四千眾生，皆發無等等阿耨多羅三藐三菩提心。",
    anchorText: "八萬四千眾生，皆發無等等阿耨多羅三藐三菩提心",
    note: "佛说普门品时，八万四千众生皆发无等等阿耨多罗三藐三菩提心。",
  },
];
