import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const LEPUXIAN_SECTION_TITLE = "樂普賢品第二十六";

export const T0263_JUAN_10_LEPUXIAN_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-060",
    category: "樂聞經法",
    text: "我從寶超威王如來佛土來，承今世尊演《正法華經》，故至忍界欲得聽受，與諸菩薩無數百千，亦樂聽聞所宣道議。",
    anchorText: "承今世尊演《正法華經》",
    note: "普贤菩萨从他方佛土来，为听受《正法华经》，并与无数菩萨乐闻所宣道义。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-061",
    category: "得經因緣",
    text: "女人有四事法，得是經卷。何謂為四？一曰常為諸佛所見建護，二曰積功累德不以懈廢，三曰能分別化究暢眾要諸所聚處，四曰普護眾生發未發者。",
    anchorText: "女人有四事法，得是經卷",
    note: "佛说明得奉持经卷的四种因缘：诸佛护念、积累功德、分别法要、护众生发心。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-062",
    category: "擁護法師",
    text: "若有比丘受是經典，長擁護之令得吉祥，除眾抂橫毒亦不行，令無伺求得其便者。",
    anchorText: "若有比丘受是經典",
    note: "普贤菩萨发愿在末世拥护受持此经者，使其得吉祥、远离横难毒害。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-063",
    category: "護持安隱",
    text: "有受是經，咸共宿衛，令魔波旬不能嬈亂，及諸官屬諸鬼神龍，溝邊溷鬼蠱道符呪，令不得行躬身自往，常以一心擁護法師，常使安隱。",
    anchorText: "有受是經，咸共宿衛",
    note: "受持此经者蒙普贤及眷属宿卫，魔事、鬼神、符咒不得扰乱，常得安隐。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-064",
    category: "不忘經義",
    text: "受是經者，思惟行者，令不忘失《正法華經》一句之義，乘駕往詣此學士所，目自奉見，為是經舉，見我歡喜普更勤學，當護法師逮得三昧。",
    anchorText: "令不忘失《正法華經》一句之義",
    note: "普贤护持受持思惟此经的人，使其不忘一句义，并护令得三昧。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-065",
    category: "總持成就",
    text: "若復獲致迴轉總持，又當逮成若干百千億周旋總持，曉了一切諸音總持。",
    anchorText: "又當逮成若干百千億周旋總持",
    note: "经文说明在普贤护持下，可得回转总持，并成就多种总持、晓了一切诸音。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-066",
    category: "精進開解",
    text: "若能受是《正法華經》，心存解義精進不廢，致二十一日諸行稍備，已致諸行，二十一日勤心存於法，自現可敬巍巍之德，乘六通馳，與諸眷屬大小相隨，往詣法師勸助法師，二十一日專修此法，使心開解懷致總持。",
    anchorText: "心存解義精進不廢",
    note: "末世受持此经、存心解义并精进不废者，得普贤劝助，心开解而怀致总持。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-067",
    category: "常行精進",
    text: "是故學者常行精進，承佛威神宿衛法師。",
    anchorText: "是故學者常行精進",
    note: "本品劝学者常行精进，并承佛威神护卫法师。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-068",
    category: "聞總持力",
    text: "若有菩薩，耳根聽聞此總持句，入耳中者，即當知之，普賢菩薩之所建立。",
    anchorText: "耳根聽聞此總持句",
    note: "听闻此总持句者，应知是普贤菩萨所建立。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-069",
    category: "威神得經",
    text: "是《正法華經》若布天下，閻浮利內值是經者，心當思念：『普賢菩薩威神所致，令我等輩致是經卷，普賢菩薩所行神化，令此眾人致此妙典。』",
    anchorText: "普賢菩薩威神所致",
    note: "经文提示，若在阎浮提值遇此经，应念这是普贤威神所致。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-070",
    category: "如來摩頂",
    text: "斯等眾生，無數佛所積眾德本，如來、至真手摩其頭。",
    anchorText: "無數佛所積眾德本",
    note: "得遇此妙典者，是于无数佛所积众德本，蒙如来手摩其头。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-071",
    category: "書持敬法",
    text: "若有書寫執持在手，則奉佛身、敬愛道法。",
    anchorText: "書寫執持在手",
    note: "经文明说书写并执持经卷在手，即是奉佛身、敬爱道法。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-072",
    category: "書經生天",
    text: "敬書是經，書是經已欲解中義，於此壽終生忉利天。適生天上，八萬四千天人玉女，往就供養鼓琴歌頌，已作天子坐玉女中，而相娛樂。",
    anchorText: "敬書是經，書是經已欲解中義",
    note: "敬书此经并欲解其中义者，命终生忉利天，受天人供养歌颂。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-073",
    category: "書經功德",
    text: "若族姓子，但書是經功德如是，何況誦說思惟中義！",
    anchorText: "但書是經功德如是",
    note: "普贤以书经功德为例，进而赞叹诵说思惟经义的功德更胜。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-074",
    category: "千佛授臂",
    text: "為千佛所見授臂，臨壽終時面見千佛",
    anchorText: "為千佛所見授臂",
    note: "书写此经至德所致，临终面见千佛，不堕恶趣，后生兜率天。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-075",
    category: "勤修具足",
    text: "是故勤修書寫宣傳《正法華經》，思惟奉行皆令具足，專精一心志未曾亂，千佛授臂。臨壽終時，面見千佛不墮惡趣，於是壽終生兜術天，在彌勒佛所成菩薩身，三十二相莊嚴其體，億千玉女眷屬圍遶，是故智者，常當勤修書是經典敷演思惟。",
    anchorText: "勤修書寫宣傳《正法華經》",
    note: "经文明劝勤修书写、宣传、思惟奉行此经，得千佛授臂、面见千佛、不堕恶趣，生兜率天。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-076",
    category: "功祚無量",
    text: "若有書此經卷思惟誦說，功祚無量不可稱限，巍巍如是。",
    anchorText: "書此經卷思惟誦說",
    note: "普贤总赞书写、思惟、诵说此经，功祚无量不可称限。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-077",
    category: "流布天下",
    text: "吾以是故，建立是經，用五弘意勤念道法，流布天下閻浮利內。",
    anchorText: "建立是經，用五弘意勤念道法",
    note: "普贤明示建立此经、勤念道法，令其流布阎浮提。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-078",
    category: "護將來眾",
    text: "汝乃發心多所哀念，精進勤護將來菩薩，勸道於斯無思誼法，其心懷抱無極大哀，發心之頃攝無量行，各執經卷建立擁護。",
    anchorText: "精進勤護將來菩薩",
    note: "佛赞普贤发心哀念、精进护持将来菩萨，建立拥护此经。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-079",
    category: "見佛聞法",
    text: "若有受持普賢菩薩宣其名者，則當知之見能仁佛，前已曾聞如是像法，供養奉事見能仁佛，班宣經道講讚善哉，如來摩頭，則當謂之是普賢也。",
    anchorText: "受持普賢菩薩宣其名者",
    note: "受持并称扬普贤名者，经文称其如见能仁佛、曾闻此法，并蒙如来摩头。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-080",
    category: "聞經奉行",
    text: "若聞是經，書寫聽受持諷誦說，樂如是像，自然之法思惟奉行，緣內精專自興福力，一切眾生若有覩見，靡不愛敬。",
    anchorText: "若聞是經，書寫聽受持諷誦說",
    note: "闻此经而书写、听受、持诵、宣说并思惟奉行者，自兴福力，众生见者皆爱敬。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-081",
    category: "離諸繫縛",
    text: "若有比丘受持此經，不為婬怒愚癡所縛，不為貪嫉自大所繫，不懷憍慢剛強自用彊梁邪見，己利止足。",
    anchorText: "受持此經，不為婬怒愚癡所縛",
    note: "受持此经者不为淫怒痴、贪嫉自大等所缚，能止足己利。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-082",
    category: "必至道場",
    text: "若有比丘受持是經，當作是知思惟解念：『是等族姓子，必至道場降伏魔宮，而轉法輪擊於法鼓，吹大法螺演時法雨，於師子座而處法座。』最後末俗世受持是經，功德如是。",
    anchorText: "必至道場降伏魔宮",
    note: "佛说明末世受持此经者，当知必至道场、降伏魔宫、转法轮。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-083",
    category: "現世安隱",
    text: "若有比丘受持是經，世世不忘所生聰明黠慧，未曾聾盲，現在獲安無有眾患。",
    anchorText: "世世不忘所生聰明黠慧",
    note: "受持此经者世世不忘，聪明黠慧，现世安稳无诸患难。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-084",
    category: "謗經罪報",
    text: "若毀此經訶學持者而復誹謗，其人現在身致癩病。",
    anchorText: "若毀此經訶學持者",
    note: "本品也以反面警示毁谤此经、呵责学持者的恶报，劝人敬慎护法。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-085",
    category: "恭敬法師",
    text: "若見比丘受持是經，遙起遠迎恭敬承事，如奉如來。",
    anchorText: "遙起遠迎恭敬承事",
    note: "佛劝见受持此经的比丘，应远迎恭敬承事，如奉如来。",
  },
  {
    sectionTitle: LEPUXIAN_SECTION_TITLE,
    id: "t0263-010-086",
    category: "聞品得持",
    text: "佛說是樂普賢品時，如江河沙億百千姟諸菩薩眾，皆逮總持。",
    anchorText: "佛說是樂普賢品時",
    note: "本品结尾明说佛说此品时，无量菩萨众皆得总持。",
  },
];