import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const YINGSHI_SECTION_TITLE = "應時品第三";

export const T0263_JUAN_2_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0263-002-001",
    category: "聞法歡喜",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "今聞大聖講斯法要，心加歡喜得未曾有。",
    anchorText: "今聞大聖講斯法要",
    note: "舍利弗闻佛讲此法要，欢喜得未曾有。",
  },
  {
    id: "t0263-002-002",
    category: "得聞佛乘",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "得聞佛乘，一句之業，超出本望，怪未曾有。",
    anchorText: "得聞佛乘，一句之業",
    note: "经文以偈赞得闻佛乘一句之业，已超出本望。",
  },
  {
    id: "t0263-002-003",
    category: "除疑歡欣",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "普興柔軟，深妙之道，以佛音聲，而得歡欣。今日所有，諸志猶預，以棄沈吟，住於聖慧。",
    anchorText: "普興柔軟，深妙之道",
    note: "佛音宣说深妙之道，令闻者欢欣并舍弃犹疑。",
  },
  {
    id: "t0263-002-004",
    category: "受經佛護",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "舍利弗！汝因本行欲得識念無央數佛，則當受斯《正法華經》一切佛護，普為聲聞分別說之。",
    anchorText: "則當受斯《正法華經》一切佛護",
    note: "佛劝舍利弗受此《正法华经》，明其为一切佛所护。",
  },
  {
    id: "t0263-002-005",
    category: "授記成佛",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "汝於來世無量無數不可計劫，供養億百千佛受正法教，奉敬修行此方等經，具足眾行當得佛道，號蓮華光如來、至真、等正覺、明行成為、善逝、世間解、無上士、道法御、天人師，其世界名離垢。",
    anchorText: "奉敬修行此方等經，具足眾行當得佛道",
    note: "舍利弗因供佛受法、奉敬修行此方等经而得授记成佛。",
  },
  {
    id: "t0263-002-006",
    category: "佛土清淨",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "平等快樂威曜巍巍，諸行清淨所立安隱，米穀豐賤人民繁熾，男女眾多具足周備，琉璃黃金以為長繩，連綿路傍一切路邊，有七寶樹八重交道，行樹枝葉華實常茂。",
    anchorText: "平等快樂威曜巍巍",
    note: "授记中描绘莲华光佛国平等快乐、清净安隐、七宝庄严。",
  },
  {
    id: "t0263-002-007",
    category: "開化眾生",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "卿舍利弗，於當來世，得成為佛，顯如來尊，號蓮華光，普平等目，教授開化，眾庶億千。",
    anchorText: "得成為佛，顯如來尊",
    note: "偈颂中重申舍利弗当成佛，并教授开化众多众生。",
  },
  {
    id: "t0263-002-008",
    category: "供佛成道",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "奉事無數，諸佛億載，於彼修力，多所興立，所在勸化，得為十力，便當成就，上尊佛道。",
    anchorText: "奉事無數，諸佛億載",
    note: "经文赞供奉无数诸佛、修力劝化，终成上尊佛道。",
  },
  {
    id: "t0263-002-009",
    category: "聞記歡喜",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "聞佛世尊授舍利弗決，當成無上正真之道，心懷欣豫歡喜踊躍，不能自勝，各自脫身衣以覆佛上。",
    anchorText: "聞佛世尊授舍利弗決",
    note: "四众闻舍利弗授记成佛，欢喜踊跃并供养世尊。",
  },
  {
    id: "t0263-002-010",
    category: "無上法輪",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "今所聞法自昔未有，前波羅奈鹿苑之中，始轉法輪蓋不足言，今佛世尊則復講說無上法輪。",
    anchorText: "今佛世尊則復講說無上法輪",
    note: "诸天赞叹此番所闻昔未曾有，是佛再转无上法轮。",
  },
  {
    id: "t0263-002-011",
    category: "決除疑網",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "善哉！世尊！願說要誼，使此比丘疑網悉除。今四部眾意咸悵悵，當令坦然無餘結恨。",
    anchorText: "使此比丘疑網悉除",
    note: "舍利弗请佛说要义，愿使比丘疑网尽除、四众坦然。",
  },
  {
    id: "t0263-002-012",
    category: "善權示現",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "以若干種善權方便，隨其因緣而示現之，如來、至真、等正覺所分別演，皆為無上正真道故，我所諮嗟皆當知之，為菩薩也。",
    anchorText: "以若干種善權方便",
    note: "佛明所说种种方便，皆为引向无上正真道。",
  },
  {
    id: "t0263-002-013",
    category: "平等大乘",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "究竟諸子志操所趣，故以方便令免患禍，況復貯畜無量寶藏，以一色類平等大乘賜子不虛。",
    anchorText: "以一色類平等大乘賜子不虛",
    note: "火宅譬喻说明以方便免难，终以平等大乘施与诸子。",
  },
  {
    id: "t0263-002-014",
    category: "如來救護",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "法王神力為世之父，善權方便攝持恩議，行乎大悲道心無盡，愍哀三界大火熾然，黎庶不解故現世間，救濟眾生生老病死諸不可意結縛之惱，裂壞所著、脫婬怒癡，誘導三乘，漸漸勸示無上正真之道。",
    anchorText: "救濟眾生生老病死",
    note: "如来以大悲和善权方便救济众生，令离诸恼并趣无上道。",
  },
  {
    id: "t0263-002-015",
    category: "施大安樂",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "三界眾生勤苦之患，吾當施立無極大安，無數百千不可思議諸佛正慧。",
    anchorText: "吾當施立無極大安",
    note: "佛见三界众生勤苦，欲施立无极大安与诸佛正慧。",
  },
  {
    id: "t0263-002-016",
    category: "三乘出苦",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "如來正覺以力、無畏建立眾德，善權方便修勇猛慧，覩見三界然熾之宅，欲以救濟眾生諸難，故現聲聞、緣覺、菩薩之道，以是三乘開化驅馳使棄愛欲，教諸萌類滅三界火、婬怒癡縛，色聲香味細滑之法，三處五欲五欲燒人，不猗三界便得三乘，勤精三乘則超三界，進三乘者諸佛所訓也。",
    anchorText: "欲以救濟眾生諸難",
    note: "三乘是如来救济众难的方便，令众生离爱欲、灭三界火。",
  },
  {
    id: "t0263-002-017",
    category: "菩薩大乘",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "假使有人，求諸通慧諸佛道慧，自在聖慧自從心出，無師主慧多所哀念，多所安隱諸天人民，欲利天上世間人民，滅度黎庶於如來法，奉修精進欲求大聖，普見之慧力無所畏，謂如來道，菩薩大士所履乘也。",
    anchorText: "多所哀念，多所安隱諸天人民",
    note: "经文界定菩萨大乘为求佛道慧、安隐利乐天人世间。",
  },
  {
    id: "t0263-002-018",
    category: "歸於佛乘",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "如來爾時從終始宅，以無數慧、力、無所畏，觀眾罹厄矜哀喻子，普勸進使歸於佛乘，不令各各從意而滅度也，如來悉誘以佛滅度而滅度之。",
    anchorText: "普勸進使歸於佛乘",
    note: "如来以智慧、力、无所畏普劝众生归于佛乘。",
  },
  {
    id: "t0263-002-019",
    category: "唯一佛乘",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "如來如是，本現三乘，然後皆化使入大乘，不為虛妄。所以者何？當知如來等覺有無央數倉庫帑藏，以得自在，為諸黎庶現大法化諸通愍慧，當作是知、當解此誼。如來等正覺善權方便，以慧行音唯說一乘，謂佛乘也。",
    anchorText: "以慧行音唯說一乘",
    note: "佛先现三乘，最终皆令入大乘；究竟唯说一乘佛乘。",
  },
  {
    id: "t0263-002-020",
    category: "出宅安隱",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "驅逐一切，迸出災屋，得脫苦惱，集子一處，安隱歡然，無復恐懼。",
    anchorText: "得脫苦惱，集子一處",
    note: "火宅譬喻以出离灾屋表示得脱苦恼、安隐无惧。",
  },
  {
    id: "t0263-002-021",
    category: "方便良藥",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "善權方便，為大良藥，分別三乘，以示眾生。",
    anchorText: "善權方便，為大良藥",
    note: "偈颂直接称善权方便为大良药，以三乘示众生。",
  },
  {
    id: "t0263-002-022",
    category: "近佛道乘",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "緣是得近，於佛道乘，受斯一切，得為最勝。",
    anchorText: "得近，於佛道乘",
    note: "由譬喻教法，众生得近佛道乘并得最胜。",
  },
  {
    id: "t0263-002-023",
    category: "一乘無二",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "告舍利弗，卿當知是，計有一乘，則無有二。",
    anchorText: "計有一乘，則無有二",
    note: "卷二核心结论之一：究竟唯有一乘，无有二乘。",
  },
  {
    id: "t0263-002-024",
    category: "佛恩普等",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "佛恩普潤，譬如良田，隨其所種，各得其類。種者所殖，非地增減，佛亦如是，一切普等。",
    anchorText: "佛恩普潤，譬如良田",
    note: "经文以良田喻佛恩普润、一切平等。",
  },
  {
    id: "t0263-002-025",
    category: "導出生死",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "三界之中，恐畏之難，佛為唱導，使得滅度。諸賢無為，今日乃知，棄捐生死，脫勤苦患。",
    anchorText: "佛為唱導，使得滅度",
    note: "佛为三界恐畏作唱导，使众生知离生死勤苦。",
  },
  {
    id: "t0263-002-026",
    category: "解脫成道",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "無所滅度，便見導師。佛何以故，而說解脫？無所逮者，乃成佛道。",
    anchorText: "無所逮者，乃成佛道",
    note: "经文以甚深义说明解脱与成佛道的究竟指归。",
  },
  {
    id: "t0263-002-027",
    category: "法印善說",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "告舍利弗，是吾法印，是佛最後，微妙善說，愍傷諸天，及於世間，在所遊處，常能獨行。",
    anchorText: "是吾法印，是佛最後",
    note: "佛称此为法印、最后微妙善说，愍念诸天与世间。",
  },
  {
    id: "t0263-002-028",
    category: "講說奉持",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "假使有人，講說是典，若有勸助，代歡喜者，聞其妙法，當奉持之，為悉供養，過去諸佛，奉持此法，至不退轉。",
    anchorText: "講說是典，若有勸助",
    note: "讲说、劝助、随喜闻此妙法者，应奉持此法，至不退转。",
  },
  {
    id: "t0263-002-029",
    category: "信樂斯經",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "假使有人，信樂斯經，往古已見，過去導師，亦悉奉順，諸聖至尊，加得逮聞，如是典摸，皆得曾見，吾之儀容。",
    anchorText: "信樂斯經，往古已見",
    note: "信乐此经者，过去已见导师、奉顺诸圣，并得闻此典。",
  },
  {
    id: "t0263-002-030",
    category: "信經功德",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "一切皆瞻，是諸菩薩，其信此經，則亦如是。",
    anchorText: "其信此經，則亦如是",
    note: "佛以菩萨为喻，赞信此经者亦具殊胜相。",
  },
  {
    id: "t0263-002-031",
    category: "謗經果報",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "謗佛斯經，獲罪若此。",
    anchorText: "謗佛斯經，獲罪若此",
    note: "本品严厉警策谤此经之罪报。",
  },
  {
    id: "t0263-002-032",
    category: "不見導師",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "若有誹謗，斯經之罪，未曾得見，世雄導師。",
    anchorText: "若有誹謗，斯經之罪",
    note: "经文说明诽谤此经者，不得见世雄导师。",
  },
  {
    id: "t0263-002-033",
    category: "擇機聽受",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "其有聰明，廣博多聞，秉志堅強，常修憶辨，若有勸發，遵尚佛道，爾乃聽受，未曾有法。",
    anchorText: "其有聰明，廣博多聞",
    note: "佛说明应为聪明多闻、志坚向道者听受未曾有法。",
  },
  {
    id: "t0263-002-034",
    category: "殖功德本",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "則以睹見，億百千佛，殖無央數，如意功德。其人志性，猛如月光，爾乃聽受，如是典籍。",
    anchorText: "殖無央數，如意功德",
    note: "能听受此典者，已见亿百千佛、殖无数功德。",
  },
  {
    id: "t0263-002-035",
    category: "精進慈悲",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "若有精進，志常懷慈，常於夙夜，炤燿悲哀，朽棄軀體，不惜壽命，爾乃聽受，於斯經卷。",
    anchorText: "若有精進，志常懷慈",
    note: "精进怀慈、不惜身命者，适合听受此经卷。",
  },
  {
    id: "t0263-002-036",
    category: "奉持經卷",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "不犯禁戒，如寶明珠，志習奉受，方等諸經，當見如茲，佛聖子孫，常專精此，一品經卷。",
    anchorText: "志習奉受，方等諸經",
    note: "持戒清净如宝珠者，志习奉受方等经，专精此一品经卷。",
  },
  {
    id: "t0263-002-037",
    category: "誦經相應",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "其在眾會，誦斯經者，心常如應，得無合會，引無央數，億載譬喻，故為是倫，而見斯典。",
    anchorText: "誦斯經者，心常如應",
    note: "众会中诵此经者，心常相应，佛以无数譬喻为其显此典。",
  },
  {
    id: "t0263-002-038",
    category: "見經頂受",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "假使比丘，欲求善說，若見此經，當欣頂受。",
    anchorText: "若見此經，當欣頂受",
    note: "欲求善说者，见此经应欢欣顶受。",
  },
  {
    id: "t0263-002-039",
    category: "奉持專精",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "其有奉持，方等經者，心常專精，不樂餘業，執持一頌，志不改易，乃得聽受，如是弘模。",
    anchorText: "其有奉持，方等經者",
    note: "奉持方等经、专精不改者，乃得听受此广大法式。",
  },
  {
    id: "t0263-002-040",
    category: "崇敬如佛",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "假使有人，慕求斯經，當崇敬之，如如來身。若人思僥，欲學此法，設令得者，當稽首受。",
    anchorText: "慕求斯經，當崇敬之",
    note: "求此经、学此法者，应如敬如来身般崇敬稽首受持。",
  },
  {
    id: "t0263-002-041",
    category: "專講斯經",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "其人不當，念索餘經，亦未曾想，世之群籍。而行佛道，志在根力，悉捨離之，講專斯經。",
    anchorText: "講專斯經",
    note: "本品劝行佛道者志在根力，专讲此经。",
  },
  {
    id: "t0263-002-042",
    category: "宣暢布散",
    sectionTitle: YINGSHI_SECTION_TITLE,
    text: "告舍利弗，佛滿一劫，舉喻億千，分別解說。設有願發，上尊佛道，當以斯經，宣暢布散。",
    anchorText: "當以斯經，宣暢布散",
    note: "卷末劝发愿求佛道者，应宣畅布散此经。",
  },
];
