import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const PIYU_SECTION_TITLE = "譬喻品第三";

export const T0264_JUAN_2_FIREHOUSE_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-002-019",
    category: "譬喻明義",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "我先不言諸佛世尊以種種因緣、譬喻言辭，方便說法，皆為阿耨多羅三藐三菩提耶？是諸所說，皆為化菩薩故。",
    anchorText: "諸佛世尊以種種因緣、譬喻言辭，方便說法",
    note: "佛明示诸佛以因缘譬喻方便说法，皆为无上菩提、化导菩萨。",
    occurrence: 1,
  },
  {
    id: "t0264-002-020",
    category: "譬喻得解",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "今當復以譬喻更明此義，諸有智者以譬喻得解。",
    anchorText: "諸有智者以譬喻得解",
    note: "佛说将以譬喻彰明一乘义，使有智者由譬喻得解。",
    occurrence: 1,
  },
  {
    id: "t0264-002-021",
    category: "方便救濟",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "我今當設方便令諸子等得免斯害。",
    anchorText: "設方便令諸子等得免斯害",
    note: "火宅譬喻中，长者设方便救子免害，喻佛方便救济众生。",
    occurrence: 1,
  },
  {
    id: "t0264-002-022",
    category: "安隱出離",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "爾時諸子聞父所說珍玩之物，適其願故心各勇銳，互相推排競共馳走爭出火宅。是時長者見諸子等安隱得出，皆於四衢道中露地而坐，無復障礙，其心泰然歡喜踊躍。",
    anchorText: "見諸子等安隱得出，皆於四衢道中露地而坐",
    note: "诸子因方便引导而出火宅，安隐无碍，喻众生由佛方便得出苦难。",
    occurrence: 1,
  },
  {
    id: "t0264-002-023",
    category: "等賜大乘",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "我有如是七寶大車，其數無量，應當等心各各與之，不宜差別。所以者何？以我此物周給一國，猶尚不匱，何況諸子。",
    anchorText: "應當等心各各與之，不宜差別",
    note: "长者以平等心赐诸子大车，喻如来以大乘平等饶益众生。",
    occurrence: 1,
  },
  {
    id: "t0264-002-024",
    category: "得未曾有",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "是時諸子，各乘大車得未曾有，非本所望。",
    anchorText: "各乘大車得未曾有，非本所望",
    note: "诸子所得超过原先所望，喻佛终以大乘给予众生殊胜利益。",
    occurrence: 1,
  },
  {
    id: "t0264-002-025",
    category: "拔濟火宅",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "是長者但令諸子得免火難，全其軀命非為虛妄。何以故？若全身命，便為已得玩好之具，況復方便於彼火宅而拔濟之。",
    anchorText: "方便於彼火宅而拔濟之",
    note: "舍利弗说明长者先令诸子免火难、全身命，即已成真实饶益。",
    occurrence: 1,
  },
  {
    id: "t0264-002-026",
    category: "利益一切",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "如來亦復如是，則為一切世間之父，於諸怖畏、衰惱、憂患、無明闇蔽，永盡無餘，而悉成就無量知見力無所畏，有大神力及智慧力，具足方便、智慧波羅蜜，大慈、大悲常無懈惓，恒求善事利益一切，",
    anchorText: "大慈、大悲常無懈惓，恒求善事利益一切",
    note: "佛以世间之父、大慈大悲，恒求善事利益一切众生。",
    occurrence: 1,
  },
  {
    id: "t0264-002-027",
    category: "教令菩提",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "為度眾生生、老、病、死、憂悲苦惱、愚癡闇蔽三毒之火，教化令得阿耨多羅三藐三菩提；",
    anchorText: "為度眾生生、老、病、死、憂悲苦惱",
    note: "经文明说如来为度众生诸苦三毒之火，教化令得无上菩提。",
    occurrence: 1,
  },
  {
    id: "t0264-002-028",
    category: "拔苦與樂",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "我為眾生之父，應拔其苦難，與無量無邊佛智慧樂，令其遊戲。",
    anchorText: "應拔其苦難，與無量無邊佛智慧樂",
    note: "佛自明为众生之父，拔苦难并给予无量无边佛智慧乐。",
    occurrence: 1,
  },
  {
    id: "t0264-002-029",
    category: "智慧方便",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "如來亦復如是，雖有力無所畏而不用之，但以智慧方便，於三界火宅拔濟眾生，為說三乘——聲聞、辟支佛、佛乘——",
    anchorText: "但以智慧方便，於三界火宅拔濟眾生",
    note: "如来以智慧方便于三界火宅拔济众生，并随根说三乘。",
    occurrence: 1,
  },
  {
    id: "t0264-002-030",
    category: "勤修出離",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "汝等速出三界，當得三乘聲聞、辟支佛、佛乘，我今為汝保任此事，終不虛也，汝等但當勤修精進。",
    anchorText: "汝等速出三界，當得三乘聲聞、辟支佛、佛乘",
    note: "佛劝众生速出三界、勤修精进，并保任所说不虚。",
    occurrence: 1,
  },
  {
    id: "t0264-002-031",
    category: "安隱快樂",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "汝等當知此三乘法皆是聖所稱嘆，自在無繫無所依求，乘是三乘，以無漏根、力、覺、道、禪定、解脫、三昧等，而自娛樂，便得無量安隱快樂。",
    anchorText: "便得無量安隱快樂",
    note: "佛赞三乘法为圣所称叹，能令修者得无量安隐快乐。",
    occurrence: 1,
  },
  {
    id: "t0264-002-032",
    category: "聞法信受",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若有眾生，內有智性，從佛世尊聞法信受，慇懃精進，欲速出三界自求涅槃，是名聲聞乘，如彼諸子為求羊車出於火宅。",
    anchorText: "從佛世尊聞法信受，慇懃精進，欲速出三界",
    note: "闻法信受、殷勤精进求出三界，是声闻乘出火宅之义。",
    occurrence: 1,
  },
  {
    id: "t0264-002-033",
    category: "聞法求慧",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若有眾生從佛世尊聞法信受，慇懃精進求自然慧，樂獨善寂，深知諸法因緣，是名辟支佛乘，如彼諸子為求鹿車出於火宅。",
    anchorText: "聞法信受，慇懃精進求自然慧",
    note: "闻法信受、精进求自然慧，能深知诸法因缘，名辟支佛乘。",
    occurrence: 1,
  },
  {
    id: "t0264-002-034",
    category: "大乘菩薩",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若有眾生，從佛世尊聞法信受，勤修精進求一切智、佛智、自然智、無師智，如來知見，力、無所畏，愍念安樂無量眾生，利益天人度脫一切，是名大乘菩薩；",
    anchorText: "勤修精進求一切智、佛智、自然智、無師智",
    note: "闻法信受并勤修精进求佛智、愍念安乐众生者，名大乘菩萨。",
    occurrence: 1,
  },
  {
    id: "t0264-002-035",
    category: "出險得樂",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若見無量億千眾生以佛教門出三界苦怖畏險道得涅槃樂，如來爾時便作是念：『我有無量無邊智慧、力、無畏等諸佛法藏，",
    anchorText: "以佛教門出三界苦怖畏險道得涅槃樂",
    note: "众生依佛教门出三界苦怖畏险道，得涅槃乐。",
    occurrence: 1,
  },
  {
    id: "t0264-002-036",
    category: "等與大乘",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "是諸眾生皆是我子，等與大乘，不令有人獨得滅度，皆以如來滅度而滅度之，",
    anchorText: "等與大乘，不令有人獨得滅度",
    note: "如来平等与众生大乘，不令独得小灭，而令以如来灭度而灭度。",
    occurrence: 1,
  },
  {
    id: "t0264-002-037",
    category: "淨妙第一樂",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "是諸眾生脫三界者，悉與諸佛禪定、解脫等娛樂之具，皆是一相一種聖所稱歎，能生淨妙第一之樂。",
    anchorText: "能生淨妙第一之樂",
    note: "众生出三界后，如来悉与诸佛禅定解脱等具，能生净妙第一之乐。",
    occurrence: 1,
  },
  {
    id: "t0264-002-038",
    category: "大乘度脫",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "如來亦復如是，無有虛妄，初說三乘引導眾生，然後但以大乘而度脫之。",
    anchorText: "初說三乘引導眾生，然後但以大乘而度脫之",
    note: "佛先以三乘引导众生，终以大乘度脱，所说无虚妄。",
    occurrence: 1,
  },
  {
    id: "t0264-002-039",
    category: "三界救護",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "今此三界，皆是我有，其中眾生，悉是吾子；而今此處，多諸患難，唯我一人，能為救護；",
    anchorText: "唯我一人，能為救護",
    note: "偈中如来自明三界众生悉是其子，于多患难中能为救护。",
    occurrence: 1,
  },
  {
    id: "t0264-002-040",
    category: "出世間道",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "是以方便，為說三乘，令諸眾生，知三界苦；開示演說，出世間道。",
    anchorText: "開示演說，出世間道",
    note: "佛以方便说三乘，令众生知三界苦，并开示出世间道。",
    occurrence: 1,
  },
  {
    id: "t0264-002-041",
    category: "信受成佛",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "汝等若能，信受是語，一切皆當，成得佛道。",
    anchorText: "信受是語，一切皆當，成得佛道",
    note: "佛明说若能信受一佛乘譬喻之语，一切皆当成得佛道。",
    occurrence: 1,
  },
  {
    id: "t0264-002-042",
    category: "一乘最上",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "是乘微妙，清淨第一，於諸世間，為無有上；佛所悅可，一切眾生，所應稱讚，供養禮拜；",
    anchorText: "是乘微妙，清淨第一，於諸世間，為無有上",
    note: "经文赞一佛乘微妙清净第一，为世间无上，应称赞供养礼拜。",
    occurrence: 1,
  },
  {
    id: "t0264-002-043",
    category: "直至道場",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "無量億千，諸力解脫，禪定智慧，及佛餘法，得如是乘，令諸子等，日夜劫數，常得遊戲；與諸菩薩，及聲聞眾，乘此寶乘，直至道場；",
    anchorText: "乘此寶乘，直至道場",
    note: "得此宝乘，具诸力解脱禅定智慧，与菩萨声闻直至道场。",
    occurrence: 1,
  },
  {
    id: "t0264-002-044",
    category: "濟拔三界",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "汝等累劫，眾苦所燒，我皆濟拔，令出三界；我雖先說，汝等滅度，但盡生死，而實不滅；今所應作，唯佛智慧。",
    anchorText: "我皆濟拔，令出三界",
    note: "佛明言累劫众苦所烧者，皆由其济拔令出三界，并指向佛智慧。",
    occurrence: 1,
  },
  {
    id: "t0264-002-045",
    category: "一心聽法",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若有菩薩，於是眾中；能一心聽，諸佛實法；諸佛世尊，雖以方便，所化眾生，皆是菩薩。",
    anchorText: "能一心聽，諸佛實法",
    note: "偈中劝菩萨一心听诸佛实法，并说明诸佛方便所化皆为菩萨。",
    occurrence: 1,
  },
  {
    id: "t0264-002-046",
    category: "離苦解脫",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "為滅諦故，修行於道，離諸苦縛，名得解脫。",
    anchorText: "修行於道，離諸苦縛，名得解脫",
    note: "佛于譬喻后说明修道离诸苦缚，名得解脱。",
    occurrence: 1,
  },
  {
    id: "t0264-002-047",
    category: "法印利益",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "我為法王，於法自在；安隱眾生，故現於世。汝舍利弗！我此法印，為欲利益，世間故說。",
    anchorText: "我此法印，為欲利益，世間故說",
    note: "佛明说此法印为利益世间而说，令众生安隐。",
    occurrence: 1,
  },
  {
    id: "t0264-002-048",
    category: "聞者不退",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若有聞者，隨喜頂受，當知是人，阿惟越致。",
    anchorText: "若有聞者，隨喜頂受，當知是人，阿惟越致",
    note: "经文直接说明闻此法印而随喜顶受者，当知是不退转。",
    occurrence: 1,
  },
  {
    id: "t0264-002-049",
    category: "信受宿因",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若有信受，此經法者，是人已曾，見過去佛；恭敬供養，亦聞是法。",
    anchorText: "若有信受，此經法者，是人已曾，見過去佛",
    note: "信受此经法者，已曾见过去佛、恭敬供养并闻此法。",
    occurrence: 1,
  },
  {
    id: "t0264-002-050",
    category: "信說見佛",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若人有能，信汝所說；則為見我，亦見於汝，及比丘僧，并諸菩薩。",
    anchorText: "信汝所說；則為見我",
    note: "佛说若能信舍利弗所说，即为见佛，并见舍利弗、僧与诸菩萨。",
    occurrence: 1,
  },
  {
    id: "t0264-002-051",
    category: "以信得入",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "汝舍利弗！尚於此經，以信得入，況餘聲聞；其餘聲聞，信佛語故，隨順此經，非己智分。",
    anchorText: "尚於此經，以信得入",
    note: "佛指出舍利弗尚以信得入此经，其余声闻亦依信佛语随顺此经。",
    occurrence: 1,
  },
];
