import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const YAOWANG_RULAI_SECTION_TITLE = "藥王如來品第十";
const QIBAO_TA_SECTION_TITLE = "七寶塔品第十一";

export const T0263_JUAN_6_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0263-006-001",
    category: "受持供養",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若族姓子欲至正覺，解無三塗去來今者，當學受持正法花經，分別空慧，無六度想，不以花香伎樂供養為供養也；當了三脫至三達智，無極之慧乃為供養。",
    anchorText: "若族姓子欲至正覺，解無三塗去來今者",
    note: "本品开端即劝欲至正觉者受持《正法华经》，以通达空慧、三脱三达为真正供养。",
  },
  {
    id: "t0263-006-002",
    category: "法供最勝",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "有法供養，最尊無極。",
    anchorText: "有法供養，最尊無極",
    note: "善盖太子由此发问，开启本品关于法供养胜于财供养的核心教义。",
  },
  {
    id: "t0263-006-003",
    category: "法藏開化",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "法之供養者，順若如來所說經典深妙優奧，開化一切世間人民，難受難見出家捨利，志求菩薩諸篋之藏，曠邈處中，以總持印而印之，精進力行，不退轉輪",
    anchorText: "法之供養者，順若如來所說經典深妙優奧",
    note: "佛解释法供养，是随顺如来深妙经典，开化世间、精进力行而入不退法轮。",
  },
  {
    id: "t0263-006-004",
    category: "大慈正法",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "於諸群生設大慈哀，降伏魔兵，離諸法見，覺了演暢十二因緣，無我無人、非壽非命，志空、無願、無想之法，不由眾行，處于道場而轉法輪。",
    anchorText: "於諸群生設大慈哀，降伏魔兵",
    note: "法供养的内容含摄大慈、降魔、离见、演畅缘起与三解脱门。",
  },
  {
    id: "t0263-006-005",
    category: "正法除苦",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "開闡法藏，護諸賢聖，宣揚顯布諸菩薩行，究竟眾苦、無我非身",
    anchorText: "開闡法藏，護諸賢聖",
    note: "经文将开阐法藏、护诸贤圣、宣扬菩萨行与究竟众苦相连。",
  },
  {
    id: "t0263-006-006",
    category: "滅苦安隱",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "諸佛之德，使滅生死，慰除所患，而見安隱無為之事，去來今佛所歎如是。",
    anchorText: "諸佛之德，使滅生死",
    note: "法供养所顺的佛德，能令众生灭生死、除忧患，见安隐无为。",
  },
  {
    id: "t0263-006-007",
    category: "除障法供",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "斷諸猗著，滅諸無黠，生老病死悉為除屏，觀十二緣而不可盡，睹諸住見不隨顛倒，是為族姓子法之供養。",
    anchorText: "斷諸猗著，滅諸無黠",
    note: "佛进一步说明法供养能断著、灭无明，并观十二缘而不随颠倒。",
  },
  {
    id: "t0263-006-008",
    category: "聞法得忍",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "王子善蓋從藥王佛聞法供養，應時逮得柔順法忍",
    anchorText: "王子善蓋從藥王佛聞法供養",
    note: "善盖太子闻佛说法供养，当即得柔顺法忍，是本品的直接证成。",
  },
  {
    id: "t0263-006-009",
    category: "護持正法",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "如來滅後，願護正法，興法供養，降魔怨敵，將迎後法。",
    anchorText: "如來滅後，願護正法",
    note: "善盖闻法得忍后立愿护正法、兴法供养、降伏魔怨。",
  },
  {
    id: "t0263-006-010",
    category: "德本成就",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "常精進學，興諸德本，不久成就，立五神通，總持辯才，無能斷截。",
    anchorText: "常精進學，興諸德本",
    note: "经文说明善盖出家精进，德本成就，得五神通与总持辩才。",
  },
  {
    id: "t0263-006-011",
    category: "護法化眾",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "善蓋比丘護正法故，於一世中化千億人，悉發無上正真道意而不退轉，十四載人立聲聞、緣覺地，不可計人得生天上。",
    anchorText: "善蓋比丘護正法故",
    note: "护持正法的果报表现为广化众生发无上道意不退，并令无量人得生天上。",
  },
  {
    id: "t0263-006-012",
    category: "供佛受持",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "一切所供無過法養，去來今佛皆從是出。若族姓子、族姓女，欲得供養十方諸佛，即當受持正法花經，持諷誦讀，宣示一切，分別一乘無有三乘道。",
    anchorText: "一切所供無過法養",
    note: "佛总结一切供养无过法供养，欲供养十方诸佛，应受持、讽诵、宣示此经。",
  },
  {
    id: "t0263-006-013",
    category: "受持宣示",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "假使有一，欲解大法，開化一切，皆至正覺。當孚受持，斯法華經，宣示遠近，諸未聞者。",
    anchorText: "假使有一，欲解大法",
    note: "偈颂劝欲解大法、开化一切者，应受持此法华经并宣示未闻者。",
  },
  {
    id: "t0263-006-014",
    category: "一乘佛慧",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "斯典如是，以無極慧，照耀三界，皆入一義。",
    anchorText: "斯典如是，以無極慧",
    note: "经文赞此典以无极智慧照耀三界，令归入一义。",
  },
  {
    id: "t0263-006-015",
    category: "法供果報",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "精進不懈，得五神通，總持辯才，開化一切。時千億人，皆立大道，十四載人，聲聞緣覺。無央數人，得生天上，以故歎稱，法供為最。",
    anchorText: "精進不懈，得五神通",
    note: "偈中重述善盖因法供养而得神通辩才、开化大众，故赞法供为最。",
  },
  {
    id: "t0263-006-016",
    category: "聞偈授決",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "一切眾會，聞一頌一偈，一發意頃，歡喜勸助，佛皆授斯四部之決，當得無上正真道意。",
    anchorText: "一切眾會，聞一頌一偈",
    note: "在会大众闻一颂一偈并生欢喜劝助，佛即授记当得无上正真道意。",
  },
  {
    id: "t0263-006-017",
    category: "滅後聞經",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "假使如來滅度之後，聞斯經典一頌四句，發意之頃，代勸助者，佛皆授決，當得無上正真之道。",
    anchorText: "假使如來滅度之後，聞斯經典一頌四句",
    note: "佛明说灭后闻此经典一颂四句、发心劝助者，皆授记当得无上道。",
  },
  {
    id: "t0263-006-018",
    category: "受持供經",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "從是經典受持一頌，諷誦書寫，載於竹帛，銘著心懷，念而不忘，若聽頌音，恭敬察之，方如如來聖尊上句",
    anchorText: "從是經典受持一頌",
    note: "受持一颂、讽诵书写、铭记不忘、敬听颂音，皆被赞为如敬如来圣句。",
  },
  {
    id: "t0263-006-019",
    category: "經卷歸依",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若以華香、繒綵幢幡，發意供養是經卷者，叉手向之，稽首作禮，則當謂之世間自歸。",
    anchorText: "若以華香、繒綵幢幡",
    note: "以香花幡盖供养经卷、叉手礼拜者，经文称为世间所归依。",
  },
  {
    id: "t0263-006-020",
    category: "聞名成佛",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若族姓子、族姓女，假使能持一頌，勸助歡喜，聞經卷名，若得聞名，則當覺是將來世尊，展轉相謂族姓子、族姓女，來世便為如來、至真、等正覺。",
    anchorText: "若族姓子、族姓女，假使能持一頌",
    note: "能持一颂、闻经卷名者，经文赞其未来当成如来正觉。",
  },
  {
    id: "t0263-006-021",
    category: "成無上道",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "其受是經，持讀誦寫，觀聽供養幡華繒綵、雜香芬薰，則當謂斯族姓子女成無上正真道",
    anchorText: "其受是經，持讀誦寫",
    note: "受持、读诵、书写、观听、供养此经者，被明说为成无上正真道之人。",
  },
  {
    id: "t0263-006-022",
    category: "嚴淨佛土",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "其人本已造微妙行，因所作行則當生於嚴淨佛土，常自觀緣，欲講法故",
    anchorText: "其人本已造微妙行",
    note: "能受持讲说此经者，因本行微妙而当生严净佛土，并为讲法而来。",
  },
  {
    id: "t0263-006-023",
    category: "如來所使",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "其族姓子則謂彼人行如來事，世尊所遣，其有講說如來所宣",
    anchorText: "其族姓子則謂彼人行如來事",
    note: "讲说如来所宣此法者，经文称为行如来事、世尊所遣。",
  },
  {
    id: "t0263-006-024",
    category: "受持大寶",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若受持經，當以衣被、甘膳飯食、香華燈火、琦珍殊妙供養奉散，斯族姓子、斯族姓女，則為大寶，當為作禮。",
    anchorText: "若受持經，當以衣被",
    note: "经文劝以衣食香灯珍宝供养受持此经者，称其为大宝，应为作礼。",
  },
  {
    id: "t0263-006-025",
    category: "一聞授決",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "乃能一反聞斯經典，若有聽者，以所供養，志願無上正真道故。",
    anchorText: "乃能一反聞斯經典",
    note: "只要一度听闻此经，以供养发愿无上正真道，即显其殊胜。",
  },
  {
    id: "t0263-006-026",
    category: "供養持經",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若欲住佛道，志慕己功德，當供養彼人，持斯經典者。若樂諸通慧，恣意有所說，則當受斯典，并供養侍者。",
    anchorText: "若欲住佛道，志慕己功德",
    note: "偈颂劝愿住佛道、乐通慧者，应供养持经者并受持此典。",
  },
  {
    id: "t0263-006-027",
    category: "法師如佛",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "恭敬彼人，常當如佛，尋叉手禮，自然聖道。",
    anchorText: "恭敬彼人，常當如佛",
    note: "经文劝恭敬持说此经者如佛，并说叉手礼敬自然趣向圣道。",
  },
  {
    id: "t0263-006-028",
    category: "滅後受持",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若最後時，逢值斯經，佛滅度已，受持經卷。常當供養，如奉最勝，飯食之屬，諸味具膳，房室牀臥，衣被億數，一反聞之，崇進如是，如來則授，其人之決。",
    anchorText: "若最後時，逢值斯經",
    note: "末世逢此经并受持经卷者，应如奉最胜而供养，佛授其决。",
  },
  {
    id: "t0263-006-029",
    category: "書寫見佛",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "設使聞者，書寫執持，於今佛在，見於目前。",
    anchorText: "設使聞者，書寫執持",
    note: "闻此经而书写执持者，经文以“佛在目前”赞其亲近如来。",
  },
  {
    id: "t0263-006-030",
    category: "贊法師福",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "稱詠法師，發心悅豫，其人獲福，不可限量。用宣譽是，明智者德，彼士獲福，復超於斯。",
    anchorText: "稱詠法師，發心悅豫",
    note: "发心欢喜称赞法师者获福不可限量，宣扬智者德福又更胜。",
  },
  {
    id: "t0263-006-031",
    category: "聞經利慶",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若有一反，聞是經者，得諸利慶，無極難比。",
    anchorText: "若有一反，聞是經者",
    note: "经文明确说一度闻此经者，得诸利庆，无极难比。",
  },
  {
    id: "t0263-006-032",
    category: "經王第一",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "今此典頌，名祚顯綽，最尊第一，普天率土所不信樂",
    anchorText: "今此典頌，名祚顯綽",
    note: "佛在诸经中赞此典名德显耀、最尊第一，甚难信乐。",
  },
  {
    id: "t0263-006-033",
    category: "如來護念",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "密從法師受斯典者，則為如來威力所護，無能破壞，乃前世時曾得聞之。",
    anchorText: "密從法師受斯典者",
    note: "从法师受此典者，为如来威力所护，无能破坏。",
  },
  {
    id: "t0263-006-034",
    category: "受持德勝",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "佛滅度後，若有信此正法典者，受持書寫、供養奉順、為他人說，德乃若斯。",
    anchorText: "佛滅度後，若有信此正法典者",
    note: "佛灭后信受此典、书写供养、为人说法，其德如前文所赞。",
  },
  {
    id: "t0263-006-035",
    category: "經處起塔",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若有能說斯經訓者，書寫見者，則於其人起佛神寺，以大寶立，高廣長大，不當復著佛舍利也。",
    anchorText: "若有能說斯經訓者",
    note: "能说此经训、书写见闻者，应为其起佛神寺，不必另安舍利。",
  },
  {
    id: "t0263-006-036",
    category: "如來舍利",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "則為全著如來舍利，其有說此經法之處，諷誦歌詠書寫，書寫已竟，竹帛經卷當供養，事如佛塔寺",
    anchorText: "則為全著如來舍利",
    note: "说法、讽诵、书写此经之处，经文称为具足如来舍利，应如佛塔寺供养。",
  },
  {
    id: "t0263-006-037",
    category: "親近經教",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若有眾生欲得佛寺，稽首作禮者，當親近斯經無上道教。",
    anchorText: "若有眾生欲得佛寺",
    note: "若欲礼拜佛寺、亲近佛塔，经文劝当亲近此经无上道教。",
  },
  {
    id: "t0263-006-038",
    category: "近無上道",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "假使得聞是佛景模，菩薩所行共行法者聽者，信樂來入其中，解達分明，即受供養，於一座上，應近無上正真之道。",
    anchorText: "假使得聞是佛景模",
    note: "菩萨行者得闻此佛景模，信乐解达，即应近无上正真之道。",
  },
  {
    id: "t0263-006-039",
    category: "疾成正覺",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "假使聞此正法華經，諷誦精修，懷抱在心而奉行之，爾乃疾成最正覺矣。",
    anchorText: "假使聞此正法華經",
    note: "闻此经并讽诵精修、怀抱奉行者，疾成最正觉。",
  },
  {
    id: "t0263-006-040",
    category: "經為道首",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "此經典者，道法之首，眾慧之元，成就菩薩。",
    anchorText: "此經典者，道法之首",
    note: "佛直称此经典为道法之首、众慧之元，能成就菩萨。",
  },
  {
    id: "t0263-006-041",
    category: "說經三軌",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "如來滅度之後，若有菩薩及大士等，欲以是經為四部說，著如來衣、坐於世尊師子之座，然後爾乃為四部眾宣傳此經。",
    anchorText: "如來滅度之後，若有菩薩及大士等",
    note: "佛教导灭后说此经者，应著如来衣、坐师子座，然后为四众宣说。",
  },
  {
    id: "t0263-006-042",
    category: "佛力助說",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "設使有聞而不樂者，吾起令樂，必使愛喜。",
    anchorText: "設使有聞而不樂者",
    note: "佛许诺说经时若有闻而不乐者，佛令其爱乐欢喜。",
  },
  {
    id: "t0263-006-043",
    category: "威神達義",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若受此典，不識句義，失其次緒，使諷學者，蒙其威神，令達義次。",
    anchorText: "若受此典，不識句義",
    note: "受此典而不识句义、失次第者，佛以威神令其通达义次。",
  },
  {
    id: "t0263-006-044",
    category: "難遇難信",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "皆相棄怯亂，而當聽此經，是法難得遇，信者亦難值。",
    anchorText: "皆相棄怯亂，而當聽此經",
    note: "偈颂劝众弃怯乱而听此经，并明此法难遇、信者难值。",
  },
  {
    id: "t0263-006-045",
    category: "聞經近道",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "斯經深巍巍，決諸聲聞事，還聞此經王，聽之思惟義。則得近大道，智者成聖慧，猶如見濕土，爾乃知得水。",
    anchorText: "斯經深巍巍，決諸聲聞事",
    note: "听闻此经王并思惟其义，如见湿土知近水，能近大道、成圣慧。",
  },
  {
    id: "t0263-006-046",
    category: "慈忍說法",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "慈心入吾室，忍柔和被服，解空師子座，而說無所畏。",
    anchorText: "慈心入吾室",
    note: "说此经者应以慈心、忍柔和、解空为三轨，说法无畏。",
  },
  {
    id: "t0263-006-047",
    category: "化人護持",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "佛滅度之後，為眾去怨結，多遣諸化人，而說此經典。",
    anchorText: "佛滅度之後，為眾去怨結",
    note: "佛灭后为众生去怨结，多遣化人说此经典。",
  },
  {
    id: "t0263-006-048",
    category: "獨誦佛伴",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "其人在彼行，晝夜一己身，吾遣與共俱，為伴說此典。",
    anchorText: "其人在彼行，晝夜一己身",
    note: "独自讽诵翫习此典者，佛遣化人为伴，共说此典。",
  },
  {
    id: "t0263-006-049",
    category: "辯才悅眾",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "其人辯才，無所罣礙，多能明了，隨順之法。可悅人民，億百千孩，猶如佛聖，之所建立。",
    anchorText: "其人辯才，無所罣礙",
    note: "受持说此法者得辩才无碍，能明了随顺法，悦可无量人民。",
  },
  {
    id: "t0263-006-050",
    category: "見佛無量",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "學者遊行，及有所坐，得見諸佛，如江河沙。",
    anchorText: "學者遊行，及有所坐",
    note: "本品末偈以学者行坐得见诸佛如江河沙作结，赞叹受学此法的殊胜。",
  },
  {
    id: "t0263-006-051",
    category: "寶塔讚法",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "善哉！善哉！世尊安住！審如所言，道德玄妙超絶無侣，慧平等一猶如虚空，實無有異。",
    anchorText: "善哉！善哉！世尊安住",
    note: "七宝塔自然发声赞叹佛所说法玄妙无侣、平等如空。",
  },
  {
    id: "t0263-006-052",
    category: "聽受成道",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "吾會當以此正法華經當自修成，使諸菩薩皆得聽受，然後乃坐於佛樹下逮，成無上正真之道。",
    anchorText: "吾會當以此正法華經當自修成",
    note: "多宝如来本愿以《正法华经》自修成就，并令诸菩萨听受而后成道。",
  },
  {
    id: "t0263-006-053",
    category: "開化得道",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "爲諸十方講説經法，開化一切皆令得道。",
    anchorText: "爲諸十方講説經法",
    note: "经文说明多宝如来为十方讲说经法，开化一切令得道。",
  },
  {
    id: "t0263-006-054",
    category: "見塔功德",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "若見塔者悉得其所，功德難限。",
    anchorText: "若見塔者悉得其所",
    note: "多宝如来临灭度时明说见塔者功德难以限量。",
  },
  {
    id: "t0263-006-055",
    category: "法華作證",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "十方世界其有講説此法華經，吾七寶塔涌，現諸佛所説經處，其舍利身在七寶塔，贊言善哉！",
    anchorText: "十方世界其有講説此法華經",
    note: "多宝如来誓愿凡十方有说《法华经》处，七宝塔即涌现作证赞叹。",
  },
  {
    id: "t0263-006-056",
    category: "精進成佛",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "用衆生故不惜身命，精進不懈行權方便，布施、持戒、忍辱、精進、一心、智慧，求頭與頭求眼與眼，求鼻與鼻求耳與耳求，手足肢體妻子侍從，七寶車乘象馬衣裘，國邑墟聚恣人所求，無所愛惜自致得佛。",
    anchorText: "用衆生故不惜身命",
    note: "佛以自身往昔菩萨行说明为众生不惜身命、修六度方便而成佛。",
  },
  {
    id: "t0263-006-057",
    category: "講經蒙恩",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "講正法華開化一切，使蒙其恩。",
    anchorText: "講正法華開化一切",
    note: "多宝如来请释迦讲《正法华》，开化一切众生，使蒙法恩。",
  },
  {
    id: "t0263-006-058",
    category: "聞名離苦",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "設聞多寶佛，知其名號者，未曽畏終始，不復遭苦患多。",
    anchorText: "設聞多寶佛，知其名號者",
    note: "偈颂说闻知多宝佛名号者，不畏生死终始，不复遭诸苦患。",
  },
  {
    id: "t0263-006-059",
    category: "奉法成道",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "一切所供養，奉法爲最上，分别空無慧，自致得佛道。",
    anchorText: "一切所供養，奉法爲最上",
    note: "偈颂再次赞法供养最上，并以分别空无慧而自致佛道。",
  },
  {
    id: "t0263-006-060",
    category: "宣經一乘",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "宣揚法華經，以示諸不及，解本無三乘，順一無上真。",
    anchorText: "宣揚法華經，以示諸不及",
    note: "宣扬《法华经》能显示无三乘、顺入一无上真。",
  },
  {
    id: "t0263-006-061",
    category: "聞經現塔",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "今者多寶如來、至真，在斯塔寺，遥聞説此正法華典，是以涌出，贊言善哉！",
    anchorText: "遥聞説此正法華典",
    note: "多宝如来因遥闻说此《正法华》而涌现赞叹，突显此经殊胜。",
  },
  {
    id: "t0263-006-062",
    category: "開發大道",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "願垂恩慈加以威神，使諸來者各得其所開發大道。",
    anchorText: "願垂恩慈加以威神",
    note: "大辩菩萨请佛加被，使会众得见多宝佛形，各得开发展大道。",
  },
  {
    id: "t0263-006-063",
    category: "見佛供養",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "我之塔寺所至方面，聽此經典，設諸如來及四部衆，欲睹吾身，隨其十方之所欲願，皆當得見，咸共供養於此化像。",
    anchorText: "我之塔寺所至方面，聽此經典",
    note: "多宝如来本誓随说经之处令诸佛与四众得见其身，共作供养。",
  },
  {
    id: "t0263-006-064",
    category: "十方佛集",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "一切世界所化如來，講説法者皆令詣此。",
    anchorText: "一切世界所化如來",
    note: "经文说明十方讲说法的化佛皆来集会，彰显此经为诸佛所共证。",
  },
  {
    id: "t0263-006-065",
    category: "普現佛德",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "唯然世尊，垂加大恩，普現一切十方國土諸佛聖德。",
    anchorText: "垂加大恩，普現一切十方國土諸佛聖德",
    note: "大辩请佛普现十方诸佛圣德，令会众得见诸佛境界。",
  },
  {
    id: "t0263-006-066",
    category: "聞法啟受",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "爲諸衆生講説經法，音聲柔和靡不解達，百千菩薩啓受所聞。",
    anchorText: "爲諸衆生講説經法，音聲柔和",
    note: "十方诸佛为众生讲说经法，音声柔和，菩萨启受所闻。",
  },
  {
    id: "t0263-006-067",
    category: "瞻禮二佛",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "汝輩當徃詣忍世界見能仁佛如來、至真，并當瞻戴多寶世尊形像塔寺。",
    anchorText: "汝輩當徃詣忍世界見能仁佛",
    note: "十方诸佛劝诸菩萨往诣忍世界，见释迦如来并瞻戴多宝佛塔。",
  },
  {
    id: "t0263-006-068",
    category: "大道德相",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "各從十方諸佛刹土而來到此，顯示大道無極之德。",
    anchorText: "各從十方諸佛刹土而來到此",
    note: "十方诸佛来集，显示大道无极之德。",
  },
  {
    id: "t0263-006-069",
    category: "經法感現",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "善哉！善哉！釋迦文佛！説此經典，何其快乎！吾以欲聞此經法故，故自出現。",
    anchorText: "善哉！善哉！釋迦文佛",
    note: "多宝如来现身后亲口赞叹释迦说此经典，并明言为闻此经法而出现。",
  },
  {
    id: "t0263-006-070",
    category: "神力攝眾",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "佛知所念，現神足力，使四部衆自然超上處於虚空。",
    anchorText: "佛知所念，現神足力",
    note: "佛知四众愿处虚空的心念，以神足力令众自然升处虚空。",
  },
  {
    id: "t0263-006-071",
    category: "滅後持經",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "如來現在、若滅度後，當受此法持諷誦讀。",
    anchorText: "如來現在、若滅度後",
    note: "佛明令现在及灭后都应受持、讽诵、读此法。",
  },
  {
    id: "t0263-006-072",
    category: "奉敬經典",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "比丘當捨如來所供養供事之宜，奉順恭敬於此經典。",
    anchorText: "比丘當捨如來所供養",
    note: "佛将灭度时，特别劝比丘舍供事如来之宜，转而奉顺恭敬此经典。",
  },
  {
    id: "t0263-006-073",
    category: "聽法精進",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "比丘欲知，聽法故舉，何人省是，不興精進。",
    anchorText: "比丘欲知，聽法故舉",
    note: "偈颂说明多宝塔为听法而举现，见此因缘者应兴精进。",
  },
  {
    id: "t0263-006-074",
    category: "護法久住",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "皆欲將護，於正法故，何緣當今，經典久存？因由依附，諸佛之道",
    anchorText: "皆欲將護，於正法故",
    note: "十方诸佛为护正法而来，说明经典久存依附诸佛之道。",
  },
  {
    id: "t0263-006-075",
    category: "持經授決",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "吾滅度之後，其持此經典，速逮得受決，目見世導師。",
    anchorText: "吾滅度之後，其持此經典",
    note: "佛明说灭后持此经典者，速得授决，并得目见世导师。",
  },
  {
    id: "t0263-006-076",
    category: "聞法奉事",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "若聞此法，能受究竟，則爲奉事，歸命我身，并及多寶，如來之尊順，奉現在，十方諸佛。",
    anchorText: "若聞此法，能受究竟",
    note: "闻此法并究竟受持者，即为奉事释迦、多宝与现在十方诸佛。",
  },
  {
    id: "t0263-006-077",
    category: "受持供養",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "悉爲供養，具足無限，用遵修受，此經典故。",
    anchorText: "悉爲供養，具足無限",
    note: "遵修受此经典，即成对诸佛具足无限的供养。",
  },
  {
    id: "t0263-006-078",
    category: "末世奇特",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "佛滅度之後，末世能堪受頒，宣此經典，爾乃爲奇特。",
    anchorText: "佛滅度之後，末世能堪受頒",
    note: "佛以多重难事作比，指出灭后末世能受持宣此经才是真奇特。",
  },
  {
    id: "t0263-006-079",
    category: "書經奇特",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "我滅度之後，若歸如是像，來世書是經，爾乃爲奇特。",
    anchorText: "我滅度之後，若歸如是像",
    note: "佛赞来世归敬此像而书写此经者，是难得奇特之行。",
  },
  {
    id: "t0263-006-080",
    category: "讀經殊勝",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "此者不爲難，精進無奇特，不如於來世，須臾讀此經。",
    anchorText: "不如於來世，須臾讀此經",
    note: "偈颂以举地至梵天为比，反显来世须臾读此经更为殊胜。",
  },
  {
    id: "t0263-006-081",
    category: "一人說經",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "我滅度之後，若持此經典，爲一人説者，爾乃爲殊特。",
    anchorText: "我滅度之後，若持此經典",
    note: "佛赞灭后持此经典，即使只为一人说，也是殊特难得。",
  },
  {
    id: "t0263-006-082",
    category: "信喜咨講",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "持此經典，信喜而愛樂，數數咨講者，爾乃爲殊特。",
    anchorText: "持此經典，信喜而愛樂",
    note: "信喜爱乐、屡屡咨讲此经者，经文称为殊特。",
  },
  {
    id: "t0263-006-083",
    category: "持經功報",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "佛滅度之後，設持此經者，其人得功報，過是難限量。",
    anchorText: "佛滅度之後，設持此經者",
    note: "佛以为无数无著圣者立塔作比，赞灭后持此经者功报更过其上、难以限量。",
  },
  {
    id: "t0263-006-084",
    category: "經中之尊",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "計是經典者，一切經中尊，其奉持此典，則侍諸佛身。",
    anchorText: "計是經典者，一切經中尊",
    note: "佛明称此经典为一切经中之尊，奉持此典即如侍奉诸佛身。",
  },
  {
    id: "t0263-006-085",
    category: "須臾持經",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "須臾持此經，則爲奉敬佛，一切諸導師，是經難值遇。",
    anchorText: "須臾持此經",
    note: "片刻持此经即为奉敬诸佛导师，并说明此经难得值遇。",
  },
  {
    id: "t0263-006-086",
    category: "諸佛愛樂",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "一切十方佛，爲現所咨嗟，勇猛有威神，神通爲巳達。名德遠流布，諸佛所愛樂因，持此經故，逮得寂定地。",
    anchorText: "一切十方佛，爲現所咨嗟",
    note: "十方诸佛咨嗟持经者，称其名德远流布，并因持此经得寂定地。",
  },
  {
    id: "t0263-006-087",
    category: "世間眼目",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "導師滅度後，則爲天世人，顯示作眼目，宣布此經故。",
    anchorText: "導師滅度後，則爲天世人",
    note: "佛灭度后宣布此经者，为天与世人显示作眼目。",
  },
  {
    id: "t0263-006-088",
    category: "說經受禮",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "於當來之世，須臾説此典，其一切衆生，稽首禮明者",
    anchorText: "於當來之世，須臾説此典",
    note: "未来世能须臾说此典者，经文说一切众生应稽首礼敬。",
  },
];
