import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const FANGBIAN_SECTION_TITLE = "方便品第二";

export const T0262_JUAN_1_FANGBIAN_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0262-001-020",
    category: "佛智難入",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "爾時世尊從三昧安詳而起。告舍利弗。諸佛智慧，甚深無量。其智慧門。難解難入。一切聲聞辟支佛。所不能知。所以者何。佛曾親近百千萬億無數諸佛。盡行諸佛無量道法。勇猛精進。名稱普聞。成就甚深未曾有法。隨宜所說。意趣難解。舍利弗。吾從成佛已來。種種因緣。種種譬喻。廣演言教。無數方便引導眾生。令離諸著。",
    anchorText: "諸佛智慧，甚深無量。其智慧門。難解難入",
    note: "方便品开篇赞叹佛智慧甚深难入，并说明佛以无数方便引导众生离著。",
  },
  {
    id: "t0262-001-021",
    category: "如來知見",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "如來知見。廣大深遠。無量無礙。力無所畏。禪定解脫三昧。深入無際。成就一切未曾有法。",
    anchorText: "如來知見。廣大深遠。無量無礙",
    note: "此段直接赞叹如来知见广大深远、成就一切未曾有法。",
  },
  {
    id: "t0262-001-022",
    category: "諸法實相",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "佛所成就第一希有難解之法。唯佛與佛。乃能究盡諸法實相。所謂諸法如是相。如是性。如是體。如是力。如是作。如是因。如是緣。如是果。如是報。如是本末究竟等。",
    anchorText: "唯佛與佛。乃能究盡諸法實相",
    note: "方便品以十如是开显诸法实相，为本品核心法义。",
  },
  {
    id: "t0262-001-023",
    category: "深妙難了",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "本從無數佛 具足行諸道 甚深微妙法 難見難可了",
    anchorText: "本從無數佛 具足行諸道",
    note: "偈颂赞叹佛从无数佛修行诸道，所得甚深微妙法难见难了。",
  },
  {
    id: "t0262-001-024",
    category: "信受真實",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "舍利弗當知 諸佛語無異 於佛所說法 當生大信力 世尊法久後 要當說真實",
    anchorText: "於佛所說法 當生大信力",
    note: "经文劝于佛所说法生大信力，承接法久后当说真实。",
  },
  {
    id: "t0262-001-025",
    category: "方便出離",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "佛以方便力 示以三乘教 眾生處處著 引之令得出",
    anchorText: "佛以方便力 示以三乘教",
    note: "此偈明说佛以方便示三乘教，引导处处执著的众生得出离。",
  },
  {
    id: "t0262-001-026",
    category: "聞法敬信",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "世尊。惟願說之。惟願說之。所以者何。是會無數百千萬億阿僧祇眾生。曾見諸佛。諸根猛利。智慧明了。聞佛所說。則能敬信。",
    anchorText: "聞佛所說。則能敬信",
    note: "舍利弗请佛说法，说明会众善根成熟，闻佛所说则能敬信。",
  },
  {
    id: "t0262-001-027",
    category: "安隱饒益",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "世尊。惟願說之。惟願說之。今此會中如我等比。百千萬億。世世已曾從佛受化。如此人等。必能敬信。長夜安隱多所饒益。",
    anchorText: "必能敬信。長夜安隱多所饒益",
    note: "第三请中明说若闻此法，能敬信并得长夜安隐、多所饶益。",
  },
  {
    id: "t0262-001-028",
    category: "聞法歡喜",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "是等聞此法 則生大歡喜",
    anchorText: "是等聞此法 則生大歡喜",
    note: "偈颂以简明句说明闻此法则生大欢喜。",
  },
  {
    id: "t0262-001-029",
    category: "妙法稀有",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "如是妙法。諸佛如來時乃說之。如優曇鉢華。時一現耳。舍利弗。汝等當信佛之所說。言不虛妄。",
    anchorText: "如是妙法。諸佛如來時乃說之",
    note: "佛明说此妙法如优昙钵华时一现耳，劝众信佛语不虚。",
  },
  {
    id: "t0262-001-030",
    category: "一大事因緣",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "諸佛世尊。唯以一大事因緣故出現於世。舍利弗。云何名諸佛世尊。唯以一大事因緣故出現於世。諸佛世尊。欲令眾生開佛知見使得清淨故。出現於世。欲示眾生佛之知見故。出現於世。欲令眾生悟佛知見故。出現於世。欲令眾生入佛知見道故。出現於世。",
    anchorText: "唯以一大事因緣故出現於世",
    note: "本段完整说明诸佛出世一大事因缘：开示悟入佛知见。",
  },
  {
    id: "t0262-001-031",
    category: "一佛乘",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "如來但以一佛乘故。為眾生說法。無有餘乘。若二若三。",
    anchorText: "如來但以一佛乘故。為眾生說法",
    note: "方便品明示如来以一佛乘为众生说法。",
  },
  {
    id: "t0262-001-032",
    category: "聞法得智",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "是諸眾生從諸佛聞法。究竟皆得一切種智。",
    anchorText: "是諸眾生從諸佛聞法",
    note: "经文直接说明众生从诸佛闻法，究竟皆得一切种智。",
  },
  {
    id: "t0262-001-033",
    category: "安樂眾生",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "現在十方無量百千萬億佛土中諸佛世尊。多所饒益。安樂眾生。",
    anchorText: "多所饒益。安樂眾生",
    note: "赞叹现在十方诸佛多所饶益、安乐众生。",
  },
  {
    id: "t0262-001-034",
    category: "受持難得",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "佛滅度後。如是等經。受持讀誦解義者。是人難得。",
    anchorText: "如是等經。受持讀誦解義者。是人難得",
    note: "此句直接赞叹佛灭度后能受持、读诵、解义此等经者难得。",
  },
  {
    id: "t0262-001-035",
    category: "信解受持",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "舍利弗。汝等當一心信解。受持佛語。諸佛如來。言無虛妄。無有餘乘。唯一佛乘。",
    anchorText: "汝等當一心信解。受持佛語",
    note: "佛劝众一心信解、受持佛语，并明示唯一佛乘。",
  },
  {
    id: "t0262-001-036",
    category: "方便歡喜",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "佛悉知是已 以諸緣譬喻 言辭方便力 令一切歡喜",
    anchorText: "以諸緣譬喻 言辭方便力",
    note: "偈中说明佛知众生根性后，以因缘譬喻方便令一切欢喜。",
  },
  {
    id: "t0262-001-037",
    category: "入大乘",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "我設是方便 令得入佛慧 未曾說汝等 當得成佛道 所以未曾說 說時未至故 今正是其時 決定說大乘",
    anchorText: "我設是方便 令得入佛慧",
    note: "佛说明方便本为令众生入佛慧，今正是时决定说大乘。",
  },
  {
    id: "t0262-001-038",
    category: "成佛無疑",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "聲聞若菩薩 聞我所說法 乃至於一偈 皆成佛無疑",
    anchorText: "聞我所說法 乃至於一偈",
    note: "此偈直接说明声闻、菩萨闻佛所说法乃至一偈，皆成佛无疑。",
  },
  {
    id: "t0262-001-039",
    category: "佛願度生",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "欲令一切眾 如我等無異 如我昔所願 今者已滿足 化一切眾生 皆令入佛道",
    anchorText: "欲令一切眾 如我等無異",
    note: "佛自述本愿：令一切众如佛无异，化一切众生皆入佛道。",
  },
  {
    id: "t0262-001-040",
    category: "盡苦作佛",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "我為設方便 說諸盡苦道 示之以涅槃 我雖說涅槃 是亦非真滅 諸法從本來 常自寂滅相 佛子行道已 來世得作佛",
    anchorText: "我為設方便 說諸盡苦道",
    note: "偈中说明佛设方便说尽苦道，并引导佛子行道后作佛。",
  },
  {
    id: "t0262-001-041",
    category: "善根成佛",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "若聞法布施 或持戒忍辱 精進禪智等 種種修福慧 如是諸人等 皆已成佛道",
    anchorText: "若聞法布施 或持戒忍辱",
    note: "经文总摄闻法布施、持戒忍辱、精进禅智等修福慧，皆成佛道。",
  },
  {
    id: "t0262-001-042",
    category: "供養成佛",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "若人於塔廟 寶像及畫像 以華香旛蓋 敬心而供養 若使人作樂 擊鼓吹角貝 簫笛琴箜篌 琵琶鐃銅鈸 如是眾妙音 盡持以供養 或以歡喜心 歌唄頌佛德 乃至一小音 皆已成佛道",
    anchorText: "若人於塔廟 寶像及畫像",
    note: "此段完整说明以香华、音乐、歌呗供养佛像塔庙，乃至一小音，皆已成佛道。",
  },
  {
    id: "t0262-001-043",
    category: "禮拜成道",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "或有人禮拜 或復但合掌 乃至舉一手 或復小低頭 以此供養像 漸見無量佛 自成無上道 廣度無數眾",
    anchorText: "或有人禮拜 或復但合掌",
    note: "偈中说明礼拜、合掌乃至低头供养佛像，渐见无量佛并成无上道。",
  },
  {
    id: "t0262-001-044",
    category: "稱佛成道",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "若人散亂心 入於塔廟中 一稱南無佛 皆已成佛道",
    anchorText: "若人散亂心 入於塔廟中",
    note: "经文以极简句说明散乱心入塔庙一称南无佛，皆已成佛道。",
  },
  {
    id: "t0262-001-045",
    category: "聞法成佛",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "若有聞是法 皆已成佛道",
    anchorText: "若有聞是法 皆已成佛道",
    note: "偈中直说若有闻是法者皆已成佛道。",
  },
  {
    id: "t0262-001-046",
    category: "聞法成佛",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "若有聞法者 無一不成佛",
    anchorText: "若有聞法者 無一不成佛",
    note: "此句以最直接方式说明闻法者无一不成佛。",
  },
  {
    id: "t0262-001-047",
    category: "聞法供養",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "聞法歡喜讚 乃至發一言 則為已供養 一切三世佛 是人甚希有 過於優曇花",
    anchorText: "聞法歡喜讚 乃至發一言",
    note: "经文赞叹闻法欢喜赞乃至发一言，即为供养三世佛。",
  },
  {
    id: "t0262-001-048",
    category: "妙法秘要",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "當知是妙法 諸佛之秘要",
    anchorText: "當知是妙法 諸佛之秘要",
    note: "偈中点明此妙法为诸佛秘要。",
  },
  {
    id: "t0262-001-049",
    category: "除疑歡喜",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "汝等既已知 諸佛世之師 隨宜方便事 無復諸疑惑 心生大歡喜 自知當作佛",
    anchorText: "無復諸疑惑 心生大歡喜",
    note: "方便品结尾劝众知诸佛方便后无复疑惑，心生大欢喜，自知当作佛。",
  },
];
