import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const XINLE_SECTION_TITLE = "信樂品第四";
const YAOCAO_SECTION_TITLE = "藥草品第五";

export const T0263_JUAN_3_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0263-003-001",
    category: "聞法歡喜",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "聽演大法，得未曾有，本所未聞；而見世尊授舍利弗決，當得無上正真之道，驚喜踊躍咸從坐起",
    anchorText: "聽演大法，得未曾有，本所未聞",
    note: "须菩提等闻大法并见舍利弗授记，生起未曾有的欢喜踊跃。",
  },
  {
    id: "t0263-003-002",
    category: "聽法無厭",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "如來所講我等靖聽，次第坐定諸來大眾，不敢危疲無所患厭。",
    anchorText: "如來所講我等靖聽",
    note: "声闻大众安住听受如来所讲，无疲厌心。",
  },
  {
    id: "t0263-003-003",
    category: "發大意",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "爾乃誨我以奇特誼，樂於等一，則發大意於無上正真道。",
    anchorText: "誨我以奇特誼",
    note: "如来以奇特义教诲，使其乐于一乘而发无上正真道意。",
  },
  {
    id: "t0263-003-004",
    category: "得大利",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "而今大聖授聲聞決當成正覺，心用愕然怪未曾有，余得大利各當奉事，乃獲逮聞如是品經。",
    anchorText: "余得大利各當奉事",
    note: "闻声闻授记成佛并得闻此品，经文明说为得大利。",
  },
  {
    id: "t0263-003-005",
    category: "值法如寶",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "從過去佛常聞斯法，故初值遇，則我祿厚喻獲妙寶",
    anchorText: "從過去佛常聞斯法",
    note: "经文以获得妙宝譬喻值遇此法。",
  },
  {
    id: "t0263-003-006",
    category: "宿福得藏",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "余何宿福得領室藏？",
    anchorText: "何宿福得領室藏",
    note: "穷子领受宝藏的譬喻，表达得此法藏源于宿福。",
  },
  {
    id: "t0263-003-007",
    category: "如來度脫",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "大富長者則譬如來，諸學士者則謂佛子，勉濟吾等三界勤苦，如富長者還執其子度脫生死。",
    anchorText: "大富長者則譬如來",
    note: "本品明以长者喻如来，救济佛子三界勤苦、度脱生死。",
  },
  {
    id: "t0263-003-008",
    category: "除蓋精進",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "有無央數聖眾之寶，以五神通除五陰蓋，常修精進在彼道教，志于滅度謂為妙印。",
    anchorText: "以五神通除五陰蓋",
    note: "以圣众之宝譬佛法资财，能除五阴盖并令精进修道。",
  },
  {
    id: "t0263-003-009",
    category: "法寶施與",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "此如來法珍寶之藏，於今世尊以權方便，觀于本際慧寶帑藏，蠲除饑𩚛授大妙印。",
    anchorText: "如來法珍寶之藏",
    note: "如来以方便开示法宝之藏，蠲除贫乏而授大妙印。",
  },
  {
    id: "t0263-003-010",
    category: "菩薩慧義",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "世尊為我等示現菩薩大士慧誼，余黨奉行為眾說法，當顯如來聖明大德，咸使暢入隨時之誼。",
    anchorText: "示現菩薩大士慧誼",
    note: "如来示现菩萨智慧义，使众人奉行说法、显发如来大德。",
  },
  {
    id: "t0263-003-011",
    category: "善權方便",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "世雄大通善權方便，知我志操不解深法，為現聲聞，畏三界法及生老死，色聲香味細滑之事",
    anchorText: "世雄大通善權方便",
    note: "佛以善权方便，随声闻怖畏生死的根机而示现教法。",
  },
  {
    id: "t0263-003-012",
    category: "佛子大慧",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "今乃自知成佛真子，無上孫息為佛所矜，施以大慧。",
    anchorText: "成佛真子，無上孫息",
    note: "声闻自知为佛真子，蒙佛哀矜而施以大慧。",
  },
  {
    id: "t0263-003-013",
    category: "甘露法",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "世尊興為二事，為諸菩薩現甘露法，為諸下劣志願小者，轉復勸進入微妙誼。",
    anchorText: "為諸菩薩現甘露法",
    note: "世尊为菩萨现甘露法，也劝小志者入微妙义。",
  },
  {
    id: "t0263-003-014",
    category: "獲大珍寶",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "今如來尊現諸通慧，我等以獲大聖珍寶，佛則為父我則為子，父子同體焉得差別。",
    anchorText: "我等以獲大聖珍寶",
    note: "闻法后自觉获得大圣珍宝，并明白佛子同体之义。",
  },
  {
    id: "t0263-003-015",
    category: "一乘授記",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "佛權方便說三乘耳，尚無有二豈當有三？是諸聲聞皆當成佛，我等悅豫不能自勝。",
    anchorText: "佛權方便說三乘耳",
    note: "本品直显三乘为方便，究竟无二无三，声闻皆当成佛。",
  },
  {
    id: "t0263-003-016",
    category: "聞法悲喜",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "我等今日，逮聞斯音，怪之愕然，得未曾有，由是之故，心用悲喜。",
    anchorText: "逮聞斯音，怪之愕然",
    note: "大迦叶偈中赞今日闻佛音声，得未曾有而悲喜交集。",
  },
  {
    id: "t0263-003-017",
    category: "法寶賜與",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "尊妙珍寶，為大積聚，一處合集，以賜我等。",
    anchorText: "尊妙珍寶，為大積聚",
    note: "以尊妙珍宝譬佛所赐大法。",
  },
  {
    id: "t0263-003-018",
    category: "安隱成佛",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "大雄導師，教化我等，覩見下劣，樂喜小乘，度脫我輩，使得安隱，便復授決，當成佛道。",
    anchorText: "度脫我輩，使得安隱",
    note: "佛教化小乘根机者，使其安隐并授记成佛。",
  },
  {
    id: "t0263-003-019",
    category: "大道奉行",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "最勝諸子，則便奉行，尊上大道，所當起立，視眾眼目，當於世間，得成佛道，而為聖尊",
    anchorText: "最勝諸子，則便奉行",
    note: "佛子奉行尊上大道，最终在世间成佛为圣尊。",
  },
  {
    id: "t0263-003-020",
    category: "講法利眾",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "將養擁護，於此佛法，講說分別，最勝慧誼。則為感動，一切眾生",
    anchorText: "講說分別，最勝慧誼",
    note: "拥护佛法、讲说分别最胜智慧义，能感动一切众生。",
  },
  {
    id: "t0263-003-021",
    category: "精進解脫",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "今乃究竟，具足最勝，得無為限，當捨陰蓋，長夜精進，修理空誼，解脫三界，勤苦之惱。",
    anchorText: "長夜精進，修理空誼",
    note: "经文劝长夜精进修空义，舍阴盖、解脱三界苦恼。",
  },
  {
    id: "t0263-003-022",
    category: "願佛道者",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "最勝所演，經身之慧，假使有人，願等佛道，為是等故，加賜法事",
    anchorText: "假使有人，願等佛道",
    note: "佛为愿求佛道者加赐法事，显示经身智慧。",
  },
  {
    id: "t0263-003-023",
    category: "令得利義",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "有大導師，周旋世間，普悉觀察，如此輩相。諸恐懼者，令得利誼，求索勸助，令我信樂。",
    anchorText: "諸恐懼者，令得利誼",
    note: "大导师观察众生根相，令恐惧者得利益义并生信乐。",
  },
  {
    id: "t0263-003-024",
    category: "法施方便",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "大聖導師，所興希有，分別宣暢，善權方便。諸子之黨，志樂下劣，修行調定，而以法施。",
    anchorText: "分別宣暢，善權方便",
    note: "佛以希有善权方便，对志乐下劣者施以法施。",
  },
  {
    id: "t0263-003-025",
    category: "獲道得寶",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "我等今日，致得百千，未曾有法，如貧得財。於佛教化，獲道得寶，第一清淨，無復諸漏。",
    anchorText: "致得百千，未曾有法",
    note: "闻佛教化如贫得财，获道得宝，第一清净无漏。",
  },
  {
    id: "t0263-003-026",
    category: "聽佛道音",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "我等今日，乃為聲聞，還得聽省，上尊佛道，當復見揚，聖覺音聲，以故獲聽，超度恐懼。",
    anchorText: "還得聽省，上尊佛道",
    note: "声闻今日得以听省上尊佛道，闻圣觉音声而超度恐惧。",
  },
  {
    id: "t0263-003-027",
    category: "頂受具願",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "今日無著，燒罪度岸，修行為業，踊躍歡喜。吾等歸聖，以頂受之，所願具足，如江河沙。",
    anchorText: "燒罪度岸，修行為業",
    note: "偈中以烧罪度岸、顶受佛法、所愿具足赞叹闻法受持之益。",
  },
  {
    id: "t0263-003-028",
    category: "隨根開化",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "如來皆覩，眾人性行，他人心念。一切群萌，以若干法，而致墮落。以法示現，此尊佛道。",
    anchorText: "如來皆覩，眾人性行",
    note: "如来洞见众生性行心念，随其所堕以法示现尊佛道。",
  },
  {
    id: "t0263-003-029",
    category: "如來功德",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "如來之德如向所喻，復倍無數不可思誼，無能計量劫之姟底，一一計數大聖所應，如來之慧無能限者，不有法想道地處所，莫能盡原。",
    anchorText: "如來之德如向所喻，復倍無數不可思誼",
    note: "佛印可迦叶所赞，并说明如来功德智慧不可思议、不可计量。",
  },
  {
    id: "t0263-003-030",
    category: "度於彼岸",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "世尊普入一切諸誼，察于世間見眾庶心，所度無極一切分別，皆使決了權慧之事，勸立一切度於彼岸，皆現普智入諸通慧。",
    anchorText: "勸立一切度於彼岸",
    note: "经文明说世尊观众生心，令众生决了权慧、度于彼岸。",
  },
  {
    id: "t0263-003-031",
    category: "法雨普潤",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "如來正覺講說深法，猶如大雨。",
    anchorText: "如來正覺講說深法，猶如大雨",
    note: "本品以大雨譬喻如来说深法，普润众生。",
  },
  {
    id: "t0263-003-032",
    category: "未度令度",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "吾為如來使，天上天下諸天世人，未度者度，未脫者脫，未安者安，未滅度者令得滅度。",
    anchorText: "未度者度，未脫者脫",
    note: "如来自宣为天上天下作利益，令未度、未脱、未安、未灭度者得成就。",
  },
  {
    id: "t0263-003-033",
    category: "佛為道父",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "吾於講法現其道誼，佛為道父分別道慧。",
    anchorText: "佛為道父分別道慧",
    note: "经文以佛为道父，显示如来分别道慧、引导众生。",
  },
  {
    id: "t0263-003-034",
    category: "聽經歡喜",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "于時黎庶無數億姟，皆來聽經，如來通見一切根本，大精進力如應說法，分別散告無量言教，不失本心咸令歡喜，安隱無患或得度世，終生善處恣其所好，各自然生。",
    anchorText: "皆來聽經，如來通見一切根本",
    note: "无数众生来听经，如来随根说法，令欢喜、安隐无患，乃至得度善处。",
  },
  {
    id: "t0263-003-035",
    category: "聞法離惑",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "或習愛欲便為說經，或聽受法離諸貪惑，轉稍以漸遵諸通慧，因從本力如其能量，堅固成就平等法身",
    anchorText: "或聽受法離諸貪惑",
    note: "听受法能离贪惑，渐入通慧，坚固成就平等法身。",
  },
  {
    id: "t0263-003-036",
    category: "受持功德",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "如來演法一品如是，至解脫味離欲寂滅，入諸通慧，若聽受持諷誦奉者，不自識省無所觀念。",
    anchorText: "若聽受持諷誦奉者",
    note: "本品直接提到听受、受持、讽诵、奉行此法者有功德，只是自己不自觉知。",
  },
  {
    id: "t0263-003-037",
    category: "無畏解脫",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "世尊如之見一味已，入解脫味志于滅度，度諸未度究竟滅度，令至一土一同法味，到無恐懼使得解脫。",
    anchorText: "到無恐懼使得解脫",
    note: "如来以一味法度未度者，令同至法味、无恐惧而得解脱。",
  },
  {
    id: "t0263-003-038",
    category: "信樂通慧",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "化於眾生使得信樂，苞育將護悉令普至於諸通慧，讚詠分別逮賢聖法",
    anchorText: "化於眾生使得信樂",
    note: "如来化导众生，使得信乐，并将护至通慧、贤圣法。",
  },
  {
    id: "t0263-003-039",
    category: "隨信說法",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "吾興於世間，仁和為法王，為眾生說法，隨其所信樂。意勇建大業，久立分別說，群萌多受持，蒸庶無所言。",
    anchorText: "為眾生說法，隨其所信樂",
    note: "佛为法王，随众生信乐而说法，令群萌受持。",
  },
  {
    id: "t0263-003-040",
    category: "現正法",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "隨其境界說，如本力所任，又示餘利誼，則為現正法。",
    anchorText: "又示餘利誼，則為現正法",
    note: "佛随众生境界、本力所任开示利益义，即是现正法。",
  },
  {
    id: "t0263-003-041",
    category: "法雨蒙恩",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "眾藥咸茂殖，莖幹華實繁，隨其本境界，皆令得蒙恩。",
    anchorText: "隨其本境界，皆令得蒙恩",
    note: "法雨譬喻中，众药随其本性都得蒙润恩益。",
  },
  {
    id: "t0263-003-042",
    category: "除苦大安",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "吾當飽滿，一切群萌，愚騃之黨，身形枯燥，除諸苦患，得立大安，燒盡愛欲，獲至滅度。",
    anchorText: "除諸苦患，得立大安",
    note: "如来法雨饱满众生，除苦患、立大安、烧爱欲、至灭度。",
  },
  {
    id: "t0263-003-043",
    category: "平等解脫",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "又復示現，若干種誼，於彼若此，常行平等，得至解脫，滅度無為。",
    anchorText: "常行平等，得至解脫",
    note: "佛示现种种义而常行平等，令得解脱、灭度无为。",
  },
  {
    id: "t0263-003-044",
    category: "道德之藏",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "或在門前，而說經典，則為造立，道德之藏，諸等不等，皆令平等，無有所憎，愛欲永除。",
    anchorText: "則為造立，道德之藏",
    note: "说经典能造立道德之藏，令等不等皆平等，爱欲永除。",
  },
  {
    id: "t0263-003-045",
    category: "應病與藥",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "尋興慧雲，而降法雨，暢發微妙，應病與藥。",
    anchorText: "而降法雨，暢發微妙",
    note: "如来兴慧云、降法雨，应众生病而与法药。",
  },
  {
    id: "t0263-003-046",
    category: "近法調柔",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "常為眾生，說賢聖誼，皆令奉戒，如天陰涼。眾人失言，及違諸行，欲使近法，轉漸調柔。",
    anchorText: "欲使近法，轉漸調柔",
    note: "佛说贤圣义，令众生奉戒、亲近正法而渐得调柔。",
  },
  {
    id: "t0263-003-047",
    category: "捨邪入法",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "使住疑者，捨諸邪見，勸化導利，令淨所覩。捨置下劣，遠眾懈廢，隨其所趣，而令入法。",
    anchorText: "捨諸邪見，勸化導利",
    note: "佛令疑者舍邪见，远离懈废，随其所趣而入法。",
  },
  {
    id: "t0263-003-048",
    category: "至佛道",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "世尊等演，經法之雨，悉使得至，大尊佛道，任其力耐，而令聽受，若干道慧，而化立之。",
    anchorText: "悉使得至，大尊佛道",
    note: "世尊平等演经法之雨，令众生依其力堪听受道慧，至大尊佛道。",
  },
  {
    id: "t0263-003-049",
    category: "無漏無為",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "吾悉當說，以能識慧，無漏之法，便得無為，所在遊行，神通三達，亦復如是。",
    anchorText: "無漏之法，便得無為",
    note: "经中以识慧、无漏法指向无为与神通三达。",
  },
  {
    id: "t0263-003-050",
    category: "疾得成道",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "設使欲為，安住之子，恃怙慈心，而行寂然，疾得成道，為人中尊",
    anchorText: "疾得成道，為人中尊",
    note: "愿作安住佛子、依慈心寂然行者，经文明说疾得成道。",
  },
  {
    id: "t0263-003-051",
    category: "不退度眾",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "是等能轉，不退轉輪，建立神足，根力之行，緣是長養，醫藥除病，英雄度脫，無數億人，隨時示現，於斯佛道",
    anchorText: "是等能轉，不退轉輪",
    note: "大树譬喻菩萨能转不退法轮、以法药除病、度脱无数人。",
  },
  {
    id: "t0263-003-052",
    category: "多所安隱",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "佛以法雨，多所安隱，普潤天下，有所成就。",
    anchorText: "佛以法雨，多所安隱",
    note: "本品直说佛以法雨普润天下，多所安隐而有所成就。",
  },
  {
    id: "t0263-003-053",
    category: "經典安隱",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "設使世間，行慈愍法，常以經典，飽滿天下。以現世間，令普安隱",
    anchorText: "常以經典，飽滿天下",
    note: "以经典饱满天下、现于世间，令众生普得安隐。",
  },
  {
    id: "t0263-003-054",
    category: "聞空解達",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "修進神足，專達四禪，若聞空慧，心則解達。放出光明，無數億千，是為大樹，而復滋茂。",
    anchorText: "若聞空慧，心則解達",
    note: "菩萨闻空慧而心得解达，如大树滋茂。",
  },
  {
    id: "t0263-003-055",
    category: "皆得佛道",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "斯諸說法，為最究暢，諸聲聞等，皆當承是。緣斯之行，當得佛行，此諸羅漢，如是無異。世尊演誼，盡極於斯，化諸小乘，皆得佛道。",
    anchorText: "化諸小乘，皆得佛道",
    note: "本品结论之一是化诸小乘皆得佛道。",
  },
  {
    id: "t0263-003-056",
    category: "智慧普照",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "佛亦如是，以智慧光普照一切，五道生死、菩薩、緣覺、聲聞，慧無增減，隨心所解各得其所，本無三乘緣行致之。",
    anchorText: "以智慧光普照一切",
    note: "佛智慧光普照一切，随各自所解而得其所。",
  },
  {
    id: "t0263-003-057",
    category: "法性一等",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "泥本一等，作器別異所受不同。本際亦爾，一等無異，各隨所行成上中下。",
    anchorText: "本際亦爾，一等無異",
    note: "以陶器譬喻说明本际一等无异，众生随行显上中下。",
  },
  {
    id: "t0263-003-058",
    category: "法藥療盲",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "於時良醫愍傷病人，為設方便即入雪山，採四品藥㕮咀搗合，以療其盲，目便見明。",
    anchorText: "採四品藥㕮咀搗合，以療其盲",
    note: "良医譬喻如来设方便，以法药疗治众生盲冥。",
  },
  {
    id: "t0263-003-059",
    category: "發心成佛",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "觀於眾生心之根原，病有輕重，垢有厚薄，解有難易，覩見遠近，便見三乘，發菩薩心，至不退轉，無所從生徑得至佛",
    anchorText: "發菩薩心，至不退轉",
    note: "佛观众生根病，开三乘方便，令发菩萨心、不退转而至佛。",
  },
  {
    id: "t0263-003-060",
    category: "法藥除苦",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "空、無想、無願、向泥洹門，謂四藥也。藥行病愈，則無有癡，名色、六入、所更、痛、愛、受、有、生、老病死憂惱苦患，皆悉除矣。",
    anchorText: "藥行病愈，則無有癡",
    note: "经文以四法为药，能除无明乃至老病死忧恼苦患。",
  },
  {
    id: "t0263-003-061",
    category: "發菩薩意",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "臨欲滅度佛在前住，誨以要法發菩薩意，不在生死不住滅度，解三界空，十方一切如化如幻，如夢、野馬、深山之響，悉無所有無所希望，無取無捨無冥無明",
    anchorText: "誨以要法發菩薩意",
    note: "佛以要法教诲声闻缘觉发菩萨意，通达三界空如幻。",
  },
  {
    id: "t0263-003-062",
    category: "平等濟度",
    sectionTitle: YAOCAO_SECTION_TITLE,
    text: "不生死泥洹，悉等如虛空，無見無不見，乃覩一切本。當爾時所見，不造三界觀，一切普平等，所濟無有量。",
    anchorText: "一切普平等，所濟無有量",
    note: "偈末以一切平等、所济无量总结深观所得。",
  },
];
