import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const MIAOZHUANGYAN_SECTION_TITLE = "妙莊嚴王本事品第二十五";

export const T0264_JUAN_7_MIAOZHUANGYAN_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-007-049",
    category: "久修功德",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "是二子，有大神力福德智慧，久修菩薩所行之道，所謂檀波羅蜜、尸羅波羅蜜、羼提波羅蜜、毘梨耶波羅蜜、禪波羅蜜、般若波羅蜜、方便波羅蜜，慈、悲、喜、捨，乃至三十七助道法，皆悉明了通達。",
    anchorText: "是二子，有大神力福德智慧",
    note: "净藏、净眼二子久修菩萨道，具神力、福德、智慧，并通达诸波罗蜜与助道法。",
  },
  {
    id: "t0264-007-050",
    category: "三昧通達",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "又得菩薩淨三昧、日星宿三昧、淨光三昧、淨色三昧、淨照明三昧、長莊嚴三昧、大威德藏三昧，於此三昧亦悉通達。",
    anchorText: "於此三昧亦悉通達",
    note: "经文明示二子已得并通达多种菩萨三昧。",
  },
  {
    id: "t0264-007-051",
    category: "愍眾說經",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "爾時彼佛欲引導妙莊嚴王，及愍念眾生故，說是《法華經》。",
    anchorText: "及愍念眾生故，說是《法華經》",
    note: "佛为引导妙庄严王并愍念众生而说《法华经》。",
  },
  {
    id: "t0264-007-052",
    category: "宜應聽受",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "此佛於一切天人眾中，說《法華經》，宜應聽受。",
    anchorText: "說《法華經》，宜應聽受",
    note: "二子劝母亲近供养佛，因佛于天人众中说《法华经》，宜应听受。",
  },
  {
    id: "t0264-007-053",
    category: "神變信解",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "於是二子，念其父故，踊在虛空高七多羅樹，現種種神變，於虛空中行、住、坐、臥，身上出水身下出火，身下出水身上出火；或現大身滿虛空中，而復現小，小復現大；於空中滅，忽然在地；入地如水履水如地，現如是等種種神變，令其父王心淨信解。",
    anchorText: "現如是等種種神變，令其父王心淨信解",
    note: "二子为父现种种神变，使父王心净信解。",
  },
  {
    id: "t0264-007-054",
    category: "發菩提心",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "父王今已信解，堪任發阿耨多羅三藐三菩提心，我等為父已作佛事，願母見聽於彼佛所出家修道。",
    anchorText: "堪任發阿耨多羅三藐三菩提心",
    note: "二子确认父王已能发无上菩提心，并说明已为父作佛事。",
  },
  {
    id: "t0264-007-055",
    category: "佛難值遇",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "諸佛甚難值，我等隨佛學。如優曇波羅，值佛復難是；脫諸難亦難，願聽我出家。",
    anchorText: "諸佛甚難值，我等隨佛學",
    note: "偈中劝出家随佛学，明示诸佛难值、脱诸难亦难。",
  },
  {
    id: "t0264-007-056",
    category: "宿福值法",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "佛難得值，如優曇波羅華；又如一眼之龜值浮木孔，而我等宿福深厚生值佛法。",
    anchorText: "宿福深厚生值佛法",
    note: "二子以宿福深厚生值佛法，强调遇佛闻法稀有。",
  },
  {
    id: "t0264-007-057",
    category: "堪任受持",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "彼時妙莊嚴王，後宮八萬四千人，悉皆堪任受持是《法華經》。",
    anchorText: "悉皆堪任受持是《法華經》",
    note: "妙庄严王后宫八万四千人皆堪任受持《法华经》。",
  },
  {
    id: "t0264-007-058",
    category: "離惡趣願",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "淨藏菩薩，已於無量百千萬億劫通達離諸惡趣三昧，欲令一切眾生離諸惡趣故。",
    anchorText: "欲令一切眾生離諸惡趣故",
    note: "净藏菩萨通达离诸恶趣三昧，志在令众生离诸恶趣。",
  },
  {
    id: "t0264-007-059",
    category: "方便善化",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "二子如是以方便力善化其父，令心信解好樂佛法。",
    anchorText: "令心信解好樂佛法",
    note: "二子以方便力善化其父，使其信解并好乐佛法。",
  },
  {
    id: "t0264-007-060",
    category: "示教利喜",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "爾時彼佛，為王說法示教利喜，王大歡悅。",
    anchorText: "為王說法示教利喜",
    note: "佛为王说法示教利喜，令王大欢悦。",
  },
  {
    id: "t0264-007-061",
    category: "授記作佛",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "此王於我法中作比丘，精勤修習助佛道法，當得作佛，號娑羅樹王，國名大光，劫名大高王。",
    anchorText: "精勤修習助佛道法，當得作佛",
    note: "佛为妙庄严王授记，说明其出家精勤修习助佛道法，当得作佛。",
  },
  {
    id: "t0264-007-062",
    category: "修經得定",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "王出家已，於八萬四千歲常勤精進，修行《妙法華經》，過是已後，得一切淨功德莊嚴三昧。",
    anchorText: "修行《妙法華經》",
    note: "妙庄严王出家后长时精进修行《妙法华经》，得一切净功德庄严三昧。",
  },
  {
    id: "t0264-007-063",
    category: "善知識益",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "此二子者是我善知識，為欲發起宿世善根饒益我故，來生我家。",
    anchorText: "為欲發起宿世善根饒益我故",
    note: "妙庄严王称二子为善知识，能发起宿世善根而饶益自己。",
  },
  {
    id: "t0264-007-064",
    category: "善知識大因緣",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "若善男子、善女人，種善根故，世世得善知識，其善知識，能作佛事示教利喜，令入阿耨多羅三藐三菩提。",
    anchorText: "世世得善知識",
    note: "佛明示种善根者世世得善知识，善知识能作佛事，令入无上菩提。",
  },
  {
    id: "t0264-007-065",
    category: "見佛發心",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "善知識者是大因緣，所謂化導令得見佛，發阿耨多羅三藐三菩提心。",
    anchorText: "化導令得見佛",
    note: "佛说善知识是大因缘，能化导众生见佛并发无上菩提心。",
  },
  {
    id: "t0264-007-066",
    category: "受持正見",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "此二子已曾供養六十五百千萬億那由他恒河沙諸佛親見恭敬，於諸佛所受持《法華經》，愍念邪見眾生，令住正見。",
    anchorText: "愍念邪見眾生，令住正見",
    note: "佛赞二子曾供养无量诸佛、受持《法华经》，愍念邪见众生令住正见。",
  },
  {
    id: "t0264-007-067",
    category: "法益安隱",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "如來之法具足成就，不可思議微妙功德，教戒所行安隱快善。",
    anchorText: "教戒所行安隱快善",
    note: "妙庄严王赞如来之法具足不可思议微妙功德，教戒所行安隐快善。",
  },
  {
    id: "t0264-007-068",
    category: "離諸惡心",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "我從今日，不復自隨心行，不生邪見、憍慢、瞋恚諸惡之心。",
    anchorText: "不生邪見、憍慢、瞋恚諸惡之心",
    note: "妙庄严王闻法赞叹后发愿不再随心行，不生邪见、憍慢、瞋恚等恶心。",
  },
  {
    id: "t0264-007-069",
    category: "識名禮拜",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "是藥王、藥上菩薩，成就如此諸大功德，已於無量百千萬億諸佛所殖眾德本，成就不可思議諸善功德。若有人識是二菩薩名字者，一切世間諸天人民，亦應禮拜。",
    anchorText: "若有人識是二菩薩名字者",
    note: "佛赞药王、药上二菩萨成就不可思议善功德，识其名字者，世间天人亦应礼拜。",
  },
  {
    id: "t0264-007-070",
    category: "聞品法眼",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "佛說是〈妙莊嚴王本事品〉時，八萬四千人遠塵離垢，於諸法中得法眼淨。",
    anchorText: "八萬四千人遠塵離垢",
    note: "佛说本品时，八万四千人远尘离垢，得法眼净。",
  },
];
