import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const CONGDIYONGCHU_SECTION_TITLE = "菩薩從地踊出品第十四";

export const T0263_JUAN_7_CONGDIYONGCHU_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-043",
    category: "請付正法",
    text: "鄙之徒類來造忍界，欲聞斯典受持諷寫，精進供養奉行如法，惟願大聖垂心於我，如來滅度後，以《正法華經》加哀見付。",
    anchorText: "欲聞斯典受持諷寫，精進供養奉行如法",
    note: "他方菩萨请佛付嘱《正法华经》，明示闻、受持、讽写、供养、奉行为本品开端愿行。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-044",
    category: "滅後弘宣",
    text: "今此忍界自有八江河沙等大士，一一大士各有眷屬，如六十億江河沙等菩薩大士，後末世時，皆當受持分布班宣。",
    anchorText: "後末世時，皆當受持分布班宣",
    note: "佛说明忍界自有无量菩萨，将在后末世受持、分布、班宣此经。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-045",
    category: "聞法踊出",
    text: "聞佛顯揚《法華》音聲從地踊出，一一菩薩，與六十億江河沙等諸菩薩俱，營從相隨一心一行，無有差別。",
    anchorText: "聞佛顯揚《法華》音聲從地踊出",
    note: "无量菩萨因闻佛显扬《法华》音声而从地踊出，显示此经感召护持之众。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-046",
    category: "禮讚二尊",
    text: "或有菩薩，以若干品奇妙之誼，諮嗟二尊讚詠諸佛，從始已來假使具足，五十中劫不能究暢",
    anchorText: "以若干品奇妙之誼，諮嗟二尊讚詠諸佛",
    note: "从地踊出诸菩萨以奇妙义赞叹二尊诸佛，五十中劫尚不能尽。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-047",
    category: "神力普見",
    text: "爾時世尊，即如色像現其神足，令四部眾悉得普見。",
    anchorText: "現其神足，令四部眾悉得普見",
    note: "佛现神足，使四部众普见从地踊出的菩萨大会。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-048",
    category: "攝護佛土",
    text: "又使念知此忍世界，諸菩薩眾於虛空中，各各攝護百千佛土，諸菩薩眾，皆滿具足百千佛土。",
    anchorText: "諸菩薩眾於虛空中，各各攝護百千佛土",
    note: "经文赞叹诸菩萨于虚空中各摄护百千佛土，护持境界广大。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-049",
    category: "善學入慧",
    text: "眾庶各各悉受律行，善學道教不敢興厭，欲至嚴淨。所以者何？斯之品類，乃於往古諸平等覺，各各作行，是諸聲聞，信樂吾教入于佛慧，又各各異三乘學者，住聲聞乘，我悉立志入佛大慧。",
    anchorText: "信樂吾教入于佛慧",
    note: "佛说明众生受律行、善学道教，并令信乐佛教者入于佛慧。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-050",
    category: "聞法供養",
    text: "欲得聞大聖，教命詢深要，聽之歡喜信，乃入法供養。",
    anchorText: "聽之歡喜信，乃入法供養",
    note: "诸菩萨偈赞听闻大圣深要教命，欢喜信受而入法供养。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-051",
    category: "普聞佛道",
    text: "諸族姓子，皆聽佛道，今吾所說，慧柔和悅。若明達者，以為美香，如來之慧，不可思議。",
    anchorText: "皆聽佛道，今吾所說",
    note: "佛劝大众皆听佛道，并赞如来之慧不可思议。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-052",
    category: "堅固發心",
    text: "皆當強意，普存堅固，各建立志，一心平等。",
    anchorText: "皆當強意，普存堅固",
    note: "佛劝会众强意坚固、建立其志、一心平等，以承受甚深法义。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-053",
    category: "聽未曾法",
    text: "大聖難值，愍哀世間，今當聽受，未曾有法。",
    anchorText: "今當聽受，未曾有法",
    note: "本品明言大圣难值，佛愍世间，劝众听受未曾有法。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-054",
    category: "斷疑聞法",
    text: "佛當建立，仁者諸黨，一切無得，生狐疑心。",
    anchorText: "一切無得，生狐疑心",
    note: "佛将建立说明此事，劝大众勿生狐疑。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-055",
    category: "甚深法義",
    text: "安住所療，法甚深奧，非心所思，不可限量。今當講說，無極因緣，普共聽之，義何所趣。",
    anchorText: "法甚深奧，非心所思，不可限量",
    note: "佛标举此法甚深奥妙、非心所思，并将讲说无极因缘。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-056",
    category: "勸立不退",
    text: "吾始逮無上正真道成最正覺時，勸悅斯等立不退轉，使成大道教授化立，族姓開士大士之眾，處于下方而於其中，有所救護讚經諷誦，思惟禪定專察其歸，欣然悅豫樂無為行。",
    anchorText: "勸悅斯等立不退轉，使成大道教授化立",
    note: "佛说明自己成道时已劝悦这些菩萨立不退转，并令其救护、赞经、讽诵、思惟禅定。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-057",
    category: "專修求慧",
    text: "諸族姓子，志于恬惔，不存遠近，天上人間常應專修，轉於法輪無為無會，好深神通法樂為樂，志願精進求于佛慧。",
    anchorText: "天上人間常應專修",
    note: "本品赞叹诸菩萨志于恬惔，天上人间常专修，精进求佛慧。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-058",
    category: "博聞智慧",
    text: "今此無數，諸菩薩眾，不可思議，無能限量，造行億數，不可限劫，殖積神足，博聞智慧。",
    anchorText: "殖積神足，博聞智慧",
    note: "佛偈赞无数菩萨久远造行，积集神足与博闻智慧。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-059",
    category: "佛授其決",
    text: "吾悉勸誘，於大聖道，今佛一切，皆授其決。",
    anchorText: "今佛一切，皆授其決",
    note: "佛说明这些菩萨由佛劝诱于大圣道，并皆得授决。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-060",
    category: "佛子修行",
    text: "悉捨棄離，諸所習地，一切皆處，閑居得度。斯諸佛子，所行無為，精修學習，奉遵上道。",
    anchorText: "精修學習，奉遵上道",
    note: "佛赞诸佛子舍离所习地，闲居得度，精修学习、奉遵上道。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-061",
    category: "攝護國土",
    text: "斯聰哲者，在于下方，今日故來，攝護國土。",
    anchorText: "今日故來，攝護國土",
    note: "从地踊出的菩萨今日来会，为摄护国土。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-062",
    category: "晝夜精進",
    text: "晝夜精進，無有逸慢，積累德行，分別佛道，常行勤修，立於慧力，一切意堅，而無限量，志常勇猛，思惟法典，普悉是吾，達清淨子。",
    anchorText: "晝夜精進，無有逸慢",
    note: "佛赞这些菩萨昼夜精进、积累德行、分辨佛道、志常勇猛。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-063",
    category: "講演法輪",
    text: "吾初逮成，為佛道時，在於城中，若樹無著，則便講演，無上法輪，勸立其志，於尊佛道。",
    anchorText: "則便講演，無上法輪",
    note: "佛说明自己初成佛道时即讲演无上法轮，劝立众志于尊佛道。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-064",
    category: "信佛至誠",
    text: "今佛所說，至誠無漏，聞佛歎詠，皆當信之。",
    anchorText: "今佛所說，至誠無漏",
    note: "佛偈明示所说至诚无漏，闻佛赞咏皆应信受。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-065",
    category: "久立正道",
    text: "開化發起，此諸群英，從久曩來，立尊正道。",
    anchorText: "從久曩來，立尊正道",
    note: "佛说明这些菩萨从久远以来已被开化发起，立于尊正道。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-066",
    category: "久修德本",
    text: "今是菩薩大會之眾，悉皆如來之所開導，部黨部黨眾多無量，久修梵行殖眾德本，供養無數百千諸佛，假使欲計成就已來劫數無限。",
    anchorText: "久修梵行殖眾德本",
    note: "彌勒赞叹此菩萨大会为如来所开导，久修梵行、殖众德本、供养无数诸佛。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-067",
    category: "導立菩薩",
    text: "世尊往古，亦復教化于斯品類，誘導建立於菩薩地，當成無上正真之道致諸正覺，悉行方便所作已辦。",
    anchorText: "誘導建立於菩薩地",
    note: "彌勒请问中重述如来往古教化此等菩萨，诱导建立菩萨地，当成无上正真道。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-068",
    category: "滅後斷疑",
    text: "善哉！世尊！現說此誼，其有狐疑於斯典者，當來末世諸學大乘，設使聞者令不沈吟。",
    anchorText: "當來末世諸學大乘，設使聞者令不沈吟",
    note: "彌勒请佛说明此义，是为令末世学大乘者闻后不再疑滞。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-069",
    category: "不退救眾",
    text: "今此諸樂，不退轉子，無數億劫，行救大眾，神足之力，住不可動。學智慧強，靡所不入，今來至斯，在所開通。",
    anchorText: "不退轉子，無數億劫，行救大眾",
    note: "彌勒偈赞这些不退转子无数亿劫行救大众，神足不动、智慧广大。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-070",
    category: "蓮華無著",
    text: "如水蓮華，悉無所著，威神尊重，志超於世。",
    anchorText: "如水蓮華，悉無所著",
    note: "彌勒以水莲花喻赞诸菩萨无所著，威神尊重、志超于世。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-071",
    category: "智慧無畏",
    text: "無數菩薩，如來集會，心強智慧，又無所畏，無數億劫。所學審諦，志懷明哲，其目通達，威神巍巍。",
    anchorText: "心強智慧，又無所畏",
    note: "彌勒偈赞无数菩萨心强智慧、无所畏，久学审谛、威神巍巍。",
  },
  {
    sectionTitle: CONGDIYONGCHU_SECTION_TITLE,
    id: "t0263-007-072",
    category: "禪定精進",
    text: "所見諮嗟，而竄山巖，靜行無為，如虛空界，悉無所著。禪定精進，為安住子，而心志求，於此佛道。",
    anchorText: "禪定精進，為安住子",
    note: "彌勒偈赞诸菩萨静行无为、悉无所著，禅定精进并志求佛道。",
  },
];
