import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const XINJIE_SECTION_TITLE = "信解品第四";

export const T0262_JUAN_3_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0262-003-001",
    category: "聞法歡喜",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "爾時慧命須菩提。摩訶迦旃延。摩訶迦葉。摩訶目犍連。從佛所聞未曾有法。世尊授舍利弗阿耨多羅三藐三菩提記。發希有心。歡喜踊躍。",
    anchorText: "從佛所聞未曾有法。世尊授舍利弗",
    note: "四大聲聞聞佛授舍利弗記，發希有心、歡喜踊躍。",
  },
  {
    id: "t0262-003-002",
    category: "聞記善利",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我等今於佛前。聞授聲聞阿耨多羅三藐三菩提記。心甚歡喜。得未曾有。不謂於今忽然得聞希有之法。深自慶幸。獲大善利。無量珍寶。不求自得。",
    anchorText: "聞授聲聞阿耨多羅三藐三菩提記。心甚歡喜",
    note: "經文明說聞授記後心甚歡喜、獲大善利，無量珍寶不求自得。",
  },
  {
    id: "t0262-003-003",
    category: "譬喻得益",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我若得子委付財物。坦然快樂。無復憂慮。",
    anchorText: "我若得子委付財物。坦然快樂",
    note: "窮子喻中長者念子，為後文佛付法財作譬喻鋪墊。",
  },
  {
    id: "t0262-003-004",
    category: "譬喻得益",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我財物庫藏。今有所付。我常思念此子。無由見之。而忽自來。甚適我願。",
    anchorText: "我財物庫藏。今有所付",
    note: "長者見子，歡喜其財物庫藏有所付，呼應如來法藏終歸佛子。",
  },
  {
    id: "t0262-003-005",
    category: "方便攝受",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "汝等勤作。勿得懈息。",
    anchorText: "汝等勤作。勿得懈息",
    note: "譬喻中長者以方便接近窮子，勸其勤作不懈。",
  },
  {
    id: "t0262-003-006",
    category: "漸入信解",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "過是已後。心相體信入出無難。",
    anchorText: "過是已後。心相體信入出無難",
    note: "窮子由久近長者而心相體信，象徵漸得信解。",
  },
  {
    id: "t0262-003-007",
    category: "成就大志",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "復經少時。父知子意漸以通泰。成就大志。自鄙先心。",
    anchorText: "父知子意漸以通泰。成就大志",
    note: "譬喻明示心意通泰、成就大志，從小志轉向大乘承當。",
  },
  {
    id: "t0262-003-008",
    category: "法藏付囑",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "今我所有一切財物。皆是子有。先所出內。是子所知。",
    anchorText: "今我所有一切財物。皆是子有",
    note: "長者宣布一切財物皆是子有，譬喻佛子本應得如來法藏。",
  },
  {
    id: "t0262-003-009",
    category: "寶藏自至",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "是時窮子聞父此言。即大歡喜。得未曾有。而作是念。我本無心有所希求。今此寶藏自然而至。",
    anchorText: "我本無心有所希求。今此寶藏自然而至",
    note: "本品核心譬喻句，說明無心希求而寶藏自然至。",
  },
  {
    id: "t0262-003-010",
    category: "真是佛子",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "大富長者則是如來。我等皆似佛子。如來常說我等為子。",
    anchorText: "大富長者則是如來。我等皆似佛子",
    note: "經文自解譬喻，明說聲聞亦似佛子，如來常說為子。",
  },
  {
    id: "t0262-003-011",
    category: "勤修涅槃",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "今日世尊。令我等思惟蠲除諸法戲論之糞。我等於中勤加精進。得至涅槃一日之價。既得此已。心大歡喜。自以為足。",
    anchorText: "令我等思惟蠲除諸法戲論之糞",
    note: "以除糞譬喻修斷戲論，勤加精進而得涅槃利益。",
  },
  {
    id: "t0262-003-012",
    category: "如來知見",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "汝等當有如來知見寶藏之分。世尊以方便力。說如來智慧。",
    anchorText: "汝等當有如來知見寶藏之分",
    note: "本品明說眾人當有如來知見寶藏之分，佛以方便說如來智慧。",
  },
  {
    id: "t0262-003-013",
    category: "佛智無吝",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "今我等方知。世尊於佛智慧無所吝惜。",
    anchorText: "世尊於佛智慧無所吝惜",
    note: "聲聞領解佛於佛智慧無所吝惜。",
  },
  {
    id: "t0262-003-014",
    category: "一乘法義",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我等昔來真是佛子。而但樂小法。若我等有樂大之心。佛則為我說大乘法。於此經中。唯說一乘。",
    anchorText: "若我等有樂大之心。佛則為我說大乘法",
    note: "本品直指此經唯說一乘，佛子若樂大，佛即為說大乘法。",
  },
  {
    id: "t0262-003-015",
    category: "大乘教化",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "然佛實以大乘教化。",
    anchorText: "然佛實以大乘教化",
    note: "以簡明句總結佛實以大乘教化。",
  },
  {
    id: "t0262-003-016",
    category: "法王大寶",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "今法王大寶自然而至。如佛子所應得者皆已得之。",
    anchorText: "今法王大寶自然而至",
    note: "聲聞領解法王大寶自然至，佛子所應得者皆已得之。",
  },
  {
    id: "t0262-003-017",
    category: "聞佛音教",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我等今日 聞佛音教 歡喜踊躍 得未曾有",
    anchorText: "我等今日 聞佛音教",
    note: "偈頌重申聞佛音教，歡喜踊躍，得未曾有。",
  },
  {
    id: "t0262-003-018",
    category: "聲聞作佛",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "佛說聲聞 當得作佛 無上寶聚 不求自得",
    anchorText: "佛說聲聞 當得作佛",
    note: "偈中明說聲聞當得作佛，無上寶聚不求自得。",
  },
  {
    id: "t0262-003-019",
    category: "修習成佛",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "佛敕我等 說最上道 修習此者 當得成佛",
    anchorText: "說最上道 修習此者 當得成佛",
    note: "此偈把最上道與修習成佛直接相連。",
  },
  {
    id: "t0262-003-020",
    category: "聞法授記",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "諸佛子等 從我聞法 日夜思惟 精勤修習 是時諸佛 即授其記 汝於來世 當得作佛",
    anchorText: "諸佛子等 從我聞法",
    note: "諸佛子聞法後日夜思惟、精勤修習，諸佛即授當作佛記。",
  },
  {
    id: "t0262-003-021",
    category: "諸佛秘藏",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "一切諸佛 秘藏之法 但為菩薩 演其實事",
    anchorText: "一切諸佛 秘藏之法",
    note: "偈中稱此為一切諸佛秘藏之法，為菩薩演其實事。",
  },
  {
    id: "t0262-003-022",
    category: "解脫苦患",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我等長夜 修習空法 得脫三界 苦惱之患 住最後身 有餘涅槃",
    anchorText: "修習空法 得脫三界",
    note: "此句說明修習空法能得脫三界苦惱之患。",
  },
  {
    id: "t0262-003-023",
    category: "得道報恩",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "佛所教化 得道不虛 則為已得 報佛之恩",
    anchorText: "佛所教化 得道不虛",
    note: "偈中說佛所教化得道不虛，即是報佛之恩。",
  },
  {
    id: "t0262-003-024",
    category: "方便調伏",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "以方便力 柔伏其心 然後乃付 一切財物",
    anchorText: "以方便力 柔伏其心",
    note: "以長者譬喻佛以方便柔伏其心，然後付與一切財物。",
  },
  {
    id: "t0262-003-025",
    category: "教以大智",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "佛亦如是 現希有事 知樂小者 以方便力 調伏其心 乃教大智",
    anchorText: "知樂小者 以方便力",
    note: "佛知樂小者，以方便調伏其心，乃教大智。",
  },
  {
    id: "t0262-003-026",
    category: "得無量寶",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我等今日 得未曾有 非先所望 而今自得 如彼窮子 得無量寶",
    anchorText: "我等今日 得未曾有",
    note: "以窮子得無量寶喻聲聞今日得未曾有。",
  },
  {
    id: "t0262-003-027",
    category: "清淨眼",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "世尊我今 得道得果 於無漏法 得清淨眼",
    anchorText: "世尊我今 得道得果",
    note: "偈中直說得道得果，於無漏法得清淨眼。",
  },
  {
    id: "t0262-003-028",
    category: "無上大果",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "法王法中 久修梵行 今得無漏 無上大果",
    anchorText: "法王法中 久修梵行",
    note: "於法王法中久修梵行，今得無漏、無上大果。",
  },
  {
    id: "t0262-003-029",
    category: "佛道聲聞",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我等今者 真是聲聞 以佛道聲 令一切聞",
    anchorText: "真是聲聞 以佛道聲",
    note: "本品將聲聞重新會入佛道，以佛道聲令一切聞。",
  },
  {
    id: "t0262-003-030",
    category: "應受供養",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我等今者 真阿羅漢 於諸世間 天人魔梵 普於其中 應受供養",
    anchorText: "真阿羅漢 於諸世間",
    note: "經文明說真阿羅漢於諸世間天人魔梵中應受供養。",
  },
  {
    id: "t0262-003-031",
    category: "佛恩難報",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "世尊大恩 以希有事 憐愍教化 利益我等 無量億劫 誰能報者",
    anchorText: "世尊大恩 以希有事",
    note: "偈中讚佛大恩，以希有事憐愍教化、利益眾生，難以報答。",
  },
  {
    id: "t0262-003-032",
    category: "供養難報",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "手足供給 頭頂禮敬 一切供養 皆不能報",
    anchorText: "手足供給 頭頂禮敬",
    note: "即使供給禮敬、一切供養，仍不能報佛恩。",
  },
  {
    id: "t0262-003-033",
    category: "供養難報",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "若以頂戴 兩肩荷負 於恆沙劫 盡心恭敬 又以美膳 無量寶衣 及諸臥具 種種湯藥 牛頭栴檀 及諸珍寶 以起塔廟 寶衣布地 如斯等事 以用供養 於恆沙劫 亦不能報",
    anchorText: "若以頂戴 兩肩荷負",
    note: "以恆沙劫種種供養作比較，仍說亦不能報佛恩。",
  },
  {
    id: "t0262-003-034",
    category: "諸佛希有",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "諸佛希有 無量無邊 不可思議 大神通力 無漏無為 諸法之王 能為下劣 忍於斯事",
    anchorText: "諸佛希有 無量無邊",
    note: "偈中讚諸佛稀有、不可思議，能為下劣隨順忍受。",
  },
  {
    id: "t0262-003-035",
    category: "隨宜說法",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "諸佛於法 得最自在 知諸眾生 種種欲樂 及其志力 隨所堪任 以無量喻 而為說法",
    anchorText: "諸佛於法 得最自在",
    note: "此偈說諸佛於法自在，知眾生欲樂志力，隨所堪任以無量喻說法。",
  },
  {
    id: "t0262-003-036",
    category: "一乘方便",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "隨諸眾生 宿世善根 又知成熟 未成熟者 種種籌量 分別知已 於一乘道 隨宜說三",
    anchorText: "隨諸眾生 宿世善根",
    note: "結偈總明佛知善根成熟與否，於一乘道隨宜說三。",
  },
];
