import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const YAOWANG_RULAI_SECTION_TITLE = "藥王如來品第十";

export const T0263_JUAN_6_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0263-006-001",
    category: "受持供養",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若族姓子欲至正覺，解無三塗去來今者，當學受持正法花經，分別空慧，無六度想，不以花香伎樂供養為供養也；當了三脫至三達智，無極之慧乃為供養。",
    anchorText: "若族姓子欲至正覺，解無三塗去來今者",
    note: "本品开端即劝欲至正觉者受持《正法华经》，以通达空慧、三脱三达为真正供养。",
  },
  {
    id: "t0263-006-002",
    category: "法供最勝",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "有法供養，最尊無極。",
    anchorText: "有法供養，最尊無極",
    note: "善盖太子由此发问，开启本品关于法供养胜于财供养的核心教义。",
  },
  {
    id: "t0263-006-003",
    category: "法藏開化",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "法之供養者，順若如來所說經典深妙優奧，開化一切世間人民，難受難見出家捨利，志求菩薩諸篋之藏，曠邈處中，以總持印而印之，精進力行，不退轉輪",
    anchorText: "法之供養者，順若如來所說經典深妙優奧",
    note: "佛解释法供养，是随顺如来深妙经典，开化世间、精进力行而入不退法轮。",
  },
  {
    id: "t0263-006-004",
    category: "大慈正法",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "於諸群生設大慈哀，降伏魔兵，離諸法見，覺了演暢十二因緣，無我無人、非壽非命，志空、無願、無想之法，不由眾行，處于道場而轉法輪。",
    anchorText: "於諸群生設大慈哀，降伏魔兵",
    note: "法供养的内容含摄大慈、降魔、离见、演畅缘起与三解脱门。",
  },
  {
    id: "t0263-006-005",
    category: "正法除苦",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "開闡法藏，護諸賢聖，宣揚顯布諸菩薩行，究竟眾苦、無我非身",
    anchorText: "開闡法藏，護諸賢聖",
    note: "经文将开阐法藏、护诸贤圣、宣扬菩萨行与究竟众苦相连。",
  },
  {
    id: "t0263-006-006",
    category: "滅苦安隱",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "諸佛之德，使滅生死，慰除所患，而見安隱無為之事，去來今佛所歎如是。",
    anchorText: "諸佛之德，使滅生死",
    note: "法供养所顺的佛德，能令众生灭生死、除忧患，见安隐无为。",
  },
  {
    id: "t0263-006-007",
    category: "除障法供",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "斷諸猗著，滅諸無黠，生老病死悉為除屏，觀十二緣而不可盡，睹諸住見不隨顛倒，是為族姓子法之供養。",
    anchorText: "斷諸猗著，滅諸無黠",
    note: "佛进一步说明法供养能断著、灭无明，并观十二缘而不随颠倒。",
  },
  {
    id: "t0263-006-008",
    category: "聞法得忍",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "王子善蓋從藥王佛聞法供養，應時逮得柔順法忍",
    anchorText: "王子善蓋從藥王佛聞法供養",
    note: "善盖太子闻佛说法供养，当即得柔顺法忍，是本品的直接证成。",
  },
  {
    id: "t0263-006-009",
    category: "護持正法",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "如來滅後，願護正法，興法供養，降魔怨敵，將迎後法。",
    anchorText: "如來滅後，願護正法",
    note: "善盖闻法得忍后立愿护正法、兴法供养、降伏魔怨。",
  },
  {
    id: "t0263-006-010",
    category: "德本成就",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "常精進學，興諸德本，不久成就，立五神通，總持辯才，無能斷截。",
    anchorText: "常精進學，興諸德本",
    note: "经文说明善盖出家精进，德本成就，得五神通与总持辩才。",
  },
  {
    id: "t0263-006-011",
    category: "護法化眾",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "善蓋比丘護正法故，於一世中化千億人，悉發無上正真道意而不退轉，十四載人立聲聞、緣覺地，不可計人得生天上。",
    anchorText: "善蓋比丘護正法故",
    note: "护持正法的果报表现为广化众生发无上道意不退，并令无量人得生天上。",
  },
  {
    id: "t0263-006-012",
    category: "供佛受持",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "一切所供無過法養，去來今佛皆從是出。若族姓子、族姓女，欲得供養十方諸佛，即當受持正法花經，持諷誦讀，宣示一切，分別一乘無有三乘道。",
    anchorText: "一切所供無過法養",
    note: "佛总结一切供养无过法供养，欲供养十方诸佛，应受持、讽诵、宣示此经。",
  },
  {
    id: "t0263-006-013",
    category: "受持宣示",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "假使有一，欲解大法，開化一切，皆至正覺。當孚受持，斯法華經，宣示遠近，諸未聞者。",
    anchorText: "假使有一，欲解大法",
    note: "偈颂劝欲解大法、开化一切者，应受持此法华经并宣示未闻者。",
  },
  {
    id: "t0263-006-014",
    category: "一乘佛慧",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "斯典如是，以無極慧，照耀三界，皆入一義。",
    anchorText: "斯典如是，以無極慧",
    note: "经文赞此典以无极智慧照耀三界，令归入一义。",
  },
  {
    id: "t0263-006-015",
    category: "法供果報",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "精進不懈，得五神通，總持辯才，開化一切。時千億人，皆立大道，十四載人，聲聞緣覺。無央數人，得生天上，以故歎稱，法供為最。",
    anchorText: "精進不懈，得五神通",
    note: "偈中重述善盖因法供养而得神通辩才、开化大众，故赞法供为最。",
  },
  {
    id: "t0263-006-016",
    category: "聞偈授決",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "一切眾會，聞一頌一偈，一發意頃，歡喜勸助，佛皆授斯四部之決，當得無上正真道意。",
    anchorText: "一切眾會，聞一頌一偈",
    note: "在会大众闻一颂一偈并生欢喜劝助，佛即授记当得无上正真道意。",
  },
  {
    id: "t0263-006-017",
    category: "滅後聞經",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "假使如來滅度之後，聞斯經典一頌四句，發意之頃，代勸助者，佛皆授決，當得無上正真之道。",
    anchorText: "假使如來滅度之後，聞斯經典一頌四句",
    note: "佛明说灭后闻此经典一颂四句、发心劝助者，皆授记当得无上道。",
  },
  {
    id: "t0263-006-018",
    category: "受持供經",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "從是經典受持一頌，諷誦書寫，載於竹帛，銘著心懷，念而不忘，若聽頌音，恭敬察之，方如如來聖尊上句",
    anchorText: "從是經典受持一頌",
    note: "受持一颂、讽诵书写、铭记不忘、敬听颂音，皆被赞为如敬如来圣句。",
  },
  {
    id: "t0263-006-019",
    category: "經卷歸依",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若以華香、繒綵幢幡，發意供養是經卷者，叉手向之，稽首作禮，則當謂之世間自歸。",
    anchorText: "若以華香、繒綵幢幡",
    note: "以香花幡盖供养经卷、叉手礼拜者，经文称为世间所归依。",
  },
  {
    id: "t0263-006-020",
    category: "聞名成佛",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若族姓子、族姓女，假使能持一頌，勸助歡喜，聞經卷名，若得聞名，則當覺是將來世尊，展轉相謂族姓子、族姓女，來世便為如來、至真、等正覺。",
    anchorText: "若族姓子、族姓女，假使能持一頌",
    note: "能持一颂、闻经卷名者，经文赞其未来当成如来正觉。",
  },
  {
    id: "t0263-006-021",
    category: "成無上道",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "其受是經，持讀誦寫，觀聽供養幡華繒綵、雜香芬薰，則當謂斯族姓子女成無上正真道",
    anchorText: "其受是經，持讀誦寫",
    note: "受持、读诵、书写、观听、供养此经者，被明说为成无上正真道之人。",
  },
  {
    id: "t0263-006-022",
    category: "嚴淨佛土",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "其人本已造微妙行，因所作行則當生於嚴淨佛土，常自觀緣，欲講法故",
    anchorText: "其人本已造微妙行",
    note: "能受持讲说此经者，因本行微妙而当生严净佛土，并为讲法而来。",
  },
  {
    id: "t0263-006-023",
    category: "如來所使",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "其族姓子則謂彼人行如來事，世尊所遣，其有講說如來所宣",
    anchorText: "其族姓子則謂彼人行如來事",
    note: "讲说如来所宣此法者，经文称为行如来事、世尊所遣。",
  },
  {
    id: "t0263-006-024",
    category: "受持大寶",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若受持經，當以衣被、甘膳飯食、香華燈火、琦珍殊妙供養奉散，斯族姓子、斯族姓女，則為大寶，當為作禮。",
    anchorText: "若受持經，當以衣被",
    note: "经文劝以衣食香灯珍宝供养受持此经者，称其为大宝，应为作礼。",
  },
  {
    id: "t0263-006-025",
    category: "一聞授決",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "乃能一反聞斯經典，若有聽者，以所供養，志願無上正真道故。",
    anchorText: "乃能一反聞斯經典",
    note: "只要一度听闻此经，以供养发愿无上正真道，即显其殊胜。",
  },
  {
    id: "t0263-006-026",
    category: "供養持經",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若欲住佛道，志慕己功德，當供養彼人，持斯經典者。若樂諸通慧，恣意有所說，則當受斯典，并供養侍者。",
    anchorText: "若欲住佛道，志慕己功德",
    note: "偈颂劝愿住佛道、乐通慧者，应供养持经者并受持此典。",
  },
  {
    id: "t0263-006-027",
    category: "法師如佛",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "恭敬彼人，常當如佛，尋叉手禮，自然聖道。",
    anchorText: "恭敬彼人，常當如佛",
    note: "经文劝恭敬持说此经者如佛，并说叉手礼敬自然趣向圣道。",
  },
  {
    id: "t0263-006-028",
    category: "滅後受持",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若最後時，逢值斯經，佛滅度已，受持經卷。常當供養，如奉最勝，飯食之屬，諸味具膳，房室牀臥，衣被億數，一反聞之，崇進如是，如來則授，其人之決。",
    anchorText: "若最後時，逢值斯經",
    note: "末世逢此经并受持经卷者，应如奉最胜而供养，佛授其决。",
  },
  {
    id: "t0263-006-029",
    category: "書寫見佛",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "設使聞者，書寫執持，於今佛在，見於目前。",
    anchorText: "設使聞者，書寫執持",
    note: "闻此经而书写执持者，经文以“佛在目前”赞其亲近如来。",
  },
  {
    id: "t0263-006-030",
    category: "贊法師福",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "稱詠法師，發心悅豫，其人獲福，不可限量。用宣譽是，明智者德，彼士獲福，復超於斯。",
    anchorText: "稱詠法師，發心悅豫",
    note: "发心欢喜称赞法师者获福不可限量，宣扬智者德福又更胜。",
  },
  {
    id: "t0263-006-031",
    category: "聞經利慶",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若有一反，聞是經者，得諸利慶，無極難比。",
    anchorText: "若有一反，聞是經者",
    note: "经文明确说一度闻此经者，得诸利庆，无极难比。",
  },
  {
    id: "t0263-006-032",
    category: "經王第一",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "今此典頌，名祚顯綽，最尊第一，普天率土所不信樂",
    anchorText: "今此典頌，名祚顯綽",
    note: "佛在诸经中赞此典名德显耀、最尊第一，甚难信乐。",
  },
  {
    id: "t0263-006-033",
    category: "如來護念",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "密從法師受斯典者，則為如來威力所護，無能破壞，乃前世時曾得聞之。",
    anchorText: "密從法師受斯典者",
    note: "从法师受此典者，为如来威力所护，无能破坏。",
  },
  {
    id: "t0263-006-034",
    category: "受持德勝",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "佛滅度後，若有信此正法典者，受持書寫、供養奉順、為他人說，德乃若斯。",
    anchorText: "佛滅度後，若有信此正法典者",
    note: "佛灭后信受此典、书写供养、为人说法，其德如前文所赞。",
  },
  {
    id: "t0263-006-035",
    category: "經處起塔",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若有能說斯經訓者，書寫見者，則於其人起佛神寺，以大寶立，高廣長大，不當復著佛舍利也。",
    anchorText: "若有能說斯經訓者",
    note: "能说此经训、书写见闻者，应为其起佛神寺，不必另安舍利。",
  },
  {
    id: "t0263-006-036",
    category: "如來舍利",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "則為全著如來舍利，其有說此經法之處，諷誦歌詠書寫，書寫已竟，竹帛經卷當供養，事如佛塔寺",
    anchorText: "則為全著如來舍利",
    note: "说法、讽诵、书写此经之处，经文称为具足如来舍利，应如佛塔寺供养。",
  },
  {
    id: "t0263-006-037",
    category: "親近經教",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若有眾生欲得佛寺，稽首作禮者，當親近斯經無上道教。",
    anchorText: "若有眾生欲得佛寺",
    note: "若欲礼拜佛寺、亲近佛塔，经文劝当亲近此经无上道教。",
  },
  {
    id: "t0263-006-038",
    category: "近無上道",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "假使得聞是佛景模，菩薩所行共行法者聽者，信樂來入其中，解達分明，即受供養，於一座上，應近無上正真之道。",
    anchorText: "假使得聞是佛景模",
    note: "菩萨行者得闻此佛景模，信乐解达，即应近无上正真之道。",
  },
  {
    id: "t0263-006-039",
    category: "疾成正覺",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "假使聞此正法華經，諷誦精修，懷抱在心而奉行之，爾乃疾成最正覺矣。",
    anchorText: "假使聞此正法華經",
    note: "闻此经并讽诵精修、怀抱奉行者，疾成最正觉。",
  },
  {
    id: "t0263-006-040",
    category: "經為道首",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "此經典者，道法之首，眾慧之元，成就菩薩。",
    anchorText: "此經典者，道法之首",
    note: "佛直称此经典为道法之首、众慧之元，能成就菩萨。",
  },
  {
    id: "t0263-006-041",
    category: "說經三軌",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "如來滅度之後，若有菩薩及大士等，欲以是經為四部說，著如來衣、坐於世尊師子之座，然後爾乃為四部眾宣傳此經。",
    anchorText: "如來滅度之後，若有菩薩及大士等",
    note: "佛教导灭后说此经者，应著如来衣、坐师子座，然后为四众宣说。",
  },
  {
    id: "t0263-006-042",
    category: "佛力助說",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "設使有聞而不樂者，吾起令樂，必使愛喜。",
    anchorText: "設使有聞而不樂者",
    note: "佛许诺说经时若有闻而不乐者，佛令其爱乐欢喜。",
  },
  {
    id: "t0263-006-043",
    category: "威神達義",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "若受此典，不識句義，失其次緒，使諷學者，蒙其威神，令達義次。",
    anchorText: "若受此典，不識句義",
    note: "受此典而不识句义、失次第者，佛以威神令其通达义次。",
  },
  {
    id: "t0263-006-044",
    category: "難遇難信",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "皆相棄怯亂，而當聽此經，是法難得遇，信者亦難值。",
    anchorText: "皆相棄怯亂，而當聽此經",
    note: "偈颂劝众弃怯乱而听此经，并明此法难遇、信者难值。",
  },
  {
    id: "t0263-006-045",
    category: "聞經近道",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "斯經深巍巍，決諸聲聞事，還聞此經王，聽之思惟義。則得近大道，智者成聖慧，猶如見濕土，爾乃知得水。",
    anchorText: "斯經深巍巍，決諸聲聞事",
    note: "听闻此经王并思惟其义，如见湿土知近水，能近大道、成圣慧。",
  },
  {
    id: "t0263-006-046",
    category: "慈忍說法",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "慈心入吾室，忍柔和被服，解空師子座，而說無所畏。",
    anchorText: "慈心入吾室",
    note: "说此经者应以慈心、忍柔和、解空为三轨，说法无畏。",
  },
  {
    id: "t0263-006-047",
    category: "化人護持",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "佛滅度之後，為眾去怨結，多遣諸化人，而說此經典。",
    anchorText: "佛滅度之後，為眾去怨結",
    note: "佛灭后为众生去怨结，多遣化人说此经典。",
  },
  {
    id: "t0263-006-048",
    category: "獨誦佛伴",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "其人在彼行，晝夜一己身，吾遣與共俱，為伴說此典。",
    anchorText: "其人在彼行，晝夜一己身",
    note: "独自讽诵翫习此典者，佛遣化人为伴，共说此典。",
  },
  {
    id: "t0263-006-049",
    category: "辯才悅眾",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "其人辯才，無所罣礙，多能明了，隨順之法。可悅人民，億百千孩，猶如佛聖，之所建立。",
    anchorText: "其人辯才，無所罣礙",
    note: "受持说此法者得辩才无碍，能明了随顺法，悦可无量人民。",
  },
  {
    id: "t0263-006-050",
    category: "見佛無量",
    sectionTitle: YAOWANG_RULAI_SECTION_TITLE,
    text: "學者遊行，及有所坐，得見諸佛，如江河沙。",
    anchorText: "學者遊行，及有所坐",
    note: "本品末偈以学者行坐得见诸佛如江河沙作结，赞叹受学此法的殊胜。",
  },
];
