import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const YAOWANG_SECTION_TITLE = "藥王菩薩品第二十一";

export const T0263_JUAN_9_YAOWANG_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-040",
    category: "聞法發心",
    text: "若有聞佛班宣藥王初發道心宿行功勳，為今眾會及後來世，普聞受持追學究竟，天人龍鬼、諸尊神王，僉皆悅豫發大道意，自致正覺度脫一切。",
    anchorText: "若有聞佛班宣藥王初發道心宿行功勳",
    note: "宿王华请佛宣说药王往昔行愿，明确为现在与后世闻受追学、发大道意、成正觉度脱一切。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-041",
    category: "勸進後學",
    text: "善哉！乃為將來諸菩薩施，勸進後學令入道智。",
    anchorText: "乃為將來諸菩薩施",
    note: "佛赞此问能利益将来菩萨，劝进后学入于道智。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-042",
    category: "聞經得定",
    text: "時有菩薩，名眾生憙見，聞佛敷演散解義要，即奉佛法遵習苦行，夙夜精進萬二千歲，經行不坐竟萬二千歲，即便逮得普現三昧。",
    anchorText: "聞佛敷演散解義要",
    note: "众生喜见菩萨闻佛讲说《正法华经》义要后精进修行，得普现三昧。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-043",
    category: "供養經佛",
    text: "『我當供養離垢日月光首如來、至真，奉《正法華經》。』即如其像三昧正受，處在虛空，雨心天華雜香栴檀，用供養佛。應時所雨眾華雜香，普熏十方諸佛世界，其聞香者悉得法忍，眾生之類和心相向。",
    anchorText: "我當供養離垢日月光首如來",
    note: "本段把供养佛与奉《正法华经》相连，并说香熏十方、闻香者得法忍。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-044",
    category: "法供養勝",
    text: "善哉！善哉！族姓子！精進乃爾，世之希有，斯真供養如來經典，乃為眾生忍苦不勞，超踰天人一切所行，國財妻子施所不及，供養之中為尊為上，為最為長為無疇匹，以身施者乃成法施。",
    anchorText: "斯真供養如來經典",
    note: "诸佛赞叹众生喜见以身供养为真供养如来经典，超过国财妻子等布施。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-045",
    category: "精進供養果",
    text: "於是之後火焰乃息，勤修精進供養法故，於是終沒還生其世，更復值見離垢日月光首如來、至真之士，生離垢施國王宮內，自然化生結加趺坐，而為父母說此頌曰：「『尊王識念我本行，堅強勤修大精進，所重愛身以用施，建立住此逮三昧。』",
    anchorText: "勤修精進供養法故",
    note: "经文明说因勤修精进供养法，命终还生彼世，复值如来并自然化生。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-046",
    category: "總持法要",
    text: "吾往昔時至心供養，因是逮致了一切音總持法要。是《正法華》，無上經典學中要者，經卷本有八十姟百千億那術姟偈，當一心思，何所造作立佛像摸，而常心中無瞋恚怒。",
    anchorText: "至心供養，因是逮致了一切音總持法要",
    note: "众生喜见自述因至心供养而得总持法要，并赞《正法华》为无上经典学中要者。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-047",
    category: "經典流布",
    text: "以斯經典重相囑累，普令流布等潤十方，咸使一切皆蒙福慶。",
    anchorText: "以斯經典重相囑累",
    note: "离垢日月光首如来以经典相嘱累，令普流布十方，使一切蒙福庆。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-048",
    category: "供養開化",
    text: "供養訖竟，在其眾會，化無數千諸聲聞眾，開諸菩薩皆令逮得普現三昧。",
    anchorText: "化無數千諸聲聞眾",
    note: "供养舍利塔后，众生喜见开化大众，使诸菩萨得普现三昧。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-049",
    category: "福德功勳",
    text: "所言適竟，地即大動，天雨眾華，尋時手臂平復如故。眾生憙見欲度一切，因示現此慧力所行，福德功勳勢力所致。",
    anchorText: "眾生憙見欲度一切",
    note: "经文说明手臂平复的瑞相，出于欲度一切的慧力所行与福德功勋势力。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-050",
    category: "供養功德",
    text: "又族姓子，菩薩勤苦不可稱計，捐身棄命無有限量，常建大乘志無上道，興發大功無極之德，於如來前然一足指，功德難喻，況然其身以為供養，勝施國土妻子血肉。",
    anchorText: "菩薩勤苦不可稱計",
    note: "佛总结药王菩萨往昔难行，赞其为无上道兴发大功德，供养功德难喻。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-051",
    category: "受持四句",
    text: "若族姓子族姓女，受《正法華》一四句頌，分別奉行為人解說，比其福施萬不如一。",
    anchorText: "受《正法華》一四句頌",
    note: "这是本品最直接的受持功德句：受一四句颂、奉行并为人解说，胜过巨大布施。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-052",
    category: "經文總讚",
    text: "此經如是，一切諸法最為元首。猶若須彌眾山中高，如月盛滿星中最明，大慧光明照曜三界，為諸法首無上道王，猶如日出普照天下消眾幽冥；此經如是，蠲除一切愚癡闇蔽，皆入道明。",
    anchorText: "此經如是，一切諸法最為元首",
    note: "佛以大海、须弥、满月、日光等譬喻赞此经为诸法之首，能除愚痴暗蔽。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-053",
    category: "經典度脫",
    text: "此經如是，一切諸法眾經典主，攬持十方度脫一切。猶梵天王處第七宮，制御諸天莫不奉命；此經如是，普濟眾生學與不學，教導三乘行君父業。",
    anchorText: "一切諸法眾經典主",
    note: "经文赞《正法华经》为众经典主，摄持十方、度脱一切、普济众生。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-054",
    category: "成就正真",
    text: "此經如是，調御諸法，悉令成就無上正真。猶如世尊三界法王，被道服飾三十二相誘眾愚蔽；此經如是，從菩薩學乃至如來，開導聲聞、諸緣覺等，皆使成就無上正真。",
    anchorText: "調御諸法，悉令成就無上正真",
    note: "本品总赞此经调御诸法，能开导三乘皆成就无上正真。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-055",
    category: "三界護持",
    text: "斯經典者為三界護，度脫眾生危厄之難，飽滿饑虛眾情之患，寒者溫煖，熱者清涼，有裸露者皆得衣被，開導眾生悉令入道。",
    anchorText: "斯經典者為三界護",
    note: "经文直称此经为三界护，能度脱危厄、开导众生入道。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-056",
    category: "不退成道",
    text: "此經如是，以聖道明照燿三界。猶如大明消天下冥；此經如是，致不退轉無從生忍至成佛道。",
    anchorText: "以聖道明照燿三界",
    note: "佛以大明除暗为喻，赞此经能致不退转、无从生忍乃至成佛道。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-057",
    category: "聞寫功德",
    text: "斯經典者，度脫一切眾苦之患，拔斷諸垢三毒疹疾，救濟生死諸繫牢獄。若聞此經，尋即解了能書寫者，其功德福無能稱計，何況聞持懷抱誦說，華香供養雜香澤香然燈幢幡。",
    anchorText: "度脫一切眾苦之患",
    note: "佛明说此经典度脱众苦、拔断三毒，闻解书写功德不可称计，闻持诵说供养更胜。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-058",
    category: "聞持本品",
    text: "若有聞持藥王菩薩往古學品，受持思念之，其福過彼眾物供養，不可稱載。",
    anchorText: "聞持藥王菩薩往古學品",
    note: "本品自身的闻持、受持、思念功德被明确赞为超过众物供养。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-059",
    category: "聞法轉報",
    text: "若有女人，聞此經法尋即受持，便於此世畢女形壽，後得男子。若有女人，於五濁世最後末俗，聞是經法能奉行者，於是壽終生安養國，見無量壽佛，與諸菩薩眷屬圍繞，生寶蓮華坐師子座，無婬怒癡除去眾結，亦無貪嫉未曾懷恨。",
    anchorText: "聞此經法尋即受持",
    note: "经文详说女人闻此经法受持奉行的转报与往生安养国等利益。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-060",
    category: "不退法忍",
    text: "適生其國得五神通，逮不退轉不起法忍。已逮法忍，輒得覩見七十二億兆載江河沙諸如來眾。適見諸佛，眼根清淨。",
    anchorText: "適生其國得五神通",
    note: "承接往生安养国的利益，说明得五神通、不退转、不起法忍，并见无数诸佛、眼根清净。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-061",
    category: "持經護祐",
    text: "受持諷誦為他人說，此功德福，火不能燒水不能漂，盜賊怨家縣官不侵，千佛嗟歎不能究竟，所獲功德不可限量，巍巍如是。",
    anchorText: "受持諷誦為他人說，此功德福",
    note: "诸佛遥赞受持讽诵、为人说此经的功德福不可限量，并具火水盗怨等不能侵害的护佑。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-062",
    category: "降魔度難",
    text: "緣斯功德，降伏眾魔，棄諸怨敵，渡生死難周旋諸患。又族姓子，以是經法伏眾惡逆，為諸千佛所見建立，擁護汝身，天上世間而無儔匹，自捨如來，未有聲聞及諸菩薩，功德福祐智慧定意，無有等侶。",
    anchorText: "緣斯功德，降伏眾魔",
    note: "此段继续说明受持此经的功德能降魔、离怨、渡生死难，并受千佛护念建立。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-063",
    category: "受經威德",
    text: "若有學人，受是經者，所逮聖明勢力威德，超越若斯。",
    anchorText: "若有學人，受是經者",
    note: "佛总括受此经者所获圣明、势力、威德超越如上。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-064",
    category: "讚善功德",
    text: "若有講說此藥王品，有讚善者，後生為人，口中自然優鉢華香，身栴檀香。若聞此經讚歎善者，其人現在功德遠聞，佛已豫歎其人功勳。",
    anchorText: "若有講說此藥王品",
    note: "本品明说讲说药王品而赞善者，后生口香身香；闻经赞叹善者，现世功德远闻。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-065",
    category: "流布護持",
    text: "吾以是經囑累汝等，眾生憙見往古法品，最後末俗五濁之世，流布天下閻浮利內，無能中壞，其魔波旬不能得便，及魔官屬邪神鬼魅，無能害者，天、龍、羅剎、鳩洹厭鬼，無敢當者。",
    anchorText: "最後末俗五濁之世，流布天下閻浮利內",
    note: "佛将此经与本品嘱累流布，并说五浊末世流布时，魔及邪神鬼魅不能中坏。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-066",
    category: "聞法除病",
    text: "是藥王品威德所立，所流布處若有疾病，聞是經法病則消除，無有眾患，因是功德，後致正真，無老病死。",
    anchorText: "是藥王品威德所立",
    note: "经文直接说明药王品流布处，病者闻法病除，并因功德后致正真、无老病死。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-067",
    category: "持卷功德",
    text: "若大乘學，見諸比丘持是經卷，當觀其人功德如是。",
    anchorText: "見諸比丘持是經卷",
    note: "佛嘱大乘学人见比丘持此经卷，当观其人具如是功德。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-068",
    category: "聞品得益",
    text: "佛說是藥王菩薩往古品時，八萬四千菩薩，即皆逮得曉一切音方便總持。",
    anchorText: "佛說是藥王菩薩往古品時",
    note: "佛说本品时，八万四千菩萨即得晓一切音方便总持。",
  },
  {
    sectionTitle: YAOWANG_SECTION_TITLE,
    id: "t0263-009-069",
    category: "經典行業",
    text: "善哉！善哉！宿王華菩薩！卿能諮啟不可思議經典行業，如來講說何以快哉！",
    anchorText: "諮啟不可思議經典行業",
    note: "众宝如来赞宿王华能启问不可思议经典行业，称叹如来讲说。",
  },
];
