import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const HUACHENG_SECTION_TITLE = "化城喻品第七";

export const T0264_JUAN_3_HUACHENG_VERSE_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-003-148",
    category: "成佛供養",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "大通智勝佛，十劫坐道場，佛法不現前，不得成佛道。諸天神龍王，阿脩羅眾等，常雨於天花，以供養彼佛。諸天擊天鼓，并作眾伎樂，香風吹萎花，更雨新好者，過十小劫已，乃得成佛道；諸天及世人，心皆懷踊躍。",
    anchorText: "大通智勝佛，十劫坐道場",
    note: "偈颂重宣大通智胜佛久坐道场、诸天供养，最终成佛时天人踊跃欢喜。",
    occurrence: 1,
  },
  {
    id: "t0264-003-149",
    category: "請轉法輪",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "彼佛十六子，皆與其眷屬，千萬億圍繞，俱行至佛所，頭面禮佛足，而請轉法輪：「聖師子法雨，充我及一切。」",
    anchorText: "聖師子法雨，充我及一切",
    note: "十六王子请佛转法轮，愿法雨充满自他一切众生。",
    occurrence: 1,
  },
  {
    id: "t0264-003-150",
    category: "佛出世利",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "世尊甚難值，久遠時一現，為覺悟群生，振動於一切。",
    anchorText: "世尊甚難值，久遠時一現",
    note: "偈颂赞佛久远难值，为觉悟群生而现世。",
    occurrence: 1,
  },
  {
    id: "t0264-003-151",
    category: "甘露法輪",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "三方及四維，上下亦復爾，散華奉宮殿，請佛轉法輪：「世尊甚難值，願以大慈悲，廣開甘露門，轉無上法輪。」",
    anchorText: "願以大慈悲，廣開甘露門",
    note: "十方梵天请佛以大慈悲广开甘露门、转无上法轮。",
    occurrence: 1,
  },
  {
    id: "t0264-003-152",
    category: "聞法解脫",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "無量慧世尊，受彼眾人請，為宣種種法：「四諦十二緣，無明至老死，皆從生緣有，如是眾過患，汝等應當知。」宣暢是法時，六百萬億姟，得盡諸苦際，皆成阿羅漢。第二說法時，千萬恒沙眾，於諸法不受，亦得阿羅漢。從是後得道，其數無有量，萬億劫算數，不能得其邊。",
    anchorText: "宣暢是法時，六百萬億姟",
    note: "大通智胜佛宣说四谛十二因缘，众生闻法得尽苦际，得道者无量无边。",
    occurrence: 1,
  },
  {
    id: "t0264-003-153",
    category: "請說大乘",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "時十六王子，出家作沙彌，皆共請彼佛，演說大乘法：「我等及營從，皆當成佛道，願得如世尊，慧眼第一淨。」",
    anchorText: "皆共請彼佛，演說大乘法",
    note: "十六王子出家为沙弥，请佛演说大乘法，愿自他皆成佛道。",
    occurrence: 1,
  },
  {
    id: "t0264-003-154",
    category: "宣說法華",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "佛知童子心，宿世之所行，以無量因緣，種種諸譬喻，說六波羅蜜，及諸神通事，分別真實法，菩薩所行道。說是《法華經》，如恒河沙偈。",
    anchorText: "分別真實法，菩薩所行道",
    note: "佛知十六沙弥心行，以无量因缘譬喻分别真实法、菩萨道，并说《法华经》。",
    occurrence: 1,
  },
  {
    id: "t0264-003-155",
    category: "弘法利生",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "彼佛說經已，靜室入禪定，一心一處坐，八萬四千劫。是諸沙彌等，知佛禪未出，為無量億眾，說佛無上慧，各各坐法座，說是大乘經，於佛宴寂後，宣揚助法化。一一沙彌等，所度諸眾生，有六百萬億，恒河沙等眾。",
    anchorText: "為無量億眾，說佛無上慧",
    note: "佛入定后，十六沙弥各坐法座，为无量众说佛无上慧、宣扬助化。",
    occurrence: 1,
  },
  {
    id: "t0264-003-156",
    category: "常遇善師",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "彼佛滅度後，是諸聞法者，在在諸佛土，常與師俱生。是十六沙彌，具足行佛道，今現在十方，各得成正覺。",
    anchorText: "在在諸佛土，常與師俱生",
    note: "闻法者在诸佛土常与师俱生，十六沙弥也具足佛道，今于十方成正觉。",
    occurrence: 1,
  },
  {
    id: "t0264-003-157",
    category: "引入佛慧",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "爾時聞法者，各在諸佛所，其有住聲聞，漸教以佛道。我在十六數，曾亦為汝說，是故以方便，引汝趣佛慧；以是本因緣，今說《法華經》，令汝入佛道，慎勿懷驚懼。",
    anchorText: "是故以方便，引汝趣佛慧",
    note: "佛说明宿世因缘，以方便引导声闻趣向佛慧，今说《法华经》令入佛道。",
    occurrence: 1,
  },
  {
    id: "t0264-003-158",
    category: "導師濟難",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "譬如險惡道，逈絕多毒獸，又復無水草，人所怖畏處，無數千萬眾，欲過此險道，其路甚曠遠，經五百由旬。時有一導師，強識有智慧，明了心決定，在險濟眾難。",
    anchorText: "時有一導師，強識有智慧",
    note: "化城譬喻中，导师智慧明了，能在险道中济度众难。",
    occurrence: 1,
  },
  {
    id: "t0264-003-159",
    category: "方便安隱",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "眾人皆疲倦，而白導師言：「我等今頓乏，於此欲退還。」導師作是念：「此輩甚可愍，如何欲退還，而失大珍寶？」尋時思方便，當設神通力，化作大城郭，莊嚴諸舍宅，周匝有園林，流渠及浴池，重門高樓閣，男女皆充滿。即作是化已，慰眾言勿懼：「汝等入此城，各可隨所樂。」諸人既入城，心皆大歡喜，皆生安隱想，自謂已得度。",
    anchorText: "尋時思方便，當設神通力",
    note: "导师见众人疲惫欲退，以方便力化城安慰，使众人生欢喜安隐想。",
    occurrence: 1,
  },
  {
    id: "t0264-003-160",
    category: "勸進寶所",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "導師知已息，集眾而告言：「汝等當前進，此是化城耳！我見汝疲極，中道欲退還，故以方便力，權化作此城；汝今勤精進，當共至寶所。」",
    anchorText: "汝今勤精進，當共至寶所",
    note: "导师待众人止息后，明示化城非究竟，劝令勤精进共至宝所。",
    occurrence: 1,
  },
  {
    id: "t0264-003-161",
    category: "方便涅槃",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "我亦復如是，為一切導師，見諸求道者，中路而懈廢，不能度生死，煩惱諸險道；故以方便力，為息說涅槃，言：「汝等苦滅，所作皆已辦。」",
    anchorText: "我亦復如是，為一切導師",
    note: "佛以一切导师自喻，见求道者中途懈废，以方便说涅槃令其止息。",
    occurrence: 1,
  },
  {
    id: "t0264-003-162",
    category: "真實一乘",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "既知到涅槃，皆得阿羅漢；爾乃集大眾，為說真實法。諸佛方便力，分別說三乘，唯有一佛乘，息處故說二。",
    anchorText: "爾乃集大眾，為說真實法",
    note: "佛待众生得止息后，集大众说真实法，明诸佛方便分说三乘而唯有一佛乘。",
    occurrence: 1,
  },
  {
    id: "t0264-003-163",
    category: "佛慧究竟",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "「今為汝說實，汝所得非滅，為佛一切智，當發大精進，汝證一切智，十力等佛法，具三十二相，乃是真實滅。」諸佛之導師，為息說涅槃，既知是息已，引入於佛慧。",
    anchorText: "為佛一切智，當發大精進",
    note: "偈颂收束化城譬喻，说明应为佛一切智发大精进，诸佛最终引入佛慧。",
    occurrence: 1,
  },
];