import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const WANGGU_SECTION_TITLE = "往古品第七";

export const T0263_JUAN_4_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0263-004-001",
    category: "佛智久遠",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "比丘欲知，佛之智慧，聖明普達，等無有異。佛皆覺了，過無數劫，不計微妙，無漏之誼。",
    anchorText: "比丘欲知，佛之智慧，聖明普達",
    note: "本品以大通眾慧佛往古因緣开示佛智通达久远劫事。",
  },
  {
    id: "t0263-004-002",
    category: "精進成道",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "修勤苦行，竟十中劫，專精一心，處在一座，其身清淨，而不動搖，燒諸苦患，如拔樹根。",
    anchorText: "修勤苦行，竟十中劫，專精一心",
    note: "大通眾慧佛久修专精，显示成道来自清净坚固的精进。",
  },
  {
    id: "t0263-004-003",
    category: "成佛安隱",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "究竟寂定，無有諸漏。現在吉祥，常獲大安，無想著故，得尊佛道。",
    anchorText: "究竟寂定，無有諸漏",
    note: "偈中赞佛寂定无漏、常获大安而得佛道。",
  },
  {
    id: "t0263-004-004",
    category: "見佛增益",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "我等見之，增智無畏，如是比類，長益德義。",
    anchorText: "我等見之，增智無畏",
    note: "十六王子等见佛成道，增长智慧、无畏与德义。",
  },
  {
    id: "t0263-004-005",
    category: "不信果報",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "其不篤信，諸佛音聲，長夜增益，惡道之罪，則失人身，墮落惡趣，為一切世，所見謗毀。",
    anchorText: "其不篤信，諸佛音聲",
    note: "经文反面说明不信诸佛音声的恶趣果报。",
  },
  {
    id: "t0263-004-006",
    category: "說法饒益",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "願說經法安住分別，多所安隱多所愍傷，饒益眾生安諸天人。",
    anchorText: "願說經法安住分別",
    note: "众王子劝请佛说经法，明说能安隐、愍伤、饶益众生与天人。",
  },
  {
    id: "t0263-004-007",
    category: "開化蒙度",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "惟願大聖，讚說經典，開化眾生，發起黎庶。三界群萌，悉共渴仰，使建道意，皆令蒙度。",
    anchorText: "惟願大聖，讚說經典",
    note: "劝请赞说经典的目的，是开化众生、发起道意、令得蒙度。",
  },
  {
    id: "t0263-004-008",
    category: "轉法輪益",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "則為轉法輪，最勝無等倫，勉脫眾生厄，悉令至大道。",
    anchorText: "則為轉法輪，最勝無等倫",
    note: "转法轮能勉脱众生厄难，使趣向大道。",
  },
  {
    id: "t0263-004-009",
    category: "佛出護世",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "見佛無量，得未曾有，多所愍傷，興出于世。世尊所演，如師子吼，則已將護，十方黎庶。",
    anchorText: "見佛無量，得未曾有",
    note: "梵天赞佛出世稀有，如师子吼演法，将护十方众生。",
  },
  {
    id: "t0263-004-010",
    category: "聞法成佛",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "最上大人，願轉法輪，惟講經典，為十方人。度脫羣萌，苦惱之患，令一切人，喜踊亘然。其有聞者，得成佛道，諸天人民，咸蒙安隱。",
    anchorText: "最上大人，願轉法輪",
    note: "经文直接说闻此转法轮者得成佛道，诸天人民蒙安隐。",
  },
  {
    id: "t0263-004-011",
    category: "甘露法門",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "開通甘露門，度脫無數人。",
    anchorText: "開通甘露門，度脫無數人",
    note: "梵天赞佛开通甘露门，能度脱无数人。",
  },
  {
    id: "t0263-004-012",
    category: "聽法得道",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "若得聽佛法，進獲平等道。",
    anchorText: "若得聽佛法，進獲平等道",
    note: "本品明说得听佛法者，能进获平等道。",
  },
  {
    id: "t0263-004-013",
    category: "正法反誡",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "常不行佛道，不處於正法，違無量聖教，即墮於惡趣。",
    anchorText: "常不行佛道，不處於正法",
    note: "反面警示远离佛道正法、违背圣教的恶趣果报。",
  },
  {
    id: "t0263-004-014",
    category: "法音度苦",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "思願講說，無上法輪，惟雷法鼓，尊妙法音。度脫眾生，勤苦之患，加哀示現，無為大道。",
    anchorText: "思願講說，無上法輪",
    note: "梵天请佛击大法鼓，以尊妙法音度脱众生勤苦。",
  },
  {
    id: "t0263-004-015",
    category: "四諦緣起",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "轉大法輪三轉十二事，開化發起沙門梵志、諸天龍神、眾魔梵天及世人民",
    anchorText: "轉大法輪三轉十二事",
    note: "大通眾慧佛转法轮，开化沙门梵志乃至诸天世人。",
  },
  {
    id: "t0263-004-016",
    category: "聞法漏盡",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "大通眾慧如來三說經法，須臾之頃分別此誼，令十六億百千姟眾漏盡意解，逮得六通三達之智，無央數人皆得度脫。",
    anchorText: "大通眾慧如來三說經法",
    note: "三说经法令大众漏尽意解，得六通三达，无数人度脱。",
  },
  {
    id: "t0263-004-017",
    category: "受持授決",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "聞佛所說悉共受持，諷誦講讚。其佛授決，當得無上正真之道。",
    anchorText: "聞佛所說悉共受持",
    note: "十六沙弥闻佛所说后受持、讽诵、讲赞，并蒙授记成佛。",
  },
  {
    id: "t0263-004-018",
    category: "化度大乘",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "一一菩薩化度六十萬江河沙億百千姟，處於無上正真道，皆立大乘。",
    anchorText: "一一菩薩化度六十萬江河沙",
    note: "十六王子说法时，一一菩萨化度无量众生，令处无上道、立大乘。",
  },
  {
    id: "t0263-004-019",
    category: "功德難量",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "十六王子所建功德難及無量，至未曾有智慧巍巍，則以供養無數億百千諸佛，眾行具足普受聖慧，入于道明合集佛智",
    anchorText: "十六王子所建功德難及無量",
    note: "佛亲赞十六王子功德无量、智慧巍巍，众行具足而入佛智。",
  },
  {
    id: "t0263-004-020",
    category: "聽經成佛",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "諸族姓子，聽所說經不拒逆者，皆當逮得無上正真之道，成佛聖慧。",
    anchorText: "聽所說經不拒逆者",
    note: "经文明说听所说经而不拒逆者，皆当逮得无上正真道。",
  },
  {
    id: "t0263-004-021",
    category: "值佛聞法",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "其十六子具菩薩乘，一一開化六十江河沙等人，所生之處常共俱會，亦復普說聽正法誼，各各值見四十億百千諸佛世尊",
    anchorText: "其十六子具菩薩乘",
    note: "十六王子开化众生，使所化者生处常会闻法，并值见众多诸佛。",
  },
  {
    id: "t0263-004-022",
    category: "現成佛道",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "今皆成無上正真之道，今悉現在，處于十方說法救護，無數億百千姟兆載聲聞眾，不可稱計菩薩",
    anchorText: "今皆成無上正真之道",
    note: "十六王子今皆成佛，于十方说法救护无量声闻菩萨。",
  },
  {
    id: "t0263-004-023",
    category: "漸進佛道",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "住聲聞地者，漸當誘進無上大道，稍稍當成最正覺。",
    anchorText: "住聲聞地者，漸當誘進無上大道",
    note: "对住声闻地者，佛仍渐次诱进无上大道，令终成正觉。",
  },
  {
    id: "t0263-004-024",
    category: "信樂佛護",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "如來滅度時，若有聞說歡喜信者，佛恩所護。",
    anchorText: "若有聞說歡喜信者",
    note: "经文直说闻说欢喜信受者，为佛恩所护。",
  },
  {
    id: "t0263-004-025",
    category: "一乘方便",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "佛在前立勸發無上正真道意。其羅漢事，限礙非真不至大道，若至他方與佛相見，得不退轉無所從生，乃為大寶究竟之事。",
    anchorText: "佛在前立勸發無上正真道意",
    note: "化城喻结明声闻涅槃非究竟，佛终劝发无上道意，至不退转。",
  },
  {
    id: "t0263-004-026",
    category: "善權三乘",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "佛語諸比丘：「如來說法爾等聞之，謂悉備足，不知所作尚未成辦。又如來慧，普見世間一切人心，示現泥洹，如來、至真、等正覺，善權方便說有三乘。」",
    anchorText: "如來慧，普見世間一切人心",
    note: "佛解释三乘为善权方便，提醒所作尚未究竟成办。",
  },
  {
    id: "t0263-004-027",
    category: "法眼甘露",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "願轉法輪，光闡心目，無數億劫，難得值遇，惟垂示現，往古根力，加哀開䦱，甘露法門，普等法眼",
    anchorText: "願轉法輪，光闡心目",
    note: "偈中请佛转法轮、开甘露门与平等法眼，显明此法难值。",
  },
  {
    id: "t0263-004-028",
    category: "開眼解法",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "時佛為說，遍示四諦，一切具解，十二因緣。為顯無黠，令得眼目，講說生死，憂苦空患。",
    anchorText: "時佛為說，遍示四諦",
    note: "佛说四谛与十二因缘，为无明众生开眼目，令解生死苦患。",
  },
  {
    id: "t0263-004-029",
    category: "流布佛化",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "顯揚宣布，斯《正法華》。普雨講說，大方等經，若干千頌，不可思念。",
    anchorText: "顯揚宣布，斯《正法華》",
    note: "本品明十六沙弥显扬宣布《正法华》，普雨讲说大方等经。",
  },
  {
    id: "t0263-004-030",
    category: "供佛成道",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "悉得覲于，四十億佛。彼諸學士，適聞斯名，便即供養，兩足之尊。有四事行，離垢為貴，悉得佛道，現在十方。",
    anchorText: "悉得覲于，四十億佛",
    note: "闻法所化者值见诸佛、供养两足尊，最终皆得佛道。",
  },
  {
    id: "t0263-004-031",
    category: "親近發心",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "步步各各，若干色像，今當親近，發大道意。",
    anchorText: "今當親近，發大道意",
    note: "经文劝令亲近诸佛因缘，发起大道意。",
  },
  {
    id: "t0263-004-032",
    category: "方便開導",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "佛告比丘，吾亦如是，見無央數，億千眾生，患厭勤苦，周旋迷惑，以方便教，而開導之。",
    anchorText: "見無央數，億千眾生",
    note: "化城喻后佛自明：见众生疲苦迷惑，故以方便教开导。",
  },
  {
    id: "t0263-004-033",
    category: "唯一佛乘",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "諸佛大聖，善權方便，講說佛教，大仙救護。其乘有一，未曾有二。",
    anchorText: "其乘有一，未曾有二",
    note: "本品以化城喻归结一乘，三乘只是诸佛善权方便。",
  },
  {
    id: "t0263-004-034",
    category: "勸修佛慧",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "此諸比丘，當興精進，第一英妙。諸仁當志，一切敏慧，菩薩典法，無有滅度。",
    anchorText: "當興精進，第一英妙",
    note: "结偈劝诸比丘兴精进，志求一切敏慧与菩萨法。",
  },
  {
    id: "t0263-004-035",
    category: "當得佛道",
    sectionTitle: WANGGU_SECTION_TITLE,
    text: "我常發求，成諸通慧，得達十方，最勝之法。顏貌殊妙，相三十二，當得佛道，乃應滅度。",
    anchorText: "我常發求，成諸通慧",
    note: "终结处明发求诸通慧、达最胜法，最终当得佛道。",
  },
];
