import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const WUBAIDIZI_SECTION_TITLE = "五百弟子受記品第八";
const SHOUXUEWUXUERENJI_SECTION_TITLE = "授學無學人記品第九";

export const T0262_JUAN_4_WUBAIDIZI_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0262-004-060",
    category: "聞法歡喜",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "爾時富樓那彌多羅尼子。從佛聞是智慧方便隨宜說法。又聞授諸大弟子阿耨多羅三藐三菩提記。復聞宿世因緣之事。復聞諸佛有大自在神通之力。得未曾有。心淨踊躍。",
    anchorText: "從佛聞是智慧方便隨宜說法",
    note: "富樓那聞佛方便說法、授記、宿世因緣與佛神通力，得未曾有，心淨踊躍。",
  },
  {
    id: "t0262-004-061",
    category: "佛德希有",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "世尊甚奇特。所為希有。隨順世間若干種性。以方便知見而為說法。拔出眾生處處貪著。",
    anchorText: "世尊甚奇特。所為希有",
    note: "富樓那讚佛隨順眾生根性，以方便知見說法，拔出眾生貪著。",
  },
  {
    id: "t0262-004-062",
    category: "護法利生",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "精勤護持。助宣我法。能於四眾示教利喜。具足解釋佛之正法。而大饒益同梵行者。",
    anchorText: "精勤護持。助宣我法",
    note: "佛讚富樓那精勤護持、助宣佛法，能示教利喜並饒益同修梵行者。",
  },
  {
    id: "t0262-004-063",
    category: "說法第一",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "亦於過去九十億諸佛所。護持助宣佛之正法。於彼說法人中亦最第一。",
    anchorText: "亦於過去九十億諸佛所",
    note: "富樓那不只今世助宣佛法，過去九十億佛所亦護持正法，說法人中最為第一。",
  },
  {
    id: "t0262-004-064",
    category: "清淨說法",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "又於諸佛所說空法。明了通達。得四無礙智。常能審諦清淨說法。無有疑惑。",
    anchorText: "於諸佛所說空法。明了通達",
    note: "富樓那通達空法，得四無礙智，能審諦清淨說法。",
  },
  {
    id: "t0262-004-065",
    category: "方便饒益",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "而富樓那以斯方便。饒益無量百千眾生。又化無量阿僧祇人。令立阿耨多羅三藐三菩提。",
    anchorText: "富樓那以斯方便。饒益無量",
    note: "本品明說富樓那以方便饒益無量眾生，令無量人安立無上菩提。",
  },
  {
    id: "t0262-004-066",
    category: "教化眾生",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "為淨佛土故。常作佛事教化眾生。",
    anchorText: "常作佛事教化眾生",
    note: "富樓那為淨佛土常作佛事，教化眾生。",
  },
  {
    id: "t0262-004-067",
    category: "護法授記",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "亦於未來護持助宣無量無邊諸佛之法。教化饒益無量眾生。令立阿耨多羅三藐三菩提。",
    anchorText: "亦於未來護持助宣無量無邊諸佛之法",
    note: "佛授記富樓那未來仍護持助宣諸佛之法，教化饒益無量眾生。",
  },
  {
    id: "t0262-004-068",
    category: "精進成佛",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "為淨佛土故。當勤精進教化眾生。漸漸具足菩薩之道。過無量阿僧祇劫。當於此土得阿耨多羅三藐三菩提。",
    anchorText: "當勤精進教化眾生。漸漸具足菩薩之道",
    note: "富樓那因勤精進教化眾生、具足菩薩道，未來當得無上菩提。",
  },
  {
    id: "t0262-004-069",
    category: "淨土莊嚴",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "七寶為地。地平如掌。無有山陵谿澗溝壑。七寶臺觀。充滿其中。諸天宮殿。近處虛空。人天交接。兩得相見。",
    anchorText: "七寶為地。地平如掌",
    note: "法明如來佛土七寶莊嚴，平正清淨，人天相見。",
  },
  {
    id: "t0262-004-070",
    category: "離惡清淨",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "無諸惡道。亦無女人。一切眾生皆以化生。無有淫欲。得大神通。身出光明。飛行自在。志念堅固。精進智慧。",
    anchorText: "無諸惡道。亦無女人",
    note: "法明如來佛土無諸惡道，眾生化生，具神通光明、志念堅固與精進智慧。",
  },
  {
    id: "t0262-004-071",
    category: "法喜禪悅",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "其國眾生常以二食。一者法喜食。二者禪悅食。",
    anchorText: "其國眾生常以二食",
    note: "法明如來國中眾生以法喜、禪悅為食。",
  },
  {
    id: "t0262-004-072",
    category: "善教眾生",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "有無量阿僧祇千萬億那由他諸菩薩眾。得大神通。四無礙智。善能教化眾生之類。",
    anchorText: "諸菩薩眾。得大神通",
    note: "法明如來國中菩薩眾無量，具大神通與四無礙智，善能教化眾生。",
  },
  {
    id: "t0262-004-073",
    category: "三明八解脫",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "其聲聞眾。算數校計所不能知。皆得具足六通三明及八解脫。",
    anchorText: "皆得具足六通三明及八解脫",
    note: "法明如來國中聲聞無量，皆具六通、三明與八解脫。",
  },
  {
    id: "t0262-004-074",
    category: "功德莊嚴",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "其佛國土。有如是等無量功德莊嚴成就。",
    anchorText: "有如是等無量功德莊嚴成就",
    note: "經文總結法明如來佛國土具無量功德莊嚴。",
  },
  {
    id: "t0262-004-075",
    category: "方便度眾",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "以無數方便 化諸眾生類 自說是聲聞 去佛道甚遠 度脫無量眾 皆悉得成就 雖小欲懈怠 漸當令作佛",
    anchorText: "以無數方便 化諸眾生類",
    note: "偈頌開示菩薩以聲聞相方便化眾，度脫無量眾，漸令作佛。",
  },
  {
    id: "t0262-004-076",
    category: "助佛正法",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "所說無所畏 能令眾歡喜 未曾有疲倦 而以助佛事 已度大神通 具四無礙智 知諸根利鈍 常說清淨法",
    anchorText: "所說無所畏 能令眾歡喜",
    note: "偈中讚富樓那說法無畏，令眾歡喜，具四無礙智，常說清淨法。",
  },
  {
    id: "t0262-004-077",
    category: "住大乘法",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "演暢如是義 教諸千億眾 令住大乘法 而自淨佛土",
    anchorText: "教諸千億眾 令住大乘法",
    note: "富樓那演說法義，教千億眾住大乘法，並自淨佛土。",
  },
  {
    id: "t0262-004-078",
    category: "成就一切智",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "常以諸方便 說法無所畏 度不可計眾 成就一切智",
    anchorText: "度不可計眾 成就一切智",
    note: "偈頌說富樓那以方便無畏說法，度不可計眾，成就一切智。",
  },
  {
    id: "t0262-004-079",
    category: "功德成滿",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "富樓那比丘 功德悉成滿 當得斯淨土 賢聖眾甚多",
    anchorText: "富樓那比丘 功德悉成滿",
    note: "偈末總讚富樓那功德成滿，當得清淨佛土與眾多賢聖。",
  },
  {
    id: "t0262-004-080",
    category: "聞記歡喜",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "爾時千二百阿羅漢心自在者。作是念。我等歡喜。得未曾有。若世尊各見授記。如餘大弟子者。不亦快乎。",
    anchorText: "我等歡喜。得未曾有",
    note: "千二百阿羅漢聞授記因緣後歡喜，盼得佛親授無上菩提記。",
  },
  {
    id: "t0262-004-081",
    category: "授記作佛",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "是千二百阿羅漢。我今當現前次第與授阿耨多羅三藐三菩提記。",
    anchorText: "我今當現前次第與授阿耨多羅三藐三菩提記",
    note: "佛明說將為千二百阿羅漢現前次第授無上菩提記。",
  },
  {
    id: "t0262-004-082",
    category: "普明授記",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "其五百阿羅漢。優樓頻螺迦葉。伽耶迦葉。那提迦葉。迦留陀夷。優陀夷。阿[少/兔]樓馱。離婆多。劫賓那。薄拘羅。周陀。莎伽陀等。皆當得阿耨多羅三藐三菩提。盡同一號。名曰普明。",
    anchorText: "其五百阿羅漢。優樓頻螺迦葉",
    note: "五百阿羅漢皆得授記，未來同號普明如來。",
  },
  {
    id: "t0262-004-083",
    category: "供養歡喜",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "咸升妙樓閣 遊諸十方國 以無上供具 奉獻於諸佛 作是供養已 心懷大歡喜 須臾還本國 有如是神力",
    anchorText: "以無上供具 奉獻於諸佛",
    note: "普明如來國中菩薩遊十方國，以無上供具奉獻諸佛，供養已心大歡喜。",
  },
  {
    id: "t0262-004-084",
    category: "五百成佛",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "其五百比丘 次第當作佛 同號曰普明 轉次而授記",
    anchorText: "其五百比丘 次第當作佛",
    note: "偈頌明說五百比丘次第作佛，同號普明。",
  },
  {
    id: "t0262-004-085",
    category: "廣宣授記",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "餘諸聲聞眾 亦當復如是 其不在此會 汝當為宣說",
    anchorText: "餘諸聲聞眾 亦當復如是",
    note: "佛囑迦葉為不在會的聲聞眾宣說授記，顯示授記利益廣及眾多聲聞。",
  },
  {
    id: "t0262-004-086",
    category: "悔過得記",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "爾時五百阿羅漢。於佛前得授記已。歡喜踊躍。即從座起。到於佛前。頭面禮足。悔過自責。",
    anchorText: "於佛前得授記已。歡喜踊躍",
    note: "五百阿羅漢得授記後歡喜踊躍，禮佛悔過自責。",
  },
  {
    id: "t0262-004-087",
    category: "應得佛智",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "我等常作是念。自謂已得究竟滅度。今乃知之如無智者。所以者何。我等應得如來智慧。而便自以小智為足。",
    anchorText: "我等應得如來智慧",
    note: "阿羅漢自省過去以小智為足，今知本應得如來智慧。",
  },
  {
    id: "t0262-004-088",
    category: "衣珠譬喻",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "我昔欲令汝得安樂五欲自恣。於某年日月。以無價寶珠繫汝衣裏。今故現在。而汝不知。勤苦憂惱以求自活。甚為癡也。汝今可以此寶。貿易所需。常可如意。無所乏短。",
    anchorText: "以無價寶珠繫汝衣裏",
    note: "衣珠譬喻說明本有寶珠而不自知，一旦知之即可常得如意、無所乏短。",
  },
  {
    id: "t0262-004-089",
    category: "善根不失",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "佛亦如是。為菩薩時。教化我等。令發一切智心。而尋廢忘。不知不覺。既得阿羅漢道。自謂滅度。資生艱難。得少為足。一切智願。猶在不失。",
    anchorText: "令發一切智心。而尋廢忘",
    note: "佛久遠教化令發一切智心；雖後來忘失、得少為足，一切智願猶在不失。",
  },
  {
    id: "t0262-004-090",
    category: "非究竟滅",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "諸比丘。汝等所得。非究竟滅。我久令汝等種佛善根。以方便故示涅槃相。而汝謂為實得滅度。",
    anchorText: "汝等所得。非究竟滅",
    note: "佛覺悟聲聞，開示所得非究竟滅，久已令種佛善根，只是方便示涅槃相。",
  },
  {
    id: "t0262-004-091",
    category: "歡喜得記",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "世尊。我今乃知實是菩薩。得受阿耨多羅三藐三菩提記。以是因緣。甚大歡喜。得未曾有。",
    anchorText: "我今乃知實是菩薩",
    note: "阿羅漢聞佛開示後知自身實是菩薩，得受無上菩提記，甚大歡喜。",
  },
  {
    id: "t0262-004-092",
    category: "安隱授記",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "我等聞無上 安隱授記聲 歡喜未曾有 禮無量智佛",
    anchorText: "我等聞無上 安隱授記聲",
    note: "偈頌以聞無上安隱授記聲為歡喜未曾有。",
  },
  {
    id: "t0262-004-093",
    category: "無上願種",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "我等亦如是 世尊於長夜 常愍見教化 令種無上願 我等無智故 不覺亦不知",
    anchorText: "世尊於長夜 常愍見教化",
    note: "偈中回顧世尊長夜愍念教化，令種無上願。",
  },
  {
    id: "t0262-004-094",
    category: "真實滅度",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "今佛覺悟我 言非實滅度 得佛無上慧 爾乃為真滅",
    anchorText: "得佛無上慧 爾乃為真滅",
    note: "偈頌明示非實滅度，得佛無上慧才是真滅。",
  },
  {
    id: "t0262-004-095",
    category: "受決歡喜",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "我今從佛聞 授記莊嚴事 乃轉次受決 身心遍歡喜",
    anchorText: "我今從佛聞 授記莊嚴事",
    note: "品末以聞授記莊嚴、轉次受決而身心遍歡喜作結。",
  },
  {
    id: "t0262-004-096",
    category: "授記歡喜",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "我等每自思惟：『設得受記，不亦快乎。』",
    anchorText: "設得受記，不亦快乎",
    note: "阿難與羅睺羅表明求得佛授記即為快樂，顯示聞記受決的殊勝。",
  },
  {
    id: "t0262-004-097",
    category: "護持法藏",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "又我等為一切世間天、人、阿修羅所見知識——阿難常為侍者，護持法藏；羅睺羅是佛之子——若佛見授阿耨多羅三藐三菩提記者，我願既滿，眾望亦足。",
    anchorText: "阿難常為侍者，護持法藏",
    note: "阿難以侍佛、護持法藏為本行，得記則自願滿足，眾望亦足。",
  },
  {
    id: "t0262-004-098",
    category: "一心瞻仰",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "學、無學聲聞弟子二千人，皆從座起，偏袒右肩，到於佛前，一心合掌，瞻仰世尊，如阿難、羅睺羅所願，住立一面。",
    anchorText: "一心合掌，瞻仰世尊",
    note: "二千學無學弟子同向佛前，一心合掌瞻仰，隨喜求記。",
  },
  {
    id: "t0262-004-099",
    category: "阿難授記",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "汝於來世當得作佛，號山海慧自在通王如來、應供、正遍知、明行足、善逝、世間解、無上士、調御丈夫、天人師、佛、世尊。",
    anchorText: "汝於來世當得作佛，號山海慧自在通王",
    note: "佛為阿難授記，明示其未來當得作佛。",
  },
  {
    id: "t0262-004-100",
    category: "供佛成道",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "當供養六十二億諸佛，護持法藏，然後得阿耨多羅三藐三菩提。",
    anchorText: "當供養六十二億諸佛，護持法藏",
    note: "阿難未來供養諸佛、護持法藏，然後成就無上菩提。",
  },
  {
    id: "t0262-004-101",
    category: "教化菩薩",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "教化二十千萬億恒河沙諸菩薩等，令成阿耨多羅三藐三菩提。",
    anchorText: "教化二十千萬億恒河沙諸菩薩等",
    note: "阿難成佛後教化無量菩薩，令成無上菩提。",
  },
  {
    id: "t0262-004-102",
    category: "淨土莊嚴",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "國名常立勝幡，其土清淨，琉璃為地。",
    anchorText: "國名常立勝幡，其土清淨",
    note: "山海慧自在通王佛國土清淨，以琉璃為地。",
  },
  {
    id: "t0262-004-103",
    category: "佛德讚歎",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "是山海慧自在通王佛，為十方無量千萬億恒河沙等諸佛如來所共讚歎，稱其功德。",
    anchorText: "為十方無量千萬億恒河沙等諸佛如來所共讚歎",
    note: "阿難未來成佛，為十方諸佛共讚其功德。",
  },
  {
    id: "t0262-004-104",
    category: "聞記憶法",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "阿難面於佛前，自聞授記及國土莊嚴，所願具足，心大歡喜，得未曾有。即時憶念過去無量千萬億諸佛法藏，通達無礙，如今所聞，亦識本願。",
    anchorText: "自聞授記及國土莊嚴，所願具足",
    note: "阿難聞授記後所願具足、心大歡喜，並憶念過去諸佛法藏，通達無礙。",
  },
  {
    id: "t0262-004-105",
    category: "安住佛道",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "我今無復疑，安住於佛道，方便為侍者，護持諸佛法。",
    anchorText: "我今無復疑，安住於佛道",
    note: "阿難自述聞記後無復疑惑，安住佛道，護持諸佛法。",
  },
  {
    id: "t0262-004-106",
    category: "羅睺羅授記",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "汝於來世當得作佛，號蹈七寶華如來、應供、正遍知、明行足、善逝、世間解、無上士、調御丈夫、天人師、佛、世尊。",
    anchorText: "汝於來世當得作佛，號蹈七寶華如來",
    note: "佛為羅睺羅授記，明示其未來當得作佛。",
  },
  {
    id: "t0262-004-107",
    category: "一心求道",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "於未來世中，見無量億佛，皆為其長子，一心求佛道。",
    anchorText: "見無量億佛，皆為其長子，一心求佛道",
    note: "羅睺羅未來見無量佛，皆為長子，一心求佛道。",
  },
  {
    id: "t0262-004-108",
    category: "密行功德",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "羅睺羅密行，唯我能知之，現為我長子，以示諸眾生。無量億千萬，功德不可數，安住於佛法，以求無上道。",
    anchorText: "羅睺羅密行，唯我能知之",
    note: "佛讚羅睺羅密行與不可數功德，安住佛法求無上道。",
  },
  {
    id: "t0262-004-109",
    category: "清淨求記",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "爾時世尊見學、無學二千人，其意柔軟，寂然清淨，一心觀佛。",
    anchorText: "其意柔軟，寂然清淨，一心觀佛",
    note: "二千學無學弟子意柔軟、寂然清淨，一心觀佛，成為受記前的清淨狀態。",
  },
  {
    id: "t0262-004-110",
    category: "二千授記",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "是諸人等，當供養五十世界微塵數諸佛如來，恭敬尊重，護持法藏。末後同時於十方國各得成佛，皆同一號，名曰寶相如來、應供、正遍知、明行足、善逝、世間解、無上士、調御丈夫、天人師、佛、世尊。",
    anchorText: "當供養五十世界微塵數諸佛如來",
    note: "佛為二千學無學弟子授記，明示供養諸佛、護持法藏，末後同時成佛。",
  },
  {
    id: "t0262-004-111",
    category: "神通度生",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "咸以諸神通，度十方眾生，名聞普周遍，漸入於涅槃。",
    anchorText: "咸以諸神通，度十方眾生",
    note: "二千聲聞未來成佛後，以神通度十方眾生，名聞周遍。",
  },
  {
    id: "t0262-004-112",
    category: "聞記歡喜",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "世尊慧燈明，我聞授記音，心歡喜充滿，如甘露見灌。",
    anchorText: "我聞授記音，心歡喜充滿",
    note: "二千學無學弟子聞佛授記，心中歡喜充滿，如甘露灌頂。",
  },
];
