import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const XINJIE_SECTION_TITLE = "信解品第四";

export const T0264_JUAN_3_XINJIE_VERSE_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-003-021",
    category: "聞佛歡喜",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我等今日，聞佛音教，歡喜踊躍，得未曾有。佛說聲聞，當得作佛；無上寶聚，不求自得。",
    anchorText: "我等今日，聞佛音教，歡喜踊躍",
    note: "迦叶等闻佛音教，知声闻当得作佛，如无上宝聚不求自得。",
    occurrence: 1,
  },
  {
    id: "t0264-003-022",
    category: "方便攝受",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "長者知子，愚癡狹劣，不信我言，不信是父；即以方便，更遣餘人，眇目矬陋，無威德者，汝可語之：『云當相雇；除諸糞穢，倍與汝價。』窮子聞之，歡喜隨來，為除糞穢，淨諸房舍。",
    anchorText: "即以方便，更遣餘人",
    note: "偈颂重明长者随子根性设方便，喻佛渐次摄受、令其欢喜随来。",
    occurrence: 1,
  },
  {
    id: "t0264-003-023",
    category: "漸令知藏",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "長者有智，漸令入出，經二十年，執作家事，示其金銀、真珠頗梨，諸物出入，皆使令知；猶處門外，止宿草庵，自念貧事，我無此物。",
    anchorText: "長者有智，漸令入出",
    note: "长者渐令穷子出入知藏，喻佛以方便渐示法藏。",
    occurrence: 1,
  },
  {
    id: "t0264-003-024",
    category: "法財付囑",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "父知子心，漸已曠大，欲與財物，即聚親族，國王大臣，剎利居士，於此大眾，說是我子；捨我他行，經五十年，自見子來，已二十年。昔於某城，而失是子，周行求索，遂來至此。凡我所有，舍宅人民，悉以付之，恣其所用。",
    anchorText: "凡我所有，舍宅人民，悉以付之",
    note: "父见子心渐大而公开付与所有，喻如来令佛子承受法财。",
    occurrence: 1,
  },
  {
    id: "t0264-003-025",
    category: "得未曾有",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "子念昔貧，志意下劣，今於父所，大獲珍寶，并及舍宅，一切財物，甚大歡喜，得未曾有。",
    anchorText: "大獲珍寶，并及舍宅",
    note: "穷子得父财宝而大欢喜，喻声闻得大乘法财而获未曾有。",
    occurrence: 1,
  },
  {
    id: "t0264-003-026",
    category: "佛知根機",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "佛亦如是，知我樂小，未曾說言，汝等作佛。而說我等，得諸無漏，成就小乘，聲聞弟子。",
    anchorText: "佛亦如是，知我樂小",
    note: "经文说明佛知声闻乐小，先随宜说小乘成就。",
    occurrence: 1,
  },
  {
    id: "t0264-003-027",
    category: "修道成佛",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "佛勅我等，說最上道，修習此者，當得成佛。",
    anchorText: "說最上道，修習此者",
    note: "佛教声闻宣说最上道，并明修习此道当得成佛。",
    occurrence: 1,
  },
  {
    id: "t0264-003-028",
    category: "聞法授記",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "『諸佛子等，從我聞法，日夜思惟，精勤修習。』是時諸佛，即授其記；『汝於來世，當得作佛。』",
    anchorText: "從我聞法，日夜思惟，精勤修習",
    note: "诸佛子闻法后昼夜思惟、精勤修习，诸佛即为授记作佛。",
    occurrence: 1,
  },
  {
    id: "t0264-003-029",
    category: "諸佛祕藏",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "一切諸佛，祕藏之法，但為菩薩，演其實事，而不為我，說斯真要。",
    anchorText: "一切諸佛，祕藏之法",
    note: "偈中称大乘真实义为一切诸佛祕藏之法。",
    occurrence: 1,
  },
  {
    id: "t0264-003-030",
    category: "離苦得道",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我等長夜，修習空法；得脫三界，苦惱之患，住最後身，有餘涅槃。佛所教化，得道不虛，則為已得，報佛之恩。",
    anchorText: "得脫三界，苦惱之患",
    note: "声闻自述由佛教化修习空法，得脱三界苦患，得道不虚。",
    occurrence: 1,
  },
  {
    id: "t0264-003-031",
    category: "調伏教智",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "導師見捨，觀我心故，初不勸進，說有實利；如富長者，知子志劣，以方便力，柔伏其心，然後乃付，一切財寶；佛亦如是，現希有事，知樂小者，以方便力，調伏其心，乃教大智。",
    anchorText: "以方便力，柔伏其心",
    note: "佛如长者先柔伏其心，后付财宝，最终教以大智。",
    occurrence: 1,
  },
  {
    id: "t0264-003-032",
    category: "自得無量寶",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我等今日，得未曾有，非先所望，而今自得；如彼窮子，得無量寶。",
    anchorText: "非先所望，而今自得",
    note: "声闻自庆今日所得超出先望，如穷子得无量宝。",
    occurrence: 1,
  },
  {
    id: "t0264-003-033",
    category: "清淨法眼",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "世尊我今，得道得果，於無漏法，得清淨眼。",
    anchorText: "於無漏法，得清淨眼",
    note: "声闻自陈得道得果，于无漏法得清净眼。",
    occurrence: 1,
  },
  {
    id: "t0264-003-034",
    category: "持戒果報",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我等長夜，持佛淨戒，始於今日，得其果報。",
    anchorText: "持佛淨戒，始於今日",
    note: "长夜持佛净戒，至今日得其果报。",
    occurrence: 1,
  },
  {
    id: "t0264-003-035",
    category: "無上大果",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "法王法中，久修梵行，今得無漏，無上大果。",
    anchorText: "久修梵行，今得無漏",
    note: "久修梵行而得无漏、无上大果，是本段明确果报语。",
    occurrence: 1,
  },
  {
    id: "t0264-003-036",
    category: "佛道令聞",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我等今者，真是聲聞，以佛道聲，令一切聞。",
    anchorText: "以佛道聲，令一切聞",
    note: "偈中重新定义声闻：以佛道之声令一切闻。",
    occurrence: 1,
  },
  {
    id: "t0264-003-037",
    category: "應受供養",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我等今者，真阿羅漢，於諸世間，天人魔梵，普於其中，應受供養。",
    anchorText: "天人魔梵，普於其中，應受供養",
    note: "声闻自述今日真实成就阿罗汉，应受世间天人魔梵供养。",
    occurrence: 1,
  },
  {
    id: "t0264-003-038",
    category: "佛恩難報",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "世尊大恩，以希有事，憐愍教化，利益我等；無量億劫，誰能報者？",
    anchorText: "世尊大恩，以希有事",
    note: "本段以佛恩难报赞叹世尊悲愍教化、利益声闻。",
    occurrence: 1,
  },
  {
    id: "t0264-003-039",
    category: "隨宜而說",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "諸佛希有，無量無邊，不可思議，大神通力；無漏無為，諸法之王，能為下劣，忍于斯事；取相凡夫，隨宜而說。",
    anchorText: "諸佛希有，無量無邊",
    note: "偈中赞诸佛希有，以不可思议神通力随宜为凡夫说法。",
    occurrence: 1,
  },
  {
    id: "t0264-003-040",
    category: "一乘方便",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "諸佛於法，得最自在，知諸眾生，種種欲樂，及其志力，隨所堪任；以無量喻，而為說法，隨諸眾生，宿世善根；又知成熟，未成熟者，種種籌量，分別知已，於一乘道，隨宜說三。",
    anchorText: "諸佛於法，得最自在",
    note: "结尾总赞诸佛于法自在，知众生根机，于一乘道随宜说三。",
    occurrence: 1,
  },
];
