import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const SHOUJI_SECTION_TITLE = "授記品第六";

export const T0264_JUAN_3_SHOUJI_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-003-100",
    category: "授記成佛",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "我此弟子摩訶迦葉，於未來世，當得奉覲三百萬億諸佛世尊，供養、恭敬、尊重、讚嘆，廣宣諸佛無量大法，於最後身得成為佛，名曰光明如來、應供、正遍知、明行足、善逝、世間解、無上士、調御丈夫、天人師、佛、世尊，",
    anchorText: "我此弟子摩訶迦葉，於未來世",
    note: "佛为摩诃迦叶授记，明其未来供养诸佛、广宣大法，最后成佛。",
    occurrence: 1,
  },
  {
    id: "t0264-003-101",
    category: "淨土莊嚴",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "國界嚴飾，無諸穢惡、瓦礫、荊棘、便利、不淨，其土平正，無有高下坑坎堆埠，琉璃為地寶樹行列，黃金為繩以界道側，散諸寶華周遍清淨；",
    anchorText: "國界嚴飾，無諸穢惡",
    note: "迦叶未来佛土清净严饰、无诸秽恶，显示授记果报庄严。",
    occurrence: 1,
  },
  {
    id: "t0264-003-102",
    category: "護持佛法",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "其國菩薩無量千億，諸聲聞眾亦復無數，無有魔事，雖有魔及魔民，皆護佛法。",
    anchorText: "無有魔事，雖有魔及魔民，皆護佛法",
    note: "经文称其国无有魔事，乃至魔民皆护佛法。",
    occurrence: 1,
  },
  {
    id: "t0264-003-103",
    category: "修集佛慧",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "而於來世，供養奉覲，三百萬億，諸佛世尊；為佛智慧，淨修梵行。供養最上，兩足尊已，修集一切，無上之慧，於最後身，得成為佛。",
    anchorText: "為佛智慧，淨修梵行",
    note: "偈颂说明迦叶为佛智慧净修梵行、修集无上慧，最后成佛。",
    occurrence: 1,
  },
  {
    id: "t0264-003-104",
    category: "奉持大乘",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "諸菩薩眾，不可稱計，其心調柔，逮大神通，奉持諸佛，大乘經典。",
    anchorText: "奉持諸佛，大乘經典",
    note: "未来国土菩萨不可称计，调柔具神通，并奉持诸佛大乘经典。",
    occurrence: 1,
  },
  {
    id: "t0264-003-105",
    category: "聞記安樂",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "若蒙佛授記，爾乃快安樂。大雄猛世尊，常欲安世間，願賜我等記，如飢須教食。",
    anchorText: "若蒙佛授記，爾乃快安樂",
    note: "大弟子以甘露、王膳作喻，请佛授记；若蒙授记，便得快安乐。",
    occurrence: 1,
  },
  {
    id: "t0264-003-106",
    category: "須菩提授記",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "是須菩提，於當來世，奉覲三百萬億那由他佛，供養、恭敬、尊重、讚嘆，常修梵行具菩薩道，於最後身得成為佛，號曰名相如來、應供、正遍知、明行足、善逝、世間解、無上士、調御丈夫、天人師、佛、世尊，",
    anchorText: "是須菩提，於當來世",
    note: "佛为须菩提授记，明其未来供养诸佛、具菩萨道，最后成佛。",
    occurrence: 1,
  },
  {
    id: "t0264-003-107",
    category: "說法度眾",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "其佛常處虛空，為眾說法，度脫無量菩薩及聲聞眾。",
    anchorText: "為眾說法，度脫無量菩薩及聲聞眾",
    note: "须菩提未来成佛后常为众说法，度脱无量菩萨与声闻。",
    occurrence: 1,
  },
  {
    id: "t0264-003-108",
    category: "漸具大道",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "我大弟子，須菩提者，當得作佛，號曰名相；當供無數，萬億諸佛；隨佛所作，漸具大道，最後身得，三十二相；",
    anchorText: "隨佛所作，漸具大道",
    note: "偈颂重申须菩提随佛所作、渐具大道，最后成佛。",
    occurrence: 1,
  },
  {
    id: "t0264-003-109",
    category: "聽受佛語",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "其佛說法，現於無量，神通變化，不可思議；諸天人民，數如恒沙，皆共合掌，聽受佛語。",
    anchorText: "皆共合掌，聽受佛語",
    note: "须菩提未来佛说法现不可思议神变，恒沙诸天人民合掌听受。",
    occurrence: 1,
  },
  {
    id: "t0264-003-110",
    category: "迦旃延授記",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "是大迦旃延，於當來世，以諸供具，供養奉事八千億佛，恭敬尊重；諸佛滅後，各起塔廟高千由旬，縱廣正等五百由旬，",
    anchorText: "是大迦旃延，於當來世",
    note: "佛为大迦旃延授记，明其未来供养奉事诸佛并起塔供养。",
    occurrence: 1,
  },
  {
    id: "t0264-003-111",
    category: "具道成佛",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "供養是諸佛已，具菩薩道當得作佛，號曰閻浮那提金光如來、應供、正遍知、明行足、善逝、世間解、無上士、調御丈夫、天人師、佛、世尊，",
    anchorText: "供養是諸佛已，具菩薩道當得作佛",
    note: "大迦旃延供养诸佛后具菩萨道，当得成佛。",
    occurrence: 1,
  },
  {
    id: "t0264-003-112",
    category: "無惡道土",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "其土平正，頗梨為地，寶樹莊嚴，黃金為繩以界道側，妙華覆地周遍清淨，見者歡喜；無四惡道，地獄、餓鬼、畜生、阿修羅道，多有天人，諸聲聞眾，及諸菩薩；",
    anchorText: "無四惡道，地獄、餓鬼、畜生、阿修羅道",
    note: "迦旃延未来佛土清净严饰，且无四恶道。",
    occurrence: 1,
  },
  {
    id: "t0264-003-113",
    category: "真實授記",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "諸比丘眾，皆一心聽；如我所說，真實無異。是迦旃延，當以種種，妙好供具，供養諸佛；諸佛滅後，起七寶塔，亦以華香，供養舍利。",
    anchorText: "如我所說，真實無異",
    note: "偈颂强调佛所授记真实无异，并重申迦旃延未来供佛起塔。",
    occurrence: 1,
  },
  {
    id: "t0264-003-114",
    category: "目連授記",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "我今語汝，是大目犍連，當以種種供具供養八千諸佛，恭敬尊重，諸佛滅後，各起塔廟高千由旬，縱廣正等五百由旬，",
    anchorText: "我今語汝，是大目犍連",
    note: "佛为大目犍连授记，明其未来供养诸佛、起塔供养。",
    occurrence: 1,
  },
  {
    id: "t0264-003-115",
    category: "奉持佛法",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "為佛道故，供養恭敬，於諸佛所，常修梵行，於無量劫，奉持佛法；",
    anchorText: "於無量劫，奉持佛法",
    note: "偈颂说明目犍连为佛道供养恭敬、常修梵行，并于无量劫奉持佛法。",
    occurrence: 1,
  },
  {
    id: "t0264-003-116",
    category: "說法不退",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "常為天人，演說佛道，聲聞無量，如恒河沙，三明六通，有大威德；菩薩無數，志固精進，於佛智慧，皆不退轉；",
    anchorText: "常為天人，演說佛道",
    note: "目犍连未来成佛后常为天人演说佛道，菩萨无数且于佛智慧不退转。",
    occurrence: 1,
  },
  {
    id: "t0264-003-117",
    category: "弟子成佛",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "我諸弟子，威德具足，其數五百，皆當授記，於未來世，咸得成佛；",
    anchorText: "其數五百，皆當授記",
    note: "品末总明五百威德具足弟子皆当授记，未来悉得成佛。",
    occurrence: 1,
  },
];