import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const YAOWANG_SECTION_TITLE = "藥王菩薩本事品第二十二";

export const T0264_JUAN_6_YAOWANG_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-006-093",
    category: "聞經得三昧",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "我得現一切色身三昧，皆是得聞《法華經》力，我今當供養日月淨明德佛及《法華經》。",
    anchorText: "皆是得聞《法華經》力",
    note: "一切众生喜见菩萨自述，所得现一切色身三昧皆由得闻《法华经》之力。",
  },
  {
    id: "t0264-006-094",
    category: "真法供養",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "善哉，善哉！善男子！是真精進，是名真法供養如來。",
    anchorText: "是真精進，是名真法供養如來",
    note: "诸佛赞叹一切众生喜见菩萨以身供养，为真精进、真法供养如来。",
  },
  {
    id: "t0264-006-095",
    category: "第一之施",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "善男子！是名第一之施，於諸施中最尊、最上，以法供養諸如來故。",
    anchorText: "是名第一之施，於諸施中最尊",
    note: "诸佛说明此法供养为诸施中最尊最上。",
  },
  {
    id: "t0264-006-096",
    category: "供養後得陀羅尼",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "我先供養佛已，得解一切眾生語言陀羅尼。復聞是《法華經》八百千萬億那由他甄迦羅、頻婆羅、阿閦婆等偈。",
    anchorText: "得解一切眾生語言陀羅尼",
    note: "菩萨供养佛后，得解一切众生语言陀罗尼，并复闻广大《法华经》偈。",
  },
  {
    id: "t0264-006-097",
    category: "供養舍利發心入定",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "作是語已，即於八萬四千塔前，然百福莊嚴臂，七萬二千歲而以供養，令無數求聲聞眾，無量阿僧祇人發阿耨多羅三藐三菩提心，皆使得住現一切色身三昧。",
    anchorText: "令無數求聲聞眾，無量阿僧祇人發",
    note: "一切众生喜见菩萨供养舍利，使无数众生发无上菩提心，并住现一切色身三昧。",
  },
  {
    id: "t0264-006-098",
    category: "福智淳厚感應",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "作是誓已，自然還復，由斯菩薩福德智慧淳厚所致。",
    anchorText: "由斯菩薩福德智慧淳厚所致",
    note: "经文明言菩萨两臂自然还复，是福德智慧淳厚所致。",
  },
  {
    id: "t0264-006-099",
    category: "燃指供塔勝施珍寶",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "若有發心欲得阿耨多羅三藐三菩提者，能燃手指乃至足一指供養佛塔，勝以國城妻子及三千大千國土山林河池諸珍寶物而供養者。",
    anchorText: "能燃手指乃至足一指供養佛塔",
    note: "佛以校量说明，发菩提心者燃指供塔，胜过以国城妻子及三千大千珍宝供养。",
  },
  {
    id: "t0264-006-100",
    category: "受持一偈福最多",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "若復有人，以七寶滿三千大千世界，供養於佛及大菩薩、辟支佛、阿羅漢，是人所得功德，不如受持此《法華經》乃至一四句偈，其福最多。",
    anchorText: "不如受持此《法華經》乃至一四句偈",
    note: "佛以七宝满三千大千世界供养校量，显受持《法华经》乃至一四句偈福最多。",
  },
  {
    id: "t0264-006-101",
    category: "經中最深大",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "此《法華經》亦復如是，於諸如來所說經中最為深大。",
    anchorText: "於諸如來所說經中最為深大",
    note: "以海为诸水第一作譬，赞《法华经》于诸如来所说经中最为深大。",
  },
  {
    id: "t0264-006-102",
    category: "破不善闇",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "又如日天子能除諸闇；此經亦復如是，能破一切不善之闇。",
    anchorText: "能破一切不善之闇",
    note: "佛以日能除暗为喻，说明此经能破一切不善之暗。",
  },
  {
    id: "t0264-006-103",
    category: "諸經中王",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "如佛為諸法王；此經亦復如是，諸經中王。",
    anchorText: "此經亦復如是，諸經中王",
    note: "经文以佛为诸法王作譬，赞此经为诸经中王。",
  },
  {
    id: "t0264-006-104",
    category: "救苦滿願",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "此經能救一切眾生者，此經能令一切眾生離諸苦惱，此經能大饒益一切眾生，充滿其願，如清涼池，能滿一切諸渴乏者，如寒者得火，如裸者得衣，如商人得主，如子得母，如渡得船，如病得醫，如闇得燈，如貧得寶，如民得王，如賈客得海，如炬除闇；此《法華經》亦復如是，能令眾生離一切苦，一切病痛，能解一切生死之縛。",
    anchorText: "能令一切眾生離諸苦惱",
    note: "佛直说此经能救护众生、离诸苦恼、大饶益众生并充满其愿。",
  },
  {
    id: "t0264-006-105",
    category: "離苦病縛",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "此《法華經》亦復如是，能令眾生離一切苦，一切病痛，能解一切生死之縛。",
    anchorText: "能令眾生離一切苦，一切病痛",
    note: "佛明此经能令众生离一切苦与病痛，并解生死之缚。",
  },
  {
    id: "t0264-006-106",
    category: "聞寫功德無邊",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "若人得聞此《法華經》，若自書，若使人書，所得功德，以佛智慧籌量多少，不得其邊。",
    anchorText: "以佛智慧籌量多少，不得其邊",
    note: "闻此《法华经》、自书或使人书，所得功德以佛智慧亦不能量其边。",
  },
  {
    id: "t0264-006-107",
    category: "供養經卷功德無量",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "若書是經卷，華香、瓔珞、燒香、粖香、塗香、幡蓋、衣服，種種之燈，穌燈、油燈、諸香油燈、瞻蔔油燈、須曼那油燈、波羅羅油燈、婆利師迦油燈、那婆摩利油燈供養，所得功德亦復無量。",
    anchorText: "所得功德亦復無量",
    note: "书写经卷并以华香、灯明等供养，所得功德无量。",
  },
  {
    id: "t0264-006-108",
    category: "聞品功德無量",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "若有人聞是〈藥王菩薩本事品〉者，亦得無量無邊功德。",
    anchorText: "聞是〈藥王菩薩本事品〉者",
    note: "佛直说闻此《药王菩萨本事品》者，亦得无量无边功德。",
  },
  {
    id: "t0264-006-109",
    category: "聞品受持轉女身",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "若有女人，聞是〈藥王菩薩本事品〉，能受持者，盡是女身，後不復受。",
    anchorText: "能受持者，盡是女身，後不復受",
    note: "经文说明女人闻此品而能受持者，尽此女身后不复受。",
  },
  {
    id: "t0264-006-110",
    category: "如說修行往生安樂",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "若有女人，聞是經典如說修行，於此命終，即往安樂世界阿彌陀佛、大菩薩眾圍遶住處，生蓮花中寶座之上，不復為貪欲所惱，亦復不為瞋恚、愚癡所惱，亦復不為憍慢、嫉妬諸垢所惱，得菩薩神通，無生法忍。",
    anchorText: "聞是經典如說修行，於此命終",
    note: "后五百岁中，女人闻此经典如说修行，命终往安乐世界，生莲华宝座，离诸烦恼并得无生法忍。",
  },
  {
    id: "t0264-006-111",
    category: "受持說經福德無量",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "汝能於釋迦牟尼佛法中，受持、讀誦、思惟是經，為他人說，所得福德無量無邊，火不能焚，水不能漂，汝之功德，千佛共說不能令盡，汝今已能破諸魔賊，壞生死軍，諸餘怨敵皆悉摧滅。",
    anchorText: "受持、讀誦、思惟是經，為他人說",
    note: "诸佛赞叹受持、读诵、思惟此经并为人说者，福德无量无边，千佛共说不能令尽。",
  },
  {
    id: "t0264-006-112",
    category: "破魔護念",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "汝今已能破諸魔賊，壞生死軍，諸餘怨敵皆悉摧滅。善男子！百千諸佛以神通力，共守護汝，於一切世間天、人之中，無如汝者，唯除如來。",
    anchorText: "百千諸佛以神通力，共守護汝",
    note: "诸佛赞说持经者能破魔贼、坏生死军，并为百千诸佛神力守护。",
  },
  {
    id: "t0264-006-113",
    category: "隨喜讚善香潔功德",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "若有人聞是〈藥王菩薩本事品〉，能隨喜、讚善者，是人現世口中，常出青蓮華香，身毛孔中，常出牛頭栴檀之香，所得功德如上所說。",
    anchorText: "能隨喜、讚善者",
    note: "闻此品能随喜赞善者，现世口出青莲华香、身毛孔出牛头栴檀香，并得如上功德。",
  },
  {
    id: "t0264-006-114",
    category: "守護流布",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "以此〈藥王菩薩本事品〉囑累於汝，我滅度後，後五百歲中，廣宣流布於閻浮提，無令斷絕，惡魔、魔民、諸天、龍、夜叉、鳩槃茶等，得其便也。",
    anchorText: "廣宣流布於閻浮提，無令斷絕",
    note: "佛嘱累宿王华菩萨于后五百岁广宣流布此品，不令断绝，并令诸魔等不得其便。",
  },
  {
    id: "t0264-006-115",
    category: "聞經病滅",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "此經則為閻浮提人病之良藥，若人有病，得聞是經，病即消滅，不老、不死。",
    anchorText: "若人有病，得聞是經，病即消滅",
    note: "佛称此经为阎浮提人病之良药，若有病得闻此经，病即消灭。",
  },
  {
    id: "t0264-006-116",
    category: "敬持經者",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "此人不久，必當取草坐於道場破諸魔軍，當吹法螺，擊大法鼓，度脫一切眾生、老、病、死海。",
    anchorText: "必當取草坐於道場破諸魔軍",
    note: "佛教见受持此经者应生恭敬，因其不久当坐道场破魔军、转法并度脱众生生老病死海。",
  },
  {
    id: "t0264-006-117",
    category: "聞品得陀羅尼",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "說是〈藥王菩薩本事品〉時，八萬四千菩薩，得解一切眾生語言陀羅尼。",
    anchorText: "八萬四千菩薩，得解一切眾生語言陀羅尼",
    note: "说此品时，八万四千菩萨得解一切众生语言陀罗尼。",
  },
  {
    id: "t0264-006-118",
    category: "問法利益眾生",
    sectionTitle: YAOWANG_SECTION_TITLE,
    text: "善哉，善哉！宿王華！汝成就不可思議功德，乃能問釋迦牟尼佛如此之事，利益無量一切眾生。",
    anchorText: "利益無量一切眾生",
    note: "多宝如来赞宿王华菩萨能问此事，利益无量一切众生。",
  },
];
