import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const DHARANI_SECTION_TITLE = "陀羅尼品第二十一";

export const T0264_JUAN_6_DHARANI_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-006-077",
    category: "受持一偈功德甚多",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "若善男子、善女人，能於是經，乃至受持一四句偈，讀誦、解義、如說修行，功德甚多。",
    anchorText: "能於是經，乃至受持一四句偈",
    note: "佛以供养无量诸佛校量，明受持乃至一四句偈、读诵解义、如说修行，其功德甚多。",
  },
  {
    id: "t0264-006-078",
    category: "陀羅尼守護說法者",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊！我今當與說法者陀羅尼呪以守護之。",
    anchorText: "我今當與說法者陀羅尼呪以守護之",
    note: "药王菩萨为守护说法者而说陀罗尼。",
  },
  {
    id: "t0264-006-079",
    category: "侵毀法師即侵毀諸佛",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊！是陀羅尼神呪，六十二億恒河沙等諸佛所說，若有侵毀此法師者，則為侵毀是諸佛已。",
    anchorText: "六十二億恒河沙等諸佛所說",
    note: "药王菩萨说明此陀罗尼为六十二亿恒河沙等诸佛所说，侵毁法师即同侵毁诸佛。",
  },
  {
    id: "t0264-006-080",
    category: "多所饒益",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "善哉，善哉！藥王！汝愍念擁護此法師故，說是陀羅尼，於諸眾生多所饒益。",
    anchorText: "汝愍念擁護此法師故，說是陀羅尼",
    note: "佛赞叹药王菩萨愍念拥护法师，说此陀罗尼能多所饶益众生。",
  },
  {
    id: "t0264-006-081",
    category: "護持經者無能得便",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊！我亦為擁護、讀誦、受持《法華經》者，說陀羅尼；若此法師得是陀羅尼，若夜叉、若羅剎、若富單那、若吉蔗、若鳩槃荼、若餓鬼等，伺求其短無能得便。",
    anchorText: "為擁護、讀誦、受持《法華經》者",
    note: "勇施菩萨为拥护读诵受持《法华经》者说陀罗尼，使诸鬼神伺求其短亦无能得便。",
  },
  {
    id: "t0264-006-082",
    category: "諸佛隨喜護法",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊！是陀羅尼神呪，恒河沙等諸佛所說，亦皆隨喜，若有侵毀此法師者，則為侵毀是諸佛已。",
    anchorText: "恒河沙等諸佛所說，亦皆隨喜",
    note: "勇施菩萨说明此陀罗尼为恒河沙等诸佛所说且皆随喜，侵毁法师即同侵毁诸佛。",
  },
  {
    id: "t0264-006-083",
    category: "天王愍念擁護",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊！我亦為愍念眾生，擁護此法師故，說是陀羅尼。",
    anchorText: "為愍念眾生，擁護此法師故",
    note: "毗沙门天王为愍念众生、拥护法师而说陀罗尼。",
  },
  {
    id: "t0264-006-084",
    category: "百由旬內無諸衰患",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊！以是神呪擁護法師，我亦自當擁護持是經者，令百由旬內無諸衰患。",
    anchorText: "令百由旬內無諸衰患",
    note: "毗沙门天王发愿拥护持经者，令百由旬内无诸衰患。",
  },
  {
    id: "t0264-006-085",
    category: "擁護持經者",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊！我亦以陀羅尼神呪，擁護持《法華經》者。",
    anchorText: "擁護持《法華經》者",
    note: "持国天王亦以陀罗尼神咒拥护持《法华经》者。",
  },
  {
    id: "t0264-006-086",
    category: "侵毀法師即侵毀諸佛",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊！是陀羅尼神呪，四十二億諸佛所說，若有侵毀此法師者，則為侵毀是諸佛已。",
    anchorText: "四十二億諸佛所說，若有侵毀此法師者",
    note: "持国天王说明此陀罗尼为四十二亿诸佛所说，侵毁法师即同侵毁诸佛。",
  },
  {
    id: "t0264-006-087",
    category: "除衰患不得便",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊！我亦欲擁護讀誦受持《法華經》者，除其衰患，若有伺求法師短者，令不得便。",
    anchorText: "擁護讀誦受持《法華經》者，除其衰患",
    note: "十罗刹女与鬼子母发愿拥护读诵受持者，除其衰患，使伺求法师短者不得便。",
  },
  {
    id: "t0264-006-088",
    category: "夢中亦莫惱法師",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "寧上我頭上，莫惱於法師，若夜叉、若羅剎、若餓鬼、若富單那、若吉蔗、若毘陀羅、若乾馱、若烏摩勒伽、若阿跋摩羅、若夜叉吉蔗、若人吉蔗、若熱病、若一日、若二日、若三日、若四日乃至七日、若常熱病、若男形、若女形、若童男形、若童女形，乃至夢中亦復莫惱。",
    anchorText: "寧上我頭上，莫惱於法師",
    note: "罗刹女等严誓护持法师，令诸鬼神热病等乃至梦中亦不得恼乱。",
  },
  {
    id: "t0264-006-089",
    category: "惱亂說法者得殃",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "若不順我呪，惱亂說法者；頭破作七分，如摩利闍迦，如殺父母罪，亦如壓油殃，㪷秤欺誑人，調達破僧罪，犯此法師者，當獲如是殃。",
    anchorText: "若不順我呪，惱亂說法者",
    note: "偈颂警策恼乱说法者、侵犯法师者，当获重殃。",
  },
  {
    id: "t0264-006-090",
    category: "安隱離患消毒",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊！我等亦當身自擁護受持、讀誦、修行是經者，令得安隱離諸衰患，消眾毒藥。",
    anchorText: "令得安隱離諸衰患，消眾毒藥",
    note: "罗刹女等发愿亲自拥护受持、读诵、修行此经者，令得安隐、离患、消众毒药。",
  },
  {
    id: "t0264-006-091",
    category: "擁護法華名福不可量",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "善哉，善哉！汝等但能擁護受持《法華》名者，福不可量，何況擁護具足受持，供養經卷，華香、瓔珞、末香、塗香、燒香、幡蓋、伎樂；然種種燈，穌燈、油燈、諸香油燈、穌摩那華油燈、瞻蔔華油燈、婆師迦華油燈、優波羅華油燈，如是等百千種供養者，睪諦！汝等及眷屬，應當擁護如是法師。",
    anchorText: "但能擁護受持《法華》名者，福不可量",
    note: "佛赞叹罗刹女等：但能拥护受持《法华》名者，福已不可量，何况具足受持并供养经卷者。",
  },
  {
    id: "t0264-006-092",
    category: "聞品得忍",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "說此陀羅尼呪品時，六萬八千人得無生法忍。",
    anchorText: "六萬八千人得無生法忍",
    note: "说此陀罗尼品时，六万八千人得无生法忍。",
  },
];
