import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const YAOCAOYU_SECTION_TITLE = "藥草喻品第五";

export const T0262_JUAN_3_YAOCAOYU_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0262-003-037",
    category: "如來功德",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "善哉善哉。迦葉善說如來真實功德。誠如所言。如來復有無量無邊阿僧祇功德。汝等若於無量億劫說不能盡。",
    anchorText: "如來復有無量無邊阿僧祇功德",
    note: "佛印可迦葉所說，並明示如來功德無量無邊，久說不能盡。",
  },
  {
    id: "t0262-003-038",
    category: "法王實語",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "迦葉當知。如來是諸法之王。若有所說。皆不虛也。",
    anchorText: "如來是諸法之王。若有所說",
    note: "本品先標舉如來為諸法之王，所說真實不虛。",
  },
  {
    id: "t0262-003-039",
    category: "佛智方便",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "於一切法。以智方便而演說之。其所說法。皆悉到於一切智地。",
    anchorText: "以智方便而演說之。其所說法",
    note: "如來以智慧方便演說一切法，所說皆導向一切智地。",
  },
  {
    id: "t0262-003-040",
    category: "示眾智慧",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如來觀知一切諸法之所歸趣。亦知一切眾生深心所行。通達無礙。又於諸法究盡明了。示諸眾生一切智慧。",
    anchorText: "如來觀知一切諸法之所歸趣",
    note: "經文說如來通達諸法與眾生深心，能為眾生示一切智慧。",
  },
  {
    id: "t0262-003-041",
    category: "法雨普潤",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "一雲所雨。稱其種性而得生長。華果敷實。雖一地所生。一雨所潤。而諸草木各有差別。",
    anchorText: "一雲所雨。稱其種性而得生長",
    note: "藥草喻以一雨普潤而各得生長，顯示佛法隨根成益。",
  },
  {
    id: "t0262-003-042",
    category: "度脫安隱",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "未度者令度。未解者令解。未安者令安。未涅槃者令得涅槃。",
    anchorText: "未度者令度。未解者令解",
    note: "如來出世說法，令未度、未解、未安、未涅槃者各得成就。",
  },
  {
    id: "t0262-003-043",
    category: "為聽法故",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "我是一切知者。一切見者。知道者。開道者。說道者。汝等天人阿修羅眾。皆應到此。為聽法故。",
    anchorText: "知道者。開道者。說道者",
    note: "如來自稱知、見、開、說道者，勸天人阿修羅眾來聽法。",
  },
  {
    id: "t0262-003-044",
    category: "聞法善利",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如來於時觀是眾生。諸根利鈍。精進懈怠。隨其所堪而為說法。種種無量。皆令歡喜快得善利。",
    anchorText: "隨其所堪而為說法。種種無量",
    note: "如來觀眾生根機而說法，令眾生歡喜並快得善利。",
  },
  {
    id: "t0262-003-045",
    category: "聞法安隱",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "是諸眾生聞是法已。現世安隱後生善處。以道受樂。亦得聞法。",
    anchorText: "聞是法已。現世安隱後生善處",
    note: "本品直接說聞法後現世安隱、後生善處，並以道受樂。",
  },
  {
    id: "t0262-003-046",
    category: "離障入道",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "既聞法已。離諸障礙。於諸法中任力所能。漸得入道。",
    anchorText: "既聞法已。離諸障礙",
    note: "聞法之後能離諸障礙，依自身能力漸入於道。",
  },
  {
    id: "t0262-003-047",
    category: "如說修行",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "其有眾生聞如來法。若持讀誦。如說修行。所得功德。不自覺知。",
    anchorText: "聞如來法。若持讀誦",
    note: "聞如來法並持讀誦、如說修行者，所得功德甚深，自己尚不覺知。",
  },
  {
    id: "t0262-003-048",
    category: "一味解脫",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如來知是一相一味之法。所謂解脫相。離相。滅相。究竟涅槃常寂滅相。終歸於空。",
    anchorText: "如來知是一相一味之法",
    note: "本品說如來知一相一味之法，指向解脫、離、滅與究竟涅槃。",
  },
  {
    id: "t0262-003-049",
    category: "能信能受",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "汝等迦葉甚為希有。能知如來隨宜說法。能信能受。所以者何。諸佛世尊隨宜說法。難解難知。",
    anchorText: "能知如來隨宜說法。能信能受",
    note: "佛讚迦葉等能知、能信、能受如來隨宜說法，甚為希有。",
  },
  {
    id: "t0262-003-050",
    category: "聞已信解",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "有智若聞 則能信解 無智疑悔 則為永失",
    anchorText: "有智若聞 則能信解",
    note: "偈中明示有智慧者聞法能信解，反顯聞法信解之重要。",
  },
  {
    id: "t0262-003-051",
    category: "令得正見",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "是故迦葉 隨力為說 以種種緣 令得正見",
    anchorText: "以種種緣 令得正見",
    note: "如來隨眾生能力，以種種因緣說法，令得正見。",
  },
  {
    id: "t0262-003-052",
    category: "法雨悅豫",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "慧雲含潤 電光晃曜 雷聲遠震 令眾悅豫",
    anchorText: "慧雲含潤 電光晃曜",
    note: "偈以慧雲雷雨喻佛法，能令眾生悅豫。",
  },
  {
    id: "t0262-003-053",
    category: "離苦安樂",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "出於世間 猶如大雲 充潤一切 枯槁眾生 皆令離苦 得安隱樂 世間之樂 及涅槃樂",
    anchorText: "充潤一切 枯槁眾生",
    note: "偈中說如來如大雲充潤眾生，令離苦得世間樂與涅槃樂。",
  },
  {
    id: "t0262-003-054",
    category: "甘露淨法",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "為大眾說 甘露淨法 其法一味 解脫涅槃",
    anchorText: "為大眾說 甘露淨法",
    note: "本品稱如來為大眾所說是一味甘露淨法，通向解脫涅槃。",
  },
  {
    id: "t0262-003-055",
    category: "平等說法",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "我無貪著 亦無限礙 恆為一切 平等說法",
    anchorText: "恆為一切 平等說法",
    note: "如來無貪著、無限礙，恒為一切平等說法。",
  },
  {
    id: "t0262-003-056",
    category: "等雨法雨",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "貴賤上下 持戒毀戒 威儀具足 及不具足 正見邪見 利根鈍根 等雨法雨 而無懈倦",
    anchorText: "正見邪見 利根鈍根",
    note: "佛以法雨平等普施不同根機眾生，而無懈倦。",
  },
  {
    id: "t0262-003-057",
    category: "涅槃神通",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "知無漏法 能得涅槃 起六神通 及得三明",
    anchorText: "知無漏法 能得涅槃",
    note: "偈中說知無漏法者能得涅槃，起六神通並得三明。",
  },
  {
    id: "t0262-003-058",
    category: "作佛無疑",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "求世尊處 我當作佛 行精進定 是上藥草 又諸佛子 專心佛道 常行慈悲 自知作佛 決定無疑",
    anchorText: "求世尊處 我當作佛",
    note: "偈中以藥草喻修行差別，明說專心佛道者自知作佛、決定無疑。",
  },
  {
    id: "t0262-003-059",
    category: "不退利生",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "安住神通 轉不退輪 度無量億 百千眾生 如是菩薩 名為大樹",
    anchorText: "安住神通 轉不退輪",
    note: "大樹菩薩安住神通，轉不退法輪，度無量眾生。",
  },
  {
    id: "t0262-003-060",
    category: "佛智方便",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "種種言辭 演說一法 於佛智慧 如海一滴",
    anchorText: "種種言辭 演說一法",
    note: "種種言辭皆為演說一法，而此於佛智慧僅如海一滴，顯佛智深廣。",
  },
  {
    id: "t0262-003-061",
    category: "世間具足",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "諸佛之法 常以一味 令諸世間 普得具足 漸次修行 皆得道果",
    anchorText: "諸佛之法 常以一味",
    note: "諸佛之法一味平等，令世間普得具足，漸次修行皆得道果。",
  },
  {
    id: "t0262-003-062",
    category: "聞法得果",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "聲聞緣覺 處於山林 住最後身 聞法得果 是名藥草 各得增長",
    anchorText: "住最後身 聞法得果",
    note: "偈中說聲聞緣覺聞法得果，如藥草各得增長。",
  },
  {
    id: "t0262-003-063",
    category: "聞空歡喜",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "復有住襌 得神通力 聞諸法空 心大歡喜 放無數光 度諸眾生",
    anchorText: "聞諸法空 心大歡喜",
    note: "住禪菩薩聞諸法空，心大歡喜，並放光度眾生。",
  },
  {
    id: "t0262-003-064",
    category: "開示佛道",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "迦葉當知 以諸因緣 種種譬喻 開示佛道 是我方便 諸佛亦然",
    anchorText: "以諸因緣 種種譬喻",
    note: "如來以因緣譬喻開示佛道，此是佛方便，諸佛亦然。",
  },
  {
    id: "t0262-003-065",
    category: "悉當成佛",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "今為汝等 說最實事 諸聲聞眾 皆非滅度 汝等所行 是菩薩道 漸漸修學 悉當成佛",
    anchorText: "今為汝等 說最實事",
    note: "本品結尾宣說最實事：聲聞所行是菩薩道，漸漸修學悉當成佛。",
  },
];
