import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const ANXING_SECTION_TITLE = "安行品第十三";

export const T0263_JUAN_7_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-001",
    category: "安行說經",
    text: "菩薩先處二法乃應講經，一曰威儀，二曰禮節。",
    anchorText: "菩薩先處二法乃應講經，一曰威儀，二曰禮節",
    note: "本品直接开示菩萨说此经前应安住威仪与礼节二法。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-002",
    category: "忍辱調柔",
    text: "假使持心忍辱調柔，將護其意畏不自立，其志如地不見有人，不見有人而行法者，觀自然相諸法本無，此諸法者眾行之式，亦無想念，是謂威儀。",
    anchorText: "假使持心忍辱調柔，將護其意畏不自立",
    note: "威仪以忍辱调柔、护心如地、观诸法本无为核心。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-003",
    category: "清淨說經",
    text: "除其往至講經會時，唯與講會而共從事，縱有所說亦無所著，是為禮節。",
    anchorText: "唯與講會而共從事，縱有所說亦無所著",
    note: "讲经时以无所著为礼节，避免攀缘杂事。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-004",
    category: "閑居精進",
    text: "常好燕坐綢繆好習辟屏閑居，是為禮節。",
    anchorText: "常好燕坐綢繆好習辟屏閑居",
    note: "本品赞成说经者安住闲居、燕坐修习。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-005",
    category: "觀法安住",
    text: "假使菩薩，乙密觀察斯一切法，欵欵修此所當行者，常住威儀禮節二事。",
    anchorText: "欵欵修此所當行者，常住威儀禮節二事",
    note: "菩萨细密观察诸法并修所当行，即常住威仪礼节。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-006",
    category: "勇猛說經",
    text: "若菩薩好樂，說此經典者，於後當來世，勇猛無怯劣，順威儀禮節，善明清白行。",
    anchorText: "若菩薩好樂，說此經典者",
    note: "后世好乐说此经典者，应勇猛无怯并顺威仪礼节。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-007",
    category: "欲獲法",
    text: "現在欲獲法，常當止息非，好住滅度地，是謂為威儀。",
    anchorText: "現在欲獲法，常當止息非",
    note: "欲获法者应止息过非、安住灭度地。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-008",
    category: "持法無著",
    text: "假使不肯往，諮問於道法，為斯持法說，不怯無所著。",
    anchorText: "為斯持法說，不怯無所著",
    note: "说经者为持法而说，应无怯、无所著。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-009",
    category: "奉持斯典",
    text: "佛故先示現，此威儀禮節，其奉持斯典，則當勤行之。",
    anchorText: "其奉持斯典，則當勤行之",
    note: "经文明示奉持此经典者应勤行威仪礼节。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-010",
    category: "無怯說經",
    text: "我滅度後，若有比丘，敢能守護，如是法則。無所怯軟，心不起想，為無數人，說此經典。",
    anchorText: "我滅度後，若有比丘，敢能守護",
    note: "佛灭后守护法则者，能无所怯软，为无数人说此经典。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-011",
    category: "清淨說義",
    text: "觀察諸法，一切普淨，宴然說誼，而不動搖。",
    anchorText: "觀察諸法，一切普淨",
    note: "说经者观察诸法普净，安然说义而不动摇。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-012",
    category: "聽法供養",
    text: "國主帝王，及與太子，欲聽聞法，皆供養之。并餘長者，及諸梵志，立諸眷屬，皆無所欲。",
    anchorText: "國主帝王，及與太子，欲聽聞法，皆供養之",
    note: "经文说明国王太子等欲听法时皆供养说法者，而说法者无所欲求。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-013",
    category: "佛道安住",
    text: "智者常安，住於佛道，先隱定坐，爾乃說經。",
    anchorText: "智者常安，住於佛道",
    note: "智者先安住佛道与定坐，然后说经。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-014",
    category: "普等說法",
    text: "而普等心，為一切人。",
    anchorText: "而普等心，為一切人",
    note: "说经者以平等心面向一切人。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-015",
    category: "微妙法義",
    text: "應所樂聞，為講無量。明智無限，次第剖判，為演種種，微妙之誼。",
    anchorText: "應所樂聞，為講無量",
    note: "随众所乐而讲无量，次第剖判种种微妙义。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-016",
    category: "聽聞得道",
    text: "而入神足，柔順之忍，其有聽聞，悉得佛道。",
    anchorText: "其有聽聞，悉得佛道",
    note: "本品明确说有听闻者悉得佛道。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-017",
    category: "慈心說法",
    text: "常以慈心，為眾說法，未曾起于，勞廢之想。",
    anchorText: "常以慈心，為眾說法",
    note: "说经者常以慈心为众说法，不生厌倦。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-018",
    category: "勸悅眾心",
    text: "普能勸悅，諸會者心，無敢生念，欲危害者。",
    anchorText: "普能勸悅，諸會者心",
    note: "说法能普遍劝悦会众之心，并使人不起危害之念。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-019",
    category: "眾解佛道",
    text: "欲令眾庶，悉解佛道。若一切人，來聽經法，我乃嘉豫，如獲大安。",
    anchorText: "欲令眾庶，悉解佛道",
    note: "说经者为令众人了解佛道，见人来听经法如获大安。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-020",
    category: "住忍功德",
    text: "佛滅度後，若有比丘，宣揚經法，無所悕望，無所妨廢，不遭苦患，常察精進，離於疾病。無能為彼，造恐怖事，不被杖痛，無誹謗想，身無疲厭，不有所患，其人住忍，得力如是。",
    anchorText: "佛滅度後，若有比丘，宣揚經法",
    note: "佛灭后无所希求地宣扬经法，得不遭苦患、离病怖畏等住忍之力。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-021",
    category: "稱譽難盡",
    text: "若已諮嗟，億百功德，一切稱譽，不能究竟。",
    anchorText: "億百功德，一切稱譽，不能究竟",
    note: "经文赞叹此安隐住法功德，即使用一切称誉也不能究竟。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-022",
    category: "遠離佛道",
    text: "其族姓子則遠無上正真之道，而不得近佛天中天所在行處。假使究竟不蒙福力不成最正覺。",
    anchorText: "則遠無上正真之道，而不得近佛天中天所在行處",
    note: "本品以反面说明疑谤大乘、轻慢求道者会远离无上正真之道。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-023",
    category: "敬護斯典",
    text: "所在晝夜敬護斯典。",
    anchorText: "所在晝夜敬護斯典",
    note: "菩萨昼夜敬护此典，是本品安行的重要行相。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-024",
    category: "信樂供養",
    text: "若講若聞信樂斯典，誦持書寫載之竹帛，供養奉事德不可量，說以安住。",
    anchorText: "若講若聞信樂斯典",
    note: "讲闻信乐、诵持书写、供养奉事此典，功德不可量。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-025",
    category: "講誦不倦",
    text: "數數講誦，佛之典誥，未曾以此，持作懈倦。",
    anchorText: "數數講誦，佛之典誥",
    note: "安住之子数数讲诵佛典，不以为懈倦。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-026",
    category: "安隱調定",
    text: "所行安隱，常得調定，將御佛道，救億眾生。",
    anchorText: "所行安隱，常得調定",
    note: "安隐行能令行者常得调定，并导向佛道、救度众生。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-027",
    category: "四事護持",
    text: "佛滅度後，菩薩有四事說法而不諍怒。何等為四？為諸比丘、比丘尼、清信士、清信女所見奉敬，帝王太子、大臣群寮、郡國人民所見供養，長者梵志皆共承順，虛空神明無數天子聽所說經，天龍鬼神侍衛其後皆營護之；是為四。",
    anchorText: "菩薩有四事說法而不諍怒",
    note: "佛灭后菩萨以四事说法而不诤怒，得四众奉敬、人王供养、天子听经、天龙护卫。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-028",
    category: "聞名難遇",
    text: "若於忍界聞正法華品，服名聽聲者甚難值遇。",
    anchorText: "聞正法華品，服名聽聲者甚難值遇",
    note: "在忍界闻《正法华》名声，甚难值遇。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-029",
    category: "第一法要",
    text: "如大聖帝髻中明珠，以為世尊第一法要，緣是趣行，如來使聞深妙之典，往古來今諸行班宣，斯經為最。",
    anchorText: "以為世尊第一法要",
    note: "本品以转轮圣王髻中明珠喻此经为世尊第一法要、诸行所宣之最。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-030",
    category: "消除緣患",
    text: "消除一切緣起之患，猶如聖帝珍重愛護髻中明珠，久乃解出以賜元功。",
    anchorText: "消除一切緣起之患",
    note: "经文以明珠喻说明此经能消除一切缘起之患。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-031",
    category: "尊經方便",
    text: "設能逮聞，於是尊經，則便建立，億權方便。",
    anchorText: "設能逮聞，於是尊經",
    note: "能够听闻此尊经，便能建立亿种权方便。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-032",
    category: "諸法莫及",
    text: "最後世時，正典所處，一切諸法，皆無及者。",
    anchorText: "正典所處，一切諸法，皆無及者",
    note: "偈中赞此正典所在，一切诸法皆无能及。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-033",
    category: "滅後怙恃",
    text: "吾以演現，如是像法，佛滅度後，當恃怙之。",
    anchorText: "佛滅度後，當恃怙之",
    note: "佛说明示此像法在佛灭度后应作为依怙。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-034",
    category: "求道授決",
    text: "其有志求，斯尊道者，普當受決，如佛所言。",
    anchorText: "其有志求，斯尊道者",
    note: "有志求此尊道者，普当受决。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-035",
    category: "無上真慧",
    text: "彼人未曾，有疵瑕欲，無有疾病，眾患之難，則於末後，將來之世，便即逮成，無上真慧。",
    anchorText: "無有疾病，眾患之難",
    note: "经文说此人无疾病众难，末后将来世即逮成无上真慧。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-036",
    category: "聞法除漏",
    text: "若有聞者，除身諸漏，怪其無為，悉叉手歸，己身景曜，所照光光，其奉行是，所獲若此。",
    anchorText: "若有聞者，除身諸漏",
    note: "听闻者除身诸漏，归敬无为，所得如此。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-037",
    category: "成覺轉法",
    text: "得成正覺，而轉法輪，則覩弘摸，及見最勝。",
    anchorText: "得成正覺，而轉法輪",
    note: "经文继续说明修学所得可至成正觉、转法轮。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-038",
    category: "聞已為說",
    text: "佛所說經，設得聞已，為眾會說，及諸親族，皆悉具足。",
    anchorText: "佛所說經，設得聞已",
    note: "听闻佛所说经后，能为众会及亲族宣说，皆悉具足。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-039",
    category: "求道利益",
    text: "皆得往至，於佛道場。便即處於，師子之座，是為求道，所獲利誼。",
    anchorText: "是為求道，所獲利誼",
    note: "求道所得利益，至佛道场、处师子座。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-040",
    category: "奉最勝佛",
    text: "所謂七寶，悉歸於斯，修此則奉，最勝如來。",
    anchorText: "修此則奉，最勝如來",
    note: "修此法即是奉事最胜如来。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-041",
    category: "無漏教化",
    text: "已得佛道，存立惠施，即轉法輪，無有諸漏。為諸四輩，而說經法，不可思議，億千劫數。分別講說，無漏之法，教化無數，億姟眾生。",
    anchorText: "分別講說，無漏之法",
    note: "经文以成佛转法轮、讲说无漏之法、教化无数众生收束利益。",
  },
  {
    sectionTitle: ANXING_SECTION_TITLE,
    id: "t0263-007-042",
    category: "末世廣說",
    text: "最後末世，求斯尊法，分別廣說，安住所演。",
    anchorText: "最後末世，求斯尊法",
    note: "品末劝末世求此尊法者分别广说、安住所演。",
  },
];