import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const MIAOYIN_SECTION_TITLE = "妙音菩薩品第二十三";

export const T0264_JUAN_7_MIAOYIN_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-007-001",
    category: "久殖德本",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "妙音，久已殖眾德本，供養親近無量百千萬億諸佛，而悉成就甚深智慧",
    anchorText: "久已殖眾德本",
    note: "妙音菩萨久植德本、供养亲近无量诸佛，成就甚深智慧。",
  },
  {
    id: "t0264-007-002",
    category: "諸大三昧",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "得妙幢相三昧、法華三昧、淨德三昧、宿王戲三昧、無緣三昧、智印三昧、解一切眾生語言三昧、集一切功德三昧、清淨三昧、神通遊戲三昧、慧炬三昧、莊嚴王三昧、淨光明三昧、淨藏三昧、不共三昧、日旋三昧、得如是等百千萬億恒河沙等諸大三昧。",
    anchorText: "得妙幢相三昧",
    note: "本品列举妙音菩萨所得法华三昧、集一切功德三昧等无量三昧。",
  },
  {
    id: "t0264-007-003",
    category: "禮佛供養",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "我當往詣娑婆世界，禮拜親近供養釋迦牟尼佛，及見文殊師利法王子菩薩、藥王菩薩、勇施菩薩、宿王華菩薩、上行意菩薩、莊嚴王菩薩、藥上菩薩。",
    anchorText: "禮拜親近供養釋迦牟尼佛",
    note: "妙音菩萨发愿来娑婆，礼拜亲近供养释迦牟尼佛，并见诸大菩萨。",
  },
  {
    id: "t0264-007-004",
    category: "勿輕娑婆",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "是故汝往莫輕彼國，若佛菩薩及國土生下劣想。",
    anchorText: "是故汝往莫輕彼國",
    note: "净华宿王智佛告诫妙音勿轻娑婆国土、佛与菩萨，含敬法敬土之义。",
  },
  {
    id: "t0264-007-005",
    category: "如來力用",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "世尊！我今詣娑婆世界，皆是如來之力，如來神通遊戲，如來功德智慧莊嚴。",
    anchorText: "皆是如來之力",
    note: "妙音菩萨明说往诣娑婆皆依如来之力、神通游戏与功德智慧庄严。",
  },
  {
    id: "t0264-007-006",
    category: "三昧現瑞",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "於是妙音菩薩，不起于座，身不動搖而入三昧，以三昧力，於耆闍崛山去法座不遠，化作八萬四千眾寶蓮華",
    anchorText: "不起于座，身不動搖而入三昧",
    note: "妙音菩萨不起于座而入三昧，以三昧力于灵鹫山化现众宝莲华。",
  },
  {
    id: "t0264-007-007",
    category: "供養聽經",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "是妙音菩薩摩訶薩，欲從淨華宿王智佛國，與八萬四千菩薩圍遶，而來至此娑婆世界，供養親近禮拜於我，亦欲供養聽《法華經》。",
    anchorText: "亦欲供養聽《法華經》",
    note: "佛说明妙音菩萨来娑婆，是为供养亲近礼拜佛，也为供养听《法华经》。",
  },
  {
    id: "t0264-007-008",
    category: "勤修三昧",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "願為我等說是三昧名字，我等亦欲勤修行之，行此三昧，乃能見是菩薩色相大小威儀進止。",
    anchorText: "我等亦欲勤修行之",
    note: "文殊请问三昧名字，明说大众亦欲勤修此三昧。",
  },
  {
    id: "t0264-007-009",
    category: "供佛聞經",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "善哉，善哉！汝能為供養釋迦牟尼佛及聽《法華經》并見文殊師利等故來至此。",
    anchorText: "汝能為供養釋迦牟尼佛",
    note: "多宝佛赞妙音菩萨为供养释迦牟尼佛、听《法华经》并见文殊等而来。",
  },
  {
    id: "t0264-007-010",
    category: "供養果報",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "妙音菩薩於萬二千歲，以十萬種伎樂供養雲雷音王佛，并奉上八萬四千七寶鉢，以是因緣果報，今生淨華宿王智佛所，有是神力。",
    anchorText: "以是因緣果報",
    note: "佛明示妙音菩萨昔以伎乐、宝钵供佛，因缘果报今生佛国并具神力。",
  },
  {
    id: "t0264-007-011",
    category: "供佛善根",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "華德！是妙音菩薩，已曾供養親近無量諸佛，久殖德本，又值恒河沙等百千萬億那由他佛。",
    anchorText: "已曾供養親近無量諸佛",
    note: "佛再次说明妙音菩萨已曾供养亲近无量诸佛，久植德本。",
  },
  {
    id: "t0264-007-012",
    category: "現身說經",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "而是菩薩現種種身，處處為諸眾生說是經典",
    anchorText: "現種種身，處處為諸眾生說是經典",
    note: "本品总说妙音菩萨能现种种身，处处为众生说此经典。",
  },
  {
    id: "t0264-007-013",
    category: "救濟眾難",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "或現天、龍、夜叉、乾闥婆、阿脩羅、迦樓羅、緊那羅、摩睺羅伽、人非人等身、而說是經。諸有地獄、餓鬼、畜生及眾難處皆能救濟，乃至於王後宮變為女身，而說是經。",
    anchorText: "諸有地獄、餓鬼、畜生及眾難處皆能救濟",
    note: "妙音菩萨随类现身说经，地狱、饿鬼、畜生及众难处皆能救济。",
  },
  {
    id: "t0264-007-014",
    category: "救護娑婆",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "華德！是妙音菩薩，能救護娑婆世界諸眾生者。",
    anchorText: "能救護娑婆世界諸眾生",
    note: "佛明说妙音菩萨能救护娑婆世界诸众生。",
  },
  {
    id: "t0264-007-015",
    category: "智慧明照",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "是菩薩，以若干智慧明照娑婆世界，令一切眾生各得所知",
    anchorText: "明照娑婆世界",
    note: "妙音菩萨以若干智慧明照娑婆世界，令一切众生各得所知。",
  },
  {
    id: "t0264-007-016",
    category: "隨類度生",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "如是種種隨所應度者，而為現形。乃至應以滅度而得度者，示現滅度。",
    anchorText: "隨所應度者，而為現形",
    note: "佛总结妙音菩萨随所应度而现形，乃至示现灭度以度众生。",
  },
  {
    id: "t0264-007-017",
    category: "三昧饒益",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "善男子！其三昧，名現一切色身；妙音菩薩住是三昧中，能如是饒益無量眾生。",
    anchorText: "能如是饒益無量眾生",
    note: "佛说妙音菩萨住现一切色身三昧，能如是饶益无量众生。",
  },
  {
    id: "t0264-007-018",
    category: "聞品得益",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "說是〈妙音菩薩品〉時，與妙音菩薩俱來者八萬四千人，皆得現一切色身三昧，此娑婆世界無量菩薩，亦得是三昧及陀羅尼。",
    anchorText: "皆得現一切色身三昧",
    note: "说此品时，俱来八万四千人与娑婆无量菩萨皆得三昧，并得陀罗尼。",
  },
  {
    id: "t0264-007-019",
    category: "來往饒益",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "世尊！我到娑婆世界饒益眾生，見釋迦牟尼佛及見多寶佛塔，禮拜供養",
    anchorText: "我到娑婆世界饒益眾生",
    note: "妙音菩萨回本国自述到娑婆世界饶益众生，并礼拜供养释迦佛与多宝佛塔。",
  },
  {
    id: "t0264-007-020",
    category: "聞品證法",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "說是〈妙音菩薩來往品〉時，四萬二千天子得無生法忍，華德菩薩得法華三昧。",
    anchorText: "四萬二千天子得無生法忍",
    note: "本品结尾明说，四万二千天子得无生法忍，华德菩萨得法华三昧。",
  },
];
