import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const YAOCAOYU_SECTION_TITLE = "藥草喻品第五";

export const T0264_JUAN_3_YAOCAOYU_OPENING_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-003-041",
    category: "讚如來德",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "善哉，善哉！迦葉！善說如來真實功德。誠如所言，如來復有無量無邊阿僧祇功德，汝等若於無量億劫說不能盡。",
    anchorText: "善說如來真實功德",
    note: "佛印可迦叶善说如来真实功德，并说明如来功德无量，久说不能尽。",
    occurrence: 1,
  },
  {
    id: "t0264-003-042",
    category: "法王說實",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "迦葉當知！如來是諸法之王，若有所說皆不虛也，於一切法，以智方便而演說之；其所說法，皆悉到於一切智地，",
    anchorText: "如來是諸法之王",
    note: "本段明示如来为诸法之王，所说不虚，并以智慧方便令法趣向一切智地。",
    occurrence: 1,
  },
  {
    id: "t0264-003-043",
    category: "知機無礙",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如來觀知一切諸法之所歸趣，亦知一切眾生深心所行，通達無礙。又於諸法究盡明了，示諸眾生一切智慧。",
    anchorText: "亦知一切眾生深心所行",
    note: "如来通达诸法与众生深心所行，因此能为众生开示一切智慧。",
    occurrence: 1,
  },
  {
    id: "t0264-003-044",
    category: "法雨普潤",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "一時等澍其澤普洽，卉、木、叢林及諸藥草，小根、小莖、小枝、小葉，中根、中莖、中枝、中葉，大根、大莖、大枝、大葉，諸樹大小隨上、中、下，各有所受，",
    anchorText: "一時等澍其澤普洽",
    note: "大云一时等澍，普润草木，譬喻如来法雨平等普被而众生各随根性受益。",
    occurrence: 1,
  },
  {
    id: "t0264-003-045",
    category: "隨性生長",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "一雲所雨稱其種性，而得生長華菓敷實，雖一地所生，一雨所潤，而諸草木各有差別。",
    anchorText: "一雲所雨稱其種性",
    note: "同一云雨随草木种性令其生长结果，显佛法一味而众生受益各别。",
    occurrence: 1,
  },
  {
    id: "t0264-003-046",
    category: "大音普遍",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如來亦復如是，出現於世如大雲起，以大音聲普遍世界天、人、阿脩羅，如彼大雲遍覆三千大千國土，",
    anchorText: "出現於世如大雲起",
    note: "如来出世如大云起，以大音声普遍天、人、阿修罗众。",
    occurrence: 1,
  },
  {
    id: "t0264-003-047",
    category: "四事令得",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "未度者令度，未解者令解，未安者令安，未涅槃者令得涅槃，今世後世如實知之。",
    anchorText: "未度者令度，未解者令解",
    note: "经文直述如来令未度、未解、未安、未涅槃者各得其益。",
    occurrence: 1,
  },
  {
    id: "t0264-003-048",
    category: "開示道法",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "我是一切知者，一切見者，知道者，開道者，說道者，汝等天、人、阿脩羅眾，皆應到此，為聽法故。",
    anchorText: "知道者，開道者，說道者",
    note: "如来自称知道、开道、说道，劝天人阿修罗众来听法。",
    occurrence: 1,
  },
  {
    id: "t0264-003-049",
    category: "隨堪說法",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如來于時觀是眾生諸根利、鈍、精進、懈怠，隨其所堪而為說法，種種無量皆令歡喜，快得善利。",
    anchorText: "隨其所堪而為說法",
    note: "如来观众生根机勤怠，随其所堪说法，令大众欢喜并获善利。",
    occurrence: 1,
  },
  {
    id: "t0264-003-050",
    category: "聞法安隱",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "是諸眾生聞是法已，現世安隱後生善處，以道受樂亦得聞法，既聞法已離諸障礙，於諸法中任力所能漸得入道，",
    anchorText: "聞是法已，現世安隱後生善處",
    note: "本段明确说明闻法后现世安隐、后生善处、离障碍并渐得入道。",
    occurrence: 1,
  },
  {
    id: "t0264-003-051",
    category: "一味解脫",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如來說法一相一味，所謂解脫相、離相、滅相，究竟至於一切種智。",
    anchorText: "如來說法一相一味",
    note: "如来说法一相一味，指向解脱、离、灭，并究竟至一切种智。",
    occurrence: 1,
  },
  {
    id: "t0264-003-052",
    category: "持誦修行",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "其有眾生聞如來法，若持、讀誦、如說修行，所得功德不自覺知。",
    anchorText: "聞如來法，若持、讀誦",
    note: "经文明确说闻如来法并持、读诵、如说修行者所得功德，众生自己不尽觉知。",
    occurrence: 1,
  },
  {
    id: "t0264-003-053",
    category: "如實見知",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "眾生住於種種之地，唯有如來如實見之，明了無礙，如彼卉、木、叢林諸藥草等，而不自知上、中、下性。",
    anchorText: "唯有如來如實見之",
    note: "如来如实见知众生所住种种地，明了无碍，显其善巧护念。",
    occurrence: 1,
  },
  {
    id: "t0264-003-054",
    category: "將護眾生",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "佛知是已，觀眾生心欲而將護之，是故不即為說一切種智。",
    anchorText: "觀眾生心欲而將護之",
    note: "佛观众生心欲而将护，显示随根机渐次开示，不急说一切种智。",
    occurrence: 1,
  },
  {
    id: "t0264-003-055",
    category: "能信能受",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "汝等迦葉甚為希有，能知如來隨宜說法，能信能受。所以者何？諸佛世尊隨宜說法難解難知。",
    anchorText: "能知如來隨宜說法",
    note: "佛赞迦叶等能知如来随宜说法、能信能受，因诸佛随宜说法难解难知。",
    occurrence: 1,
  },
];
