import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const FASHI_SECTION_TITLE = "法師品第十";

export const T0264_JUAN_4_FASHI_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-004-038",
    category: "聞經授記",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "聞《妙法華經》一偈一句乃至一念隨喜者，我皆與授記，當得阿耨多羅三藐三菩提。",
    anchorText: "聞《妙法華經》一偈一句乃至一念隨喜者",
    note: "佛明示大众中闻《妙法华经》一偈一句乃至一念随喜者，皆得授记当成无上菩提。",
    occurrence: 1,
  },
  {
    id: "t0264-004-039",
    category: "滅後隨喜",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "又如來滅度之後，若有人聞《妙法華經》乃至一偈一句一念隨喜者，我亦與授阿耨多羅三藐三菩提記。",
    anchorText: "又如來滅度之後，若有人聞《妙法華經》",
    note: "佛灭度后，闻经一偈一句而一念随喜，也蒙佛授无上菩提记。",
    occurrence: 1,
  },
  {
    id: "t0264-004-040",
    category: "受持供養",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若復有人，受持、讀誦、解說、書寫《妙法華經》乃至一偈，於此經卷敬視如佛，種種供養，華香、瓔珞，末香、塗香、燒香，繒蓋、幢幡、衣服、伎樂，乃至合掌恭敬。藥王當知！是諸人等，已曾供養十萬億佛，於諸佛所成就大願，愍眾生故，生此人間。",
    anchorText: "受持、讀誦、解說、書寫《妙法華經》乃至一偈",
    note: "受持读诵、解说书写乃至一偈并敬供经卷者，曾供养十万亿佛，成就大愿，愍众生故生此人间。",
    occurrence: 1,
  },
  {
    id: "t0264-004-041",
    category: "未來作佛",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "藥王！若有人問：『何等眾生，於未來世當得作佛？』應示是諸人等於未來世必得作佛。",
    anchorText: "何等眾生，於未來世當得作佛",
    note: "佛令药王指示：受持供养此经者，未来世必得作佛。",
    occurrence: 1,
  },
  {
    id: "t0264-004-042",
    category: "如來供養",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若善男子、善女人，於《法華經》乃至一句，受持、讀誦、解說、書寫，種種供養經卷，華香、瓔珞、末香、塗香、燒香，繒蓋、幢幡、衣服、伎樂，合掌恭敬，是人一切世間所應瞻奉，應以如來供養而供養之，當知此人是大菩薩，成就阿耨多羅三藐三菩提，哀愍眾生，願生此間，廣演分別《妙法花經》，何況盡能受持種種供養者。",
    anchorText: "是人一切世間所應瞻奉",
    note: "于《法华经》乃至一句受持读诵、解说书写并供养者，应以如来供养而供养之，是大菩萨成就无上菩提。",
    occurrence: 1,
  },
  {
    id: "t0264-004-043",
    category: "如來使者",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若是善男子、善女人，我滅度後，能竊為一人說《法華經》，乃至一句，當知是人，則如來使，如來所遣，行如來事，何況於大眾中廣為人說。",
    anchorText: "能竊為一人說《法華經》，乃至一句",
    note: "佛灭后能为一人说《法华经》乃至一句者，即是如来使、如来所遣，行如来事。",
    occurrence: 1,
  },
  {
    id: "t0264-004-044",
    category: "護持法師",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若人以一惡言，毀呰在家、出家讀誦《法華經》者，其罪甚重。",
    anchorText: "毀呰在家、出家讀誦《法華經》者",
    note: "经文以重罪警示不可毁呰读诵《法华经》的在家、出家行者，显示护持法师的重要。",
    occurrence: 1,
  },
  {
    id: "t0264-004-045",
    category: "佛莊嚴身",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "其有讀誦《法華經》者，當知是人，以佛莊嚴而自莊嚴，則為如來肩所荷擔，其所至方，應隨向禮一心合掌，恭敬、供養、尊重、讚歎，華香、瓔珞，末香、塗香、燒香，繒蓋、幢幡、衣服、餚饌，作諸伎樂，人中上供而供養之，應持天寶而以散之，天上寶聚應以奉獻。",
    anchorText: "其有讀誦《法華經》者，當知是人",
    note: "读诵《法华经》者以佛庄严自庄严，为如来肩所荷担，所到之处应受恭敬供养赞叹。",
    occurrence: 1,
  },
  {
    id: "t0264-004-046",
    category: "聞法究竟",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "是人歡喜說法，須臾聞之，即得究竟阿耨多羅三藐三菩提故。",
    anchorText: "是人歡喜說法，須臾聞之",
    note: "佛说明供养读诵说法者的原因：闻其欢喜说法须臾，即得究竟无上菩提。",
    occurrence: 1,
  },
  {
    id: "t0264-004-047",
    category: "成就佛智",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若欲住佛道，成就自然智，常當勤供養，受持《法花》者。其有欲疾得，一切種智慧，當受持是經，并供養持者。",
    anchorText: "若欲住佛道，成就自然智",
    note: "偈颂劝欲住佛道、成就自然智或疾得一切种智者，应受持此经并供养持经者。",
    occurrence: 1,
  },
  {
    id: "t0264-004-048",
    category: "佛所使遣",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若有能受持，《妙法華經》者；當知佛所使，愍念諸眾生。諸有能受持，《妙法華經》者；捨於清淨土，愍眾故生此。",
    anchorText: "若有能受持，《妙法華經》者",
    note: "受持《妙法华经》者为佛所使，愍念众生，舍清净土而生此间。",
    occurrence: 1,
  },
  {
    id: "t0264-004-049",
    category: "惡世弘法",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "當知如是人，自在所欲生，能於此惡世，廣說無上法。",
    anchorText: "自在所欲生，能於此惡世",
    note: "经文赞受持者自在所欲生，能于恶世广说无上法。",
    occurrence: 1,
  },
  {
    id: "t0264-004-050",
    category: "如供世尊",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "吾滅後惡世，能持是經者；當合掌禮敬，如供養世尊。",
    anchorText: "吾滅後惡世，能持是經者",
    note: "佛灭后恶世能持此经者，应合掌礼敬，如供养世尊。",
    occurrence: 1,
  },
  {
    id: "t0264-004-051",
    category: "持經福勝",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "有人求佛道，而於一劫中，合掌在我前，以無數偈讚，由是讚佛故，得無量功德，歎美持經者，其福復過彼。",
    anchorText: "有人求佛道，而於一劫中",
    note: "经文以赞佛功德作比较，说明赞美持经者所得福德更胜。",
    occurrence: 1,
  },
  {
    id: "t0264-004-052",
    category: "聞經大利",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "於八十億劫，以最妙色聲，及與香味觸，供養持經者；如是供養已，若得須臾聞，則應自欣慶，我今獲大利。",
    anchorText: "於八十億劫，以最妙色聲",
    note: "长期以妙色声香味触供养持经者后，若得须臾闻法，应自庆获大利。",
    occurrence: 1,
  },
  {
    id: "t0264-004-053",
    category: "經中第一",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "藥王！今告汝，我所說諸經，而於此經中，《法華》最第一。",
    anchorText: "我所說諸經，而於此經中",
    note: "佛明说在所说诸经之中，《法华》最为第一。",
    occurrence: 1,
  },
  {
    id: "t0264-004-054",
    category: "祕藏護念",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "我所說經典，無量千萬億，已說、今說、當說，而於其中，此《法華經》最為難信、難解。藥王！此經是諸佛祕要之藏，不可分布，妄授與人，諸佛世尊之所守護，從昔已來未曾顯說。",
    anchorText: "此《法華經》最為難信、難解",
    note: "佛赞《法华经》为已说、今说、当说诸经中最难信难解，是诸佛秘要之藏、世尊所守护。",
    occurrence: 1,
  },
  {
    id: "t0264-004-055",
    category: "如來護持",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "如來滅後，其能書持、讀誦、供養、為他人說者，如來則為以衣覆之，又為他方、現在諸佛之所護念，是人有大信力及志願力、諸善根力，當知是人與如來共宿，則為如來手摩其頭。",
    anchorText: "其能書持、讀誦、供養、為他人說者",
    note: "如来灭后能书持读诵、供养并为人说此经者，为如来衣覆、诸佛护念，与如来共宿，如来摩顶。",
    occurrence: 1,
  },
  {
    id: "t0264-004-056",
    category: "經處起塔",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "在在處處，若說、若讀、若誦、若書，若經卷所住處，皆應起七寶塔，極令高廣嚴飾，不須復安舍利。所以者何？此中已有如來全身，此塔應以一切華香、瓔珞、繒蓋、幢幡、伎樂、歌頌，供養、恭敬、尊重、讚歎，若有人得見此塔禮拜、供養，當知是等，皆近阿耨多羅三藐三菩提。",
    anchorText: "若說、若讀、若誦、若書，若經卷所住處",
    note: "说读诵书或经卷所在之处应起七宝塔供养，因为经中已有如来全身，见塔礼拜供养者皆近无上菩提。",
    occurrence: 1,
  },
  {
    id: "t0264-004-057",
    category: "善行菩薩道",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若不能得見聞、讀誦、書持、供養是《法華經》者，當知是人未善行菩薩道。若有得聞是經典者，乃能善行菩薩之道，其有眾生求佛道者，若見、若聞是《法華經》，聞已信解、受持者，當知是人，得近阿耨多羅三藐三菩提。",
    anchorText: "若不能得見聞、讀誦、書持、供養是《法華經》者",
    note: "经文明示见闻、读诵、书持、供养此经与善行菩萨道相关；求佛道者见闻后信解受持，即近无上菩提。",
    occurrence: 1,
  },
  {
    id: "t0264-004-058",
    category: "聞解近道",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若未聞、未解、未能修習是《法華經》，當知是人，去阿耨多羅三藐三菩提尚遠。若得聞解、思惟、修習，必知得近阿耨多羅三藐三菩提。所以者何？一切菩薩阿耨多羅三藐三菩提，皆屬此經。此經開方便門，示真實相，是《法華經》藏，深固幽遠無人能到，今佛教化成就菩薩而為開示。",
    anchorText: "若得聞解、思惟、修習",
    note: "得闻解、思惟、修习《法华经》者，必知近无上菩提；此经开方便门、示真实相。",
    occurrence: 1,
  },
  {
    id: "t0264-004-059",
    category: "說經方法",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "如來滅後，欲為四眾說是《法華經》者，云何應說？是善男子、善女人，入如來室，著如來衣，坐如來座，爾乃應為四眾廣說斯經。如來室者，一切眾生中大慈悲心是；如來衣者，柔和忍辱心是；如來座者，一切法空是；安住是中，然後以不懈怠心，為諸菩薩及四眾，廣說是《法華經》。",
    anchorText: "入如來室，著如來衣，坐如來座",
    note: "佛教灭后说经者应具大慈悲、柔和忍辱与一切法空，以不懈怠心广说此经。",
    occurrence: 1,
  },
  {
    id: "t0264-004-060",
    category: "佛遣護助",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "我於餘國遣化人，為其集聽法眾，亦遣化比丘、比丘尼、優婆塞、優婆夷，聽其說法，是諸化人，聞法信受，隨順不逆。若說法者在空閑處，我時廣遣天、龍、鬼神、乾闥婆、阿修羅等，聽其說法。",
    anchorText: "我於餘國遣化人，為其集聽法眾",
    note: "佛在余国也遣化人、化四众集听法众，又遣天龙鬼神等听其说法。",
    occurrence: 1,
  },
  {
    id: "t0264-004-061",
    category: "見佛補闕",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "我雖在異國，時時令說法者得見我身，若於此經忘失句逗，我還為說令得具足。",
    anchorText: "時時令說法者得見我身",
    note: "说法者若忘失经文章句，佛令其得见佛身，并为其补说令具足。",
    occurrence: 1,
  },
  {
    id: "t0264-004-062",
    category: "聞經離怠",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "欲捨諸懈怠，應當聽是經，此經難得聞，信受者亦難。",
    anchorText: "欲捨諸懈怠，應當聽是經",
    note: "偈颂劝欲舍懈怠者应听此经，并指出此经难闻、信受亦难。",
    occurrence: 1,
  },
  {
    id: "t0264-004-063",
    category: "近佛智慧",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "不聞《法華經》，去佛智甚遠；若聞是深經，決了聲聞法，是諸經之王，聞已諦思惟，當知此人等，近於佛智慧。",
    anchorText: "不聞《法華經》，去佛智甚遠",
    note: "偈颂说不闻《法华经》则去佛智甚远；闻此深经并谛思惟者，近于佛智慧。",
    occurrence: 1,
  },
  {
    id: "t0264-004-064",
    category: "忍辱說法",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若說此經時，有人惡口罵，加刀杖瓦石，念佛故應忍。",
    anchorText: "若說此經時，有人惡口罵",
    note: "说此经时若遭恶口、刀杖瓦石，应念佛而忍，是说经者应具的护法忍辱。",
    occurrence: 1,
  },
  {
    id: "t0264-004-065",
    category: "化眾供養",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若我滅度後，能說此經者，我遣化四眾，比丘比丘尼，及清信士女，供養於法師，引導諸眾生，集之令聽法。",
    anchorText: "若我滅度後，能說此經者",
    note: "佛灭后能说此经者，佛遣化四众供养法师，引导众生集来听法。",
    occurrence: 1,
  },
  {
    id: "t0264-004-066",
    category: "變化衛護",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若人欲加惡，刀杖及瓦石，則遣變化人，為之作衛護。",
    anchorText: "若人欲加惡，刀杖及瓦石",
    note: "若有人欲以刀杖瓦石加害说经者，佛遣变化人为其卫护。",
    occurrence: 1,
  },
  {
    id: "t0264-004-067",
    category: "空處見佛",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若說法之人，獨在空閑處，寂寞無人聲，讀誦此經典；我爾時為現，清淨光明身，若忘失章句，為說令通利；若人具是德，或為四眾說，空處讀誦經，皆得見我身。",
    anchorText: "若說法之人，獨在空閑處",
    note: "说法者独处空闲读诵此经，佛为现清净光明身；忘失章句则为说令通利，并令得见佛身。",
    occurrence: 1,
  },
  {
    id: "t0264-004-068",
    category: "天龍聽法",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若人在空閑，我遣天龍王，夜叉鬼神等，為作聽法眾。",
    anchorText: "我遣天龍王，夜叉鬼神等",
    note: "人在空闲处说读此经，佛遣天龙王、夜叉鬼神等为作听法众。",
    occurrence: 1,
  },
  {
    id: "t0264-004-069",
    category: "諸佛護念",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "是人樂說法，分別無罣礙，諸佛護念故，能令大眾喜。",
    anchorText: "是人樂說法，分別無罣礙",
    note: "乐说法者因诸佛护念，分别无碍，能令大众欢喜。",
    occurrence: 1,
  },
  {
    id: "t0264-004-070",
    category: "親近法師",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若親近法師，速得菩薩道，隨順是師學，得見恒沙佛。",
    anchorText: "若親近法師，速得菩薩道",
    note: "亲近法师、随顺学习者，速得菩萨道，并得见恒河沙诸佛。",
    occurrence: 1,
  },
];