import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const JIANBAOTA_SECTION_TITLE = "見寶塔品第十一";

export const T0262_JUAN_5_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0262-005-148",
    category: "寶塔作證",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "善哉，善哉！釋迦牟尼世尊！能以平等大慧，教菩薩法，佛所護念，妙法華經，為大眾說。如是，如是！釋迦牟尼世尊！如所說者，皆是真實。",
    anchorText: "能以平等大慧，教菩薩法，佛所護念，妙法華經",
    note: "多寶塔中出聲讚歎，為釋迦說《法華經》作證，稱所說皆是真實。",
  },
  {
    id: "t0262-005-149",
    category: "聞聲法喜",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "爾時四眾，見大寶塔住在空中，又聞塔中所出音聲，皆得法喜，怪未曾有，從座而起，恭敬合掌，却住一面。",
    anchorText: "又聞塔中所出音聲，皆得法喜",
    note: "四眾見寶塔、聞塔中音聲，皆得法喜，生未曾有心。",
  },
  {
    id: "t0262-005-150",
    category: "為聽此經",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "若我成佛、滅度之後，於十方國土有說法華經處，我之塔廟，為聽是經故，踊現其前，為作證明，讚言善哉。",
    anchorText: "於十方國土有說法華經處，我之塔廟，為聽是經故",
    note: "多寶如來本願明示：凡十方有說《法華經》處，寶塔為聽此經而現前作證。",
  },
  {
    id: "t0262-005-151",
    category: "寶塔現前",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "十方世界，在在處處，若有說法華經者，彼之寶塔皆踊出其前，全身在於塔中，讚言：『善哉，善哉！』",
    anchorText: "若有說法華經者，彼之寶塔皆踊出其前",
    note: "經文明說在在處處有說《法華經》者，多寶寶塔皆現前讚歎。",
  },
  {
    id: "t0262-005-152",
    category: "聞經讚歎",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "今多寶如來塔，聞說法華經故，從地踊出，讚言：『善哉，善哉！』",
    anchorText: "聞說法華經故，從地踊出",
    note: "佛直接說明寶塔從地踊出的原因，是聞說《法華經》故。",
  },
  {
    id: "t0262-005-153",
    category: "分身來集",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "若我寶塔，為聽法華經故，出於諸佛前時，其有欲以我身示四眾者，彼佛分身諸佛——在於十方世界說法，盡還集一處，然後我身乃出現耳。",
    anchorText: "為聽法華經故，出於諸佛前時",
    note: "多寶佛深重願力，把寶塔現前、十方分身佛來集，皆與聽《法華經》相連。",
  },
  {
    id: "t0262-005-154",
    category: "供養寶塔",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "善男子！我今應往娑婆世界，釋迦牟尼佛所，并供養多寶如來寶塔。",
    anchorText: "我今應往娑婆世界，釋迦牟尼佛所，并供養多寶如來寶塔",
    note: "十方諸佛因寶塔與法華會集，皆往娑婆供養多寶如來寶塔。",
  },
  {
    id: "t0262-005-155",
    category: "為聽經故",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "善哉，善哉！釋迦牟尼佛！快說是法華經，我為聽是經故而來至此。",
    anchorText: "快說是法華經，我為聽是經故而來至此",
    note: "多寶如來現身後再次讚歎，明說自己為聽《法華經》而來。",
  },
  {
    id: "t0262-005-156",
    category: "付囑弘經",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "誰能於此娑婆國土廣說妙法華經，今正是時。如來不久當入涅槃，佛欲以此妙法華經付囑有在。",
    anchorText: "誰能於此娑婆國土廣說妙法華經，今正是時",
    note: "佛在二如來同坐寶塔後，正式付囑於娑婆廣說《妙法華經》。",
  },
  {
    id: "t0262-005-157",
    category: "勤為法故",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "聖主世尊，雖久滅度，在寶塔中，尚為法來。諸人云何不勤為法？",
    anchorText: "雖久滅度，在寶塔中，尚為法來",
    note: "偈頌以多寶如來久滅仍為法而來，勸眾勤為法。",
  },
  {
    id: "t0262-005-158",
    category: "令法久住",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "又我分身，無量諸佛，如恒沙等，來欲聽法。及見滅度，多寶如來，各捨妙土，及弟子眾、天人龍神、諸供養事，令法久住，故來至此。",
    anchorText: "令法久住，故來至此",
    note: "十方分身佛與多寶如來來集，旨在聽法並令法久住。",
  },
  {
    id: "t0262-005-159",
    category: "護持讀說",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "我滅度後，誰能護持、讀說斯經？今於佛前，自說誓言。",
    anchorText: "誰能護持、讀說斯經",
    note: "佛直接勸眾於佛前立誓，在滅後護持、讀說此經。",
  },
  {
    id: "t0262-005-160",
    category: "供養諸佛",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "其有能護，此經法者，則為供養，我及多寶。",
    anchorText: "其有能護，此經法者，則為供養，我及多寶",
    note: "能護持此經法者，經文明說即是供養釋迦佛與多寶佛。",
  },
  {
    id: "t0262-005-161",
    category: "見佛功德",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "若說此經，則為見我、多寶如來，及諸化佛。",
    anchorText: "若說此經，則為見我、多寶如來，及諸化佛",
    note: "偈中明說說此經者，即為見釋迦、多寶如來及諸化佛。",
  },
  {
    id: "t0262-005-162",
    category: "惡世說經",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "若佛滅後，於惡世中，能說此經，是則為難。",
    anchorText: "於惡世中，能說此經，是則為難",
    note: "佛以多重譬喻襯托，佛滅後惡世能說此經最為難得。",
  },
  {
    id: "t0262-005-163",
    category: "書持難得",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "於我滅後，若自書持，若使人書，是則為難。",
    anchorText: "若自書持，若使人書，是則為難",
    note: "佛明示滅後自行書持或使人書此經，皆屬難行難得。",
  },
  {
    id: "t0262-005-164",
    category: "暫讀難得",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "佛滅度後，於惡世中，暫讀此經，是則為難。",
    anchorText: "於惡世中，暫讀此經，是則為難",
    note: "即使暫讀此經，於佛滅後惡世中亦被佛標舉為難得。",
  },
  {
    id: "t0262-005-165",
    category: "為人說經",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "我滅度後，若持此經、為一人說，是則為難。",
    anchorText: "若持此經、為一人說，是則為難",
    note: "滅後受持此經並為一人說，也是本品反覆讚歎的難行。",
  },
  {
    id: "t0262-005-166",
    category: "聽受問義",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "於我滅後，聽受此經，問其義趣，是則為難。",
    anchorText: "聽受此經，問其義趣，是則為難",
    note: "滅後能聽受此經並詢問義趣，亦被佛列為難得之事。",
  },
  {
    id: "t0262-005-167",
    category: "奉持難得",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "於我滅後，若能奉持，如斯經典，是則為難。",
    anchorText: "若能奉持，如斯經典，是則為難",
    note: "佛總結滅後奉持此經典極為難得。",
  },
  {
    id: "t0262-005-168",
    category: "此經第一",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "我為佛道，於無量土，從始至今，廣說諸經，而於其中，此經第一。",
    anchorText: "廣說諸經，而於其中，此經第一",
    note: "佛親自總讚：從始至今廣說諸經，其中此經第一。",
  },
  {
    id: "t0262-005-169",
    category: "持佛身",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "若有能持，則持佛身。",
    anchorText: "若有能持，則持佛身",
    note: "本品以極簡重語讚歎持經者：能持此經，即持佛身。",
  },
  {
    id: "t0262-005-170",
    category: "諸佛歡喜",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "此經難持，若暫持者，我則歡喜，諸佛亦然。",
    anchorText: "此經難持，若暫持者，我則歡喜，諸佛亦然",
    note: "佛明說此經難持，若能暫持，釋迦與諸佛皆歡喜。",
  },
  {
    id: "t0262-005-171",
    category: "諸佛所歎",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "如是之人，諸佛所歎。是則勇猛，是則精進，是名持戒，行頭陀者，則為疾得，無上佛道。",
    anchorText: "如是之人，諸佛所歎",
    note: "能暫持此經者為諸佛所歎，經中稱為勇猛、精進、持戒，疾得無上佛道。",
  },
  {
    id: "t0262-005-172",
    category: "真佛子",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "能於來世，讀持此經，是真佛子，住淳善地。",
    anchorText: "能於來世，讀持此經，是真佛子",
    note: "來世能讀持此經者，經文明稱為真佛子，住淳善地。",
  },
  {
    id: "t0262-005-173",
    category: "世間之眼",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "佛滅度後，能解其義，是諸天人，世間之眼。",
    anchorText: "能解其義，是諸天人，世間之眼",
    note: "佛滅後能解此經義趣者，為諸天人、世間之眼。",
  },
  {
    id: "t0262-005-174",
    category: "天人供養",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "於恐畏世，能須臾說，一切天人，皆應供養。",
    anchorText: "於恐畏世，能須臾說，一切天人，皆應供養",
    note: "在恐畏惡世中能須臾說此經者，一切天人皆應供養。",
  },
  {
    id: "t0262-005-175",
    category: "求法無倦",
    sectionTitle: "提婆達多品第十二",
    text: "吾於過去無量劫中。求法華經無有懈惓。於多劫中常作國王。發願求於無上菩提。心不退轉。",
    anchorText: "求法華經無有懈惓。於多劫中常作國王",
    note: "佛自述過去無量劫為求《法華經》不懈，發願求無上菩提而心不退轉。",
  },
  {
    id: "t0262-005-176",
    category: "為法捨身",
    sectionTitle: "提婆達多品第十二",
    text: "爲於法故。捐捨國位委政太子。撃鼓宣令四方求法。誰能爲我説大乘者。吾當終身供給走使。",
    anchorText: "爲於法故。捐捨國位委政太子",
    note: "為求大乘妙法，國王捨國位、求說法者，顯示求法之重。",
  },
  {
    id: "t0262-005-177",
    category: "勤求大法",
    sectionTitle: "提婆達多品第十二",
    text: "情存妙法故 身心無懈惓 普爲諸衆生 勤求於大法 亦不爲己身 及以五欲樂 故爲大國王 勤求獲此法 遂致得成佛 今故爲汝説",
    anchorText: "普爲諸衆生 勤求於大法",
    note: "偈頌明說佛昔日不為自身五欲，而為眾生勤求大法，終致成佛。",
  },
  {
    id: "t0262-005-178",
    category: "善知識力",
    sectionTitle: "提婆達多品第十二",
    text: "由提婆達多善知識故。令我具足六波羅蜜慈悲喜捨三十二相八十種好紫磨金色。十力四無所畏四攝法。十八不共神通道力。成等正覺廣度衆生。皆因提婆達多善知識故。",
    anchorText: "由提婆達多善知識故。令我具足六波羅蜜",
    note: "佛明說因提婆達多作善知識，令其具足諸功德、成正覺並廣度眾生。",
  },
  {
    id: "t0262-005-179",
    category: "授記成佛",
    sectionTitle: "提婆達多品第十二",
    text: "提婆達多。却後過無量劫。當得成佛。號曰天王如來應供正遍知明行足善逝世間解無上士調御丈夫天人師佛世尊。",
    anchorText: "提婆達多。却後過無量劫。當得成佛",
    note: "本品直接授記提婆達多未來成佛，號天王如來。",
  },
  {
    id: "t0262-005-180",
    category: "說法度眾",
    sectionTitle: "提婆達多品第十二",
    text: "時天王佛。住世二十中劫。廣爲衆生説於妙法。恒河沙衆生得阿羅漢果。無量衆生發縁覺心。恒河沙衆生發無上道心。得無生忍至不退轉。",
    anchorText: "廣爲衆生説於妙法。恒河沙衆生得阿羅漢果",
    note: "天王佛住世說妙法，令眾生證果、發心、得無生忍至不退轉。",
  },
  {
    id: "t0262-005-181",
    category: "供塔得益",
    sectionTitle: "提婆達多品第十二",
    text: "諸天人民悉以雜華末香燒香塗香衣服瓔珞幢幡寶蓋伎樂歌頌。禮拜供養七寶妙塔。無量衆生得阿羅漢果。無量衆生悟辟支佛。不可思議衆生發菩提心至不退轉。",
    anchorText: "禮拜供養七寶妙塔。無量衆生得阿羅漢果",
    note: "供養天王佛舍利寶塔，經文明說無量眾生得果、發心乃至不退轉。",
  },
  {
    id: "t0262-005-182",
    category: "聞品利益",
    sectionTitle: "提婆達多品第十二",
    text: "未來世中。若有善男子善女人。聞妙法華經提婆達多品。淨心信敬不生疑惑者。不墮地獄餓鬼畜生。生十方佛前所生之處常聞此經。若生人天中受勝妙樂。若在佛前蓮華化生。",
    anchorText: "聞妙法華經提婆達多品。淨心信敬不生疑惑者",
    note: "佛明示未來聞本品而淨信不疑者，不墮三惡道，所生常聞此經。",
  },
  {
    id: "t0262-005-183",
    category: "論說妙法",
    sectionTitle: "提婆達多品第十二",
    text: "此有菩薩。名文殊師利。可與相見論説妙法可還本土。",
    anchorText: "名文殊師利。可與相見論説妙法",
    note: "佛留智積菩薩與文殊相見論說妙法，引出後文龍宮化度與速成佛的證明。",
  },
  {
    id: "t0262-005-184",
    category: "龍宮化度",
    sectionTitle: "提婆達多品第十二",
    text: "此諸菩薩皆是文殊師利之所化度。具菩薩行皆共論説六波羅蜜。本聲聞人在虚空中説聲聞行。今皆修行大乘空義。",
    anchorText: "皆是文殊師利之所化度。具菩薩行",
    note: "文殊在龍宮所化眾生無量，已具菩薩行，並修行大乘空義。",
  },
  {
    id: "t0262-005-185",
    category: "令速菩提",
    sectionTitle: "提婆達多品第十二",
    text: "大智徳勇健 化度無量衆 今此諸大會 及我皆已見 演暢實相義 開闡一乘法 廣導諸衆生 令速成菩提",
    anchorText: "演暢實相義 開闡一乘法",
    note: "智積以偈讚文殊演暢實相、開闡一乘，廣導眾生令速成菩提。",
  },
  {
    id: "t0262-005-186",
    category: "常說法華",
    sectionTitle: "提婆達多品第十二",
    text: "文殊師利言。我於海中唯常宣説妙法華經。",
    anchorText: "我於海中唯常宣説妙法華經",
    note: "文殊自明在海中唯常宣說《妙法華經》，本品以此承接龍宮化度。",
  },
  {
    id: "t0262-005-187",
    category: "經中之寶",
    sectionTitle: "提婆達多品第十二",
    text: "此經甚深微妙。諸經中寶世所希有。",
    anchorText: "此經甚深微妙。諸經中寶世所希有",
    note: "智積讚歎此經甚深微妙，是諸經中寶、世所希有。",
  },
  {
    id: "t0262-005-188",
    category: "修行此經",
    sectionTitle: "提婆達多品第十二",
    text: "頗有衆生勤加精進修行此經速得佛不。",
    anchorText: "勤加精進修行此經速得佛不",
    note: "智積以此發問，將本品焦點轉到修行此經能否速得佛果。",
  },
  {
    id: "t0262-005-189",
    category: "受持祕藏",
    sectionTitle: "提婆達多品第十二",
    text: "智慧利根善知衆生諸根行業。得陀羅尼。諸佛所説甚深祕藏悉能受持。深入禪定了達諸法。",
    anchorText: "諸佛所説甚深祕藏悉能受持",
    note: "龍女智慧利根，能受持諸佛甚深祕藏，並深入禪定、了達諸法。",
  },
  {
    id: "t0262-005-190",
    category: "速得不退",
    sectionTitle: "提婆達多品第十二",
    text: "於刹那頃發菩提心。得不退轉辯才無礙。慈念衆生猶如赤子。功徳具足心念口演。微妙廣大慈悲仁讓。志意和雅能至菩提。",
    anchorText: "於刹那頃發菩提心。得不退轉",
    note: "文殊舉龍女為證，明其剎那發菩提心，得不退轉，功德具足而能至菩提。",
  },
  {
    id: "t0262-005-191",
    category: "讚佛度生",
    sectionTitle: "提婆達多品第十二",
    text: "深達罪福相 遍照於十方 微妙淨法身 具相三十二 以八十種好 用莊嚴法身 天人所戴仰 龍神咸恭敬 一切衆生類 無不宗奉者 又聞成菩提 唯佛當證知 我闡大乘教 度脱苦衆生",
    anchorText: "我闡大乘教 度脱苦衆生",
    note: "龍女偈讚佛德，並發願闡大乘教、度脫苦眾生。",
  },
  {
    id: "t0262-005-192",
    category: "速成正覺",
    sectionTitle: "提婆達多品第十二",
    text: "女言。以汝神力觀我成佛。復速於此。當時衆會皆見龍女。忽然之間變成男子。具菩薩行。即往南方無垢世界。坐寶蓮華成等正覺。",
    anchorText: "以汝神力觀我成佛。復速於此",
    note: "龍女以獻珠納受為喻，示現更速成佛，眾會皆見其成等正覺。",
  },
  {
    id: "t0262-005-193",
    category: "演說妙法",
    sectionTitle: "提婆達多品第十二",
    text: "三十二相八十種好。普爲十方一切衆生演説妙法。",
    anchorText: "普爲十方一切衆生演説妙法",
    note: "龍女成佛後具足相好，普為十方一切眾生演說妙法。",
  },
  {
    id: "t0262-005-194",
    category: "眾會歡喜",
    sectionTitle: "提婆達多品第十二",
    text: "爾時娑婆世界菩薩聲聞天龍八部人與非人。皆遙見彼龍女成佛。普爲時會人天説法。心大歡喜悉遙敬禮。",
    anchorText: "皆遙見彼龍女成佛。普爲時會人天説法",
    note: "娑婆大眾遙見龍女成佛並說法，心大歡喜，悉遙敬禮。",
  },
  {
    id: "t0262-005-195",
    category: "聞法得益",
    sectionTitle: "提婆達多品第十二",
    text: "無量衆生聞法解悟得不退轉。無量衆生得受道記。",
    anchorText: "無量衆生聞法解悟得不退轉",
    note: "龍女成佛說法後，無量眾生聞法解悟、得不退轉，並得受道記。",
  },
  {
    id: "t0262-005-196",
    category: "發心受記",
    sectionTitle: "提婆達多品第十二",
    text: "娑婆世界三千衆生住不退地。三千衆生發菩提心而得受記。",
    anchorText: "三千衆生發菩提心而得受記",
    note: "娑婆世界亦有三千眾生住不退地，三千眾生發菩提心而得受記。",
  },
  {
    id: "t0262-005-197",
    category: "默然信受",
    sectionTitle: "提婆達多品第十二",
    text: "智積菩薩及舍利弗。一切衆會默然信受",
    anchorText: "一切衆會默然信受",
    note: "本品以智積、舍利弗及一切眾會默然信受作結，顯示眾會對所證法義的信受。",
  },
];