import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const GUANGSHIYIN_PUMEN_SECTION_TITLE = "光世音普門品第二十三";

export const T0263_JUAN_10_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-001",
    category: "聞名解脫",
    text: "若有眾生，遭億百千姟困厄患難苦毒無量，適聞光世音菩薩名者，輒得解脫無有眾惱，故名光世音。",
    anchorText: "遭億百千姟困厄患難苦毒無量",
    note: "本品开端明示众生遭遇诸难，适闻光世音菩萨名即得解脱众恼。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-002",
    category: "火水海難",
    text: "若有持名執在心懷，設遇大火然其山野，燒百草木叢林屋宅，身墮火中，得聞光世音名，火即尋滅。",
    anchorText: "若有持名執在心懷，設遇大火",
    note: "经文以火难为例，说明持名在心、得闻其名可令火难寻灭。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-003",
    category: "火水海難",
    text: "若入大水江河駛流心中恐怖，稱光世音菩薩，一心自歸，則威神護令不見溺，使出安隱。",
    anchorText: "若入大水江河駛流心中恐怖",
    note: "遇大水恐怖时称名自归，蒙威神护持而出安隐。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-004",
    category: "火水海難",
    text: "眾中一人竊獨心念，光世音菩薩功德威神，而稱名號，皆得解脫一切眾患，及其伴侶眾得濟渡，不遇諸魔邪鬼之厄，故名光世音。",
    anchorText: "光世音菩薩功德威神，而稱名號",
    note: "海难与鬼界险厄中，一人称名亦令同伴济渡，解脱众患。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-005",
    category: "怨賊鬼難",
    text: "若見怨賊欲來危害，即稱光世音菩薩名號，而自歸命，賊所持刀杖，尋段段壞手不得舉，自然慈心。",
    anchorText: "若見怨賊欲來危害",
    note: "称名归命可令怨贼刀杖坏、恶害止息，并转为慈心。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-006",
    category: "怨賊鬼難",
    text: "此三千大千世界滿中諸鬼神，眾邪逆魅欲來嬈人，一心稱呼光世音名，自然為伏不能妄犯，惡心不生不得邪觀。",
    anchorText: "滿中諸鬼神，眾邪逆魅欲來嬈人",
    note: "面对诸鬼神邪魅扰害，一心称名可令其自然降伏，不得妄犯。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-007",
    category: "繫縛解脫",
    text: "若人犯罪若無有罪，若為惡人縣官所錄，縛束其身杻械在體，若枷鎖之，閉在牢獄，拷治苦毒，一心自歸，稱光世音名號，疾得解脫，開獄門出無能拘制，故名光世音。",
    anchorText: "縛束其身杻械在體",
    note: "经文明说被系缚、枷锁、牢狱苦毒者一心称名，可疾得解脱。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-008",
    category: "威神總讚",
    text: "光世音境界，威神功德難可限量，光光若斯，故號光世音。",
    anchorText: "光世音境界，威神功德難可限量",
    note: "佛总赞光世音境界与威神功德难可限量。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-009",
    category: "賊難解脫",
    text: "稱光世音菩薩威神，輒來擁護令無恐懼，普心自歸便脫眾難，不遇賊害。",
    anchorText: "稱光世音菩薩威神",
    note: "商旅遇众贼险路时，共称光世音威神而得拥护、脱难。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-010",
    category: "賊難解脫",
    text: "眾賈人聞悉共受教，咸俱同聲稱光世音，身命自歸願脫此畏難，適稱其名，賊便退卻不敢觸犯，眾賈解脫永無恐怖。",
    anchorText: "咸俱同聲稱光世音",
    note: "经中以商众称名为例，显示称名即能令贼退却、众人无怖。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-011",
    category: "離三毒",
    text: "若有學人，婬怒癡盛，稽首歸命光世音菩薩，婬怒癡休，觀於無常苦空非身，一心得定。",
    anchorText: "婬怒癡盛，稽首歸命光世音菩薩",
    note: "归命光世音可令淫怒痴休息，并观无常苦空非身而一心得定。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-012",
    category: "求子德本",
    text: "若有女人，無有子姓，求男求女，歸光世音，輒得男女，一心精進自歸命者，世世端正顏貌無比，見莫不歡，所生子姓而有威相，眾人所愛願樂欲見，殖眾德本不為罪業。",
    anchorText: "求男求女，歸光世音",
    note: "经文明说求男女者归光世音，并赞一心精进归命所得端正、德本等利益。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-013",
    category: "聞名不虛",
    text: "其聞名者，所至到處終不虛妄，不遇邪害，致得無上道德果實，常遇諸佛真人、菩薩高德正士，不與逆人，無反復會，若聞名執持懷抱，功德無量不可稱載。",
    anchorText: "其聞名者，所至到處終不虛妄",
    note: "本段总说闻名执持者不遇邪害、趋向无上道果、常遇善圣，功德无量。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-014",
    category: "持名勝福",
    text: "雖供養此無限菩薩，不如一歸光世音稽首作禮執持名號，福過於彼，況復供養？",
    anchorText: "不如一歸光世音稽首作禮執持名號",
    note: "佛以供养无量菩萨作比较，显明一归礼拜执持名号的殊胜福德。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-015",
    category: "持名勝福",
    text: "雖復供養六十二億江河沙數諸菩薩等，執持名號，計此二福，億百千劫不可盡極，終不相比，是故名曰光世音。",
    anchorText: "執持名號，計此二福",
    note: "继续承接比较，说明执持光世音名号所得福德久劫不可尽。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-016",
    category: "隨類說法",
    text: "光世音菩薩所遊世界，或現佛身而班宣法；或現菩薩形像色貌，說經開化；或現緣覺或現聲聞，或現梵天帝像而說經道",
    anchorText: "光世音菩薩所遊世界",
    note: "佛说明光世音游诸世界，随应现佛、菩萨、缘觉、声闻等身说法开化。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-017",
    category: "普門開度",
    text: "光世音菩薩，遊諸佛土，而普示現若干種形，在所變化開度一切。",
    anchorText: "遊諸佛土，而普示現若干種形",
    note: "这一句概括普门示现的核心：以若干形变化开度一切。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-018",
    category: "施無畏",
    text: "一切眾生咸當供養光世音。其族姓子，所可周旋有恐懼者，令無所畏，已致無畏使普安隱，各自欣慶，故遊忍界。",
    anchorText: "一切眾生咸當供養光世音",
    note: "佛劝一切众生供养光世音，并明其于恐惧中令无所畏、普得安隐。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-019",
    category: "無所不濟",
    text: "其族姓子，普為一切，以是之故，神足變化遊忍世界，無所不濟。",
    anchorText: "神足變化遊忍世界，無所不濟",
    note: "受宝璎供养一段后，总结光世音普为一切而游忍世界，无所不济。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-020",
    category: "聞德安隱",
    text: "假使有人，聞光世音所行德本，終不虛妄，世世安隱至無極慧，其光世音，神足變化普至道門，所顯威神而無窮極。",
    anchorText: "聞光世音所行德本",
    note: "持地菩萨总结：闻光世音所行德本，世世安隐，至无极慧。",
  },
  {
    sectionTitle: GUANGSHIYIN_PUMEN_SECTION_TITLE,
    id: "t0263-010-021",
    category: "聞品發心",
    text: "佛說是普門道品，彼時會中八萬四千人，至無等倫，尋發無上正真道意。",
    anchorText: "佛說是普門道品",
    note: "本品结尾明说佛说普门道品时，八万四千人随即发无上正真道意。",
  },
];
