import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const FASHI_GONGDE_SECTION_TITLE = "法師功德品第十八";

export const T0264_JUAN_6_FASHI_GONGDE_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-006-019",
    category: "六根清淨",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "若善男子、善女人，受持是《法華經》，若讀、若誦、若解說、若書寫，是人當得八百眼功德，千二百耳功德，八百鼻功德，千二百舌功德，八百身功德，千二百意功德，以是功德莊嚴六根，皆令清淨；",
    anchorText: "受持是《法華經》，若讀、若誦、若解說、若書寫",
    note: "受持、读诵、解说、书写《法华经》者，得六根功德庄严，令六根清净。",
  },
  {
    id: "t0264-006-020",
    category: "眼根功德",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "是善男子、善女人，父母所生清淨肉眼，見於三千大千世界內外所有山林、河、海，下至阿鼻地獄上至有頂，亦見其中一切眾生，及業因緣、果報、生處，悉見、悉知。",
    anchorText: "父母所生清淨肉眼",
    note: "持经者以父母所生清净肉眼，见三千大千世界乃至众生业因缘、果报、生处。",
  },
  {
    id: "t0264-006-021",
    category: "眼根清淨",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "是人得八百，功德殊勝眼；以是莊嚴故，其目甚清淨。父母所生眼，悉見三千界，內外彌樓山，須彌及鐵圍，并諸餘山林，大海江河水，下至阿鼻獄，上至有頂處，其中諸眾生，一切皆悉見；雖未得天眼，肉眼力如是。",
    anchorText: "是人得八百，功德殊勝眼",
    note: "偈颂重申持经说法者得殊胜眼功德，虽未得天眼，肉眼力已能悉见三千界众生。",
  },
  {
    id: "t0264-006-022",
    category: "耳根功德",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "若善男子、善女人，受持此經，若讀、若誦、若解說、若書寫，得千二百耳功德，以是清淨耳，聞三千大千世界，下至阿鼻地獄上至有頂，其中內、外種種所有語言、音聲，",
    anchorText: "得千二百耳功德，以是清淨耳",
    note: "受持读诵、解说书写此经者，得一千二百耳功德，能闻三千大千世界内外诸声。",
  },
  {
    id: "t0264-006-023",
    category: "聞知諸聲",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "三千大千世界中，一切內、外所有諸聲，雖未得天耳，以父母所生清淨常耳，皆悉聞知，如是分別種種音聲，而不壞耳根。",
    anchorText: "雖未得天耳，以父母所生清淨常耳",
    note: "持经者虽未得天耳，以清净常耳悉闻知并分别一切诸声，且不坏耳根。",
  },
  {
    id: "t0264-006-024",
    category: "耳根聰利",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "三千大千界，內外諸音聲，下至阿鼻獄，上至有頂天，皆聞其音聲，而不壞耳根；其耳聰利故，悉能分別知，持是《法華》者，雖未得天耳，但用所生耳，功德已如是。",
    anchorText: "三千大千界，內外諸音聲",
    note: "偈颂说明持《法华》者耳根聪利，能闻知三千界内外诸声而不坏耳根。",
  },
  {
    id: "t0264-006-025",
    category: "鼻根功德",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "若善男子、善女人，受持是經，若讀、若誦、若解說、若書寫，成就八百鼻功德，以是清淨鼻根，聞於三千大千世界，上、下、內、外種種諸香，",
    anchorText: "成就八百鼻功德",
    note: "受持读诵、解说书写此经者，成就八百鼻功德，清净鼻根能闻三千界种种诸香。",
  },
  {
    id: "t0264-006-026",
    category: "聞香分別",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "持是經者，於此間住，悉能分別。又復別知眾生之香，象香、馬香、牛、羊等香，男香、女香、童子香、童女香，及草、木、叢林香，若近、若遠所有諸香，悉皆得聞分別不錯。",
    anchorText: "若近、若遠所有諸香",
    note: "持经者能分别近远诸香，并知众生、草木丛林等香，分辨不错。",
  },
  {
    id: "t0264-006-027",
    category: "諸聖身香",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "并聞諸天所燒之香，及聲聞香、辟支佛香，菩薩香、諸佛身香，亦皆遙聞知其所在。雖聞此香，然於鼻根不壞不錯，若欲分別為他人說，憶念不謬。",
    anchorText: "聲聞香、辟支佛香，菩薩香、諸佛身香",
    note: "持经者能遥闻声闻、辟支佛、菩萨、诸佛身香，知其所在，鼻根不坏，忆念不谬。",
  },
  {
    id: "t0264-006-028",
    category: "聞香知心",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "以聞香力故，知男女所念，染欲癡恚心，亦知修善者。",
    anchorText: "以聞香力故，知男女所念",
    note: "偈颂说持经者以闻香力，能知男女所念及染欲、痴恚、修善等心行。",
  },
  {
    id: "t0264-006-029",
    category: "鼻相先得",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "雖未得菩薩，無漏法生鼻，而是持經者，先得此鼻相。",
    anchorText: "而是持經者，先得此鼻相",
    note: "持经者虽未得菩萨无漏法生鼻，已先得此清净鼻相。",
  },
  {
    id: "t0264-006-030",
    category: "舌根功德",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "若善男子、善女人，受持是經，若讀、若誦、若解說、若書寫，得千二百舌功德，若好、若醜、若美、不美，及諸苦澁物，在其舌根，皆變成上味，如天甘露，無不美者。",
    anchorText: "得千二百舌功德",
    note: "受持读诵、解说书写此经者，得一千二百舌功德，诸味入舌皆成上味如天甘露。",
  },
  {
    id: "t0264-006-031",
    category: "妙聲說法",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "若以舌根，於大眾中有所演說，出深妙聲，能入其心，皆令歡喜快樂。又諸天子、天女、釋梵諸天，聞是深妙音聲，有所演說、言論次第，皆悉來聽。",
    anchorText: "出深妙聲，能入其心",
    note: "持经者于大众中演说，出深妙声，能入众心，令欢喜快乐，诸天亦来听受。",
  },
  {
    id: "t0264-006-032",
    category: "聽法供養",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "為聽法故，皆來親近，恭敬供養；及比丘、比丘尼、優婆塞、優婆夷，國王、王子、群臣、眷屬，小轉輪王、大轉輪王，七寶千子，內外眷屬，乘其宮殿，俱來聽法；",
    anchorText: "為聽法故，皆來親近，恭敬供養",
    note: "诸龙夜叉等与四众、国王眷属、转轮王眷属，为听法故亲近供养，俱来听法。",
  },
  {
    id: "t0264-006-033",
    category: "諸佛護念",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "又諸聲聞、辟支佛、菩薩、諸佛，常樂見之，是人所在方面，諸佛皆向其處說法，悉能受持一切佛法，又能出於深妙法音。",
    anchorText: "諸佛皆向其處說法",
    note: "诸声闻、辟支佛、菩萨、诸佛常乐见持经说法者；诸佛向其处说法，使其能受持一切佛法。",
  },
  {
    id: "t0264-006-034",
    category: "法音守護",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "諸佛及弟子，聞其說法音，常念而守護，或時為現身。",
    anchorText: "聞其說法音，常念而守護",
    note: "偈颂说诸佛及弟子闻其说法音，常念守护，或时为其现身。",
  },
  {
    id: "t0264-006-035",
    category: "身根功德",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "若善男子、善女人，受持是經，若讀、若誦、若解說、若書寫，得八百身功德，得清淨身，如淨琉璃；眾生憙見其身淨故，三千大千世界眾生，生時、死時、上、下、好、醜，生善處、惡處，悉於中現，",
    anchorText: "得八百身功德，得清淨身，如淨琉璃",
    note: "受持读诵、解说书写此经者，得八百身功德，身如净琉璃，众生喜见，三千界众生生死善恶皆于中现。",
  },
  {
    id: "t0264-006-036",
    category: "身中現法",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "若聲聞、辟支佛、菩薩、諸佛說法，皆於身中現其色像。",
    anchorText: "皆於身中現其色像",
    note: "声闻、辟支佛、菩萨、诸佛说法，皆于持经者清净身中现其色像。",
  },
  {
    id: "t0264-006-037",
    category: "清淨身相",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "若持《法華》者，其身甚清淨，如彼淨琉璃，眾生皆憙見。又如淨明鏡，悉見諸色像，菩薩於淨身，皆見世所有。",
    anchorText: "若持《法華》者，其身甚清淨",
    note: "偈颂赞持《法华》者身甚清净，如净琉璃、净明镜，能现世间诸色像。",
  },
  {
    id: "t0264-006-038",
    category: "意根功德",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "若善男子、善女人，如來滅後受持是經，若讀、若誦、若解說、若書寫，得千二百意功德，以是清淨意根，乃至聞一偈、一句，通達無量無邊之義；",
    anchorText: "得千二百意功德",
    note: "如来灭后受持读诵、解说书写此经者，得一千二百意功德，闻一偈一句即可通达无量义。",
  },
  {
    id: "t0264-006-039",
    category: "說法契實相",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "解是義已，能演說一句、一偈，至於一月、四月，乃至一歲，諸所說法隨其義趣，皆與實相不相違背。",
    anchorText: "諸所說法隨其義趣",
    note: "持经者解义后，能以一句一偈演说至久，所说皆随义趣，不违实相。",
  },
  {
    id: "t0264-006-040",
    category: "知心言真",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "三千大千世界，六趣眾生，心之所行、心所動作、心所戲論，皆悉知之。雖未得無漏智慧，而其意根清淨如此，是人有所思惟籌量言說，皆是佛法無不真實，亦是先佛經中所說。",
    anchorText: "六趣眾生，心之所行、心所動作",
    note: "持经者意根清净，能知六趣众生心行，所思惟筹量言说皆是佛法、真实不虚。",
  },
  {
    id: "t0264-006-041",
    category: "聞偈通義",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "乃至聞一偈，通達無量義，次第如法說，月四月至歲。",
    anchorText: "乃至聞一偈，通達無量義",
    note: "偈颂重申持经者乃至闻一偈即通达无量义，并能次第如法宣说。",
  },
  {
    id: "t0264-006-042",
    category: "受持不忘",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "十方無數佛，百福莊嚴相，為眾生說法，悉聞能受持，思惟無量義，說法亦無量，終始不忘錯，以持《法華》故。",
    anchorText: "悉聞能受持，思惟無量義",
    note: "以持《法华》故，闻十方诸佛说法悉能受持，思惟说法无量，终始不忘不错。",
  },
  {
    id: "t0264-006-043",
    category: "眾生愛敬",
    sectionTitle: FASHI_GONGDE_SECTION_TITLE,
    text: "是人持此經，安住希有地，為一切眾生，歡喜而愛敬。能以千萬種，善巧之語言，分別而說法，持《法華經》故。",
    anchorText: "安住希有地，為一切眾生",
    note: "持经者安住希有地，为众生欢喜爱敬，并能以千万种善巧语言分别说法。",
  },
];