import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const XUPIN_SECTION_TITLE = "序品第一";
const PUMEN_SECTION_TITLE = "觀世音菩薩普門品第二十五";

export const T0262_JUAN_1_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0262-001-001",
    category: "序品菩薩功德",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "菩薩摩訶薩八萬人，皆於阿耨多羅三藐三菩提不退轉；皆得陀羅尼；樂說辯才，轉不退轉法輪；供養無量百千諸佛，於諸佛所殖眾德本，常為諸佛之所稱歎；以慈修身，善入佛慧；通達大智，到於彼岸；名稱普聞無量世界，能度無數百千眾生。",
    anchorText: "菩薩摩訶薩八萬人，皆於阿耨多羅三藐三菩提不退轉",
    note: "序品开列大会菩萨德相，显示不退、陀罗尼、辩才、佛所称叹与度生能力。",
  },
  {
    id: "t0262-001-002",
    category: "大乘經總讚",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "為諸菩薩說大乘經，名無量義，教菩薩法，佛所護念。",
    anchorText: "為諸菩薩說大乘經，名無量義",
    note: "序品以“教菩萨法、佛所护念”说明即将展开的大乘法会背景。",
  },
  {
    id: "t0262-001-003",
    category: "聞法瑞相",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "爾時會中，比丘、比丘尼、優婆塞、優婆夷、天龍、夜叉、乾闥婆、阿修羅、迦樓羅、緊那羅、摩睺羅伽、人非人，及諸小王、轉輪聖王，是諸大眾，得未曾有，歡喜合掌，一心觀佛。",
    anchorText: "是諸大眾，得未曾有，歡喜合掌，一心觀佛",
    note: "大众见瑞得未曾有，欢喜合掌、一心观佛，适合作为序品闻法入门条目。",
  },
  {
    id: "t0262-001-004",
    category: "佛光顯法",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "爾時佛放眉間白毫相光，照東方萬八千世界，靡不周遍，下至阿鼻地獄，上至阿迦尼吒天。",
    anchorText: "爾時佛放眉間白毫相光，照東方萬八千世界",
    note: "序品以佛放光普照开显法华将说因缘。",
  },
  {
    id: "t0262-001-005",
    category: "佛光顯法",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "於此世界，盡見彼土六趣眾生，又見彼土現在諸佛，及聞諸佛所說經法。",
    anchorText: "於此世界，盡見彼土六趣眾生",
    note: "佛光令众会见六趣、见诸佛并闻经法，是序品显现佛境界的重要利益。",
  },
  {
    id: "t0262-001-006",
    category: "開悟眾生",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "各於世界，講說正法，種種因緣。以無量喻，照明佛法，開悟眾生。",
    anchorText: "各於世界，講說正法，種種因緣",
    note: "偈中说明诸佛以因缘譬喻照明佛法、开悟众生。",
  },
  {
    id: "t0262-001-007",
    category: "離苦入道",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "若人遭苦，厭老病死，為說涅槃，盡諸苦際。若人有福，曾供養佛，志求勝法，為說緣覺。若有佛子、修種種行，求無上慧，為說淨道。",
    anchorText: "若人遭苦，厭老病死，為說涅槃",
    note: "此段按众生根机说明说法利益：尽苦、缘觉、净道，语义完整。",
  },
  {
    id: "t0262-001-008",
    category: "菩薩行願",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "或有行施，金銀珊瑚、真珠摩尼、車𤦲馬腦、金剛諸珍，奴婢車乘、寶飾輦輿，歡喜布施。迴向佛道，願得是乘，三界第一，諸佛所歎。",
    anchorText: "或有行施，金銀珊瑚、真珠摩尼",
    note: "序品借佛光所见菩萨布施，显示回向佛道、愿得诸佛所叹之乘。",
  },
  {
    id: "t0262-001-009",
    category: "菩薩修行",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "又見菩薩，勇猛精進，入於深山，思惟佛道。又見離欲，常處空閑，深修禪定，得五神通。",
    anchorText: "又見菩薩，勇猛精進，入於深山",
    note: "此处清楚呈现精进、思惟佛道、离欲禅定及五神通等修行成就。",
  },
  {
    id: "t0262-001-010",
    category: "聞持說法",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "復見菩薩，智深志固，能問諸佛，聞悉受持。又見佛子，定慧具足，以無量喻，為眾講法。欣樂說法，化諸菩薩，破魔兵眾，而擊法鼓。",
    anchorText: "復見菩薩，智深志固，能問諸佛",
    note: "此段把问佛、闻持、定慧、讲法、化众与破魔连成完整功德单元。",
  },
  {
    id: "t0262-001-011",
    category: "大法將說",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "今佛世尊欲說大法，雨大法雨，吹大法螺，擊大法鼓，演大法義。",
    anchorText: "今佛世尊欲說大法，雨大法雨",
    note: "文殊解释瑞相，明说佛将说大法、雨法雨、演大法义。",
  },
  {
    id: "t0262-001-012",
    category: "聞知難信之法",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "是故當知，今佛現光，亦復如是，欲令眾生，咸得聞知一切世間難信之法，故現斯瑞。",
    anchorText: "欲令眾生，咸得聞知一切世間難信之法",
    note: "此句直接说明现瑞目的：令众生得闻知世间难信之法。",
  },
  {
    id: "t0262-001-013",
    category: "正法利益",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "演說正法，初善中善後善，其義深遠，其語巧妙，純一無雜，具足清白梵行之相。",
    anchorText: "演說正法，初善中善後善",
    note: "文殊追述日月灯明佛说法，赞叹正法初中后善、义深语妙。",
  },
  {
    id: "t0262-001-014",
    category: "三乘得益",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "為求聲聞者說應四諦法，度生老病死，究竟涅槃；為求辟支佛者說應十二因緣法；為諸菩薩說應六波羅蜜，令得阿耨多羅三藐三菩提，成一切種智。",
    anchorText: "為求聲聞者說應四諦法",
    note: "完整说明随三乘根机说法及其结果：涅槃、因缘法、无上菩提与一切种智。",
  },
  {
    id: "t0262-001-015",
    category: "法華聽受",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "是時日月燈明佛從三昧起，因妙光菩薩、說大乘經，名妙法蓮華，教菩薩法，佛所護念，六十小劫不起于座。時會聽者亦坐一處，六十小劫身心不動，聽佛所說，謂如食頃。是時眾中，無有一人若身若心而生懈惓。",
    anchorText: "說大乘經，名妙法蓮華，教菩薩法",
    note: "此段赞叹法华会中久听不倦，显示此经摄受大众的殊胜。",
  },
  {
    id: "t0262-001-016",
    category: "持經演說",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "佛滅度後，妙光菩薩持妙法蓮華經，滿八十小劫為人演說。日月燈明佛八子皆師妙光，妙光教化令其堅固阿耨多羅三藐三菩提。",
    anchorText: "妙光菩薩持妙法蓮華經",
    note: "文殊以妙光菩萨持经演说为证，说明持法华经能教化坚固无上菩提。",
  },
  {
    id: "t0262-001-017",
    category: "善根果報",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "是人亦以種諸善根因緣故，得值無量百千萬億諸佛，供養、恭敬，尊重、讚歎。",
    anchorText: "是人亦以種諸善根因緣故",
    note: "求名菩萨虽有懈怠失误，仍因善根得值诸佛并供养赞叹，宜作保守果报条目。",
  },
  {
    id: "t0262-001-018",
    category: "法雨充足",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "諸人今當知，合掌一心待，佛當雨法雨，充足求道者。",
    anchorText: "諸人今當知，合掌一心待",
    note: "序品结尾劝众合掌一心待法，佛当以法雨充足求道者。",
  },
  {
    id: "t0262-001-019",
    category: "斷疑生信",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "諸求三乘人，若有疑悔者，佛當為除斷，令盡無有餘。",
    anchorText: "諸求三乘人，若有疑悔者",
    note: "最后以佛将为三乘求法者除断疑悔作结，为下一品承接。",
  },
];

export const T0262_JUAN_7_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0262-007-001",
    category: "稱名解脫",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若有無量百千萬億眾生受諸苦惱，聞是觀世音菩薩，一心稱名，觀世音菩薩即時觀其音聲，皆得解脫。",
    anchorText: "若有無量百千萬億眾生受諸苦惱",
    note: "经文直接说明受诸苦恼者闻观世音菩萨、一心称名，即得解脱。",
  },
  {
    id: "t0262-007-002",
    category: "怖畏得脫",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "汝等應當一心稱觀世音菩薩名號。是菩薩能以無畏施於眾生。汝等若稱名者，於此怨賊當得解脫。",
    anchorText: "汝等應當一心稱觀世音菩薩名號",
    note: "商主劝众人一心称名，明说观世音菩萨能以无畏施于众生。",
  },
  {
    id: "t0262-007-003",
    category: "離三毒",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若有眾生多於婬欲，常念恭敬觀世音菩薩，便得離欲。若多瞋恚，常念恭敬觀世音菩薩，便得離瞋。若多愚癡，常念恭敬觀世音菩薩，便得離癡。",
    anchorText: "若有眾生多於婬欲，常念恭敬觀世音菩薩",
    note: "本段把常念恭敬观世音菩萨与离欲、离瞋、离痴相连。",
  },
  {
    id: "t0262-007-004",
    category: "常應心念",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "觀世音菩薩有如是等大威神力，多所饒益。是故眾生常應心念。",
    anchorText: "觀世音菩薩有如是等大威神力，多所饒益",
    note: "经文总括观世音菩萨大威神力、多所饶益，并劝众生常应心念。",
  },
  {
    id: "t0262-007-005",
    category: "求子善願",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若有女人，設欲求男，禮拜供養觀世音菩薩，便生福德智慧之男；設欲求女，便生端正有相之女。宿殖德本，眾人愛敬。",
    anchorText: "若有女人，設欲求男，禮拜供養觀世音菩薩",
    note: "经文明说礼拜供养观世音菩萨，求男、求女各有相应善果。",
  },
  {
    id: "t0262-007-006",
    category: "福不唐捐",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若有眾生恭敬禮拜觀世音菩薩，福不唐捐。是故眾生皆應受持觀世音菩薩名號。",
    anchorText: "若有眾生恭敬禮拜觀世音菩薩，福不唐捐",
    note: "经文以“福不唐捐”劝众生受持观世音菩萨名号。",
  },
  {
    id: "t0262-007-007",
    category: "福德無邊",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若復有人受持觀世音菩薩名號，乃至一時禮拜、供養。是二人福，正等無異，於百千萬億劫不可窮盡。無盡意！受持觀世音菩薩名號，得如是無量無邊福德之利。",
    anchorText: "若復有人受持觀世音菩薩名號",
    note: "受持观世音菩萨名号，乃至一时礼拜供养，经中赞为无量无边福德之利。",
  },
  {
    id: "t0262-007-008",
    category: "普門示現",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "是觀世音菩薩成就如是功德，以種種形，遊諸國土，度脫眾生。",
    anchorText: "是觀世音菩薩成就如是功德",
    note: "这一句总摄普门示现：以种种形游诸国土、度脱众生。",
  },
  {
    id: "t0262-007-009",
    category: "施無畏者",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "是觀世音菩薩摩訶薩於怖畏急難之中能施無畏，是故此娑婆世界皆號之為施無畏者。",
    anchorText: "於怖畏急難之中能施無畏",
    note: "经文直接说明观世音菩萨于怖畏急难中能施无畏。",
  },
  {
    id: "t0262-007-010",
    category: "滅諸有苦",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "聞名及見身，心念不空過，能滅諸有苦。",
    anchorText: "聞名及見身，心念不空過",
    note: "偈颂以极简句说明闻名、见身、心念皆不空过，能灭诸有苦。",
  },
  {
    id: "t0262-007-011",
    category: "救世間苦",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "眾生被困厄，無量苦逼身，觀音妙智力，能救世間苦。",
    anchorText: "眾生被困厄，無量苦逼身",
    note: "偈颂概括观音妙智力能救众生困厄与世间苦。",
  },
  {
    id: "t0262-007-012",
    category: "漸滅諸苦",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "種種諸惡趣，地獄鬼畜生，生老病死苦，以漸悉令滅。",
    anchorText: "種種諸惡趣，地獄鬼畜生",
    note: "偈颂说明种种恶趣及生老病死苦，以渐悉令灭。",
  },
  {
    id: "t0262-007-013",
    category: "甘露法雨",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "悲體戒雷震，慈意妙大雲，澍甘露法雨，滅除煩惱焰。",
    anchorText: "悲體戒雷震，慈意妙大雲",
    note: "经文以甘露法雨比喻慈悲说法能灭除烦恼焰。",
  },
  {
    id: "t0262-007-014",
    category: "常念勿疑",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "妙音觀世音，梵音海潮音，勝彼世間音，是故須常念，念念勿生疑。",
    anchorText: "妙音觀世音，梵音海潮音",
    note: "偈颂劝人常念、念念勿生疑。",
  },
  {
    id: "t0262-007-015",
    category: "聞品功德",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "若有眾生聞是觀世音菩薩品自在之業、普門示現神通力者，當知是人功德不少。",
    anchorText: "若有眾生聞是觀世音菩薩品自在之業",
    note: "本品结尾直接说明，闻此品自在之业、普门示现神通力者，功德不少。",
  },
  {
    id: "t0262-007-016",
    category: "聞法發心",
    sectionTitle: PUMEN_SECTION_TITLE,
    text: "佛說是普門品時，眾中八萬四千眾生，皆發無等等阿耨多羅三藐三菩提心。",
    anchorText: "佛說是普門品時，眾中八萬四千眾生",
    note: "经文以大众闻品发无上菩提心作为结尾。",
  },
];
