import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const PIYU_SECTION_TITLE = "譬喻品第三";

export const T0264_JUAN_2_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-002-001",
    category: "聞法歡喜",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "今從世尊聞此法音，心懷踊躍得未曾有。所以者何？我昔從佛聞如是法，見諸菩薩受記作佛，而我等不預斯事，甚自感傷，失於如來無量知見。",
    anchorText: "今從世尊聞此法音，心懷踊躍得未曾有",
    note: "舍利弗闻法华法音后欢喜踊跃，觉知过去未预受记之失。",
    occurrence: 1,
  },
  {
    id: "t0264-002-002",
    category: "斷疑安隱",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "而今從佛聞所未聞未曾有法，斷諸疑悔，身意泰然快得安隱，今日乃知真是佛子，從佛口生、從法化生，得佛法分。",
    anchorText: "斷諸疑悔，身意泰然快得安隱",
    note: "闻未曾有法后，舍利弗断疑悔、得安隐，并自知为佛子、得佛法分。",
    occurrence: 1,
  },
  {
    id: "t0264-002-003",
    category: "佛音除惱",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "我聞是法音，得所未曾有；心懷大歡喜，疑網皆已除。昔來蒙佛教，不失於大乘；佛音甚希有，能除眾生惱。我已得漏盡，聞亦除憂惱；",
    anchorText: "佛音甚希有，能除眾生惱",
    note: "偈中明说佛音希有，能除众生恼；舍利弗闻法后疑网除、忧恼除。",
    occurrence: 1,
  },
  {
    id: "t0264-002-004",
    category: "隨宜導入",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "今聞佛音聲，隨宜而說法，無漏難思議，令眾至道場。",
    anchorText: "隨宜而說法，無漏難思議，令眾至道場",
    note: "舍利弗赞佛随宜说法，能令众生至于道场。",
    occurrence: 1,
  },
  {
    id: "t0264-002-005",
    category: "拔邪證空",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "我本著邪見，為諸梵志師，世尊知我心，拔邪說涅槃；我悉除邪見，於空法得證。",
    anchorText: "世尊知我心，拔邪說涅槃",
    note: "经文回顾佛以涅槃法拔除舍利弗邪见，使其于空法得证。",
    occurrence: 1,
  },
  {
    id: "t0264-002-006",
    category: "疑悔悉除",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "佛於大眾中，說我當作佛；聞如是法音，疑悔悉已除。",
    anchorText: "聞如是法音，疑悔悉已除",
    note: "舍利弗闻佛说自己当作佛，疑悔悉除。",
    occurrence: 1,
  },
  {
    id: "t0264-002-007",
    category: "譬喻斷疑",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "佛以種種緣，譬喻巧言說，其心安如海，我聞疑網斷。",
    anchorText: "佛以種種緣，譬喻巧言說",
    note: "佛以因缘譬喻善巧说法，使闻者疑网断除。",
    occurrence: 1,
  },
  {
    id: "t0264-002-008",
    category: "聞法安住",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "聞佛柔軟音，深遠甚微妙；演暢清淨法，我心大歡喜。疑悔永已盡，安住實智中，我定當作佛，為天人所敬，轉無上法輪，教化諸菩薩。",
    anchorText: "疑悔永已盡，安住實智中",
    note: "闻佛柔软深妙音与清净法后，舍利弗疑悔永尽、安住实智，并发起成佛教化的自知。",
    occurrence: 1,
  },
  {
    id: "t0264-002-009",
    category: "方便引導",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "我昔曾於二萬億佛所，為無上道故，常教化汝，汝亦長夜隨我受學，我以方便引導，汝故生我法中。",
    anchorText: "我以方便引導，汝故生我法中",
    note: "佛说明久远以来以方便引导舍利弗，使其生于佛法中。",
    occurrence: 1,
  },
  {
    id: "t0264-002-010",
    category: "憶念本願",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "我今還欲令汝憶念本願所行道故，為諸聲聞說是大乘經，名《妙法蓮華教菩薩法佛所護念》。",
    anchorText: "令汝憶念本願所行道故，為諸聲聞說是大乘經",
    note: "佛说此大乘经，是为令声闻忆念本愿所行之道。",
    occurrence: 1,
  },
  {
    id: "t0264-002-011",
    category: "授記成佛",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "汝於未來世過無量無邊不可思議劫，供養若干千萬億佛，奉持正法，具足菩薩所行之道，當得作佛，號曰華光如來、應供、正遍知、明行足、善逝、世間解、無上士、調御丈夫、天人師、佛、世尊，",
    anchorText: "供養若干千萬億佛，奉持正法，具足菩薩所行之道",
    note: "佛为舍利弗授记，明其供佛、奉持正法、具菩萨道后当成华光如来。",
    occurrence: 1,
  },
  {
    id: "t0264-002-012",
    category: "淨土菩薩",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "此諸菩薩非初發意，皆久殖德本，於無量百千萬億佛所，淨修梵行，恒為諸佛之所稱嘆，常修佛慧具大神通，善知一切諸法之門，質直無偽志念堅固，如是菩薩充滿其國。",
    anchorText: "皆久殖德本，於無量百千萬億佛所，淨修梵行",
    note: "华光佛国菩萨久殖德本、为诸佛称叹、常修佛慧，显示授记净土功德庄严。",
    occurrence: 1,
  },
  {
    id: "t0264-002-013",
    category: "成佛度眾",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "舍利弗來世，成佛普智尊；號名曰華光，當度無量眾。供養無數佛，具足菩薩行；十力等功德，證於無上道。",
    anchorText: "舍利弗來世，成佛普智尊",
    note: "偈颂重明舍利弗来世成佛、度无量众，供佛具菩萨行而证无上道。",
    occurrence: 1,
  },
  {
    id: "t0264-002-014",
    category: "正法流布",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "佛滅度之後，正法住於世；三十二小劫，廣度諸眾生。正法滅盡已，像法三十二；舍利廣流布，天人普供養。",
    anchorText: "正法住於世；三十二小劫，廣度諸眾生",
    note: "华光佛灭后正法久住、广度众生，舍利流布受天人供养。",
    occurrence: 1,
  },
  {
    id: "t0264-002-015",
    category: "隨喜供養",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "見舍利弗於佛前得受阿耨多羅三藐三菩提記，心大歡喜踊躍無量，各各脫身所著上衣，以供養佛。",
    anchorText: "心大歡喜踊躍無量，各各脫身所著上衣，以供養佛",
    note: "大众见舍利弗得授记后欢喜踊跃，以衣供佛。",
    occurrence: 1,
  },
  {
    id: "t0264-002-016",
    category: "無上法輪",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "佛昔於波羅奈初轉法輪，今乃復轉無上最大法輪。",
    anchorText: "今乃復轉無上最大法輪",
    note: "诸天赞叹佛今复转无上最大法轮。",
    occurrence: 1,
  },
  {
    id: "t0264-002-017",
    category: "聞法隨喜",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "未曾聞如是，深妙之上法；世尊說是法，我等皆隨喜。大智舍利弗，今得受尊記；我等亦如是，必當得作佛。",
    anchorText: "世尊說是法，我等皆隨喜",
    note: "诸天子随喜深妙上法，并自知亦必当作佛。",
    occurrence: 1,
  },
  {
    id: "t0264-002-018",
    category: "迴向佛道",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "我所有福業，今世若過世，及見佛功德，盡迴向佛道。",
    anchorText: "我所有福業，今世若過世",
    note: "诸天子将今世、过去福业及见佛功德，悉皆回向佛道。",
    occurrence: 1,
  },
];
