import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const PIYU_SECTION_TITLE = "譬喻品第三";

export const T0262_JUAN_2_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0262-002-001",
    category: "聞法斷疑",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "今從世尊聞此法音。心懷踊躍。得未曾有。",
    anchorText: "今從世尊聞此法音。心懷踊躍",
    note: "舍利弗闻佛说法，欢喜踊跃，得未曾有。",
  },
  {
    id: "t0262-002-002",
    category: "聞法安隱",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "而今從佛。聞所未聞未曾有法。斷諸疑悔。身意泰然。快得安隱。",
    anchorText: "聞所未聞未曾有法。斷諸疑悔",
    note: "经文直接说明闻未曾有法后断疑悔、身意泰然、快得安隐。",
  },
  {
    id: "t0262-002-003",
    category: "佛子法分",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "今日乃知真是佛子。從佛口生。從法化生。得佛法分。",
    anchorText: "今日乃知真是佛子。從佛口生",
    note: "舍利弗领解自身从法化生、得佛法分。",
  },
  {
    id: "t0262-002-004",
    category: "法音利益",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "我聞是法音 得所未曾有 心懷大歡喜 疑網皆已除",
    anchorText: "我聞是法音 得所未曾有",
    note: "偈颂以简明句说明闻法音得未曾有、疑网除尽。",
  },
  {
    id: "t0262-002-005",
    category: "佛音除惱",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "昔來蒙佛教 不失於大乘 佛音甚希有 能除眾生惱",
    anchorText: "佛音甚希有 能除眾生惱",
    note: "此偈赞叹佛音稀有，能除众生恼。",
  },
  {
    id: "t0262-002-006",
    category: "實智安住",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "聞佛柔軟音 深遠甚微妙 演暢清淨法 我心大歡喜 疑悔永已盡 安住實智中",
    anchorText: "聞佛柔軟音 深遠甚微妙",
    note: "此偈从闻佛柔软音到疑悔尽、安住实智，语义完整。",
  },
  {
    id: "t0262-002-007",
    category: "成佛授記",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "我定當作佛 為天人所敬 轉無上法輪 教化諸菩薩",
    anchorText: "我定當作佛 為天人所敬",
    note: "舍利弗闻法后自知当作佛、转无上法轮、教化菩萨。",
  },
  {
    id: "t0262-002-008",
    category: "經文總讚",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "為諸聲聞。說是大乘經。名妙法蓮華。教菩薩法。佛所護念。",
    anchorText: "說是大乘經。名妙法蓮華",
    note: "佛明说此经为大乘经、教菩萨法、佛所护念。",
  },
  {
    id: "t0262-002-009",
    category: "授記作佛",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "舍利弗。汝於未來世過無量無邊不可思議劫。供養若干千萬億佛。奉持正法。具足菩薩所行之道。當得作佛。",
    anchorText: "供養若干千萬億佛。奉持正法",
    note: "此段为舍利弗授记，明示供养诸佛、奉持正法、具足菩萨行后当得作佛。",
  },
  {
    id: "t0262-002-010",
    category: "授記度生",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "舍利弗來世 成佛普智尊 號名曰華光 當度無量眾",
    anchorText: "舍利弗來世 成佛普智尊",
    note: "授记偈说明舍利弗来世成佛，并当度无量众。",
  },
  {
    id: "t0262-002-011",
    category: "正法利益",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "佛滅度之後 正法住於世 三十二小劫 廣度諸眾生",
    anchorText: "正法住於世 三十二小劫",
    note: "偈中说明华光佛灭后正法住世并广度众生。",
  },
  {
    id: "t0262-002-012",
    category: "聞記歡喜",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "見舍利弗於佛前受阿耨多羅三藐三菩提記。心大歡喜。踊躍無量。各各脫身所著上衣。以供養佛。",
    anchorText: "見舍利弗於佛前受阿耨多羅三藐三菩提記",
    note: "四众见舍利弗受记而大欢喜、踊跃供佛。",
  },
  {
    id: "t0262-002-013",
    category: "大法輪讚",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "今復轉最妙 無上大法輪 是法甚深奧 少有能信者",
    anchorText: "今復轉最妙 無上大法輪",
    note: "诸天赞叹佛今转最妙无上大法轮，法甚深奥。",
  },
  {
    id: "t0262-002-014",
    category: "深妙法歡喜",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "我等從昔來 數聞世尊說 未曾聞如是 深妙之上法 世尊說是法 我等皆隨喜",
    anchorText: "未曾聞如是 深妙之上法",
    note: "诸天说明从昔数闻佛说，未曾闻此深妙上法，故皆随喜。",
  },
  {
    id: "t0262-002-015",
    category: "回向佛道",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "佛道叵思議 方便隨宜說 我所有福業 今世若過世 及見佛功德 盡迴向佛道",
    anchorText: "我所有福業 今世若過世",
    note: "闻法欢喜后，诸天将所有福业及见佛功德尽回向佛道。",
  },
  {
    id: "t0262-002-016",
    category: "離疑請法",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "善哉世尊。願為四眾說其因緣。令離疑悔。",
    anchorText: "願為四眾說其因緣。令離疑悔",
    note: "舍利弗为四众请佛说因缘，目标是令离疑悔。",
  },
  {
    id: "t0262-002-017",
    category: "譬喻得解",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "今當復以譬喻更明此義。諸有智者。以譬喻得解。",
    anchorText: "諸有智者。以譬喻得解",
    note: "佛明说将以譬喻阐明，一切有智者可由譬喻得解。",
  },
  {
    id: "t0262-002-018",
    category: "方便免難",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "我今當設方便。令諸子等得免斯害。",
    anchorText: "我今當設方便。令諸子等得免斯害",
    note: "火宅譬中以长者设方便，喻佛设方便令众生免难。",
  },
  {
    id: "t0262-002-019",
    category: "拔濟火宅",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "是長者但令諸子得免火難。全其軀命。非為虛妄。何以故。若全身命。便為已得玩好之具。況復方便。於彼火宅而拔濟之。",
    anchorText: "於彼火宅而拔濟之",
    note: "舍利弗解释方便非虚妄，因为长者已于火宅拔济诸子。",
  },
  {
    id: "t0262-002-020",
    category: "如來利益",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "如來亦復如是。則為一切世間之父。於諸怖畏衰惱憂患。無明闇蔽。永盡無餘。而悉成就無量知見。力無所畏。有大神力。及智慧力。具足方便智慧波羅蜜。大慈大悲。常無懈倦。恆求善事。利益一切。",
    anchorText: "如來亦復如是。則為一切世間之父",
    note: "佛自释譬喻，以如来为世间父，具方便智慧、大慈大悲，利益一切。",
  },
  {
    id: "t0262-002-021",
    category: "教化菩提",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "為度眾生生老病死。憂悲苦惱。愚癡闇蔽三毒之火。教化令得阿耨多羅三藐三菩提。",
    anchorText: "為度眾生生老病死",
    note: "此句直接说明佛为度众生诸苦与三毒之火，教化令得无上菩提。",
  },
  {
    id: "t0262-002-022",
    category: "拔苦與樂",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "我為眾生之父。應拔其苦難。與無量無邊佛智慧樂。令其遊戲。",
    anchorText: "應拔其苦難。與無量無邊佛智慧樂",
    note: "佛以父子譬说明拔苦与给与佛智慧乐。",
  },
  {
    id: "t0262-002-023",
    category: "智慧方便",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "但以智慧方便。於三界火宅拔濟眾生。為說三乘。",
    anchorText: "但以智慧方便。於三界火宅拔濟眾生",
    note: "经文明说如来以智慧方便在三界火宅拔济众生。",
  },
  {
    id: "t0262-002-024",
    category: "勤修精進",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "汝速出三界。當得三乘。聲聞辟支佛佛乘。我今為汝保任此事。終不虛也。汝等但當勤修精進。",
    anchorText: "汝速出三界。當得三乘",
    note: "佛劝众生速出三界，并令勤修精进。",
  },
  {
    id: "t0262-002-025",
    category: "安隱快樂",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "汝等當知。此三乘法。皆是聖所稱歎。自在無繫。無所依求。乘是三乘。以無漏根力覺道禪定解脫三昧等。而自娛樂。便得無量安隱快樂。",
    anchorText: "便得無量安隱快樂",
    note: "此段明说三乘法为圣所称叹，能得无量安隐快乐。",
  },
  {
    id: "t0262-002-026",
    category: "聞法信受",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若有眾生內有智性。從佛世尊聞法信受。殷勤精進。欲速出三界。自求涅槃。是名聲聞乘。",
    anchorText: "從佛世尊聞法信受。殷勤精進",
    note: "经文以闻法信受、殷勤精进说明声闻乘出离方向。",
  },
  {
    id: "t0262-002-027",
    category: "大乘利生",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若有眾生。從佛世尊聞法信受。勤修精進。求一切智。佛智。自然智。無師智。如來知見力無所畏。愍念安樂無量眾生。利益天人。度脫一切。是名大乘。",
    anchorText: "求一切智。佛智。自然智。無師智",
    note: "此段完整说明大乘所求智慧，以及愍念安乐、利益天人、度脱一切。",
  },
  {
    id: "t0262-002-028",
    category: "大乘平等",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "是諸眾生皆是我子。等與大乘。不令有人獨得滅度。皆以如來滅度而滅度之。",
    anchorText: "等與大乘。不令有人獨得滅度",
    note: "佛以一切众生皆子说明等与大乘，不令独得小灭。",
  },
  {
    id: "t0262-002-029",
    category: "第一之樂",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "是諸眾生脫三界者悉與諸佛禪定解脫等娛樂之具。皆是一相一種。聖所稱歎。能生淨妙第一之樂。",
    anchorText: "能生淨妙第一之樂",
    note: "三界得脱者，佛悉与禅定解脱等娱乐之具，能生净妙第一之乐。",
  },
  {
    id: "t0262-002-030",
    category: "大乘度脫",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "如來亦復如是。無有虛妄。初說三乘引導眾生。然後但以大乘而度脫之。",
    anchorText: "初說三乘引導眾生。然後但以大乘而度脫之",
    note: "佛自明先以三乘引导，后以大乘度脱，方便无虚妄。",
  },
  {
    id: "t0262-002-031",
    category: "一佛乘",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "舍利弗。以是因緣。當知諸佛方便力故。於一佛乘。分別說三。",
    anchorText: "於一佛乘。分別說三",
    note: "本品总括火宅譬，说明诸佛以方便力于一佛乘分别说三。",
  },
  {
    id: "t0262-002-032",
    category: "信受成佛",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "汝等若能 信受是語 一切皆當 成得佛道",
    anchorText: "汝等若能 信受是語",
    note: "偈中直接说若能信受佛语，一切皆当成得佛道。",
  },
  {
    id: "t0262-002-033",
    category: "寶乘總讚",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "是乘微妙 清淨第一 於諸世間 為無有上 佛所悅可 一切眾生 所應稱讚 供養禮拜",
    anchorText: "是乘微妙 清淨第一",
    note: "偈颂赞叹一佛乘微妙、清净第一、世间无上。",
  },
  {
    id: "t0262-002-034",
    category: "直至道場",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "乘此寶乘 直至道場 以是因緣 十方諦求 更無餘乘 除佛方便",
    anchorText: "乘此寶乘 直至道場",
    note: "偈中以宝乘直至道场，说明究竟只是一佛乘，余乘为方便。",
  },
  {
    id: "t0262-002-035",
    category: "濟拔出界",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "汝等累劫 眾苦所燒 我皆濟拔 令出三界",
    anchorText: "汝等累劫 眾苦所燒",
    note: "偈中以佛父自述，累劫众苦所烧者皆为佛所济拔。",
  },
  {
    id: "t0262-002-036",
    category: "法印利益",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "汝舍利弗 我此法印 為欲利益 世間故說",
    anchorText: "我此法印 為欲利益",
    note: "经文直接说此法印为欲利益世间故说。",
  },
  {
    id: "t0262-002-037",
    category: "聞者不退",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若有聞者 隨喜頂受 當知是人 阿惟越致",
    anchorText: "若有聞者 隨喜頂受",
    note: "偈中明说闻者随喜顶受，当知为阿惟越致。",
  },
  {
    id: "t0262-002-038",
    category: "信受宿緣",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若有信受 此經法者 是人已曾 見過去佛 恭敬供養 亦聞是法",
    anchorText: "若有信受 此經法者",
    note: "经文说明信受此经法者，已曾见过去佛、恭敬供养并闻此法。",
  },
  {
    id: "t0262-002-039",
    category: "信即見佛",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若人有能 信汝所說 則為見我 亦見於汝 及比丘僧 并諸菩薩",
    anchorText: "若人有能 信汝所說",
    note: "佛说能信舍利弗所说，即为见佛及僧、菩萨众。",
  },
  {
    id: "t0262-002-040",
    category: "以信得入",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "汝舍利弗 尚於此經 以信得入 況餘聲聞 其餘聲聞 信佛語故 隨順此經 非己智分",
    anchorText: "尚於此經 以信得入",
    note: "经文以舍利弗尚以信得入，说明此经深妙，声闻随顺须依信佛语。",
  },
  {
    id: "t0262-002-041",
    category: "謗經果報",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若人不信 毀謗此經 則斷一切 世間佛種",
    anchorText: "若人不信 毀謗此經",
    note: "本品也以反面果报警策：不信毁谤此经，会断世间佛种。",
  },
  {
    id: "t0262-002-042",
    category: "擇機宣說",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若有利根 智慧明了 多聞強識 求佛道者 如是之人 乃可為說",
    anchorText: "若有利根 智慧明了",
    note: "经文劝择利根、智慧明了、多闻强识、求佛道者宣说。",
  },
  {
    id: "t0262-002-043",
    category: "善根信解",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若人曾見 億百千佛 植諸善本 深心堅固 如是之人 乃可為說",
    anchorText: "若人曾見 億百千佛",
    note: "此句说明曾见诸佛、植诸善本、深心坚固者堪闻此经。",
  },
  {
    id: "t0262-002-044",
    category: "求經頂受",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若有比丘 為一切智 四方求法 合掌頂受 但樂受持 大乘經典 乃至不受 餘經一偈 如是之人 乃可為說",
    anchorText: "為一切智 四方求法 合掌頂受",
    note: "经文赞许为一切智四方求法、合掌顶受、乐受持大乘经典者。",
  },
  {
    id: "t0262-002-045",
    category: "能信解者",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "如是等人 則能信解 汝當為說 妙法華經",
    anchorText: "如是等人 則能信解",
    note: "品末总结具足相应根机者能信解，佛嘱当为其说妙法华经。",
  },
];