import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const SHOUJI_SECTION_TITLE = "授記品第六";

export const T0262_JUAN_4_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0262-004-001",
    category: "授記作佛",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "我此弟子摩訶迦葉。於未來世當得奉覲三百萬億諸佛世尊。供養恭敬尊重讚歎。廣宣諸佛無量大法。於最後身得成為佛。",
    anchorText: "我此弟子摩訶迦葉。於未來世當得奉覲",
    note: "佛為摩訶迦葉授記，明示供養諸佛、廣宣大法，最後身成佛。",
  },
  {
    id: "t0262-004-002",
    category: "淨修梵行",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "為佛智慧 淨修梵行 供養最上 二足尊已 修習一切 無上之慧 於最後身 得成為佛",
    anchorText: "為佛智慧 淨修梵行",
    note: "偈頌說迦葉為佛智慧淨修梵行、修習無上之慧而成佛。",
  },
  {
    id: "t0262-004-003",
    category: "佛土清淨",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "國界嚴飾。無諸穢惡瓦礫荊棘便利不淨。其土平正。無有高下坑坎堆阜。琉璃為地寶樹行列。黃金為繩以界道側。散諸寶華周遍清淨。",
    anchorText: "國界嚴飾。無諸穢惡瓦礫荊棘",
    note: "迦葉未來佛土清淨莊嚴，無諸穢惡，寶樹華香周遍。",
  },
  {
    id: "t0262-004-004",
    category: "護持佛法",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "其國菩薩無量千億。諸聲聞眾亦復無數。無有魔事。雖有魔及魔民。皆護佛法。",
    anchorText: "無有魔事。雖有魔及魔民",
    note: "光明如來國中菩薩、聲聞無數，魔及魔民皆護佛法。",
  },
  {
    id: "t0262-004-005",
    category: "授記安樂",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "若蒙佛授記 爾乃快安樂 大雄猛世尊 常欲安世間 願賜我等記 如饑須教食",
    anchorText: "若蒙佛授記 爾乃快安樂",
    note: "諸大弟子以偈請記，明說若蒙佛授記，即得快安樂。",
  },
  {
    id: "t0262-004-006",
    category: "授記作佛",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "是須菩提。於當來世。奉覲三百萬億那由他佛。供養恭敬尊重讚歎。常修梵行具菩薩道。於最後身得成為佛。",
    anchorText: "是須菩提。於當來世",
    note: "佛為須菩提授記，明示供養諸佛、常修梵行、具菩薩道而成佛。",
  },
  {
    id: "t0262-004-007",
    category: "說法度眾",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "其佛常處虛空為眾說法。度脫無量菩薩及聲聞眾。",
    anchorText: "其佛常處虛空為眾說法",
    note: "須菩提未來成佛後，常為眾說法，度脫無量菩薩與聲聞。",
  },
  {
    id: "t0262-004-008",
    category: "聽受佛語",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "皆當一心 聽我所說 我大弟子 須菩提者 當得作佛 號曰名相",
    anchorText: "皆當一心 聽我所說",
    note: "佛勸比丘眾一心聽受授記，須菩提當得作佛。",
  },
  {
    id: "t0262-004-009",
    category: "漸具大道",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "當供無數 萬億諸佛 隨佛所行 漸具大道 最後身得 三十二相 端正姝妙",
    anchorText: "當供無數 萬億諸佛",
    note: "偈頌說須菩提供養諸佛、隨佛所行，漸具大道而成就妙相。",
  },
  {
    id: "t0262-004-010",
    category: "轉不退輪",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "其佛法中 多諸菩薩 皆悉利根 轉不退輪 彼國常以 菩薩莊嚴",
    anchorText: "其佛法中 多諸菩薩",
    note: "名相如來佛法中多利根菩薩，能轉不退法輪。",
  },
  {
    id: "t0262-004-011",
    category: "三明六通",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "諸聲聞眾 不可稱數 皆得三明 具六神通 住八解脫 有大威德",
    anchorText: "皆得三明 具六神通",
    note: "須菩提未來佛土中聲聞不可稱數，皆得三明六通、住八解脫。",
  },
  {
    id: "t0262-004-012",
    category: "供養成佛",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "是大迦旃延。於當來世。以諸供具供養奉事八千億佛恭敬尊重。諸佛滅後。各起塔廟高千由旬。",
    anchorText: "是大迦旃延。於當來世",
    note: "佛為迦旃延授記，先說其未來供養奉事諸佛並起塔供養。",
  },
  {
    id: "t0262-004-013",
    category: "具菩薩道",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "供養是諸佛已。具菩薩道當得作佛。",
    anchorText: "供養是諸佛已。具菩薩道",
    note: "迦旃延供養諸佛後具菩薩道，當得作佛。",
  },
  {
    id: "t0262-004-014",
    category: "離惡莊嚴",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "妙華覆地周遍清淨。見者歡喜。無四惡道地獄餓鬼畜生阿修羅道。多有天人諸聲聞眾。及諸菩薩無量萬億。莊嚴其國。",
    anchorText: "妙華覆地周遍清淨。見者歡喜",
    note: "迦旃延未來佛土清淨歡喜，無四惡道，菩薩聲聞莊嚴其國。",
  },
  {
    id: "t0262-004-015",
    category: "得佛智慧",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "其最後身 得佛智慧 成等正覺 國土清淨 度脫無量 萬億眾生",
    anchorText: "其最後身 得佛智慧",
    note: "偈頌總攝迦旃延最後身得佛智慧、成等正覺，並度脫無量眾生。",
  },
  {
    id: "t0262-004-016",
    category: "奉持佛法",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "為佛道故 供養恭敬 於諸佛所 常修梵行 於無量劫 奉持佛法",
    anchorText: "為佛道故 供養恭敬",
    note: "目犍連授記偈中明說為佛道故供養恭敬，於無量劫奉持佛法。",
  },
  {
    id: "t0262-004-017",
    category: "具足菩薩道",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "漸漸具足 菩薩道已 於意樂國 而得作佛 號多摩羅 栴檀之香",
    anchorText: "漸漸具足 菩薩道已",
    note: "偈頌說目犍連漸具菩薩道後，於意樂國得作佛。",
  },
  {
    id: "t0262-004-018",
    category: "演說佛道",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "其佛壽命 二十四劫 常為天人 演說佛道 聲聞無量 如恒河沙",
    anchorText: "常為天人 演說佛道",
    note: "目犍連未來成佛後，常為天人演說佛道，聲聞眾無量。",
  },
  {
    id: "t0262-004-019",
    category: "佛智不退",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "菩薩無數 志固精進 於佛智慧 皆不退轉",
    anchorText: "菩薩無數 志固精進",
    note: "多摩羅栴檀香如來國中菩薩無數，志固精進，於佛智慧不退轉。",
  },
  {
    id: "t0262-004-020",
    category: "皆當成佛",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "我諸弟子 威德具足 其數五百 皆當授記 於未來世 咸得成佛",
    anchorText: "我諸弟子 威德具足",
    note: "品末總說五百威德具足弟子皆當授記，未來咸得成佛。",
  },
  {
    id: "t0262-004-021",
    category: "宿世因緣",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "我及汝等 宿世因緣 吾今當說 汝等善聽",
    anchorText: "我及汝等 宿世因緣",
    note: "本品結尾承接後續化城喻，提示佛將說宿世因緣，勸眾善聽。",
  },
];
