import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const HUACHENG_SECTION_TITLE = "化城喻品第七";

export const T0264_JUAN_3_HUACHENG_OPENING_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-003-118",
    category: "佛智通達",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "我以如來知見力故，觀彼久遠猶若今日。",
    anchorText: "我以如來知見力故，觀彼久遠猶若今日",
    note: "佛以如来知见力观照久远因缘，显示佛智通达无碍。",
    occurrence: 1,
  },
  {
    id: "t0264-003-119",
    category: "佛智通達",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "如來無礙智，知彼佛滅度，及聲聞菩薩，如見今滅度。諸比丘當知！佛智淨微妙，無漏無所礙，通達無量劫。",
    anchorText: "如來無礙智，知彼佛滅度",
    note: "偈颂赞佛智清净微妙、通达无量劫。",
    occurrence: 1,
  },
  {
    id: "t0264-003-120",
    category: "供養諸佛",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "時諸梵天王，雨眾天華，面百由旬，香風時來吹去萎華，更雨新者，如是不絕，滿十小劫供養於佛，乃至滅度，常雨此華。四王諸天為供養佛，常擊天鼓，其餘諸天作天伎樂，滿十小劫，至於滅度，亦復如是。",
    anchorText: "滿十小劫供養於佛",
    note: "诸天长时以天华、天鼓、伎乐供养大通智胜佛。",
    occurrence: 1,
  },
  {
    id: "t0264-003-121",
    category: "見佛善利",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "今者見世尊，安隱成佛道，我等得善利，稱慶大歡喜。",
    anchorText: "今者見世尊，安隱成佛道",
    note: "十六王子赞见佛成道为得善利，心生大欢喜。",
    occurrence: 1,
  },
  {
    id: "t0264-003-122",
    category: "佛出世利",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "眾生常苦惱，盲冥無導師，不識苦盡道，不知求解脫。長夜增惡趣，減損諸天眾，從冥入於冥，永不聞佛名。今佛得最上，安隱無漏道，我等及天人，為得最大利，是故咸稽首，歸命無上尊。",
    anchorText: "我等及天人，為得最大利",
    note: "王子偈以众生苦恼无导为背景，赞佛成道令天人得最大利。",
    occurrence: 1,
  },
  {
    id: "t0264-003-123",
    category: "請轉法輪",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "世尊說法多所安隱，憐愍饒益諸天人民。",
    anchorText: "世尊說法多所安隱",
    note: "十六王子请佛转法轮，明佛说法能多所安隐、饶益天人。",
    occurrence: 1,
  },
  {
    id: "t0264-003-124",
    category: "請轉法輪",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "得無上智慧，願為世間說，度脫於我等，及諸眾生類，為分別顯示，令得是智慧。",
    anchorText: "願為世間說，度脫於我等",
    note: "王子请佛为世间说法，令自己与众生得无上智慧。",
    occurrence: 1,
  },
  {
    id: "t0264-003-125",
    category: "瑞應照世",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "大通智勝佛，得阿耨多羅三藐三菩提時，十方各五百萬億諸佛世界，六種震動，其國中間幽冥之處，日月威光所不能照，而皆大明。",
    anchorText: "其國中間幽冥之處，日月威光所不能照，而皆大明",
    note: "大通智胜佛成道时，十方震动，幽冥皆明，显佛出世瑞应。",
    occurrence: 1,
  },
  {
    id: "t0264-003-126",
    category: "佛德救護",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "世尊甚希有，難可得值遇，具無量功德，能救護一切。天人之大師，哀愍於世間，十方諸眾生，普皆蒙饒益。",
    anchorText: "具無量功德，能救護一切",
    note: "梵天赞佛具无量功德，能救护一切，普令众生蒙益。",
    occurrence: 1,
  },
  {
    id: "t0264-003-127",
    category: "慈悲度苦",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "世雄兩足尊，唯願演說法，以大慈悲力，度苦惱眾生。",
    anchorText: "以大慈悲力，度苦惱眾生",
    note: "诸梵天请佛以大慈悲力说法，度苦恼众生。",
    occurrence: 1,
  },
  {
    id: "t0264-003-128",
    category: "佛出世利",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "世尊甚希有，久遠乃一現，一百八十劫，空過無有佛。三惡道充滿，諸天眾減少，今佛出於世，為眾生作眼。世間所歸趣，救護於一切，為眾生之父，哀愍饒益者；我等宿福慶，今得值世尊。",
    anchorText: "今佛出於世，為眾生作眼",
    note: "梵王赞佛久远难值，出世为众生作眼、救护一切。",
    occurrence: 1,
  },
  {
    id: "t0264-003-129",
    category: "聞法受益",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "大聖轉法輪，顯示諸法相，度苦惱眾生，令得大歡喜。眾生聞是法，得道若生天，諸惡道減少，忍善者增益。",
    anchorText: "眾生聞是法，得道若生天",
    note: "梵天请佛转法轮，明众生闻法得道或生天，恶道减少、忍善增长。",
    occurrence: 1,
  },
  {
    id: "t0264-003-130",
    category: "法雨充滿",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "諸飢渴眾生，以法雨充滿，昔所未曾覩，無量智慧者。",
    anchorText: "諸飢渴眾生，以法雨充滿",
    note: "梵天赞佛以法雨充满饥渴众生。",
    occurrence: 1,
  },
  {
    id: "t0264-003-131",
    category: "安隱度脫",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "唯願世尊，轉於法輪，令一切世間諸天魔梵沙門婆羅門，皆獲安隱而得度脫。",
    anchorText: "皆獲安隱而得度脫",
    note: "诸梵天请佛转法轮，愿一切世间皆获安隐而度脱。",
    occurrence: 1,
  },
  {
    id: "t0264-003-132",
    category: "廣度一切",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "善哉見諸佛，救世之聖尊，能於三界獄，勉出諸眾生，普智天人尊，哀愍群萌類，能開甘露門，廣度於一切。",
    anchorText: "能於三界獄，勉出諸眾生",
    note: "上方梵天赞佛能令众生出离三界牢狱，开甘露门广度一切。",
    occurrence: 1,
  },
  {
    id: "t0264-003-133",
    category: "回向成佛",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "願以此功德，普及於一切，我等與眾生，皆共成佛道。",
    anchorText: "願以此功德，普及於一切",
    note: "梵天以供佛功德普回向一切，共成佛道。",
    occurrence: 1,
  },
  {
    id: "t0264-003-134",
    category: "請轉法輪",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "世尊轉法輪，擊甘露法鼓，度苦惱眾生，開示涅槃道。",
    anchorText: "世尊轉法輪，擊甘露法鼓",
    note: "梵天请佛转法轮、击甘露法鼓，度苦恼众生。",
    occurrence: 1,
  },
  {
    id: "t0264-003-135",
    category: "聞法解脫",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "佛於天人大眾之中說是法時，六百萬億那由他人，以不受一切法故，而於諸漏心得解脫，皆得深妙禪定，三明、六通、具八解脫。",
    anchorText: "而於諸漏心得解脫，皆得深妙禪定",
    note: "大通智胜佛说法时，大众于诸漏心得解脱，并得禅定、三明六通等益。",
    occurrence: 1,
  },
  {
    id: "t0264-003-136",
    category: "受持法華",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "說是經已，十六沙彌，為阿耨多羅三藐三菩提故，皆共受持諷誦通利。",
    anchorText: "皆共受持諷誦通利",
    note: "十六沙弥为无上菩提，共同受持讽诵通利《妙法莲华经》。",
    occurrence: 1,
  },
  {
    id: "t0264-003-137",
    category: "示教利喜",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "是時十六菩薩沙彌，知佛入室寂然禪定，各昇法座，亦於八萬四千劫，為四部眾，廣說分別《妙法華經》，一一皆度六百萬億那由他恒河沙等眾生，示教利喜，令發阿耨多羅三藐三菩提心。",
    anchorText: "廣說分別《妙法華經》",
    note: "十六菩萨沙弥广说分别《妙法华经》，示教利喜，令众生发无上菩提心。",
    occurrence: 1,
  },
  {
    id: "t0264-003-138",
    category: "信受得慧",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "若聲聞、辟支佛及諸菩薩，能信是十六菩薩所說經法受持不毀者，是人皆當得阿耨多羅三藐三菩提如來之慧。",
    anchorText: "能信是十六菩薩所說經法受持不毀者",
    note: "佛赞十六菩萨沙弥所说经法，信受不毁者皆当得如来智慧。",
    occurrence: 1,
  },
];
