import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const XINJIE_SECTION_TITLE = "信解品第四";

export const T0264_JUAN_3_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-003-001",
    category: "聞法歡喜",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "從佛所聞未曾有法，世尊授舍利弗阿耨多羅三藐三菩提記，發希有心歡喜踊躍，",
    anchorText: "從佛所聞未曾有法，世尊授舍利弗",
    note: "四大声闻闻佛授记舍利弗，发希有心、欢喜踊跃。",
    occurrence: 1,
  },
  {
    id: "t0264-003-002",
    category: "聞記歡喜",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我等今於佛前聞授聲聞阿耨多羅三藐三菩提記，心甚歡喜得未曾有；",
    anchorText: "聞授聲聞阿耨多羅三藐三菩提記",
    note: "声闻闻到得授无上菩提记，心大欢喜，得未曾有。",
    occurrence: 1,
  },
  {
    id: "t0264-003-003",
    category: "獲大善利",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "不謂於今忽然得聞希有之法，深自慶幸獲大善利，無量珍寶不求自得。",
    anchorText: "深自慶幸獲大善利，無量珍寶不求自得",
    note: "经文以“无量珍宝不求自得”赞叹闻希有法所得大善利。",
    occurrence: 1,
  },
  {
    id: "t0264-003-004",
    category: "慈父念子",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "父每念子，與子離別五十餘年，而未曾向人說如此事，但自思惟心懷悔恨，自念老朽多有財物，金銀珍寶倉庫盈溢，無有子息，一旦終沒，財物散失無所委付，是以慇懃每憶其子；",
    anchorText: "是以慇懃每憶其子",
    note: "穷子譬喻中，父常忆念失散之子，喻如来念诸佛子、欲令承受法财。",
    occurrence: 1,
  },
  {
    id: "t0264-003-005",
    category: "付囑法財",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我若得子委付財物，坦然快樂無復憂慮。",
    anchorText: "我若得子委付財物",
    note: "长者欲将财物付子，喻如来欲令佛子领受如来知见宝藏。",
    occurrence: 1,
  },
  {
    id: "t0264-003-006",
    category: "方便攝受",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "父知其子志意下劣，自知豪貴為子所難，審知是子而以方便，不語他人云是我子。",
    anchorText: "審知是子而以方便",
    note: "长者知子志意下劣，故以方便渐次摄受，喻佛随根机引导。",
    occurrence: 1,
  },
  {
    id: "t0264-003-007",
    category: "方便近子",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "以方便故得近其子。",
    anchorText: "以方便故得近其子",
    note: "经文直接标明长者以方便得近其子，显如来方便化导之义。",
    occurrence: 1,
  },
  {
    id: "t0264-003-008",
    category: "安意無憂",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "諸有所須，瓫器米麵鹽酢之屬，莫自疑難，亦有老弊使人，須者相給好自安意，我如汝父勿復憂慮。",
    anchorText: "好自安意，我如汝父勿復憂慮",
    note: "长者以父子之意安慰穷子，喻如来以方便令众生渐得安稳。",
    occurrence: 1,
  },
  {
    id: "t0264-003-009",
    category: "漸生信解",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "於二十年中常令除糞，過是已後心相體信，入出無難，然其所止猶在本處。",
    anchorText: "過是已後心相體信，入出無難",
    note: "长者长期方便教养，使穷子渐生信任，喻众生渐次成熟。",
    occurrence: 1,
  },
  {
    id: "t0264-003-010",
    category: "領知寶藏",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我今多有金銀珍寶倉庫盈溢，其中多少所應取與，汝悉知之，我心如是當體此意。",
    anchorText: "其中多少所應取與，汝悉知之",
    note: "长者令穷子领知宝藏，喻佛渐令声闻知如来智慧法藏。",
    occurrence: 1,
  },
  {
    id: "t0264-003-011",
    category: "父子不異",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "今我與汝便為不異，宜加用心無令漏失。",
    anchorText: "今我與汝便為不異",
    note: "长者明示父子不异，喻众生本为佛子，终可承受法财。",
    occurrence: 1,
  },
  {
    id: "t0264-003-012",
    category: "財物子有",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "此實我子我實其父，今我所有一切財物，皆是子有，先所出內是子所知。",
    anchorText: "今我所有一切財物，皆是子有",
    note: "长者公开宣告财物皆属其子，喻如来法藏为佛子所应得。",
    occurrence: 1,
  },
  {
    id: "t0264-003-013",
    category: "寶藏自至",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "我本無心有所希求，今此寶藏自然而至。",
    anchorText: "今此寶藏自然而至",
    note: "穷子自觉宝藏不求自至，喻声闻闻法后知大乘法财自然现前。",
    occurrence: 1,
  },
  {
    id: "t0264-003-014",
    category: "佛子自知",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "大富長者則是如來，我等皆似佛子，如來常說我等為子。",
    anchorText: "我等皆似佛子，如來常說我等為子",
    note: "经文解释譬喻：大富长者即如来，声闻亦是佛子。",
    occurrence: 1,
  },
  {
    id: "t0264-003-015",
    category: "蠲除戲論",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "今日世尊，令我等思惟蠲除諸法戲論之糞，我等於中勤加精進，得至涅槃一日之價，",
    anchorText: "令我等思惟蠲除諸法戲論之糞",
    note: "声闻自述佛令其蠲除戏论、勤加精进，先得涅槃之益。",
    occurrence: 1,
  },
  {
    id: "t0264-003-016",
    category: "如來寶藏",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "汝等當有如來知見寶藏之分。",
    anchorText: "汝等當有如來知見寶藏之分",
    note: "佛知声闻终当有如来知见宝藏之分，显大乘利益。",
    occurrence: 1,
  },
  {
    id: "t0264-003-017",
    category: "方便說智",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "世尊以方便力說如來智慧，我等從佛得涅槃一日之價，以為大得，於此大乘無有志求，",
    anchorText: "世尊以方便力說如來智慧",
    note: "经文明说世尊以方便力宣说如来智慧，渐引声闻入大乘。",
    occurrence: 1,
  },
  {
    id: "t0264-003-018",
    category: "佛智無悋",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "今我等方知，世尊於佛智慧無所悋惜。",
    anchorText: "世尊於佛智慧無所悋惜",
    note: "声闻醒悟佛于佛智慧无所吝惜，显佛平等开示大乘。",
    occurrence: 1,
  },
  {
    id: "t0264-003-019",
    category: "唯說一乘",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "於此經中唯說一乘，而昔於菩薩前毀呰聲聞樂小法者，然佛實以大乘教化，",
    anchorText: "於此經中唯說一乘",
    note: "本品明示此经唯说一乘，佛实以大乘教化。",
    occurrence: 1,
  },
  {
    id: "t0264-003-020",
    category: "法王大寶",
    sectionTitle: XINJIE_SECTION_TITLE,
    text: "今法王大寶自然而至，如佛子所應得者皆已得之。",
    anchorText: "今法王大寶自然而至",
    note: "经文以法王大宝自然至，说明佛子所应得之大乘法财皆已获得。",
    occurrence: 1,
  },
];