import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const YAOCAOYU_SECTION_TITLE = "藥草喻品第五";

export const T0264_JUAN_3_YAOCAOYU_VERSE_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-003-056",
    category: "有智信解",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "破有法王，出現世間，隨眾生欲，種種說法。如來尊重，智慧深遠，久默斯要，不務速說；有智若聞，則能信解；無智疑悔，則為永失。",
    anchorText: "破有法王，出現世間",
    note: "偈颂开明如来随众生欲种种说法；有智慧者闻此深要，能够信解。",
    occurrence: 1,
  },
  {
    id: "t0264-003-057",
    category: "令得正見",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "是故迦葉！隨力為說，以種種緣，令得正見。",
    anchorText: "隨力為說，以種種緣",
    note: "佛随众生能力与因缘说法，目的在令其得正见。",
    occurrence: 1,
  },
  {
    id: "t0264-003-058",
    category: "法雨普潤",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "其雨普等，四方俱下，流澍無量，率土充洽；山川嶮谷，幽邃所生，卉木藥草，大小諸樹，百穀苗稼，甘蔗蒲桃，雨之所潤，無不豐足。",
    anchorText: "其雨普等，四方俱下",
    note: "大云普雨、万物丰足，譬喻法雨平等普润一切根机。",
    occurrence: 1,
  },
  {
    id: "t0264-003-059",
    category: "隨分增長",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "其雲所出，一味之水，草木叢林，隨分受潤，一切諸樹，上中下等，稱其大小，各得生長；根莖枝葉，華果光色，一雨所及，皆得鮮澤；如其體相，性分大小，所潤是一，而各滋茂。",
    anchorText: "其雲所出，一味之水",
    note: "同一法雨随各自分量受润增长，显示众生随根性各得其益。",
    occurrence: 1,
  },
  {
    id: "t0264-003-060",
    category: "離苦安樂",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "佛亦如是，出現於世，譬如大雲，普覆一切；既出于世，為諸眾生，分別演說，諸法之實；大聖世尊，於諸天人，一切眾中，而宣是言：「我為如來，兩足之尊，出于世間，猶如大雲，充潤一切，枯槁眾生，皆令離苦，得安隱樂；",
    anchorText: "枯槁眾生，皆令離苦",
    note: "偈颂明说佛如大云出世，演说诸法之实，令枯槁众生离苦得安隐乐。",
    occurrence: 1,
  },
  {
    id: "t0264-003-061",
    category: "甘露淨法",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "我為世尊，無能及者，安隱眾生，故現於世，為大眾說，甘露淨法，其法一味，解脫涅槃。",
    anchorText: "安隱眾生，故現於世",
    note: "佛为安隐众生而现世，说一味甘露净法，指向解脱涅槃。",
    occurrence: 1,
  },
  {
    id: "t0264-003-062",
    category: "平等說法",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "我觀一切，普皆平等，無有彼此，愛憎之心。我無貪著，亦無限礙，恒為一切，平等說法。如為一人，眾多亦然，常演說法，曾無他事。",
    anchorText: "恒為一切，平等說法",
    note: "佛以平等心无彼此爱憎，为一切众生平等说法。",
    occurrence: 1,
  },
  {
    id: "t0264-003-063",
    category: "等雨法雨",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "貴賤上下，持戒毀戒，威儀具足，及不具足，正見邪見，利根鈍根，等雨法雨，而無懈惓。",
    anchorText: "貴賤上下，持戒毀戒",
    note: "偈颂列举贵贱、持毁、正邪、利钝，说明佛法雨平等不倦。",
    occurrence: 1,
  },
  {
    id: "t0264-003-064",
    category: "聞法得益",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "一切眾生，聞我法者，隨力所受，住於諸地，或處人天，轉輪聖王，釋梵諸天，是小藥草；知無漏法，能得涅槃，起六神通，及得三明，獨處山林，常行禪定，得緣覺證，是中藥草；求世尊處，我當作佛，行精進定，是上藥草。",
    anchorText: "一切眾生，聞我法者",
    note: "闻法者随力所受，或住人天、或证无漏涅槃、或发愿作佛，显示不同根机各得利益。",
    occurrence: 1,
  },
  {
    id: "t0264-003-065",
    category: "佛子不退",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "又諸佛子，專心佛道，常行慈悲，自知作佛，決定無疑，是名小樹；安住神通，轉不退輪，度無量億，百千眾生，如是菩薩，名為大樹。",
    anchorText: "專心佛道，常行慈悲",
    note: "专心佛道、常行慈悲者自知作佛；安住神通、转不退轮者能度无量众生。",
    occurrence: 1,
  },
  {
    id: "t0264-003-066",
    category: "方便開示",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "佛平等說，如一味雨，隨眾生性，所受不同，如彼草木，所稟各異；佛以此喻，方便開示，種種言辭，演說一法；於佛智慧，如海一渧。",
    anchorText: "佛平等說，如一味雨",
    note: "佛以一味法雨平等而说，又随众生性方便开示一法。",
    occurrence: 1,
  },
  {
    id: "t0264-003-067",
    category: "皆得道果",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "諸佛之法，常以一味，令諸世間，普得具足，漸次修行，皆得道果；",
    anchorText: "令諸世間，普得具足",
    note: "诸佛之法一味，令世间普得具足，渐次修行皆得道果。",
    occurrence: 1,
  },
  {
    id: "t0264-003-068",
    category: "聞法得果",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "聲聞緣覺，處於山林，住最後身，聞法得果；是名藥草，各得增長。",
    anchorText: "住最後身，聞法得果",
    note: "声闻缘觉闻法得果，各得增长，明示闻法所得受益。",
    occurrence: 1,
  },
  {
    id: "t0264-003-069",
    category: "菩薩增長",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "若諸菩薩，智慧堅固，了達三界，求最上乘，是名小樹，而得增長。復有住禪，得神通力，聞諸法空，心大歡喜；放無數光，度諸眾生，是名大樹，而得增長。",
    anchorText: "若諸菩薩，智慧堅固",
    note: "菩萨智慧坚固、求最上乘而增长；闻诸法空生大欢喜，并以光明度诸众生。",
    occurrence: 1,
  },
  {
    id: "t0264-003-070",
    category: "各得成實",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "如是迦葉！佛所說法，譬如大雲，以一味雨，潤於人華，各得成實。",
    anchorText: "佛所說法，譬如大雲",
    note: "佛所说法如大云一味雨，润益人华，各得成实。",
    occurrence: 1,
  },
  {
    id: "t0264-003-071",
    category: "開示佛道",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "迦葉當知！以諸因緣，種種譬喻，開示佛道，是我方便，諸佛亦然。",
    anchorText: "種種譬喻，開示佛道",
    note: "佛以因缘和种种譬喻开示佛道，说明方便说法的真实用意。",
    occurrence: 1,
  },
  {
    id: "t0264-003-072",
    category: "悉當成佛",
    sectionTitle: YAOCAOYU_SECTION_TITLE,
    text: "今為汝等，說最實事；諸聲聞眾，皆非滅度。汝等所行，是菩薩道，漸漸修學，悉當成佛。",
    anchorText: "汝等所行，是菩薩道",
    note: "佛明说声闻众并非究竟灭度，其所行是菩萨道，渐渐修学悉当成佛。",
    occurrence: 1,
  },
];
