import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const QUANCHI_SECTION_TITLE = "勸持品第十二";

export const T0264_JUAN_4_QUANCHI_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-004-103",
    category: "奉持不惜身命",
    sectionTitle: QUANCHI_SECTION_TITLE,
    text: "唯願世尊，不以為慮，我等於佛滅後，當奉持、讀誦說此經典，後惡世眾生善根轉少，多增上慢，貪利供養，增不善根，遠離解脫，雖難可教化，我等當起大忍力，讀誦此經，持說、書寫，種種供養，不惜身命。",
    anchorText: "我等於佛滅後，當奉持、讀誦說此經典",
    note: "药王、大乐说等菩萨发愿于佛灭后奉持读诵、持说书写并供养此经。",
  },
  {
    id: "t0264-004-104",
    category: "广说此经",
    sectionTitle: QUANCHI_SECTION_TITLE,
    text: "世尊！我等亦自誓願，於異國土廣說此經。",
    anchorText: "於異國土廣說此經",
    note: "得授记的五百阿罗汉亦发愿在异国土广说此经。",
  },
  {
    id: "t0264-004-105",
    category: "他土弘经",
    sectionTitle: QUANCHI_SECTION_TITLE,
    text: "世尊！我等亦當於他國土廣說此經。所以者何？是娑婆國中，人多弊惡，懷增上慢，功德淺薄，瞋濁諂曲，心不實故。",
    anchorText: "我等亦當於他國土廣說此經",
    note: "八千学无学人在佛前发愿于他国土广说此经。",
  },
  {
    id: "t0264-004-106",
    category: "授记法师",
    sectionTitle: QUANCHI_SECTION_TITLE,
    text: "憍曇彌！我先總說一切聲聞皆已授記，今汝欲知記者，將來之世，當於六萬八千億諸佛法中，為大法師，及六千學、無學比丘尼，俱為法師，如是漸漸具菩薩道，當得作佛，號一切眾生憙見如來、應供、正遍知、明行足、善逝、世間解、無上士、調御丈夫、天人師、佛、世尊。",
    anchorText: "將來之世，當於六萬八千億諸佛法中，為大法師",
    note: "摩诃波阇波提及六千比丘尼获授记，将为大法师并渐具菩萨道成佛。",
  },
  {
    id: "t0264-004-107",
    category: "渐具佛道",
    sectionTitle: QUANCHI_SECTION_TITLE,
    text: "汝於來世百千萬億諸佛法中，修菩薩行，為大法師，漸具佛道，於善國中，當得作佛，號具足千萬光相如來、應供、正遍知、明行足、善逝、世間解、無上士、調御丈夫、天人師、佛、世尊，佛壽無量阿僧祇劫。",
    anchorText: "修菩薩行，為大法師，漸具佛道",
    note: "耶输陀罗比丘尼得佛授记，将修菩萨行、为大法师而成佛。",
  },
  {
    id: "t0264-004-108",
    category: "闻记欢喜",
    sectionTitle: QUANCHI_SECTION_TITLE,
    text: "爾時摩訶波闍波提比丘尼，及耶輸陀羅比丘尼，并其眷屬，皆大歡喜得未曾有，即於佛前，而說偈言：「世尊導師！安隱天人，我等聞記，心安具足。」",
    anchorText: "我等聞記，心安具足",
    note: "比丘尼众闻佛授记，生大欢喜并心安具足。",
  },
  {
    id: "t0264-004-109",
    category: "比丘尼弘经",
    sectionTitle: QUANCHI_SECTION_TITLE,
    text: "諸比丘尼說是偈已，白佛言：「世尊！我等亦於他方國土廣說斯經。」",
    anchorText: "我等亦於他方國土廣說斯經",
    note: "比丘尼众亦在佛前发愿到他方国土广说此经。",
  },
  {
    id: "t0264-004-110",
    category: "令众受持",
    sectionTitle: QUANCHI_SECTION_TITLE,
    text: "世尊！我等於如來滅後，周旋往返十方世界，能令眾生書寫此經，受持、讀誦、解說其義，如法修行，正憶念皆是佛之威力。唯願世尊！在於他方遙見守護。",
    anchorText: "能令眾生書寫此經，受持、讀誦、解說其義",
    note: "诸菩萨发愿灭后周旋十方，令众生书写、受持、读诵、解说并如法修行此经。",
  },
  {
    id: "t0264-004-111",
    category: "恶世广说",
    sectionTitle: QUANCHI_SECTION_TITLE,
    text: "唯願不為慮，於佛滅度後，恐怖惡世中，我等當廣說。有諸無智人，惡口罵詈等，及加刀杖者，我等皆當忍。",
    anchorText: "恐怖惡世中，我等當廣說",
    note: "诸菩萨誓于恐怖恶世中广说此经，并忍受恶口刀杖等难。",
  },
  {
    id: "t0264-004-112",
    category: "忍辱护经",
    sectionTitle: QUANCHI_SECTION_TITLE,
    text: "我等敬佛故，悉忍是諸惡；為斯所輕言，汝等皆是佛，如此輕慢言，皆當忍受之。",
    anchorText: "我等敬佛故，悉忍是諸惡",
    note: "为敬佛与护经，诸菩萨发愿忍受轻慢毁辱。",
  },
  {
    id: "t0264-004-113",
    category: "忍辱铠甲",
    sectionTitle: QUANCHI_SECTION_TITLE,
    text: "濁劫惡世中，多有諸恐怖，惡鬼入其身，罵詈毀辱我，我等敬信佛，當著忍辱鎧。",
    anchorText: "我等敬信佛，當著忍辱鎧",
    note: "浊劫恶世多恐怖毁辱，护经者以敬信佛故披忍辱铠。",
  },
  {
    id: "t0264-004-114",
    category: "护持佛嘱",
    sectionTitle: QUANCHI_SECTION_TITLE,
    text: "為說是經故，忍此諸難事，我不愛身命，但惜無上道；我等於來世，護持佛所囑。",
    anchorText: "我不愛身命，但惜無上道",
    note: "诸菩萨为说此经，宁忍诸难、不爱身命而护持佛所付嘱。",
  },
  {
    id: "t0264-004-115",
    category: "求法即说",
    sectionTitle: QUANCHI_SECTION_TITLE,
    text: "諸聚落城邑，其有求法者，我皆到其所，說佛所囑法。我是世尊使，處眾無所畏，我當善說法，願佛安隱住。",
    anchorText: "其有求法者，我皆到其所",
    note: "凡有求法者，菩萨愿往其处宣说佛所付嘱之法，处众无畏。",
  },
  {
    id: "t0264-004-116",
    category: "佛知誓心",
    sectionTitle: QUANCHI_SECTION_TITLE,
    text: "我於世尊前，諸來十方佛，發如是誓言，佛悉知我心。",
    anchorText: "發如是誓言，佛悉知我心",
    note: "诸菩萨在世尊与十方诸佛前立弘经誓愿，愿佛悉知其心。",
  },
];
