import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const SHOUJI_SECTION_TITLE = "授記品第六";
const HUACHENG_SECTION_TITLE = "化城喻品第七";

export const T0262_JUAN_4_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0262-004-001",
    category: "授記作佛",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "我此弟子摩訶迦葉。於未來世當得奉覲三百萬億諸佛世尊。供養恭敬尊重讚歎。廣宣諸佛無量大法。於最後身得成為佛。",
    anchorText: "我此弟子摩訶迦葉。於未來世當得奉覲",
    note: "佛為摩訶迦葉授記，明示供養諸佛、廣宣大法，最後身成佛。",
  },
  {
    id: "t0262-004-002",
    category: "淨修梵行",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "為佛智慧 淨修梵行 供養最上 二足尊已 修習一切 無上之慧 於最後身 得成為佛",
    anchorText: "為佛智慧 淨修梵行",
    note: "偈頌說迦葉為佛智慧淨修梵行、修習無上之慧而成佛。",
  },
  {
    id: "t0262-004-003",
    category: "佛土清淨",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "國界嚴飾。無諸穢惡瓦礫荊棘便利不淨。其土平正。無有高下坑坎堆阜。琉璃為地寶樹行列。黃金為繩以界道側。散諸寶華周遍清淨。",
    anchorText: "國界嚴飾。無諸穢惡瓦礫荊棘",
    note: "迦葉未來佛土清淨莊嚴，無諸穢惡，寶樹華香周遍。",
  },
  {
    id: "t0262-004-004",
    category: "護持佛法",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "其國菩薩無量千億。諸聲聞眾亦復無數。無有魔事。雖有魔及魔民。皆護佛法。",
    anchorText: "無有魔事。雖有魔及魔民",
    note: "光明如來國中菩薩、聲聞無數，魔及魔民皆護佛法。",
  },
  {
    id: "t0262-004-005",
    category: "授記安樂",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "若蒙佛授記 爾乃快安樂 大雄猛世尊 常欲安世間 願賜我等記 如饑須教食",
    anchorText: "若蒙佛授記 爾乃快安樂",
    note: "諸大弟子以偈請記，明說若蒙佛授記，即得快安樂。",
  },
  {
    id: "t0262-004-006",
    category: "授記作佛",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "是須菩提。於當來世。奉覲三百萬億那由他佛。供養恭敬尊重讚歎。常修梵行具菩薩道。於最後身得成為佛。",
    anchorText: "是須菩提。於當來世",
    note: "佛為須菩提授記，明示供養諸佛、常修梵行、具菩薩道而成佛。",
  },
  {
    id: "t0262-004-007",
    category: "說法度眾",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "其佛常處虛空為眾說法。度脫無量菩薩及聲聞眾。",
    anchorText: "其佛常處虛空為眾說法",
    note: "須菩提未來成佛後，常為眾說法，度脫無量菩薩與聲聞。",
  },
  {
    id: "t0262-004-008",
    category: "聽受佛語",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "皆當一心 聽我所說 我大弟子 須菩提者 當得作佛 號曰名相",
    anchorText: "皆當一心 聽我所說",
    note: "佛勸比丘眾一心聽受授記，須菩提當得作佛。",
  },
  {
    id: "t0262-004-009",
    category: "漸具大道",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "當供無數 萬億諸佛 隨佛所行 漸具大道 最後身得 三十二相 端正姝妙",
    anchorText: "當供無數 萬億諸佛",
    note: "偈頌說須菩提供養諸佛、隨佛所行，漸具大道而成就妙相。",
  },
  {
    id: "t0262-004-010",
    category: "轉不退輪",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "其佛法中 多諸菩薩 皆悉利根 轉不退輪 彼國常以 菩薩莊嚴",
    anchorText: "其佛法中 多諸菩薩",
    note: "名相如來佛法中多利根菩薩，能轉不退法輪。",
  },
  {
    id: "t0262-004-011",
    category: "三明六通",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "諸聲聞眾 不可稱數 皆得三明 具六神通 住八解脫 有大威德",
    anchorText: "皆得三明 具六神通",
    note: "須菩提未來佛土中聲聞不可稱數，皆得三明六通、住八解脫。",
  },
  {
    id: "t0262-004-012",
    category: "供養成佛",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "是大迦旃延。於當來世。以諸供具供養奉事八千億佛恭敬尊重。諸佛滅後。各起塔廟高千由旬。",
    anchorText: "是大迦旃延。於當來世",
    note: "佛為迦旃延授記，先說其未來供養奉事諸佛並起塔供養。",
  },
  {
    id: "t0262-004-013",
    category: "具菩薩道",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "供養是諸佛已。具菩薩道當得作佛。",
    anchorText: "供養是諸佛已。具菩薩道",
    note: "迦旃延供養諸佛後具菩薩道，當得作佛。",
  },
  {
    id: "t0262-004-014",
    category: "離惡莊嚴",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "妙華覆地周遍清淨。見者歡喜。無四惡道地獄餓鬼畜生阿修羅道。多有天人諸聲聞眾。及諸菩薩無量萬億。莊嚴其國。",
    anchorText: "妙華覆地周遍清淨。見者歡喜",
    note: "迦旃延未來佛土清淨歡喜，無四惡道，菩薩聲聞莊嚴其國。",
  },
  {
    id: "t0262-004-015",
    category: "得佛智慧",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "其最後身 得佛智慧 成等正覺 國土清淨 度脫無量 萬億眾生",
    anchorText: "其最後身 得佛智慧",
    note: "偈頌總攝迦旃延最後身得佛智慧、成等正覺，並度脫無量眾生。",
  },
  {
    id: "t0262-004-016",
    category: "奉持佛法",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "為佛道故 供養恭敬 於諸佛所 常修梵行 於無量劫 奉持佛法",
    anchorText: "為佛道故 供養恭敬",
    note: "目犍連授記偈中明說為佛道故供養恭敬，於無量劫奉持佛法。",
  },
  {
    id: "t0262-004-017",
    category: "具足菩薩道",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "漸漸具足 菩薩道已 於意樂國 而得作佛 號多摩羅 栴檀之香",
    anchorText: "漸漸具足 菩薩道已",
    note: "偈頌說目犍連漸具菩薩道後，於意樂國得作佛。",
  },
  {
    id: "t0262-004-018",
    category: "演說佛道",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "其佛壽命 二十四劫 常為天人 演說佛道 聲聞無量 如恒河沙",
    anchorText: "常為天人 演說佛道",
    note: "目犍連未來成佛後，常為天人演說佛道，聲聞眾無量。",
  },
  {
    id: "t0262-004-019",
    category: "佛智不退",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "菩薩無數 志固精進 於佛智慧 皆不退轉",
    anchorText: "菩薩無數 志固精進",
    note: "多摩羅栴檀香如來國中菩薩無數，志固精進，於佛智慧不退轉。",
  },
  {
    id: "t0262-004-020",
    category: "皆當成佛",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "我諸弟子 威德具足 其數五百 皆當授記 於未來世 咸得成佛",
    anchorText: "我諸弟子 威德具足",
    note: "品末總說五百威德具足弟子皆當授記，未來咸得成佛。",
  },
  {
    id: "t0262-004-021",
    category: "宿世因緣",
    sectionTitle: SHOUJI_SECTION_TITLE,
    text: "我及汝等 宿世因緣 吾今當說 汝等善聽",
    anchorText: "我及汝等 宿世因緣",
    note: "本品結尾承接後續化城喻，提示佛將說宿世因緣，勸眾善聽。",
  },
  {
    id: "t0262-004-022",
    category: "佛智久遠",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "我以如來知見力故。觀彼久遠猶若今日。",
    anchorText: "我以如來知見力故。觀彼久遠猶若今日",
    note: "本品開示如來知見能觀久遠劫事，如在今日。",
  },
  {
    id: "t0262-004-023",
    category: "佛智通達",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "諸比丘當知 佛智淨微妙 無漏無所礙 通達無量劫",
    anchorText: "諸比丘當知 佛智淨微妙",
    note: "偈頌總讚佛智清淨微妙、無漏無礙，通達無量劫。",
  },
  {
    id: "t0262-004-024",
    category: "供養成道",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "如是不絕。滿十小劫供養於佛。乃至滅度。常雨此華。四王諸天為供養佛。常擊天鼓。其餘諸天作天伎樂。滿十小劫。至於滅度。亦復如是。",
    anchorText: "滿十小劫供養於佛。乃至滅度",
    note: "諸天長時以天華、天鼓、伎樂供養大通智勝佛，顯佛成道之稀有莊嚴。",
  },
  {
    id: "t0262-004-025",
    category: "安隱成佛",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "究竟永寂滅 安住無漏法 今者見世尊 安隱成佛道",
    anchorText: "究竟永寂滅 安住無漏法",
    note: "十六王子讚佛究竟寂滅、安住無漏法，安隱成就佛道。",
  },
  {
    id: "t0262-004-026",
    category: "得善大利",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "我等得善利 稱慶大歡喜 眾生常苦惱 盲瞑無導師",
    anchorText: "我等得善利 稱慶大歡喜",
    note: "見佛成道，眾生得善利而大歡喜，因苦惱眾生得遇導師。",
  },
  {
    id: "t0262-004-027",
    category: "最大利益",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "今佛得最上 安隱無漏道 我等及天人 為得最大利",
    anchorText: "今佛得最上 安隱無漏道",
    note: "偈中明說佛得最上安隱無漏道，是天人所得最大利益。",
  },
  {
    id: "t0262-004-028",
    category: "請轉法輪",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "世尊說法。多所安隱。憐愍饒益諸天人民。",
    anchorText: "世尊說法。多所安隱",
    note: "十六王子請佛說法，直指說法能多所安隱、饒益天人。",
  },
  {
    id: "t0262-004-029",
    category: "聞法得智",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "度脫於我等 及諸眾生類 為分別顯示 令得是智慧",
    anchorText: "度脫於我等 及諸眾生類",
    note: "請佛分別顯示正法，使眾生得智慧、得度脫。",
  },
  {
    id: "t0262-004-030",
    category: "救護饒益",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "世尊甚希有 難可得值遇 具無量功德 能救護一切",
    anchorText: "世尊甚希有 難可得值遇",
    note: "梵天王讚佛難值難遇，具無量功德，能救護一切。",
  },
  {
    id: "t0262-004-031",
    category: "蒙佛饒益",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "天人之大師 哀愍於世間 十方諸眾生 普皆蒙饒益",
    anchorText: "天人之大師 哀愍於世間",
    note: "讚佛為天人之師，哀愍世間，十方眾生普蒙饒益。",
  },
  {
    id: "t0262-004-032",
    category: "度苦開道",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "惟願世尊。轉於法輪。度脫眾生。開涅槃道。",
    anchorText: "轉於法輪。度脫眾生。開涅槃道",
    note: "諸梵請佛轉法輪，願眾生得度脫、開涅槃道。",
  },
  {
    id: "t0262-004-033",
    category: "聞法得益",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "眾生聞此法 得道若生天 諸惡道減少 忍善者增益",
    anchorText: "眾生聞此法 得道若生天",
    note: "經文明說眾生聞法後，或得道、或生天，惡道減少、忍善增益。",
  },
  {
    id: "t0262-004-034",
    category: "安隱度脫",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "惟願世尊轉於法輪。令一切世間諸天魔梵。沙門婆羅門。皆獲安隱。而得度脫。",
    anchorText: "令一切世間諸天魔梵",
    note: "諸梵請佛轉法輪，使一切世間皆獲安隱、得度脫。",
  },
  {
    id: "t0262-004-035",
    category: "法雨度生",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "普雨大法雨 度無量眾生 我等咸歸請 當演深遠音",
    anchorText: "普雨大法雨 度無量眾生",
    note: "以大法雨喻佛說法，能度無量眾生。",
  },
  {
    id: "t0262-004-036",
    category: "甘露法門",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "普智天人尊 哀愍群萌類 能開甘露門 廣度於一切",
    anchorText: "能開甘露門 廣度於一切",
    note: "讚佛哀愍眾生，能開甘露法門，廣度一切。",
  },
  {
    id: "t0262-004-037",
    category: "回向成佛",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "願以此功德 普及於一切 我等與眾生 皆共成佛道",
    anchorText: "願以此功德 普及於一切",
    note: "諸梵以供佛功德普回向一切，願自他皆共成佛道。",
  },
  {
    id: "t0262-004-038",
    category: "甘露法鼓",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "世尊轉法輪 擊甘露法鼓 度苦惱眾生 開示涅槃道",
    anchorText: "世尊轉法輪 擊甘露法鼓",
    note: "偈請佛轉法輪，擊甘露法鼓，度苦惱眾生並開示涅槃道。",
  },
  {
    id: "t0262-004-039",
    category: "說法解脫",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "佛於天人大眾之中說是法時。六百萬億那由他人。以不受一切法故。而於諸漏心得解脫。皆得深妙禪定。三明六通。具八解脫。",
    anchorText: "佛於天人大眾之中說是法時",
    note: "大通智勝佛說法時，無量人心得解脫，得禪定、三明六通與八解脫。",
  },
  {
    id: "t0262-004-040",
    category: "聞已修學",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "世尊亦當為我等說阿耨多羅三藐三菩提法。我等聞已。皆共修學。",
    anchorText: "世尊亦當為我等說阿耨多羅三藐三菩提法",
    note: "十六王子請佛說無上菩提法，發願聞已共同修學。",
  },
  {
    id: "t0262-004-041",
    category: "受持法華",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "說是經已。十六沙彌。為阿耨多羅三藐三菩提故。皆共受持諷誦通利。",
    anchorText: "說是經已。十六沙彌",
    note: "大通智勝佛說《妙法蓮華經》後，十六沙彌為無上菩提受持諷誦通利。",
  },
  {
    id: "t0262-004-042",
    category: "信受法華",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "說是經時。十六菩薩沙彌。皆悉信受。聲聞眾中。亦有信解。",
    anchorText: "說是經時。十六菩薩沙彌",
    note: "說《法華經》時，十六菩薩沙彌悉皆信受，聲聞眾亦有信解。",
  },
  {
    id: "t0262-004-043",
    category: "弘法利生",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "各升法座。亦於八萬四千劫。為四部眾。廣說分別妙法華經。一一皆度六百萬億那由他恆河沙等眾生。示教利喜。令發阿耨多羅三藐三菩提心。",
    anchorText: "為四部眾。廣說分別妙法華經",
    note: "十六菩薩沙彌長時廣說分別《妙法華經》，度眾無量，示教利喜，令發菩提心。",
  },
  {
    id: "t0262-004-044",
    category: "親近供養",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "汝等皆當數數親近而供養之。",
    anchorText: "汝等皆當數數親近而供養之",
    note: "佛勸大眾數數親近供養十六菩薩沙彌。",
  },
  {
    id: "t0262-004-045",
    category: "受持不毀",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "若聲聞辟支佛及諸菩薩。能信是十六菩薩所說經法。受持不毀者。是人皆當得阿耨多羅三藐三菩提如來之慧。",
    anchorText: "能信是十六菩薩所說經法",
    note: "經文明說，能信十六菩薩所說經法並受持不毀者，皆當得如來智慧。",
  },
  {
    id: "t0262-004-046",
    category: "聞法信解",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "世世所生與菩薩俱。從其聞法。悉皆信解。以此因緣。得值四萬億諸佛世尊。於今不盡。",
    anchorText: "世世所生與菩薩俱",
    note: "所化眾生世世與菩薩俱生，聞法信解，因而得值無量諸佛。",
  },
  {
    id: "t0262-004-047",
    category: "漸入佛道",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "我常教化阿耨多羅三藐三菩提。是諸人等。應以是法漸入佛道。所以者何。如來智慧。難信難解。",
    anchorText: "應以是法漸入佛道",
    note: "佛說對住聲聞地者，仍常教化無上菩提，使以此法漸入佛道。",
  },
  {
    id: "t0262-004-048",
    category: "得聞是經",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "是人雖生滅度之想。入於涅槃。而於彼土求佛智慧。得聞是經。唯以佛乘而得滅度。更無餘乘。",
    anchorText: "而於彼土求佛智慧。得聞是經",
    note: "即使先生滅度想，於彼土求佛智慧時仍得聞此經，歸於唯一佛乘。",
  },
  {
    id: "t0262-004-049",
    category: "唯一佛乘",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "世間無有二乘而得滅度。唯一佛乘得滅度耳。",
    anchorText: "世間無有二乘而得滅度",
    note: "本品明示究竟滅度唯在一佛乘。",
  },
  {
    id: "t0262-004-050",
    category: "方便信受",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "比丘當知。如來方便。深入眾生之性。知其志樂小法。深著五欲。為是等故。說於涅槃。是人若聞。則便信受。",
    anchorText: "如來方便。深入眾生之性",
    note: "如來知眾生根性，以方便說涅槃，使其聞已信受。",
  },
  {
    id: "t0262-004-051",
    category: "化城安隱",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "告眾人言。汝等勿怖。莫得退還。今此大城。可於中止。隨意所作。若入是城。快得安隱。若能前至寶所。亦可得去。",
    anchorText: "汝等勿怖。莫得退還",
    note: "化城譬喻中，導師以方便令疲極眾人暫得安隱，不退還於寶所。",
  },
  {
    id: "t0262-004-052",
    category: "免難安隱",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "我等今者免斯惡道。快得安隱。",
    anchorText: "我等今者免斯惡道",
    note: "眾人入化城後，明說免離惡道、快得安隱。",
  },
  {
    id: "t0262-004-053",
    category: "引至寶所",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "汝等去來。寶處在近。向者大城。我所化作。為止息耳。",
    anchorText: "汝等去來。寶處在近",
    note: "導師滅化城，指出寶處在近，顯方便止息後仍應前進。",
  },
  {
    id: "t0262-004-054",
    category: "佛為導師",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "諸比丘。如來亦復如是。今為汝等作大導師。知諸生死煩惱惡道險難長遠。應去應度。",
    anchorText: "如來亦復如是。今為汝等作大導師",
    note: "佛以大導師自喻，知生死煩惱惡道險難長遠，應令眾生度脫。",
  },
  {
    id: "t0262-004-055",
    category: "方便止息",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "佛知是心怯弱下劣。以方便力。而於中道為止息故。說二涅槃。",
    anchorText: "以方便力。而於中道為止息故",
    note: "如來因知眾生怯弱，以方便於中道說二涅槃，令得止息。",
  },
  {
    id: "t0262-004-056",
    category: "近於佛慧",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "汝等所作未辦。汝所住地。近於佛慧。當觀察籌量所得涅槃。非真實也。",
    anchorText: "汝所住地。近於佛慧",
    note: "如來進一步開示二乘所得非究竟，所住地近於佛慧，應觀察籌量。",
  },
  {
    id: "t0262-004-057",
    category: "一乘方便",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "但是如來方便之力。於一佛乘分別說三。",
    anchorText: "但是如來方便之力",
    note: "本品總結三乘為如來方便，實於一佛乘分別說三。",
  },
  {
    id: "t0262-004-058",
    category: "勤進寶所",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "故以方便力 權化作此城 汝等勤精進 當共至寶所",
    anchorText: "故以方便力 權化作此城",
    note: "偈頌勸眾勿住化城，應勤精進，共至寶所。",
  },
  {
    id: "t0262-004-059",
    category: "入於佛慧",
    sectionTitle: HUACHENG_SECTION_TITLE,
    text: "諸佛之導師 為息說涅槃 既知是息已 引入於佛慧",
    anchorText: "諸佛之導師 為息說涅槃",
    note: "品末偈明示諸佛為止息故說涅槃，既知息已，仍引入佛慧。",
  },
];
