import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const MIAOHOU_SECTION_TITLE = "妙吼菩薩品第二十二";

export const T0263_JUAN_9_MIAOHOU_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-070",
    category: "宿植德本",
    text: "又其佛土有一菩薩，名曰妙音，從過去佛殖眾德本，供養無數百千兆姟諸佛正覺，每見諸佛諮受經典，逮成聖慧",
    anchorText: "從過去佛殖眾德本，供養無數百千兆姟諸佛正覺",
    note: "本品先明妙音菩萨由往昔供佛、咨受经典而成就圣慧。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-071",
    category: "三昧具足",
    text: "取要言之，普悉逮得億百千姟江河沙數諸三昧定。",
    anchorText: "普悉逮得億百千姟江河沙數諸三昧定",
    note: "妙音菩萨以多种三昧为本，显示其入忍界弘法的深厚行持。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-072",
    category: "聞法發心",
    text: "我欲往詣至忍世界見能仁佛，稽首作禮，諮受經典，及欲致敬文殊師利、藥王菩薩、妙勇菩薩、宿王華菩薩、尊意行菩薩、淨王菩薩、超藥菩薩，諮講經義受諸不及，令一切聞悉發道意。",
    anchorText: "我欲往詣至忍世界見能仁佛",
    note: "妙音来此的目的包括礼佛、咨受经典、讲问经义，并令一切闻者发道意。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-073",
    category: "平等觀土",
    text: "又卿往至見彼土人，慎莫心念起不可想，如來菩薩佛土不如。所以者何？佛土本空，眾生罪福，現有不同。",
    anchorText: "慎莫心念起不可想",
    note: "离垢紫金宿华王如来告诫妙音勿轻忍土，指出佛土本空、差别由众生罪福显现。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-074",
    category: "如法無失",
    text: "承佛威神如來聖力，道德巍巍以自娛樂，往詣忍界，如來道慧清淨之業，輒當如法無所違失，不敢起想。",
    anchorText: "如來道慧清淨之業",
    note: "妙音自述承佛威神来忍界，将依如来道慧清净之业而行，不起分别想。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-075",
    category: "瑞應聽經",
    text: "有菩薩名曰妙音，從紫金離垢宿華王佛土而來，與八萬四千菩薩俱，進至此忍界，欲見吾身稽首諮問，欲得聽聞《正法華經》，故先見瑞。",
    anchorText: "欲得聽聞《正法華經》",
    note: "佛说明宝莲华瑞应，是妙音菩萨与大众欲见佛、咨问、听闻《正法华经》的先兆。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-076",
    category: "聞已奉行",
    text: "願欲聞之，所行三昧神足變化，吾等聞之當受奉行，見諸菩薩顏貌色像，為何等類？舉動進止何所饒益？",
    anchorText: "吾等聞之當受奉行",
    note: "文殊请问妙音所行三昧与神足变化，明说众会闻后当受奉行。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-077",
    category: "來受經典",
    text: "善哉！善哉！族姓子，卿能故來見能仁佛，稽首諮受《正法華經》，及復欲覩文殊師利啟諸不逮。",
    anchorText: "稽首諮受《正法華經》",
    note: "众宝如来赞妙音来见能仁佛，并咨受《正法华经》。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-078",
    category: "聞法供養",
    text: "時妙音菩薩，聞其所說欣然意解，鼓百千音樂娛樂其佛，八萬四千眾寶妙器，貢上至尊，如是精進供養如來萬二千歲。",
    anchorText: "聞其所說欣然意解",
    note: "佛追述妙音往昔闻法欣然意解，并长时以音乐宝器精进供佛。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-079",
    category: "化愚令信",
    text: "妙音菩薩往宿命時，從雲雷音王如來之世，修無上法種此功德，未曾懈廢，傳如來旨化諸愚冥，不識至真悉令信樂。",
    anchorText: "傳如來旨化諸愚冥",
    note: "妙音往昔修无上法、种此功德，以传如来旨意令愚冥众生信乐至真。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-080",
    category: "宣說此經",
    text: "今蓮華首，為現妙音菩薩所行，不可限量變無數形，為諸眾生宣布講化《正法華經》。",
    anchorText: "不可限量變無數形",
    note: "佛总说妙音菩萨以无数身形为众生宣布讲化《正法华经》。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-081",
    category: "隨類說經",
    text: "說《正法華經》，或現比丘、比丘尼、清信士、清信女形，宮人婇女、長者夫人、諸貧賤女形，男女大小而誘立之。",
    anchorText: "或現比丘、比丘尼、清信士、清信女形",
    note: "妙音随类现身，对比丘、比丘尼、清信士女乃至男女大小说《正法华经》而诱立。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-082",
    category: "惡趣救濟",
    text: "說《正法華經》，或入地獄、餓鬼、畜生及諸八難，所在擁護而救濟之，上中下士前後進退，隨其形體男女之像，而開化之。",
    anchorText: "或入地獄、餓鬼、畜生及諸八難",
    note: "经文明说妙音入恶趣与八难之处，拥护救济并随类开化。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-083",
    category: "將護眾生",
    text: "蓮華首當知，妙音菩薩將護忍界一切眾生。",
    anchorText: "妙音菩薩將護忍界一切眾生",
    note: "佛直接说明妙音菩萨将护忍界一切众生。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-084",
    category: "演經增益",
    text: "妙音菩薩以若干變無數方便，誘忍佛土演《正法華經》，神足威德未曾損耗而復增益也，聖慧道智亦復如是。",
    anchorText: "誘忍佛土演《正法華經》",
    note: "妙音以无数方便在忍土演《正法华经》，其神足威德与圣慧道智不损而增。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-085",
    category: "隨願開化",
    text: "妙音菩薩光明功勳智慧巍巍，周旋十方隨時開化，輪轉無際皆使入律，上中下願各令得所，逮遊忍界，復至他方江河沙佛土，現菩薩身而為說法。",
    anchorText: "周旋十方隨時開化",
    note: "佛赞妙音光明功勋智慧巍巍，周旋十方随时开化，使不同愿求各得其所。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-086",
    category: "顯授大道",
    text: "若有眾生，奉如來律，以佛色像，隨其道律示現形貌，顯授大道無上正真，欲導慕泥洹現已滅度，因而示儀開化道慧。",
    anchorText: "顯授大道無上正真",
    note: "妙音随众生所应，以佛身等相显授无上正真大道，开化道慧。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-087",
    category: "三昧開化",
    text: "有三昧名現入眾像，妙音菩薩住斯定意，利益開化無限眾生使入道議。",
    anchorText: "妙音菩薩住斯定意",
    note: "佛明示妙音所住三昧名现入众像，能利益开化无限众生入于道议。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-088",
    category: "聞品得定",
    text: "佛說是妙音菩薩章句品時，其諸菩薩與妙音開士俱發來者，尋時皆逮現入眾像三昧正定。",
    anchorText: "佛說是妙音菩薩章句品時",
    note: "佛说本品时，与妙音同来的诸菩萨即得现入众像三昧正定。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-089",
    category: "總持濟世",
    text: "若有逮致現入眾像三昧，便得總持，攬持三世無不蒙濟。",
    anchorText: "便得總持，攬持三世無不蒙濟",
    note: "经文明说得现入众像三昧者便得总持，摄持三世而普蒙济益。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-090",
    category: "導利眾生",
    text: "前稽首禮妙紫金離垢宿華王如來，以詣忍界導利眾生。又覩眾寶如來寶寺舍利，及文殊師利、藥王菩薩所逮精進無極道力，見妙勇菩薩，令是八萬四千菩薩，皆得正行現入眾像三昧，往到彼間俱共進行。",
    anchorText: "以詣忍界導利眾生",
    note: "妙音回到本土后，陈述来忍界导利众生，并令八万四千菩萨皆得正行现入众像三昧。",
  },
  {
    sectionTitle: MIAOHOU_SECTION_TITLE,
    id: "t0263-009-091",
    category: "聞經法忍",
    text: "四萬二千天子，聞《正法華經》，皆悉逮得無所從生法忍；蓮華首菩薩逮正法華定。",
    anchorText: "四萬二千天子，聞《正法華經》",
    note: "本品结尾明示四万二千天子闻《正法华经》得无所从生法忍，莲华首菩萨得正法华定。",
  },
];
