import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const PUXIAN_SECTION_TITLE = "普賢菩薩勸發品第二十六";

export const T0264_JUAN_7_PUXIAN_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-007-071",
    category: "遙聞聽受",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "我於寶威德上王佛國，遙聞此娑婆世界說《法華經》，與無量無邊百千萬億諸菩薩眾共來聽受。",
    anchorText: "遙聞此娑婆世界說《法華經》",
    note: "普贤菩萨遥闻娑婆说《法华经》，与无量菩萨众同来听受。",
  },
  {
    id: "t0264-007-072",
    category: "四法得經",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若善男子、善女人，成就四法，於如來滅後當得是《法華經》：一者、為諸佛護念，二者、殖諸德本，三者、入正定聚，四者、發救一切眾生之心。",
    anchorText: "成就四法，於如來滅後當得是《法華經》",
    note: "佛明示灭后能得《法华经》的四种因缘。",
  },
  {
    id: "t0264-007-073",
    category: "必得是經",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "善男子善女人，如是成就四法，於如來滅後必得是經。",
    anchorText: "於如來滅後必得是經",
    note: "成就四法者，灭后必得此经。",
  },
  {
    id: "t0264-007-074",
    category: "守護安隱",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "於後五百歲濁惡世中，其有受持是經典者，我當守護除其衰患令得安隱，使無伺求得其便者，若魔、若魔子，若魔女、若魔民，若為魔所著者，若夜叉、若羅剎，若鳩槃荼、若毘舍闍，若吉遮、若富單那，若韋陀羅等諸惱人者，皆不得便。",
    anchorText: "我當守護除其衰患令得安隱",
    note: "普贤发愿守护受持此经者，除衰患令得安隐，使诸恼害不得其便。",
  },
  {
    id: "t0264-007-075",
    category: "現身護持",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "是人若行、若立讀誦此經，我爾時乘六牙白象王，與大菩薩眾俱詣其所而自現身，供養守護安慰其心，亦為供養《法華經》故。",
    anchorText: "供養守護安慰其心",
    note: "读诵此经者，普贤现身供养守护、安慰其心。",
  },
  {
    id: "t0264-007-076",
    category: "忘失通利",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "其人若於此《法華經》，有所忘失一句一偈，我當教之與共讀誦，還令通利。",
    anchorText: "有所忘失一句一偈",
    note: "若于经文有所忘失，普贤教其共读诵，令还得通利。",
  },
  {
    id: "t0264-007-077",
    category: "見身得法",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "爾時受持讀誦《法華經》者，得見我身，甚大歡喜轉復精進，以見我故，即得三昧及陀羅尼，名為旋陀羅尼、百千萬億旋陀羅尼、法音方便陀羅尼，得如是等陀羅尼。",
    anchorText: "即得三昧及陀羅尼",
    note: "受持读诵者见普贤身，欢喜精进，并得三昧与诸陀罗尼。",
  },
  {
    id: "t0264-007-078",
    category: "精進感應",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "求索者、受持者、讀誦者、書寫者、欲修習是《法華經》者，於三七日中應一心精進，滿三七日已，我當乘六牙白象，與無量菩薩而自圍遶，以一切眾生所憙見身現其人前，而為說法示教利喜。",
    anchorText: "於三七日中應一心精進",
    note: "求索、受持、读诵、书写、修习此经者，一心精进，普贤现前说法示教利喜。",
  },
  {
    id: "t0264-007-079",
    category: "陀羅尼護",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "亦復與其陀羅尼呪，得是陀羅尼故，無有非人能破壞者，亦不為女人之所惑亂，我身亦自常護是人。",
    anchorText: "無有非人能破壞者",
    note: "得此陀罗尼者，非人不能破坏，也不为惑乱，普贤常自护念。",
  },
  {
    id: "t0264-007-080",
    category: "普賢威神",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若《法華經》行閻浮提有受持者，應作是念：『皆是普賢威神之力。』",
    anchorText: "皆是普賢威神之力",
    note: "经行阎浮提而有人受持，应知皆是普贤威神之力。",
  },
  {
    id: "t0264-007-081",
    category: "普賢行",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若有受持讀誦正憶念解其義趣如說修行，當知是人行普賢行，於無量無邊諸佛所深種善根，為諸如來手摩其頭。",
    anchorText: "當知是人行普賢行",
    note: "受持读诵、正忆念、解义趣、如说修行者，行普贤行，深种善根，为诸如来摩顶。",
  },
  {
    id: "t0264-007-082",
    category: "書寫生天",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若但書寫，是人命終，當生忉利天上，是時八萬四千天女，作眾伎樂而來迎之，其人即著七寶冠，於婇女中娛樂快樂。",
    anchorText: "若但書寫，是人命終",
    note: "单能书写此经者，命终生忉利天，天女伎乐来迎。",
  },
  {
    id: "t0264-007-083",
    category: "命終善趣",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若有人受持、讀誦、解其義趣，是人命終為千佛授手，令不恐怖，不墮惡趣，即往兜率天上彌勒菩薩所。",
    anchorText: "為千佛授手，令不恐怖",
    note: "受持读诵并解义趣者，命终为千佛授手，不恐怖、不堕恶趣，往兜率天。",
  },
  {
    id: "t0264-007-084",
    category: "功德利益",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "有如是等功德利益，是故智者應當一心自書，若使人書，受持、讀誦、正憶念、如說修行。",
    anchorText: "有如是等功德利益",
    note: "经文明说有如是功德利益，劝智者一心书写、受持、读诵、忆念、修行。",
  },
  {
    id: "t0264-007-085",
    category: "流布不絕",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "我今以神通力守護是經，於如來滅後閻浮提內，廣令流布使不斷絕。",
    anchorText: "廣令流布使不斷絕",
    note: "普贤以神通力守护此经，使其在阎浮提广为流布不断绝。",
  },
  {
    id: "t0264-007-086",
    category: "護助安樂",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "汝能護助是經，令多所眾生安樂利益，汝已成就不可思議功德，深大慈悲，從久遠來，發阿耨多羅三藐三菩提意，而能作是神通之願，守護是經",
    anchorText: "令多所眾生安樂利益",
    note: "佛赞普贤护助此经，令众生安乐利益，并成就不可思议功德与深大慈悲。",
  },
  {
    id: "t0264-007-087",
    category: "受持名號",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "我當以神通力守護能受持普賢菩薩名者。",
    anchorText: "守護能受持普賢菩薩名者",
    note: "佛说将以神通力守护能受持普贤菩萨名者。",
  },
  {
    id: "t0264-007-088",
    category: "如見聞佛",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若有受持、讀誦、正憶念、修習、書寫是《法華經》者，當知是人則見釋迦牟尼佛，如從佛口聞此經典；當知是人供養釋迦牟尼佛；當知是人佛讚善哉；當知是人為釋迦牟尼佛手摩其頭；當知是人為釋迦牟尼佛衣之所覆。",
    anchorText: "則見釋迦牟尼佛，如從佛口聞此經典",
    note: "受持读诵、忆念修习、书写此经者，如见佛、从佛口闻经，并得佛赞叹、摩顶与衣覆。",
  },
  {
    id: "t0264-007-089",
    category: "質直福德",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "是人心意質直，有正憶念，有福德力；是人不為三毒所惱，亦不為嫉妬、我慢、邪慢、增上慢所惱；是人少欲知足，能修普賢之行。",
    anchorText: "是人心意質直，有正憶念",
    note: "持经者心意质直，有正忆念与福德力，不为三毒、嫉妒诸慢所恼，能修普贤行。",
  },
  {
    id: "t0264-007-090",
    category: "敬持經者",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若如來滅後後五百歲，若有人見受持、讀誦《法華經》者，應作是念：『此人不久當詣道場破諸魔眾，得阿耨多羅三藐三菩提，轉法輪、擊法鼓、吹法螺、雨法雨，當坐天、人大眾中師子法座上。』",
    anchorText: "此人不久當詣道場破諸魔眾",
    note: "见受持读诵者，应作其不久成道、转法轮、坐师子座之想。",
  },
  {
    id: "t0264-007-091",
    category: "現世福報",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若於後世，受持、讀誦是經典者，是人不復貪著衣服、臥具、飲食、資生之物，所願不虛，亦於現世得其福報。",
    anchorText: "所願不虛，亦於現世得其福報",
    note: "受持读诵此经者不贪着资生之物，所愿不虚，并于现世得福报。",
  },
  {
    id: "t0264-007-092",
    category: "輕毀罪報",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若有人輕毀之，言：『汝狂人耳，空作是行終無所獲。』如是罪報，當世世無眼。",
    anchorText: "空作是行終無所獲",
    note: "经中严示轻毁持经者的罪报，劝人慎勿毁谤。",
  },
  {
    id: "t0264-007-093",
    category: "供養現報",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "若有供養讚歎之者，當於今世得現果報。",
    anchorText: "供養讚歎之者",
    note: "供养赞叹受持此经者，今世得现果报。",
  },
  {
    id: "t0264-007-094",
    category: "如敬佛",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "是故普賢！若見受持是經者，當起遠迎當如敬佛。",
    anchorText: "當起遠迎當如敬佛",
    note: "佛劝见受持此经者，应起远迎，如敬佛。",
  },
  {
    id: "t0264-007-095",
    category: "聞品得法",
    sectionTitle: PUXIAN_SECTION_TITLE,
    text: "說是〈普賢勸發品〉時，恒河沙等無量無邊菩薩，得百千億旋陀羅尼，三千大千世界微塵等諸菩薩，具普賢道。",
    anchorText: "恒河沙等無量無邊菩薩",
    note: "佛说本品时，无量菩萨得旋陀罗尼，微尘等诸菩萨具普贤道。",
  },
];
