import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const SHOUWUBAIDIZI_SECTION_TITLE = "授五百弟子決品第八";
const SHOUANAN_LUOYUN_SECTION_TITLE = "授阿難羅云決品第九";

export const T0263_JUAN_5_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0263-005-001",
    category: "聞法歡喜",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "聞佛世尊敷闡善權示現方便，授聲聞決當成佛道，追省往古所興立行，又瞻如來諸佛境界，得未曾有歡喜踊躍",
    anchorText: "聞佛世尊敷闡善權示現方便",
    note: "滿願子聞佛開示方便、授聲聞成佛之決，得未曾有而歡喜踊躍。",
  },
  {
    id: "t0263-005-002",
    category: "方便度脫",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "如來、至真、等正覺所設方謀甚深甚深，非口所宣，此諸世界有若干品，以無數權隨現慧誼，順化群生分別了法，為此眾人說其本原，方便度脫。",
    anchorText: "如來、至真、等正覺所設方謀甚深甚深",
    note: "本品开端赞叹如来善权甚深，能随顺众生分别说法而方便度脱。",
  },
  {
    id: "t0263-005-003",
    category: "導入佛慧",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "如來通見一切本際，推其深淺因行授與，如示聲聞卑下小乘，淫怒垢除令得休息，乃導菩薩無極之慧。",
    anchorText: "如來通見一切本際，推其深淺因行授與",
    note: "佛通见众生因行深浅，先令休息，最终导入菩萨无极之慧。",
  },
  {
    id: "t0263-005-004",
    category: "講說經道",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "發無上正真道意欲度一切，譬如導師行入大海；愍諸貧匱令入海者，謂為一切講說經道",
    anchorText: "發無上正真道意欲度一切",
    note: "佛以导师入海喻说明发无上道意、为众生讲说经道。",
  },
  {
    id: "t0263-005-005",
    category: "聞道發心",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "眾又隨從取如意珠，謂聞菩薩道而發大意得無從生",
    anchorText: "謂聞菩薩道而發大意得無從生",
    note: "譬喻中取如意珠对应闻菩萨道而发大意，并得无所从生。",
  },
  {
    id: "t0263-005-006",
    category: "成佛度眾",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "昇樓執珠向八方上下，謂得佛道；度脫十方，謂諸慧士等分至諸國；雨七寶者，謂各詣他方成最正覺",
    anchorText: "昇樓執珠向八方上下，謂得佛道",
    note: "譬喻说明得佛道后度脱十方，并在他方成最正觉。",
  },
  {
    id: "t0263-005-007",
    category: "一乘授決",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "眾貧悔還相命入海，謂諸聲聞聞有一乘無二道也，爾乃更發無上正真道意，後當成佛各有名號。",
    anchorText: "謂諸聲聞聞有一乘無二道也",
    note: "声闻闻一乘无二道，转发无上正真道意，后当成佛。",
  },
  {
    id: "t0263-005-008",
    category: "發心得道",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "即還入海，求如意珠，尋則得之，發意菩薩，得正真道。",
    anchorText: "即還入海，求如意珠",
    note: "偈颂以重入海求珠喻发意菩萨得正真道。",
  },
  {
    id: "t0263-005-009",
    category: "三界度脫",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "畏厭生死，便隨聲聞，奉行空事，無想無願，得度三界，至泥洹門。",
    anchorText: "畏厭生死，便隨聲聞",
    note: "经文承认声闻以空、无想、无愿得度三界、至泥洹门的阶段利益。",
  },
  {
    id: "t0263-005-010",
    category: "法音開化",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "開化一切，出萬億音，十方群生，莫不受教。",
    anchorText: "開化一切，出萬億音",
    note: "佛成无上道后，以广大法音开化十方群生。",
  },
  {
    id: "t0263-005-011",
    category: "發菩薩意",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "天龍鬼神，皆來稽首，發菩薩意，至無從生。",
    anchorText: "天龍鬼神，皆來稽首",
    note: "天龙鬼神闻法稽首，发菩萨意，至无所从生。",
  },
  {
    id: "t0263-005-012",
    category: "授決大道",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "佛皆授決，當至大道，國土處所，各有名號。",
    anchorText: "佛皆授決，當至大道",
    note: "佛为声闻授决，明其当至大道并各有佛土名号。",
  },
  {
    id: "t0263-005-013",
    category: "說法第一",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "於比丘眾為法都講，光揚諮嗟諸佛之德，敷陳正典精進勸助，聞佛說法諷受奉宣，散示未聞而無懈廢，闡弘誼趣解暢槃結，應答四部不以厭惓，顯諸梵行悉令歡喜。",
    anchorText: "於比丘眾為法都講",
    note: "佛赞满愿子为法都讲，能受持宣扬、答问不倦，令梵行者欢喜。",
  },
  {
    id: "t0263-005-014",
    category: "利益救濟",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "以斯善權利益救濟，於無央數億百千姟群生之類，開化無量阿僧祇人，令發無上正真道意",
    anchorText: "以斯善權利益救濟",
    note: "满愿子以善权利益救济群生，开化无量人发无上道意。",
  },
  {
    id: "t0263-005-015",
    category: "大道佛住",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "其所遊至皆為黎庶，顯暢大道令得佛住。",
    anchorText: "顯暢大道令得佛住",
    note: "其所到之处为众生显畅大道，令得佛住。",
  },
  {
    id: "t0263-005-016",
    category: "勸化成佛",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "常為無量無極品類，光益訓誼，勸化一切無限蒸民，令發無上正真道意，具足滿進菩薩道行，却無數劫當成為佛",
    anchorText: "常為無量無極品類，光益訓誼",
    note: "佛授记满愿子将常作法讲，劝化众生发心、具足菩萨行而成佛。",
  },
  {
    id: "t0263-005-017",
    category: "佛土莊嚴",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "爾時江河沙等三千大千世界為一佛土，七寶為地，地平如掌，無有山陵、丘墟谿谷、荊棘礫石，重閣精舍周匝普滿，而用七寶",
    anchorText: "爾時江河沙等三千大千世界為一佛土",
    note: "授记中说明未来佛土广大清净、七宝庄严。",
  },
  {
    id: "t0263-005-018",
    category: "法喜禪悅",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "是時人民常有二食，一曰法食，二曰樂禪悅豫，是為二食。",
    anchorText: "是時人民常有二食",
    note: "未来佛土人民以法食与禅悦为食。",
  },
  {
    id: "t0263-005-019",
    category: "法住久遠",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "佛壽無量劫。滅度之後法住甚久，起七寶塔遍是世界，十方諸佛皆共歌歎斯土功德。",
    anchorText: "佛壽無量劫。滅度之後法住甚久",
    note: "法照曜如来寿命无量，灭后法住甚久，十方诸佛歌叹其土功德。",
  },
  {
    id: "t0263-005-020",
    category: "方便修行",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "如吾所語，諸天世人，行權方便，究竟善學，若當遵崇，修佛道行。",
    anchorText: "行權方便，究竟善學",
    note: "偈中劝诸天世人遵崇善权方便，修佛道行。",
  },
  {
    id: "t0263-005-021",
    category: "漸成佛道",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "下劣懈廢，恣尚慢墮，而當漸漬，皆成佛道。",
    anchorText: "下劣懈廢，恣尚慢墮",
    note: "对下劣懈怠者，佛仍以渐次熏习令皆成佛道。",
  },
  {
    id: "t0263-005-022",
    category: "說經清淨",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "察知眾生，常見根原，為說經典，使至清淨。",
    anchorText: "察知眾生，常見根原",
    note: "佛弟子察知众生根原，为说经典，令至清净。",
  },
  {
    id: "t0263-005-023",
    category: "開化無漏",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "當復開化，無數眾生，悉在道慧，無有諸漏。",
    anchorText: "當復開化，無數眾生",
    note: "授记偈说明未来仍将开化无数众生，使住道慧、无有诸漏。",
  },
  {
    id: "t0263-005-024",
    category: "執法成佛",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "彼每事敬，諸大聖雄，常當執持，此佛尊法。當得佛道，自在導師，名法光曜，照聞十方。",
    anchorText: "常當執持，此佛尊法",
    note: "经文将执持佛尊法与当得佛道、名闻十方相连。",
  },
  {
    id: "t0263-005-025",
    category: "清淨佛土",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "其佛國土，一切眾生，皆行清淨，常修梵行，具足辯慧，眾德無乏",
    anchorText: "其佛國土，一切眾生，皆行清淨",
    note: "未来佛土众生清净修梵行，具足辩慧与众德。",
  },
  {
    id: "t0263-005-026",
    category: "無惡趣患",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "其土亦無，女人之眾，無有惡趣，勤苦之患。",
    anchorText: "無有惡趣，勤苦之患",
    note: "授记佛土无恶趣与勤苦之患。",
  },
  {
    id: "t0263-005-027",
    category: "五百成佛",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "五百弟子皆當作佛，號普光如來、至真、等正覺、明行成為、善逝、世間解、無上士、道法御、天人師，為佛、眾祐。",
    anchorText: "五百弟子皆當作佛",
    note: "佛为五百弟子授记，同号普光如来。",
  },
  {
    id: "t0263-005-028",
    category: "逮成正覺",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "五百羅漢，皆當逮成無上正真道，為最正覺，悉同一號。",
    anchorText: "五百羅漢，皆當逮成無上正真道",
    note: "经文再次明说五百罗汉皆当成无上正真道。",
  },
  {
    id: "t0263-005-029",
    category: "普光化眾",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "將來之世，無央數劫，當化眾庶，無數億千，得為最勝，號曰普光。",
    anchorText: "將來之世，無央數劫，當化眾庶",
    note: "偈颂说明普光如来将于无量劫中化导无数众生。",
  },
  {
    id: "t0263-005-030",
    category: "講說佛道",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "億千眾生，周匝圍繞，唯但講說，尊上佛道。",
    anchorText: "唯但講說，尊上佛道",
    note: "普光如来为众生唯讲尊上佛道。",
  },
  {
    id: "t0263-005-031",
    category: "正法久住",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "滅度之後，正法當住，聖所遺典，存劫三倍。又以像法，當復住立，過於正法，轉復三倍。",
    anchorText: "滅度之後，正法當住",
    note: "普光如来灭后正法与像法都将久住。",
  },
  {
    id: "t0263-005-032",
    category: "遵修雅典",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "悉當遵修，宣此雅典，一切所得，皆當若茲，現於天上，及在世間。",
    anchorText: "悉當遵修，宣此雅典",
    note: "偈中劝当遵修宣说此雅典，一切所得皆如授记所明。",
  },
  {
    id: "t0263-005-033",
    category: "念持佛名",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "卿當念持，五百佛名。諸聲聞眾，及餘一切，是故弟子，猶得自在。",
    anchorText: "卿當念持，五百佛名",
    note: "佛嘱大迦叶念持五百佛名，令声闻大众得其利益。",
  },
  {
    id: "t0263-005-034",
    category: "聞記歡喜",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "爾時五百無著，目見耳聞如來授決，歡喜踊躍往詣佛所，自投于地稽首作禮",
    anchorText: "目見耳聞如來授決",
    note: "五百无著亲闻授决，欢喜踊跃礼佛。",
  },
  {
    id: "t0263-005-035",
    category: "逮如來慧",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "今乃得逮如來之慧，當成正覺。",
    anchorText: "今乃得逮如來之慧",
    note: "五百声闻自陈今得逮如来之慧，当成正觉。",
  },
  {
    id: "t0263-005-036",
    category: "開化餘人",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "今日如此乃能志願於諸通慧，當以斯法開化餘人，以如來慧分別道意。",
    anchorText: "當以斯法開化餘人",
    note: "闻授记后，五百声闻发愿以此法开化余人。",
  },
  {
    id: "t0263-005-037",
    category: "親殖德本",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "卿諸賢者，又當親殖眾德之本。",
    anchorText: "又當親殖眾德之本",
    note: "佛劝诸贤者亲自培植众德之本。",
  },
  {
    id: "t0263-005-038",
    category: "重說授決",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "昔者如來以權方便開導若等，今亦如是重說經法，若之徒類自取滅度。今者世尊，授以無上正真道決。",
    anchorText: "昔者如來以權方便開導若等",
    note: "佛以权方便重说经法，为自谓灭度者授无上道决。",
  },
  {
    id: "t0263-005-039",
    category: "聞斯受決",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "我等聞斯，乃知前失，已得受決，是上佛道。",
    anchorText: "我等聞斯，乃知前失",
    note: "五百声闻闻法后知前失，得受上佛道之决。",
  },
  {
    id: "t0263-005-040",
    category: "覺悟開度",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "如佛聖教，所覺開度，如是計之，無得滅度。",
    anchorText: "如佛聖教，所覺開度",
    note: "声闻依佛圣教重新理解：未到究竟，不应执为灭度。",
  },
  {
    id: "t0263-005-041",
    category: "殊決怡懌",
    sectionTitle: SHOUWUBAIDIZI_SECTION_TITLE,
    text: "此結明珠，離垢上珍，今日我等，所聞無限。因從化導，普顯怡懌，各各逮得，別授殊決。",
    anchorText: "此結明珠，離垢上珍",
    note: "结尾以髻中明珠喻佛慧宝藏，五百声闻因化导而各得殊决。",
  },
  {
    id: "t0263-005-042",
    category: "甘露授決",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "唯為我等演甘露味，大聖是父靡不明徹，無歸得歸、無救得救、無護得護",
    anchorText: "唯為我等演甘露味",
    note: "阿難、羅云請佛演甘露味，稱佛能令無歸者得歸、無救者得救、無護者得護。",
  },
  {
    id: "t0263-005-043",
    category: "持法授記",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "阿難、羅云，則是佛子亦是侍者，持聖法藏，惟願世尊，孚令我等所願具足，授無上正真。",
    anchorText: "持聖法藏，惟願世尊",
    note: "本品以持聖法藏為請授無上正真的重要因緣。",
  },
  {
    id: "t0263-005-044",
    category: "供佛護法成覺",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "先當供養六十二億佛，恭順奉侍，執持正法將護經典，然後究竟成最正覺。",
    anchorText: "先當供養六十二億佛",
    note: "佛授記阿難先供養諸佛、執持正法、將護經典，然後究竟成佛。",
  },
  {
    id: "t0263-005-045",
    category: "開化發心",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "於是開化二十百千江河沙等天人，使發無上正真道意。",
    anchorText: "開化二十百千江河沙等天人",
    note: "阿難成佛後將開化無量天人，使發無上正真道意。",
  },
  {
    id: "t0263-005-046",
    category: "佛土清淨",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "其佛國土清淨無瑕，地紺琉璃，竪諸幢幡，自然莊嚴世界平正，無沙礫石、山陵谿谷，地皆柔軟如天綩綖",
    anchorText: "其佛國土清淨無瑕",
    note: "授記中明示海持覺娛樂神通如來佛土清淨莊嚴。",
  },
  {
    id: "t0263-005-047",
    category: "受道無量",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "諸弟子眾受道教者，不可計會億百千姟無能限量。",
    anchorText: "諸弟子眾受道教者",
    note: "未來佛土中受道教者不可限量。",
  },
  {
    id: "t0263-005-048",
    category: "法住久遠",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "如來滅度後法住過倍，像法存立復倍正法。",
    anchorText: "如來滅度後法住過倍",
    note: "阿難成佛滅度後，正法與像法皆久住。",
  },
  {
    id: "t0263-005-049",
    category: "諸佛歎德",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "十方無量江河沙等億百千佛，悉當歎頌彼佛功德。",
    anchorText: "十方無量江河沙等億百千佛",
    note: "十方無量諸佛皆歎頌海持覺娛樂神通如來功德。",
  },
  {
    id: "t0263-005-050",
    category: "聞記歡喜",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "爾時阿難自親從佛，聞已無量空無之誼，當得成佛授國土決，聞本行願歡喜悅豫",
    anchorText: "當得成佛授國土決",
    note: "阿難親聞成佛與國土授記，憶本願而歡喜悅豫。",
  },
  {
    id: "t0263-005-051",
    category: "憶持正典",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "尋即憶念無央數億百千之姟諸正覺典。又觀本行所履之跡前後劫數。",
    anchorText: "尋即憶念無央數億百千",
    note: "聞授記後，阿難憶念無量諸佛正覺典與本行因緣。",
  },
  {
    id: "t0263-005-052",
    category: "奉持正法",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "得立佛道，心不懷疑，如是比者，善權方便。而為安住，立侍者地，以大道故，奉持正法。",
    anchorText: "得立佛道，心不懷疑",
    note: "阿難偈明以善權方便安住侍者地，為大道故奉持正法。",
  },
  {
    id: "t0263-005-053",
    category: "供佛成覺",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "則當供事如十世界塵數如來，當為諸佛現作尊子，亦復如今為吾息也。",
    anchorText: "則當供事如十世界塵數如來",
    note: "羅云授記中明示將供事塵數如來，常為諸佛尊子。",
  },
  {
    id: "t0263-005-054",
    category: "無上正覺",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "羅云當為其佛尊子，過是已後當得無上正真道成最正覺。",
    anchorText: "羅云當為其佛尊子",
    note: "佛授記羅云過後當得無上正真道，成最正覺。",
  },
  {
    id: "t0263-005-055",
    category: "法施悅眾",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "斯佛之子，當得大道，常以法施，多所悅喜。",
    anchorText: "斯佛之子，當得大道",
    note: "偈中讚羅云當得大道，常以法施令眾悅喜。",
  },
  {
    id: "t0263-005-056",
    category: "諸德無量",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "諸德無量，億姟之數，設有思念，莫能限量。",
    anchorText: "諸德無量，億姟之數",
    note: "佛讚羅云所行諸德無量，難以思量。",
  },
  {
    id: "t0263-005-057",
    category: "二千成佛",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "斯黨同行等學大乘，當供養五百世界塵數如來執持正典，然於後世一時同集，布於十方各各異土，逮成無上正真道為最正覺",
    anchorText: "斯黨同行等學大乘",
    note: "二千學聲聞將供養諸佛、執持正典，於十方異土成最正覺。",
  },
  {
    id: "t0263-005-058",
    category: "覺慧平等",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "其壽一劫，覺慧平等，諸聲聞同多少無差，諸菩薩眾亦復如是。滅度之後正法住立，數亦無異。",
    anchorText: "其壽一劫，覺慧平等",
    note: "寶英如來授記中明其覺慧平等，聲聞菩薩眾與正法住立皆無差異。",
  },
  {
    id: "t0263-005-059",
    category: "授決成佛",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "斯等聖智，佛皆授決，將來之世，便當成佛。",
    anchorText: "斯等聖智，佛皆授決",
    note: "佛為二千聲聞授決，明其將來成佛。",
  },
  {
    id: "t0263-005-060",
    category: "供佛得道",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "覩見諸佛，悉當供養。便當逮獲，無上尊道，住於道行，猶得自在。",
    anchorText: "覩見諸佛，悉當供養",
    note: "偈中說明二千聲聞見佛供養後，將逮獲無上尊道。",
  },
  {
    id: "t0263-005-061",
    category: "光明法住",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "神足光明，皆遍世間，周流一切，十方國土。分別經法，有所依猗，正法存立，等無有異。",
    anchorText: "神足光明，皆遍世間",
    note: "寶英如來神足光明遍於十方，分別經法，正法存立無異。",
  },
  {
    id: "t0263-005-062",
    category: "聞記安樂",
    sectionTitle: SHOUANAN_LUOYUN_SECTION_TITLE,
    text: "聞佛授我決，世光見飽滿，如甘露見灌，已獲無極安。",
    anchorText: "聞佛授我決",
    note: "諸學聲聞聞佛授記，歡喜讚佛，如甘露灌頂，已獲無極安。",
  },
];
