import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const FASHI_SECTION_TITLE = "法師品第十";

export const T0262_JUAN_4_FASHI_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0262-004-113",
    category: "聞經授記",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "聞妙法華經一偈一句。乃至一念隨喜者。我皆與授記。當得阿耨多羅三藐三菩提。",
    anchorText: "聞妙法華經一偈一句。乃至一念隨喜者",
    note: "佛明說在會眾生聞《法華經》一偈一句乃至一念隨喜，皆得授記當成無上菩提。",
  },
  {
    id: "t0262-004-114",
    category: "滅後隨喜",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "又如來滅度之後。若有人聞妙法華經乃至一偈一句一念隨喜者。我亦與授阿耨多羅三藐三菩提記。",
    anchorText: "若有人聞妙法華經乃至一偈一句一念隨喜者",
    note: "佛滅後聞經一偈一句而一念隨喜者，亦蒙授無上菩提記。",
  },
  {
    id: "t0262-004-115",
    category: "受持供養",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "受持讀誦解説書寫妙法華經乃至一偈。於此經卷敬視如佛。種種供養華香瓔珞末香塗香燒香繒蓋幢幡衣服伎樂。乃至合掌恭敬。",
    anchorText: "受持讀誦解説書寫妙法華經乃至一偈",
    note: "本品明列受持、讀誦、解說、書寫與供養經卷，並教人敬視如佛。",
  },
  {
    id: "t0262-004-116",
    category: "成就大願",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "是諸人等。已曾供養十萬億佛。於諸佛所成就大願。愍衆生故生此人間。",
    anchorText: "已曾供養十萬億佛。於諸佛所成就大願",
    note: "受持供養《法華經》者，經文明示已曾供養眾佛、成就大願，為愍眾生生此人間。",
  },
  {
    id: "t0262-004-117",
    category: "未來作佛",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "應示是諸人等於未來世必得作佛。",
    anchorText: "於未來世必得作佛",
    note: "佛指示若問未來誰當作佛，應示受持供養《法華經》者必得作佛。",
  },
  {
    id: "t0262-004-118",
    category: "世間瞻奉",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "是人一切世間所應瞻奉。應以如來供養而供養之。",
    anchorText: "一切世間所應瞻奉。應以如來供養",
    note: "受持乃至一句並供養經卷者，為一切世間所應瞻奉，應以如來供養而供養。",
  },
  {
    id: "t0262-004-119",
    category: "菩薩成就",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "當知此人是大菩薩。成就阿耨多羅三藐三菩提。哀愍衆生願生此間。廣演分別妙法華經。",
    anchorText: "當知此人是大菩薩。成就阿耨多羅三藐三菩提",
    note: "經文稱此類受持弘演者為大菩薩，成就無上菩提，愍眾生而廣演此經。",
  },
  {
    id: "t0262-004-120",
    category: "如來使者",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "能竊爲一人説法華經乃至一句。當知是人。則如來使如來所遣行如來事。",
    anchorText: "則如來使如來所遣行如來事",
    note: "佛滅後即使私下為一人說《法華經》一句，亦被稱為如來使、行如來事。",
  },
  {
    id: "t0262-004-121",
    category: "護持讀誦",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "其有讀誦法華經者。當知是人。以佛莊嚴而自莊嚴。則爲如來肩所荷擔。",
    anchorText: "以佛莊嚴而自莊嚴。則爲如來肩所荷擔",
    note: "讀誦《法華經》者以佛莊嚴自莊嚴，為如來所荷擔。",
  },
  {
    id: "t0262-004-122",
    category: "聞法究竟",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "是人歡喜説法。須臾聞之。即得究竟阿耨多羅三藐三菩提故。",
    anchorText: "須臾聞之。即得究竟阿耨多羅三藐三菩提",
    note: "經文以須臾聞其歡喜說法即得究竟無上菩提，說明聞法利益極重。",
  },
  {
    id: "t0262-004-123",
    category: "住佛道",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若欲住佛道 成就自然智 常當勤供養 受持法華者",
    anchorText: "若欲住佛道 成就自然智",
    note: "偈頌勸欲住佛道、成就自然智者，常勤供養受持《法華經》者。",
  },
  {
    id: "t0262-004-124",
    category: "疾得智慧",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "其有欲疾得 一切種智慧 當受持是經 并供養持者",
    anchorText: "其有欲疾得 一切種智慧",
    note: "欲疾得一切種智慧，應受持此經並供養持經者。",
  },
  {
    id: "t0262-004-125",
    category: "惡世弘法",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "吾滅後惡世 能持是經者 當合掌禮敬 如供養世尊",
    anchorText: "吾滅後惡世 能持是經者",
    note: "佛滅後惡世能持此經者，應合掌禮敬，如供養世尊。",
  },
  {
    id: "t0262-004-126",
    category: "行如來事",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若能於後世 受持是經者 我遣在人中 行於如來事",
    anchorText: "若能於後世 受持是經者",
    note: "後世受持此經者，佛說是其所遣在人中行如來事。",
  },
  {
    id: "t0262-004-127",
    category: "讚持經者",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "有人求佛道 而於一劫中 合掌在我前 以無數偈讃 由是讃佛故 得無量功徳 歎美持經者 其福復過彼",
    anchorText: "歎美持經者 其福復過彼",
    note: "偈中比較讚佛功德與歎美持經者之福，顯示讚歎持經者福德尤勝。",
  },
  {
    id: "t0262-004-128",
    category: "獲大利",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "於八十億劫 以最妙色聲 及與香味觸 供養持經者 如是供養已 若得須臾聞 則應自欣慶 我今獲大利",
    anchorText: "若得須臾聞 則應自欣慶",
    note: "長劫供養持經者後若得須臾聞法，應自慶獲大利。",
  },
  {
    id: "t0262-004-129",
    category: "法華第一",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "藥王今告汝 我所説諸經 而於此經中 法華最第一",
    anchorText: "我所説諸經 而於此經中 法華最第一",
    note: "偈頌總讚佛所說諸經中，《法華經》最為第一。",
  },
  {
    id: "t0262-004-130",
    category: "難信難解",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "我所説經典無量千萬億。已説今説當説。而於其中。此法華經最爲難信難解。",
    anchorText: "此法華經最爲難信難解",
    note: "佛明說已說、今說、當說諸經中，《法華經》最為難信難解。",
  },
  {
    id: "t0262-004-131",
    category: "諸佛護念",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "此經是諸佛祕要之藏。不可分布妄授與人。諸佛世尊之所守護。從昔已來未曾顯説。",
    anchorText: "此經是諸佛祕要之藏",
    note: "本品稱《法華經》為諸佛秘要之藏，為諸佛世尊所守護。",
  },
  {
    id: "t0262-004-132",
    category: "佛衣護念",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "如來滅後。其能書持讀誦供養爲他人説者。如來則爲以衣覆之。又爲他方現在諸佛之所護念。",
    anchorText: "如來則爲以衣覆之。又爲他方現在諸佛之所護念",
    note: "佛滅後能書持讀誦供養、為他人說此經者，得如來衣覆與他方諸佛護念。",
  },
  {
    id: "t0262-004-133",
    category: "如來共宿",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "是人有大信力及志願力諸善根力。當知是人與如來共宿。則爲如來手摩其頭。",
    anchorText: "與如來共宿。則爲如來手摩其頭",
    note: "受持弘說者具信力、願力、善根力，經文明示與如來共宿、為如來摩頂。",
  },
  {
    id: "t0262-004-134",
    category: "經處起塔",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "在在處處。若説若讀若誦若書。若經卷所住處。皆應起七寶塔極令高廣嚴飾。不須復安舍利。所以者何。此中已有如來全身。",
    anchorText: "此中已有如來全身",
    note: "凡說、讀、誦、書及經卷所在處，應起七寶塔，因其中已有如來全身。",
  },
  {
    id: "t0262-004-135",
    category: "禮塔近覺",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若有人得見此塔禮拜供養。當知是等皆近阿耨多羅三藐三菩提。",
    anchorText: "得見此塔禮拜供養。當知是等皆近",
    note: "見此法華經塔並禮拜供養者，經文明示皆近無上菩提。",
  },
  {
    id: "t0262-004-136",
    category: "善行菩薩道",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若有得聞是經典者。乃能善行菩薩之道。",
    anchorText: "得聞是經典者。乃能善行菩薩之道",
    note: "行菩薩道者得聞《法華經》，乃能善行菩薩之道。",
  },
  {
    id: "t0262-004-137",
    category: "近無上覺",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "其有衆生求佛道者。若見若聞是法華經。聞已信解受持者。當知是人得近阿耨多羅三藐三菩提。",
    anchorText: "若見若聞是法華經。聞已信解受持者",
    note: "求佛道者見聞此經，聞已信解受持，即得近無上菩提。",
  },
  {
    id: "t0262-004-138",
    category: "開方便門",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "一切菩薩阿耨多羅三藐三菩提皆屬此經。此經開方便門示眞實相。",
    anchorText: "一切菩薩阿耨多羅三藐三菩提皆屬此經",
    note: "佛說一切菩薩無上菩提皆屬此經，因其開方便門、示真實相。",
  },
  {
    id: "t0262-004-139",
    category: "說經三軌",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "入如來室。著如來衣。坐如來座。爾乃應爲四衆廣説斯經。如來室者。一切衆生中大慈悲心是。如來衣者。柔和忍辱心是。如來座者。一切法空是。",
    anchorText: "入如來室。著如來衣。坐如來座",
    note: "本品明示滅後說《法華經》的三軌：大慈悲、柔和忍辱與一切法空。",
  },
  {
    id: "t0262-004-140",
    category: "化眾聽法",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "我於餘國遣化人爲其集聽法衆。亦遣化比丘比丘尼優婆塞優婆夷聽其説法。",
    anchorText: "遣化人爲其集聽法衆",
    note: "說法者弘說此經時，佛遣化人及四眾為其集聽法眾。",
  },
  {
    id: "t0262-004-141",
    category: "佛現令足",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "我雖在異國。時時令説法者得見我身。若於此經忘失句逗。我還爲説令得具足。",
    anchorText: "時時令説法者得見我身",
    note: "佛在異國亦令說法者得見佛身，若忘失句讀，還為宣說令得具足。",
  },
  {
    id: "t0262-004-142",
    category: "聞經近智",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若聞是深經 決了聲聞法 是諸經之王 聞已諦思惟 當知此人等 近於佛智慧",
    anchorText: "若聞是深經 決了聲聞法",
    note: "偈頌說聞此深經並諦思惟者，近於佛智慧。",
  },
  {
    id: "t0262-004-143",
    category: "變化衛護",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若人欲加惡 刀杖及瓦石 則遣變化人 爲之作衞護",
    anchorText: "則遣變化人 爲之作衞護",
    note: "弘說此經者若遭刀杖瓦石等惡害，佛遣變化人作衛護。",
  },
  {
    id: "t0262-004-144",
    category: "讀誦見佛",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若説法之人 獨在空閑處 寂寞無人聲 讀誦此經典 我爾時爲現 清淨光明身",
    anchorText: "讀誦此經典 我爾時爲現 清淨光明身",
    note: "說法者於空閑處讀誦此經，佛為現清淨光明身。",
  },
  {
    id: "t0262-004-145",
    category: "天龍聽法",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若人在空閑 我遣天龍王 夜叉鬼神等 爲作聽法衆",
    anchorText: "我遣天龍王 夜叉鬼神等 爲作聽法衆",
    note: "弘說此經者若在空閑，佛遣天龍、夜叉鬼神等作聽法眾。",
  },
  {
    id: "t0262-004-146",
    category: "諸佛護念",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "是人樂説法 分別無罣礙 諸佛護念故 能令大衆喜",
    anchorText: "諸佛護念故 能令大衆喜",
    note: "樂說此經者因諸佛護念，分別無礙，能令大眾歡喜。",
  },
  {
    id: "t0262-004-147",
    category: "速得菩薩道",
    sectionTitle: FASHI_SECTION_TITLE,
    text: "若親近法師 速得菩薩道 隨順是師學 得見恒沙佛",
    anchorText: "若親近法師 速得菩薩道",
    note: "品末明說親近法師、隨順其學，速得菩薩道並得見恒沙佛。",
  },
];
