import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const ZONGCHI_SECTION_TITLE = "總持品第二十四";

export const T0263_JUAN_10_ZONGCHI_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    sectionTitle: ZONGCHI_SECTION_TITLE,
    id: "t0263-010-022",
    category: "受持福德",
    text: "族姓子 女，受持 是 經，誦 在 懷抱 書寫 經卷，福 不可量 無 以為 喻。",
    anchorText: "受持 是 經，誦 在 懷抱 書寫 經卷",
    note: "佛答药王菩萨，明说受持、怀抱、书写此经，所得福德不可量、无以为喻。",
  },
  {
    sectionTitle: ZONGCHI_SECTION_TITLE,
    id: "t0263-010-023",
    category: "持經勝供",
    text: "若 族姓子 及 族 姓 女，受《正法 華》經典 之 要，執持 書寫 一 四句 頌，講說 諷誦 若 復 奉行，具足 成就 其 福 最多，勝 於 供養 若干 江 沙 諸佛 世尊。",
    anchorText: "受《正法 華》經典 之 要",
    note: "药王菩萨承佛意指出，执持书写乃至一四句颂、讲说讽诵奉行，福德胜于供养若干江沙诸佛。",
  },
  {
    sectionTitle: ZONGCHI_SECTION_TITLE,
    id: "t0263-010-024",
    category: "法供第一",
    text: "甚 哉！法 之 供養，最為 第一。",
    anchorText: "法 之 供養，最為 第一",
    note: "佛印可药王所说，直赞法供养最为第一。",
  },
  {
    sectionTitle: ZONGCHI_SECTION_TITLE,
    id: "t0263-010-025",
    category: "總持守護",
    text: "我 當 擁護 如是 等 輩，諸 族姓子 及 族 姓 女，受 此 經 者 斯 法師 等，以 義 宿衛 長 使 無 患，誦 總持 句。",
    anchorText: "受 此 經 者 斯 法師 等",
    note: "药王菩萨发愿拥护受持此经的法师，以总持句宿卫令其长无患难。",
  },
  {
    sectionTitle: ZONGCHI_SECTION_TITLE,
    id: "t0263-010-026",
    category: "諸佛所說",
    text: "是 總持 句，六十二 江河沙 諸佛 所 說。假使 有 犯 此 呪 言 者，若 復 違 毀 此等 法師，為 失 諸佛 世尊 道教。",
    anchorText: "六十二 江河沙 諸佛 所 說",
    note: "药王菩萨说明此总持句为六十二江河沙诸佛所说，违毁法师即失诸佛道教。",
  },
  {
    sectionTitle: ZONGCHI_SECTION_TITLE,
    id: "t0263-010-027",
    category: "多所安隱",
    text: "善哉！善哉！若 族姓子 說 總持 句 為 眾生 故，愍 念 擁護 多 所 安隱。",
    anchorText: "說 總持 句 為 眾生 故",
    note: "佛赞药王菩萨为众生说总持句，以愍念拥护令多所安隐。",
  },
  {
    sectionTitle: ZONGCHI_SECTION_TITLE,
    id: "t0263-010-028",
    category: "護法無便",
    text: "若 有 奉持 此 經典 者，授 總持 句，將 護 如此 諸法 師 等，令 無 伺 求得 其 便 者，鬼神 諸 魅、溷 廁 眾 鬼、突 鬼 厭 鬼、餓鬼 反 足，雖 欲 來 嬈，無能 得便。",
    anchorText: "若 有 奉持 此 經典 者",
    note: "妙勇菩萨说总持句，护持奉持此经的法师，使鬼神诸魅虽欲扰害亦不得便。",
  },
  {
    sectionTitle: ZONGCHI_SECTION_TITLE,
    id: "t0263-010-029",
    category: "百由旬護",
    text: "以是 故，擁護 諸法 師 等，百 由旬 內 無 敢 犯 觸，宿衛 將順。諸 族姓子，如是 比 像 至 學 法師 乃 能 受持，以是 擁護 常 獲 吉利。",
    anchorText: "百 由旬 內 無 敢 犯 觸",
    note: "毘沙门天王以总持拥护法师，百由旬内无敢侵犯，受持者常获吉利。",
  },
  {
    sectionTitle: ZONGCHI_SECTION_TITLE,
    id: "t0263-010-030",
    category: "護學經者",
    text: "唯然 世尊，此 總持 句，四千 二百億 諸佛 所 說。以此 總持，擁護 供養 諸 學 經 者，令 無 伺 求得 其 便 者。",
    anchorText: "擁護 供養 諸 學 經 者",
    note: "顺怨天王说明此总持句为四千二百亿诸佛所说，用以拥护供养学经者。",
  },
  {
    sectionTitle: ZONGCHI_SECTION_TITLE,
    id: "t0263-010-031",
    category: "吉祥護持",
    text: "我等，世尊！常 當 擁護 如是 比 像 諸法 師 等，加 施 吉祥，令 無 伺 求得 法師 短。",
    anchorText: "常 當 擁護 如是 比 像 諸法 師 等",
    note: "诸魅与鬼子母等发愿常护法师、加施吉祥，令伺求法师短者不得其便。",
  },
  {
    sectionTitle: ZONGCHI_SECTION_TITLE,
    id: "t0263-010-032",
    category: "除患安隱",
    text: "是 等 之類 是 我 眷屬，令 無 所 犯 擁護 法師。消除 鬼神、諸 魅 餓鬼、溷 神 突 鬼、蠱道 符 呪、癡 狂 顛 鬼，化 是 像 來，若 鬼神 形 及 非人 像，二 日 三 日 若 至 四 日，若 常 熱病。若 復 夜 臥，值 惡夢 者，若 現 男女 大小 諸 像，我等 擁護，令 無 伺 求得 其 便 者。",
    anchorText: "消除 鬼神、諸 魅 餓鬼",
    note: "诸魅说明所护范围，包括鬼神、符咒、癫狂、热病、恶梦等，使诸扰害不得其便。",
  },
  {
    sectionTitle: ZONGCHI_SECTION_TITLE,
    id: "t0263-010-033",
    category: "犯師罪報",
    text: "其 有 犯法 師， 皆 當 獲 此 釁，\n世世 不得 安， 不 與 諸佛 會。",
    anchorText: "其 有 犯法 師， 皆 當 獲 此 釁",
    note: "诸魅偈中警示侵犯法师者世世不得安，不与诸佛会。",
  },
  {
    sectionTitle: ZONGCHI_SECTION_TITLE,
    id: "t0263-010-034",
    category: "安隱離害",
    text: "我等 咸 護 如是 比 像 諸法 師 等，使 常 安隱 除去 怨敵，周匝 宿衛 令 無 傷害，若 有 行 毒，毒 為 不行。",
    anchorText: "使 常 安隱 除去 怨敵",
    note: "诸鬼神军头等发愿护持法师，令常安隐、远离怨敌伤害，乃至毒不能行。",
  },
  {
    sectionTitle: ZONGCHI_SECTION_TITLE,
    id: "t0263-010-035",
    category: "供經福德",
    text: "若 聞 此 經，宣 持名 號 德 不可量，何況 具足 隨時 持 說書 在 經卷，若 以 供養 華香 幢蓋 雜 香 搗 香，然燈 懸 繒，思 夷 合歡，青蓮 紅蓮，黃 蓮 白蓮，稍 著 油 蘇 以 用 然燈，供養 此 經 勤修 不懈，百 千億 倍 福 不可 限。",
    anchorText: "若 聞 此 經，宣 持名 號 德 不可量",
    note: "佛总赞闻经、宣持名号德不可量，具足持说书写并供养此经者，福德百千亿倍不可限。",
  },
  {
    sectionTitle: ZONGCHI_SECTION_TITLE,
    id: "t0263-010-036",
    category: "聞品證法",
    text: "佛說 是 總持 品 時，六 萬 八千 人，逮 得無 所 從 生法 忍。",
    anchorText: "佛說 是 總持 品 時",
    note: "本品结尾明说佛说总持品时，六万八千人得无所从生法忍。",
  },
];
