import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const GUANGRUI_SECTION_TITLE = "光瑞品第一";

export const T0263_JUAN_1_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0263-001-001",
    category: "菩薩功德",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "菩薩八萬，皆不退轉，堅住無上正真之道，逮總持法得大辯才，常讚歎不退轉法輪，供養無數百千諸佛，於無量佛殖眾德本，諸佛世尊所見諮嗟，身常行慈入如來慧，善權普至大知度無極，從無數劫多所博聞，名達十方，救護無量百千眾生，遊於三界猶如日明，解一切法如幻如化野馬影響，悉無所有住無所住，雖見終始亦無去來，既見色像本無形貌，現諸所生永無起滅，導利群黎不著三處，分別空慧無想無願，起三脫門至三達智，無去來今現在之想，開化黎庶使了本無。",
    anchorText: "菩薩八萬，皆不退轉，堅住無上正真之道",
    note: "光瑞品开列大会菩萨功德，显示不退、总持、辩才、供佛植德与救护众生。",
  },
  {
    id: "t0263-001-002",
    category: "法會總讚",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "爾時世尊與四部眾眷屬圍繞而為說經，講演菩薩方等大頌一切諸佛嚴淨之業。",
    anchorText: "講演菩薩方等大頌一切諸佛嚴淨之業",
    note: "本品说明佛为四众讲演菩萨方等大颂、一切诸佛严净之业。",
  },
  {
    id: "t0263-001-003",
    category: "瑞相感發",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "所坐立處則有瑞應，天雨、意華、大意華、柔軟音華、大柔軟音華，散世尊上及於大會四部之眾，普佛國土六反震動。",
    anchorText: "所坐立處則有瑞應",
    note: "佛入三昧后，天雨妙华、国土震动，显出将说大法的瑞相。",
  },
  {
    id: "t0263-001-004",
    category: "見未曾有",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "時大眾會比丘、比丘尼、清信士、清信女，天、龍、神鬼、揵沓惒、阿須倫、迦留羅、真陀羅、摩休勒、人與非人，國王君主大力轉輪聖王，各與營從，咸悉一心瞻戴世尊，意皆愕然怪未曾有。",
    anchorText: "咸悉一心瞻戴世尊，意皆愕然怪未曾有",
    note: "大众因瑞相一心瞻仰世尊，生未曾有心。",
  },
  {
    id: "t0263-001-005",
    category: "佛光顯法",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "於時佛放面口結光明，普炤東方萬八千佛土，其大光明照諸佛國，靡不周遍，至於無擇大地獄中，上徹三十三天，彼此世界六趣周旋，所有蒸民一切皆現，其界諸佛現在所由，此土眾會悉遙見之；彼土覩斯亦復如是，十方諸佛所說經法，普遍聞焉。",
    anchorText: "於時佛放面口結光明，普炤東方萬八千佛土",
    note: "佛光普照万八千佛土，使众会遥见诸佛世界，并普闻十方诸佛所说经法。",
  },
  {
    id: "t0263-001-006",
    category: "決散疑網",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "時四部眾比丘、比丘尼、清信士、清信女，諸天、龍、神、揵沓惒、阿須倫、迦留羅、真陀羅、摩休勒，志懷猶豫得未曾有，見斯大聖無極威曜神足變化，各各發意，欲問世尊決散疑網。",
    anchorText: "各各發意，欲問世尊決散疑網",
    note: "瑞相引发大众求问因缘，欲由佛法决除疑网。",
  },
  {
    id: "t0263-001-007",
    category: "經典利益",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "又覩諸佛，　而師子吼，　演說經典，　開闡法門，　消除眾生，　無數之穢。",
    anchorText: "演說經典，　開闡法門，　消除眾生",
    note: "弥勒所见瑞相中，诸佛演说经典、开阐法门，能消除众生无数秽垢。",
  },
  {
    id: "t0263-001-008",
    category: "聞法欣踊",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "歌頌聖教，　出柔軟音，　其響深妙，　令人欣踊。",
    anchorText: "其響深妙，　令人欣踊",
    note: "圣教音声深妙，令闻者欣喜踊跃。",
  },
  {
    id: "t0263-001-009",
    category: "離苦入道",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "一切眾生，　所造苦患，　以無巧便，　治老病死，　猶斯等類，　說寂滅度。",
    anchorText: "一切眾生，　所造苦患",
    note: "经文说明诸佛随众生苦患，以方便说寂灭度，疗治老病死。",
  },
  {
    id: "t0263-001-010",
    category: "積德見佛",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "比丘當知，　貧劇困惱，　眾人則處，　安雅快樂，　積累功德，　乃見聖尊，　又得逮至，　緣一覺乘，　一切令入，　於此道業，　見佛殊異，　諸所經籍，　或有志求，　無上之慧。",
    anchorText: "積累功德，　乃見聖尊",
    note: "此段将积累功德、见圣尊、趣入道业和志求无上慧连成完整利益。",
  },
  {
    id: "t0263-001-011",
    category: "布施回向",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "悉以勸助，　上尊佛道。　今我等類，　聞斯音聲，　安住所歎，　正覺大乘，　遊於三界，　而無所猗，　其人速逮，　得獲斯願。",
    anchorText: "悉以勸助，　上尊佛道",
    note: "弥勒见菩萨布施并劝助无上佛道，闻此大乘音声者速得所愿。",
  },
  {
    id: "t0263-001-012",
    category: "受經讀誦",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "我覩若干，　諸菩薩眾，　比丘知友，　頓止山巖，　獨處閑居，　解暢空無，　或有受經，　而讀誦讚。",
    anchorText: "或有受經，　而讀誦讚",
    note: "本品明见菩萨独处闲居，受经、读诵、赞叹。",
  },
  {
    id: "t0263-001-013",
    category: "講說佛乘",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "專精思惟，　歷察眾相，　分別講說，　演諸佛乘，　捐棄愛欲，　永使無餘。　常自纂修，　悕仰正行，　安住諸子，　不離閑居，　則便逮得，　成五神通。",
    anchorText: "分別講說，　演諸佛乘",
    note: "菩萨专精思惟、讲说佛乘，离欲修行而成五神通。",
  },
  {
    id: "t0263-001-014",
    category: "講法開化",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "我又遙見，　諸佛孫息，　為無數億，　人民講法，　而現報應，　兆載難計，　志懷欣喜，　自歸正法，　勸助開化。",
    anchorText: "為無數億，　人民講法",
    note: "菩萨为无数人民讲法，令其欢喜自归正法，并劝助开化。",
  },
  {
    id: "t0263-001-015",
    category: "持戒安隱",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "而護身口，　常行清淨，　禁戒安隱，　不畏生死，　於彼秉心，　具足諸行，　以斯禁戒，　寤諸不覺。",
    anchorText: "禁戒安隱，　不畏生死",
    note: "经文以护身口、持清净戒说明安隐不畏生死，并能觉悟未觉者。",
  },
  {
    id: "t0263-001-016",
    category: "濟乏行道",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "歡喜濟乏，　深自欣慶，　而建道行，　以此所施，　願求尊覺。",
    anchorText: "歡喜濟乏，　深自欣慶",
    note: "菩萨以布施济乏并建立道行，回向求尊觉。",
  },
  {
    id: "t0263-001-017",
    category: "大法將說",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "吾心惟忖，今者如來，當敷大法演無極典，散大法雨、擊大法鼓、吹大法螺，講無量法。",
    anchorText: "當敷大法演無極典",
    note: "文殊判断如来将敷演大法、无极典，雨法雨、击法鼓、吹法螺。",
  },
  {
    id: "t0263-001-018",
    category: "聞法除穢",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "諸如來、至真、等正覺，欲令眾生聽無極典，故現斯應。所以者何？世尊欲令群生洗除俗穢，聞服佛法，現弘大變光明神化。",
    anchorText: "欲令眾生聽無極典",
    note: "文殊明说佛现瑞应，是欲令众生听无极典、洗除俗秽、闻服佛法。",
  },
  {
    id: "t0263-001-019",
    category: "經法清淨",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "演說經典，初語亦善、中語亦善、竟語亦善，分別其誼微妙具足，究竟清淨修梵行，為聲聞乘講陳聖諦，則令眾庶度生老死憂惱眾患入近無為。為諸菩薩大士之眾，顯揚部分分別六度無極無上正真。",
    anchorText: "初語亦善、中語亦善、竟語亦善",
    note: "日月灯明佛所说经典初中后善，能令声闻度老死忧患，也为菩萨显扬六度无极。",
  },
  {
    id: "t0263-001-020",
    category: "法華聽受",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "佛三昧正受，從三昧起，為超光菩薩講正法華方等之業，諸菩薩行皆說佛法，一處安坐具足六十劫說斯經典，眾會亦然，身不傾動心無因緣。又彼世尊六十中劫，因為諸會說法，聽者一無疲厭心不勞擾。",
    anchorText: "為超光菩薩講正法華方等之業",
    note: "过去佛讲正法华方等之业，六十中劫说法，听众无疲厌、不劳扰。",
  },
  {
    id: "t0263-001-021",
    category: "供佛成佛",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "彼世尊子等類八人，皆歸超光菩薩大士而順教勅，咸志無上正真之道，見無央數億載諸佛，供養奉侍悉逮正覺，最後興者號曰法事。",
    anchorText: "見無央數億載諸佛，供養奉侍悉逮正覺",
    note: "八王子顺教志求无上道，见无数佛、供养奉侍，皆得成正觉。",
  },
  {
    id: "t0263-001-022",
    category: "今說正法華",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "是故當知，見此世尊所見瑞應放其光明，吾觀察之，今日大聖當為我等講《正法華》方等典籍。",
    anchorText: "今日大聖當為我等講《正法華》方等典籍",
    note: "光瑞品以文殊结论收束：今日佛现瑞光，是将为大众讲《正法华》。",
  },
  {
    id: "t0263-001-023",
    category: "法雨普潤",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "今者分別，　當雨法雨，　柔軟法教，　普潤飽滿，　履道意者。",
    anchorText: "當雨法雨，　柔軟法教",
    note: "文殊偈赞佛将雨法雨，以柔软法教普润履道者。",
  },
  {
    id: "t0263-001-024",
    category: "除疑去我",
    sectionTitle: GUANGRUI_SECTION_TITLE,
    text: "其有諸天，　入於無為，　志懷狐疑，　而有猶豫。　若有菩薩，　求斯道意，　今當蠲除，　吾我之想。",
    anchorText: "今當蠲除，　吾我之想",
    note: "品末指出此法将为有疑者除疑，并令求道菩萨蠲除吾我之想。",
  },
];
