import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const SHOUXUEWUXUERENJI_SECTION_TITLE = "授學無學人記品第九";

export const T0264_JUAN_4_SHOUXUEWUXUERENJI_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-004-023",
    category: "希求授記",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "爾時阿難、羅睺羅，而作是念：「我等每自思惟，設得授記，不亦快乎。」即從座起到於佛前，頭面禮足，俱白佛言：「世尊！我等於此亦應有分，唯有如來我等所歸，又我等為一切世間天、人、阿脩羅，所見知識，阿難常為侍者，護持法藏，羅睺羅是佛之子，若佛見授阿耨多羅三藐三菩提記者，我願既滿，眾望亦足。」",
    anchorText: "我等每自思惟，設得授記",
    note: "阿难与罗睺罗希求得佛授记，并以护持法藏、佛子身份表明本愿与众望。",
    occurrence: 1,
  },
  {
    id: "t0264-004-024",
    category: "一心請記",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "爾時學、無學聲聞弟子二千人，皆從座起，偏袒右肩到於佛前，一心合掌，瞻仰世尊，如阿難、羅睺羅所願，住立一面。",
    anchorText: "學、無學聲聞弟子二千人",
    note: "二千学无学声闻与阿难、罗睺罗同愿，一心合掌瞻仰世尊。",
    occurrence: 1,
  },
  {
    id: "t0264-004-025",
    category: "阿難授記",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "汝於來世當得作佛，號山海慧自在通王如來、應供、正遍知、明行足、善逝、世間解、無上士、調御丈夫、天人師、佛、世尊；當供養六十二億諸佛護持法藏，然後得阿耨多羅三藐三菩提；",
    anchorText: "號山海慧自在通王如來",
    note: "佛为阿难授记，未来供养诸佛、护持法藏，成山海慧自在通王如来。",
    occurrence: 1,
  },
  {
    id: "t0264-004-026",
    category: "教化菩薩",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "教化二十千萬億恒河沙諸菩薩等，令成阿耨多羅三藐三菩提；國名常立勝幡，其土清淨，琉璃為地，劫名妙音遍滿；",
    anchorText: "教化二十千萬億恒河沙諸菩薩等",
    note: "阿难未来成佛后教化无量菩萨成就无上菩提，佛土清净庄严。",
    occurrence: 1,
  },
  {
    id: "t0264-004-027",
    category: "諸佛讚歎",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "正法住世倍於壽命，像法住世復倍正法。阿難！是山海慧自在通王佛，為十方無量千萬億恒河沙等諸佛如來所共讚歎稱其功德。",
    anchorText: "為十方無量千萬億恒河沙等諸佛如來所共讚歎",
    note: "山海慧自在通王佛正法、像法久住，并为十方诸佛共同赞叹功德。",
    occurrence: 1,
  },
  {
    id: "t0264-004-028",
    category: "佛法因緣",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "我今僧中說，阿難持法者，當供養諸佛，然後成正覺；號曰山海慧，自在通王佛；其國土清淨，名常立勝幡，教化諸菩薩，其數如恒沙；佛有大威德，名聞滿十方，壽命無有量，以愍眾生故，正法倍壽命，像法復倍是；如恒河沙等，無數諸眾生，於此佛法中，種佛道因緣。",
    anchorText: "我今僧中說，阿難持法者",
    note: "偈颂重宣阿难持法、供佛成觉、教化菩萨，并令无数众生于其佛法中种佛道因缘。",
    occurrence: 1,
  },
  {
    id: "t0264-004-029",
    category: "本願護法",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "諸善男子！我與阿難等，於空王佛所，同時發阿耨多羅三藐三菩提心，阿難常樂多聞，我常勤精進，是故我已得成阿耨多羅三藐三菩提；而阿難護持我法，亦護將來諸佛法藏，教化成就諸菩薩眾，其本願如是，故獲斯記。",
    anchorText: "阿難護持我法，亦護將來諸佛法藏",
    note: "佛说明阿难得记的因缘：久远同发菩提心，阿难本愿护持诸佛法藏并教化菩萨。",
    occurrence: 1,
  },
  {
    id: "t0264-004-030",
    category: "聞記歡喜",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "阿難面於佛前，自聞授記及國土莊嚴，所願具足，心大歡喜，得未曾有；即時憶念過去無量千萬億諸佛法藏，通達無礙如今所聞，亦識本願。",
    anchorText: "自聞授記及國土莊嚴",
    note: "阿难闻授记与国土庄严，所愿具足，大欢喜并忆念过去诸佛法藏。",
    occurrence: 1,
  },
  {
    id: "t0264-004-031",
    category: "安住佛道",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "世尊甚希有，令我念過去，無量諸佛法，如今日所聞；我今無復疑，安住於佛道，方便為侍者，護持諸佛法。",
    anchorText: "我今無復疑，安住於佛道",
    note: "阿难偈颂赞叹世尊令其忆念过去佛法，安住佛道并护持诸佛法。",
    occurrence: 1,
  },
  {
    id: "t0264-004-032",
    category: "羅睺羅授記",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "汝於來世當得作佛，號蹈七寶華如來、應供、正遍知、明行足、善逝、世間解、無上士、調御丈夫、天人師、佛、世尊。當供養十世界微塵等數諸佛如來，常為諸佛而作長子，猶如今也。",
    anchorText: "號蹈七寶華如來",
    note: "佛为罗睺罗授记，未来成蹈七宝华如来，供养无量诸佛并常作佛长子。",
    occurrence: 1,
  },
  {
    id: "t0264-004-033",
    category: "求無上道",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "羅睺羅密行，惟我能知之，現為我長子，以示諸眾生，無量億千萬，功德不可數，安住於佛法，以求無上道。",
    anchorText: "羅睺羅密行，惟我能知之",
    note: "偈颂赞罗睺罗密行功德不可数，安住佛法而求无上道。",
    occurrence: 1,
  },
  {
    id: "t0264-004-034",
    category: "二千授記",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "阿難！是諸人等，當供養五十世界微塵數諸佛如來，恭敬、尊重、護持法藏，末後同時，於十方國各得成佛，皆同一號，名曰寶相如來、應供、正遍知、明行足、善逝、世間解、無上士、調御丈夫、天人師、佛、世尊，壽命一劫，國土莊嚴，聲聞、菩薩，正法、像法，皆悉同等。",
    anchorText: "當供養五十世界微塵數諸佛如來",
    note: "佛为二千学无学人授记，未来供养诸佛、护持法藏，并于十方国同成宝相如来。",
    occurrence: 1,
  },
  {
    id: "t0264-004-035",
    category: "護藏成覺",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "是二千聲聞，今於我前住，悉皆與授記，未來當成佛。所供養諸佛，如上說塵數，護持其法藏，後當成正覺。",
    anchorText: "是二千聲聞，今於我前住",
    note: "偈颂重宣二千声闻皆得授记，未来供佛护持法藏，后当成正觉。",
    occurrence: 1,
  },
  {
    id: "t0264-004-036",
    category: "神通度生",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "各於十方國，悉同一名號，俱時坐道場，以證無上慧。皆名為寶相，國土及弟子，正法與像法，悉等無有異。咸以諸神通，度十方眾生，名聞普周遍，漸入於涅槃。",
    anchorText: "各於十方國，悉同一名號",
    note: "二千声闻未来同号宝相，以神通度十方众生，名闻普遍。",
    occurrence: 1,
  },
  {
    id: "t0264-004-037",
    category: "甘露歡喜",
    sectionTitle: SHOUXUEWUXUERENJI_SECTION_TITLE,
    text: "爾時學、無學二千人，聞佛授記歡喜踊躍，而說偈言：「世尊慧燈明，我聞授記音，心歡喜充滿，如甘露見灌。」",
    anchorText: "聞佛授記歡喜踊躍",
    note: "二千学无学人闻佛授记，欢喜充满，如甘露灌顶。",
    occurrence: 1,
  },
];