import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const PIYU_SECTION_TITLE = "譬喻品第三";

export const T0264_JUAN_2_SLANDER_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-002-052",
    category: "慎勿妄說",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "又舍利弗！憍慢懈怠，計我見者，莫說此經；凡夫淺識，深著五欲，聞不能解，亦勿為說。",
    anchorText: "憍慢懈怠，計我見者，莫說此經",
    note: "佛诫示此经不宜随意为憍慢、懈怠、执我见及深著五欲者宣说。",
    occurrence: 1,
  },
  {
    id: "t0264-002-053",
    category: "毀謗斷種",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若人不信，毀謗此經，則斷一切，世間佛種；或復嚬蹙，而懷疑惑，汝當聽說，此人罪報。",
    anchorText: "若人不信，毀謗此經，則斷一切，世間佛種",
    note: "经文明确警示不信毁谤此经，会断世间佛种，并引出罪报说明。",
    occurrence: 1,
  },
  {
    id: "t0264-002-054",
    category: "誹謗持經",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若佛在世，若滅度後，其有誹謗，如斯經典；見有讀誦，書持經者，輕賤憎嫉，而懷結恨，此人罪報，汝今復聽。",
    anchorText: "見有讀誦，書持經者，輕賤憎嫉",
    note: "佛说明在佛世或灭后，诽谤经典、轻贱憎嫉读诵书持者，皆属重罪因缘。",
    occurrence: 1,
  },
  {
    id: "t0264-002-055",
    category: "阿鼻罪報",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "其人命終，入阿鼻獄，具足一劫，劫盡更生，如是展轉，至無數劫；",
    anchorText: "其人命終，入阿鼻獄，具足一劫",
    note: "毁谤此经者命终入阿鼻狱，展转至无数劫，显示罪报极重。",
    occurrence: 1,
  },
  {
    id: "t0264-002-056",
    category: "畜生罪報",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "從地獄出，當墮畜生，若狗野干，其形𩑔瘦，黧黮疥癩，人所觸嬈，又復為人，之所惡賤，常困飢渴，骨肉枯竭；生受楚毒，死被瓦石，斷佛種故，受斯罪報。",
    anchorText: "從地獄出，當墮畜生，若狗野干",
    note: "经文续说从地狱出后仍堕畜生，因断佛种而受饥渴、恶贱等苦报。",
    occurrence: 1,
  },
  {
    id: "t0264-002-057",
    category: "謗經受苦",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若作駱駝，或生驢中，身常負重，加諸杖捶，但念水草，餘無所知；謗斯經故，獲罪如是。",
    anchorText: "謗斯經故，獲罪如是",
    note: "经文以骆驼、驴身负重受打为喻，明示谤经所得苦报。",
    occurrence: 1,
  },
  {
    id: "t0264-002-058",
    category: "晝夜受苦",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "有作野干，來入聚落，身體疥癩，又無一目，為諸童子，之所打擲，受諸苦痛，或時致死；於此死已，更受蟒身，其形長大，五百由旬，聾騃無足，宛轉腹行；為諸小虫，之所唼食，晝夜受苦，無有休息；謗斯經故，獲罪如是。",
    anchorText: "晝夜受苦，無有休息",
    note: "毁谤此经的罪报在偈中层层展开，乃至昼夜受苦、无有休息。",
    occurrence: 1,
  },
  {
    id: "t0264-002-059",
    category: "人中衰苦",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若得為人，諸根闇鈍，矬陋攣躄，盲聾背傴，有所言說，人不信受；口氣常臭，鬼魅所著，貧窮下賤，為人所使；多病痟瘦，無所依怙，雖親附人，人不在意；",
    anchorText: "若得為人，諸根闇鈍",
    note: "经文说明谤经者即使得为人身，亦有诸根暗钝、贫病下贱、无人依怙等衰苦。",
    occurrence: 1,
  },
  {
    id: "t0264-002-060",
    category: "不見不聞",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "如斯罪人，永不見佛，眾聖之王，說法教化。如斯罪人，常生難處；狂聾心亂，永不聞法，於無數劫，如恒河沙；",
    anchorText: "永不見佛，眾聖之王，說法教化",
    note: "经文特别指出此类罪人永不见佛说法教化，常生难处，永不闻法。",
    occurrence: 1,
  },
  {
    id: "t0264-002-061",
    category: "罪不可盡",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "告舍利弗：「謗斯經者；若說其罪，窮劫不盡；以是因緣，我故語汝，無智人中，莫說此經。",
    anchorText: "謗斯經者；若說其罪，窮劫不盡",
    note: "佛总结谤经之罪穷劫难尽，因此嘱咐不要在无智人中妄说此经。",
    occurrence: 1,
  },
  {
    id: "t0264-002-062",
    category: "利根可說",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若有利根，智慧明了；多聞強識，求佛道者，如是之人，乃可為說。",
    anchorText: "利根，智慧明了；多聞強識，求佛道者",
    note: "佛说明利根、智慧明了、多闻强识、求佛道者，才是适合宣说此经的对象。",
    occurrence: 1,
  },
  {
    id: "t0264-002-063",
    category: "善本堅固",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若人曾見，億百千佛，殖諸善本，深心堅固；如是之人，乃可為說。",
    anchorText: "曾見，億百千佛，殖諸善本，深心堅固",
    note: "曾见众佛、殖诸善本、深心坚固者，具备信受此经的根基。",
    occurrence: 1,
  },
  {
    id: "t0264-002-064",
    category: "精進慈心",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若人精進，常修慈心；不惜身命，乃可為說。",
    anchorText: "精進，常修慈心；不惜身命",
    note: "精进、常修慈心、不惜身命者，是佛所许可宣说此经的对象。",
    occurrence: 1,
  },
  {
    id: "t0264-002-065",
    category: "恭敬離愚",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若人恭敬，無有異心；離諸凡愚，獨處山澤，如是之人，乃可為說。",
    anchorText: "恭敬，無有異心；離諸凡愚",
    note: "恭敬无异心、远离凡愚而清修者，适合听受此经。",
    occurrence: 1,
  },
  {
    id: "t0264-002-066",
    category: "親近善友",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "又舍利弗！若見有人，捨惡知識，親近善友；如是之人，乃可為說。",
    anchorText: "捨惡知識，親近善友",
    note: "舍恶知识、亲近善友者，被列为可为宣说《妙法华经》之人。",
    occurrence: 1,
  },
  {
    id: "t0264-002-067",
    category: "求大乘經",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若見佛子，持戒清潔，如淨明珠，求大乘經；如是之人，乃可為說。",
    anchorText: "持戒清潔，如淨明珠，求大乘經",
    note: "持戒清洁、求大乘经的佛子，是适宜宣说此经的对象。",
    occurrence: 1,
  },
  {
    id: "t0264-002-068",
    category: "柔軟敬佛",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若人無瞋，質直柔軟，常愍一切，恭敬諸佛；如是之人，乃可為說。",
    anchorText: "無瞋，質直柔軟，常愍一切",
    note: "无嗔、质直柔软、愍念一切并恭敬诸佛者，堪受此经。",
    occurrence: 1,
  },
  {
    id: "t0264-002-069",
    category: "說法無礙",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "復有佛子，於大眾中，以清淨心，種種因緣，譬喻言辭，說法無礙；如是之人，乃可為說。",
    anchorText: "以清淨心，種種因緣，譬喻言辭，說法無礙",
    note: "能以清净心于大众中用因缘譬喻无碍说法者，可为宣说此经。",
    occurrence: 1,
  },
  {
    id: "t0264-002-070",
    category: "頂受大乘",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "若有比丘，為一切智，四方求法，合掌頂受，但樂受持，大乘經典，乃至不受，餘經一偈；如是之人，乃可為說。",
    anchorText: "為一切智，四方求法，合掌頂受",
    note: "为一切智而四方求法、合掌顶受、乐受持大乘经典者，堪闻此经。",
    occurrence: 1,
  },
  {
    id: "t0264-002-071",
    category: "至心求經",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "如人至心，求佛舍利，如是求經，得已頂受，其人不復，志求餘經，亦未曾念，外道典籍；如是之人，乃可為說。",
    anchorText: "如人至心，求佛舍利，如是求經",
    note: "经文赞如求佛舍利般至心求经、得已顶受且不志求外典者，可为说此经。",
    occurrence: 1,
  },
  {
    id: "t0264-002-072",
    category: "信解妙法",
    sectionTitle: PIYU_SECTION_TITLE,
    text: "告舍利弗：「我說是相，求佛道者，窮劫不盡，如是等人，則能信解；汝當為說，《妙法華經》。」",
    anchorText: "如是等人，則能信解；汝當為說",
    note: "佛总结这些求佛道者能够信解，应为他们宣说《妙法华经》。",
    occurrence: 1,
  },
];
