import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const JIANBAOTA_SECTION_TITLE = "見寶塔品第十一";

export const T0264_JUAN_4_JIANBAOTA_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-004-071",
    category: "经文证信",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "爾時寶塔中出大音聲歎言：「善哉，善哉！釋迦牟尼世尊！能以平等大慧教菩薩法，佛所護念《妙法華經》，為大眾說。如是，如是！釋迦牟尼世尊！如所說者皆是真實。」",
    anchorText: "能以平等大慧教菩薩法，佛所護念《妙法華經》",
    note: "多寶佛塔出聲證成佛所說《妙法華經》真實可信。",
  },
  {
    id: "t0264-004-072",
    category: "闻法欢喜",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "爾時四眾見大寶塔住在空中，又聞塔中所出音聲，皆得法喜，怪未曾有，從座而起，恭敬合掌，却住一面。",
    anchorText: "又聞塔中所出音聲，皆得法喜",
    note: "大众见塔闻声，生起未曾有的法喜与恭敬。",
  },
  {
    id: "t0264-004-073",
    category: "经处证明",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "若我成佛，滅度之後，於十方國土有說《法華經》處，我之塔廟，為聽是經故，踊現其前，為作證明，讚言善哉。",
    anchorText: "於十方國土有說《法華經》處，我之塔廟",
    note: "经中明示：凡有说《法华经》处，多宝塔为听经、证明而现前。",
  },
  {
    id: "t0264-004-074",
    category: "多宝赞经",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "十方世界在在處處，若有說《法華經》者，彼之寶塔，皆踊出其前，全身在於塔中讚言：『善哉，善哉！』",
    anchorText: "若有說《法華經》者，彼之寶塔，皆踊出其前",
    note: "此经受多宝如来愿力护持，所说之处皆有宝塔赞叹。",
  },
  {
    id: "t0264-004-075",
    category: "诸佛听法",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "爾時十方諸佛，各告眾菩薩言：「善男子！我今應往娑婆世界釋迦牟尼佛所，并供養多寶如來寶塔。」",
    anchorText: "我今應往娑婆世界釋迦牟尼佛所",
    note: "十方诸佛为此会而来，显示此经法会殊胜难遇。",
  },
  {
    id: "t0264-004-076",
    category: "多宝为法",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "聖主世尊，雖久滅度，在寶塔中，尚為法來；諸人云何，不勤為法？",
    anchorText: "雖久滅度，在寶塔中，尚為法來",
    note: "多宝佛久灭度尚为法而来，劝勉众人勤求护持此法。",
  },
  {
    id: "t0264-004-077",
    category: "令法久住",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "天人龍神，諸供養事，令法久住，故來至此；為坐諸佛，以神通力，移無量眾，令國清淨。",
    anchorText: "天人龍神，諸供養事，令法久住",
    note: "诸佛、天龙等供养集会，目的在令此法久住世间。",
  },
  {
    id: "t0264-004-078",
    category: "众生蒙益",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "身出妙香，遍十方國，眾生蒙熏，喜不自勝。譬如大風，吹小樹枝；以是方便，令法久住。",
    anchorText: "身出妙香，遍十方國，眾生蒙熏",
    note: "诸佛来集之瑞相令众生欢喜，并成就令法久住的方便。",
  },
  {
    id: "t0264-004-079",
    category: "护经供佛",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "諸佛子等！誰能護法，當發大願，令得久住；其有能護，此經法者，則為供養，我及多寶。",
    anchorText: "其有能護，此經法者，則為供養",
    note: "护持此经即是供养释迦牟尼佛与多宝如来。",
  },
  {
    id: "t0264-004-080",
    category: "说经见佛",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "若說此經，則為見我，多寶如來，及諸化佛。",
    anchorText: "若說此經，則為見我",
    note: "能说此经，即如得见释迦、多宝与诸化佛。",
  },
  {
    id: "t0264-004-081",
    category: "恶世说经",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "若佛滅後，於惡世中，能說此經，是則為難。",
    anchorText: "若佛滅後，於惡世中，能說此經",
    note: "佛灭后恶世能宣说此经，较诸难事更为稀有难得。",
  },
  {
    id: "t0264-004-082",
    category: "书持难得",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "於我滅後，若自書持，若使人書，是則為難。",
    anchorText: "若自書持，若使人書",
    note: "佛灭后能自行书持或使人书写此经，极为难得。",
  },
  {
    id: "t0264-004-083",
    category: "读经难得",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "佛滅度後，於惡世中，暫讀此經，是則為難。",
    anchorText: "於惡世中，暫讀此經",
    note: "恶世中片刻读诵此经，也被佛赞为难能可贵。",
  },
  {
    id: "t0264-004-084",
    category: "为人说经",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "我滅度後，若持此經，為一人說，是則為難。",
    anchorText: "若持此經，為一人說",
    note: "佛灭后能持此经并为一人宣说，即是难行之行。",
  },
  {
    id: "t0264-004-085",
    category: "听受问义",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "於我滅後，聽受此經，問其義趣，是則為難。",
    anchorText: "聽受此經，問其義趣",
    note: "灭后能听受此经并探问义趣，同样为佛所赞的难事。",
  },
  {
    id: "t0264-004-086",
    category: "奉持难得",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "於我滅後，若能奉持，如斯經典，是則為難。",
    anchorText: "若能奉持，如斯經典",
    note: "能于佛灭后奉持此经，胜过许多世间难行之事。",
  },
  {
    id: "t0264-004-087",
    category: "经中第一",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "我為佛道，於無量土，從始至今，廣說諸經；而於其中，此經第一，若有能持，則持佛身。",
    anchorText: "而於其中，此經第一",
    note: "佛明说诸经之中此经第一，能持此经则如持佛身。",
  },
  {
    id: "t0264-004-088",
    category: "诸佛欢喜",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "此經難持，若暫持者，我則歡喜，諸佛亦然。",
    anchorText: "此經難持，若暫持者",
    note: "即使暂时受持此经，也令释迦与诸佛欢喜。",
  },
  {
    id: "t0264-004-089",
    category: "诸佛赞叹",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "如是之人，諸佛所歎；是則勇猛，是則精進，是名持戒，行頭陀者，則為疾得，無上佛道。",
    anchorText: "如是之人，諸佛所歎",
    note: "受持此经者为诸佛所赞，称为勇猛精进，速得无上佛道。",
  },
  {
    id: "t0264-004-090",
    category: "真佛子",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "能於來世，讀持此經，是真佛子，住純善地。",
    anchorText: "能於來世，讀持此經",
    note: "来世能读持此经者，经中称为真佛子，住纯善地。",
  },
  {
    id: "t0264-004-091",
    category: "世间之眼",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "佛滅度後，能解其義，是諸天人，世間之眼，於恐畏世，能須臾說；一切天人，皆應供養。",
    anchorText: "佛滅度後，能解其義",
    note: "灭后能解此经义、须臾宣说者，是世间之眼，天人皆应供养。",
  },
  {
    id: "t0264-004-092",
    category: "求法不倦",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "吾於過去無量劫中，求《法華經》無有懈倦；於多劫中常作國王，發願求於無上菩提，心不退轉，",
    anchorText: "求《法華經》無有懈倦",
    note: "佛自述宿世为求《法华经》无有懈倦，显此经难值可贵。",
  },
  {
    id: "t0264-004-093",
    category: "为法勤求",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "情存妙法故，身心無懈倦，普為諸眾生，勤求於大法；亦不為己身，及以五欲樂，故為大國王，勤求獲此法，遂致得成佛，今故為汝說。",
    anchorText: "普為諸眾生，勤求於大法",
    note: "为众生勤求妙法而不懈，终致成佛，显示求持此法的深远利益。",
  },
  {
    id: "t0264-004-094",
    category: "善知识益",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "由提婆達多善知識故，令我具足六波羅蜜，慈、悲、喜、捨，三十二相、八十種好、紫磨金色，十力、四無所畏，四攝法，十八不共神通道力，成等正覺廣度眾生，皆因提婆達多善知識故。",
    anchorText: "由提婆達多善知識故，令我具足六波羅蜜",
    note: "经中以提婆达多作善知识，说明善知识因缘能助成佛道功德。",
  },
  {
    id: "t0264-004-095",
    category: "授记成佛",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "告諸四眾，提婆達多却後過無量劫，當得成佛，號曰天王如來、應供、正遍知、明行足、善逝、世間解、無上士、調御丈夫、天人師、佛、世尊，世界名天道。",
    anchorText: "提婆達多却後過無量劫，當得成佛",
    note: "提婆达多得授记未来成佛，彰显此品的授记与成佛因缘。",
  },
  {
    id: "t0264-004-096",
    category: "闻品信敬",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "未來世中，若有善男子、善女人，聞此《妙法蓮華經》品，聞已淨心信敬，不生疑惑者，不墮地獄，餓鬼，畜生，生十方佛前；所生之處常聞此經；若生天人中受勝妙樂，若在佛前蓮華化生。",
    anchorText: "聞此《妙法蓮華經》品，聞已淨心信敬",
    note: "未来闻此品而净心信敬、不疑者，离三恶道，常闻此经，乃至佛前莲华化生。",
  },
  {
    id: "t0264-004-097",
    category: "宣说法华",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "文殊師利言：「我於海中，唯常宣說《妙法華經》。",
    anchorText: "我於海中，唯常宣說《妙法華經》",
    note: "文殊师利在龙宫常宣说此经，成为海中教化的根本。",
  },
  {
    id: "t0264-004-098",
    category: "经中之宝",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "此經甚深微妙，諸經中寶，世所希有；頗有眾生，勤加精進修行此經，速得佛不？",
    anchorText: "此經甚深微妙，諸經中寶",
    note: "智积菩萨称此经甚深微妙、诸经中宝、世所希有。",
  },
  {
    id: "t0264-004-099",
    category: "速得菩提",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "有娑竭羅龍王女，年始八歲，智慧利根，善知眾生諸根行業，得陀羅尼，諸佛所說甚深祕藏悉能受持，深入禪定了達諸法，於剎那頃發菩提心，得不退轉，辯才無礙；慈念眾生，猶如赤子，功德具足，心念口演，微妙廣大，慈悲仁讓，志意和雅，能至菩提。",
    anchorText: "於剎那頃發菩提心，得不退轉",
    note: "龙女受持甚深秘藏，剎那发心不退，具足功德而能至菩提。",
  },
  {
    id: "t0264-004-100",
    category: "大乘度生",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "有聞成菩提，唯佛當證知；我闡大乘教，度脫苦眾生。",
    anchorText: "我闡大乘教，度脫苦眾生",
    note: "龙女偈中明示大乘教能度脱苦众生，成菩提唯佛证知。",
  },
  {
    id: "t0264-004-101",
    category: "龍女成佛",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "當時眾會，皆見龍女忽然之間變成男子，具菩薩行，即往南方無垢世界，坐寶蓮華成等正覺，三十二相、八十種好，普為十方一切眾生演說妙法。",
    anchorText: "坐寶蓮華成等正覺",
    note: "龙女疾速成等正觉，并为十方众生演说妙法。",
  },
  {
    id: "t0264-004-102",
    category: "闻法得益",
    sectionTitle: JIANBAOTA_SECTION_TITLE,
    text: "無量眾生，聞法解悟得不退轉；無量眾生得受道記，無垢世界六反震動；娑婆世界三千眾生住不退地，三千眾生發菩提心而得受記。",
    anchorText: "聞法解悟得不退轉",
    note: "龙女说法后，无量众生解悟不退、得受道记，娑婆众生亦发心受记。",
  },
];
