import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const SUIXI_GONGDE_SECTION_TITLE = "隨喜功德品第十七";

export const T0264_JUAN_6_SUIXI_GONGDE_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-006-001",
    category: "闻经随喜转教",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "如來滅後，若比丘、比丘尼、優婆塞、優婆夷，及餘智者若長、若幼，聞是經隨喜已，從法會出至於餘處，若在僧坊，若空閑地，若城邑、巷陌、聚落、田里，如其所聞，為父母、宗親、善友、知識，隨力演說，是諸人等聞已隨喜，復行轉教，餘人聞已亦隨喜轉教，如是展轉至第五十。",
    anchorText: "聞是經隨喜已，從法會出至於餘處",
    note: "佛灭后闻《法华经》随喜，并随力为亲友知识演说、辗转教化，乃至第五十人，皆成随喜功德之缘。",
  },
  {
    id: "t0264-006-002",
    category: "第五十人功德",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "其第五十善男子、善女人隨喜功德，我今說之，汝當善聽。",
    anchorText: "第五十善男子、善女人隨喜功德",
    note: "佛特为弥勒说明第五十位辗转闻经随喜者的功德。",
  },
  {
    id: "t0264-006-003",
    category: "布施教化功德无量",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "是人功德甚多，無量無邊；若是施主，但施眾生一切樂具，功德無量，何況令得阿羅漢果。",
    anchorText: "是人功德甚多，無量無邊",
    note: "弥勒确认：广施众生并令得阿罗汉果，功德无量无边。",
  },
  {
    id: "t0264-006-004",
    category: "一偈随喜胜大布施",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "是人以一切樂具，施於四百萬億阿僧祇世界六趣眾生，又令得阿羅漢果，所得功德，不如是第五十人聞《法華經》一偈隨喜功德，百分、千分、百千萬億分，不及其一，乃至算數譬喻所不能知。",
    anchorText: "不如是第五十人聞《法華經》一偈隨喜功德",
    note: "即使广施无量众生并令证果，其功德仍不及第五十人闻《法华经》一偈随喜。",
  },
  {
    id: "t0264-006-005",
    category: "初闻随喜福更胜",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "如是第五十人，展轉聞《法華經》隨喜功德，尚無量無邊阿僧祇，何況最初於會中聞而隨喜者，其福復勝無量無邊阿僧祇不可得比。",
    anchorText: "何況最初於會中聞而隨喜者",
    note: "第五十人功德尚无量，最初在法会中闻经随喜者，其福更胜不可比。",
  },
  {
    id: "t0264-006-006",
    category: "须臾听受得妙乘具",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "若人為是經故，往詣僧坊，若坐、若立須臾聽受，緣是功德轉身所生，得好上妙象、馬、車乘、珍寶輦輿及乘天宮；",
    anchorText: "若坐、若立須臾聽受",
    note: "为此经故前往听受，乃至须臾之间，来世得上妙车乘、珍宝辇舆及天宫。",
  },
  {
    id: "t0264-006-007",
    category: "劝坐听法得尊贵座",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "若復有人於講法處坐，更有人來，勸令坐聽，若分座令坐，是人功德，轉身得帝釋坐處，若梵王坐處，若轉輪聖王所坐之處。",
    anchorText: "勸令坐聽，若分座令坐",
    note: "在讲法处劝人坐听、分座令坐，来世得帝释、梵王或转轮圣王所坐之处。",
  },
  {
    id: "t0264-006-008",
    category: "劝往听经智慧利根",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "若復有人語餘人言，有經名《法華》，可共往聽，即受其教，乃至須臾間聞，是人功德，轉身得與陀羅尼菩薩共生一處，利根智慧，百千萬世終不瘖瘂，",
    anchorText: "有經名《法華》，可共往聽",
    note: "劝人共同往听《法华经》，对方乃至须臾闻受，功德令其与陀罗尼菩萨共生，利根智慧。",
  },
  {
    id: "t0264-006-009",
    category: "口齿端严无诸病患",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "口氣不臭，舌常無病，口亦無病，齒不垢黑，不黃、不踈，亦不缺落，不差、不曲，唇不下垂，亦不褰縮、不麁澁、不瘡胗，亦不缺壞，亦不喎斜，不厚、不大，亦不黧黑，無諸可惡；",
    anchorText: "口氣不臭，舌常無病",
    note: "劝听受教之功德，感得口气清净、舌口无病、齿唇端严。",
  },
  {
    id: "t0264-006-010",
    category: "人相具足见佛闻法",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "面貌圓滿，眉高而長，額廣平正，人相具足，世世所生，見佛聞法，信受教誨。",
    anchorText: "世世所生，見佛聞法",
    note: "劝人听经者世世人相具足，得见佛闻法并信受教诲。",
  },
  {
    id: "t0264-006-011",
    category: "劝一人听法功德如此",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "汝且觀是勸於一人令往聽法，功德如此，何況一心聽說、讀誦，而於大眾為人分別如說修行。",
    anchorText: "勸於一人令往聽法，功德如此",
    note: "仅劝一人往听法功德已如此，何况一心听说、读诵、为大众分别并如说修行。",
  },
  {
    id: "t0264-006-012",
    category: "闻偈随喜为他说",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "若人於法會，得聞是經典，乃至於一偈，隨喜為他說；如是展轉教，至于第五十，最後人獲福，今當分別之。",
    anchorText: "乃至於一偈，隨喜為他說",
    note: "偈颂重申：法会中闻经乃至一偈，随喜并为他人说，展转至第五十人亦获福。",
  },
  {
    id: "t0264-006-013",
    category: "第五十福胜不可喻",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "最後第五十，聞一偈隨喜，是人福勝彼，不可為譬喻。如是展轉聞，其福尚無量，何況於法會，初聞隨喜者。",
    anchorText: "聞一偈隨喜，是人福勝彼",
    note: "偈颂说明第五十人闻一偈随喜之福胜过前喻，初闻随喜者更无量。",
  },
  {
    id: "t0264-006-014",
    category: "经深妙难遇",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "若有勸一人，將引聽《法華》，言此經深妙，千萬劫難遇。",
    anchorText: "言此經深妙，千萬劫難遇",
    note: "劝人听《法华》时，经文直称此经深妙，千万劫难遇。",
  },
  {
    id: "t0264-006-015",
    category: "须臾闻福报端严",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "即受教往聽，乃至須臾聞，斯人之福報，今當分別說。世世無口患，齒不踈黃黑；唇不厚褰缺，無有可惡相。舌不乾黑短，鼻高脩且直；額廣而平正，面目悉端嚴。為人所憙見，口氣無臭穢，優鉢華之香，常從其口出。",
    anchorText: "即受教往聽，乃至須臾聞",
    note: "受劝往听乃至须臾闻经，福报表现为世世无口患、面目端严、为人喜见。",
  },
  {
    id: "t0264-006-016",
    category: "须臾闻欢喜得天人妙报",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "若故詣僧坊，欲聽《法華經》，須臾聞歡喜，今當說其福。後生天人中，得妙象馬車，珍寶之輦輿，及乘天宮殿。",
    anchorText: "須臾聞歡喜",
    note: "故往僧坊欲听《法华经》，须臾闻而欢喜，后生天人中得妙象马车、珍宝辇舆及天宫殿。",
  },
  {
    id: "t0264-006-017",
    category: "劝人坐听得释梵轮王座",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "若於講法處，勸人坐聽經，是福因緣得，釋梵轉輪座。",
    anchorText: "勸人坐聽經",
    note: "偈颂重申在讲法处劝人坐听经，以此福因缘得释、梵、转轮王座。",
  },
  {
    id: "t0264-006-018",
    category: "一心听修福不可限",
    sectionTitle: SUIXI_GONGDE_SECTION_TITLE,
    text: "何況一心聽，解說其義趣，如說而修行，其福不可限。",
    anchorText: "如說而修行，其福不可限",
    note: "一心听受、解说义趣并如说修行，其福不可限量。",
  },
];