import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const YUFU_SECTION_TITLE = "御福事品第十六";
const QUANZHU_SECTION_TITLE = "勸助品第十七";

export const T0263_JUAN_8_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-001",
    category: "聞經得忍",
    text: "欲知今佛說此如來壽限經典之時，六十八億那術百千江河沙等諸菩薩，逮不起法忍。",
    anchorText: "今佛說此如來壽限經典之時",
    note: "本品承接如来寿量法门，说明佛说此经时无量菩萨得不起法忍。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-002",
    category: "總持辯才",
    text: "二千江河沙菩薩大士，皆得總持。如一佛世界塵數菩薩大士，逮得無礙辯才總持。",
    anchorText: "二千江河沙菩薩大士，皆得總持",
    note: "经文直陈闻寿量经后菩萨得总持与无碍辩才总持。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-003",
    category: "不退法輪",
    text: "復有如千佛世界塵數菩薩大士，聞是經典，轉不退轉法輪。",
    anchorText: "聞是經典，轉不退轉法輪",
    note: "听闻此经典者能转不退转法轮，是本品明确列出的闻法利益。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-004",
    category: "當成正覺",
    text: "復有如佛小千世界塵數菩薩，聞斯經典，逮得八生住，當成無上正真道。",
    anchorText: "聞斯經典，逮得八生住",
    note: "经文以八生住说明闻经菩萨将成无上正真道。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-005",
    category: "一生補處",
    text: "復有如四天下塵數菩薩大士，聞斯法已，得一生補處，當成正覺。",
    anchorText: "聞斯法已，得一生補處",
    note: "闻斯法已得一生补处，是本品对闻法果德的直接陈述。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-006",
    category: "發無上道",
    text: "復有如八佛世界塵數黎庶，聞是經典，悉發無上正真之道。",
    anchorText: "聞是經典，悉發無上正真之道",
    note: "无量众生闻此经典而发无上正真道心。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-007",
    category: "諸天供養",
    text: "佛這說斯諸菩薩大士，尋則建立，應時虛空雨諸天華，意華及大意華，紛紛如雪，以散無數百千世界億百千姟諸佛世尊，故來垂恩坐師子床七寶樹下，及能仁大聖上，其無央數不可稱限，諸滅度佛并多寶佛身，地即大動，及雨一切諸菩薩上。",
    anchorText: "應時虛空雨諸天華",
    note: "闻法大众建立功德后，虚空雨天华供养诸佛，显发此法会殊胜。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-008",
    category: "彌勒讚歎",
    text: "今日我已，所聞經典，面觀安住，現分別說。建立眾生，億百千數，大聖導師，於世殊特，不退轉輪，住於佛道。",
    anchorText: "今日我已，所聞經典",
    note: "弥勒偈赞此经能建立亿百千众生，令住佛道、不退转轮。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-009",
    category: "聞經成道",
    text: "緣從導師，聞是經典，當得佛道，顯第一誼。",
    anchorText: "聞是經典，當得佛道",
    note: "偈中以简明语句赞叹从导师闻此经典者当得佛道。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-010",
    category: "聞經發心",
    text: "若有黎庶，億數聽經，聞是皆發，殊勝道意。",
    anchorText: "若有黎庶，億數聽經",
    note: "亿数众生听闻此经，皆发殊胜道意。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-011",
    category: "功德難量",
    text: "其聞如來所現壽命所說經法，發意頃生快心篤信者，所得功德不可稱量。",
    anchorText: "發意頃生快心篤信者，所得功德不可稱量",
    note: "佛明说闻如来寿命经法，一念欢喜笃信，功德不可称量。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-012",
    category: "勝五度福",
    text: "不如族姓子、族姓女，聞斯如來壽命之限，發意之頃歡喜信樂，而不狐疑若干種行歸一道者，欲知功德，勝于八億百千劫行五度無極，百倍千倍萬倍億億倍巨億萬倍，福不可譬，無以為喻。",
    anchorText: "聞斯如來壽命之限，發意之頃歡喜信樂",
    note: "此段以长劫修五度作比较，显示闻寿量而欢喜信乐的功德超胜难喻。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-013",
    category: "堅住正覺",
    text: "族姓子、族姓女聞斯經法，一發意頃歡喜信者，則為堅住無上正真道成最正覺。",
    anchorText: "聞斯經法，一發意頃歡喜信者",
    note: "佛直接说闻此经法一念欢喜信者，坚住无上正真道。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-014",
    category: "信聞最上",
    text: "若男子女人，其聞佛壽限，一時歡喜信，此德為最上。",
    anchorText: "其聞佛壽限，一時歡喜信",
    note: "偈颂将听闻佛寿量并一时欢喜信受称为最上之德。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-015",
    category: "信樂大法",
    text: "當棄捐猶豫，諸著思想事，信樂大法誼，其福為若斯。",
    anchorText: "當棄捐猶豫，諸著思想事",
    note: "经文劝舍疑与执著，信乐大法义，所得福德如上所说。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-016",
    category: "受持曉了",
    text: "其有聞說如來壽經者，入中受持分別曉了，其得福德不可稱限。",
    anchorText: "入中受持分別曉了，其得福德不可稱限",
    note: "闻说如来寿经后受持、分别晓了，福德不可称限。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-017",
    category: "書寫供養",
    text: "其聞是經，即持書寫已，載於竹帛供養奉事，散華燒香、搗香雜香、繒綵幢幡，麻油燈香、油燈醍醐燈，其福過彼甚多無數，當致如來慧見之事，猶如阿逸。",
    anchorText: "其聞是經，即持書寫已",
    note: "闻经后书写并以香华灯幡供养，福德甚多无数，并趋向如来慧见。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-018",
    category: "如來擁護",
    text: "如來滅度後族姓子女，聞此經卷亦不誹謗，歡樂受持，則為如來所見擁護。",
    anchorText: "聞此經卷亦不誹謗，歡樂受持",
    note: "佛灭后闻此经卷、不谤且欢喜受持者，为如来所见护念。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-019",
    category: "超諸供養",
    text: "其族姓子，超於興起為佛塔廟，起於建立精舍講堂，超於瞻視比丘疾病，而給醫藥供養之具。",
    anchorText: "超於興起為佛塔廟",
    note: "经文以造塔、建精舍、给病医药等供养作比较，显出受持此经者功德超胜。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-020",
    category: "持說福勝",
    text: "佛滅度後其有得聞此經典者，持讀書寫若分別說，福勝無量。",
    anchorText: "持讀書寫若分別說，福勝無量",
    note: "佛灭后得闻此经并持、读、书写、分别解说，福德殊胜无量。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-021",
    category: "增福滅罪",
    text: "幡蓋校飾，勸助福故，稍稍轉具而滅除罪，靡不粲麗。",
    anchorText: "勸助福故，稍稍轉具而滅除罪",
    note: "供养、劝助与受持相连，能渐具福德并灭除罪障。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-022",
    category: "持經具辯",
    text: "其有持此經，於亂講說法，以為具足辯，斯若干供養。",
    anchorText: "其有持此經，於亂講說法",
    note: "偈中赞持此经者能于乱世讲说法，具足辩才，等同成办若干供养。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-023",
    category: "讀寫福勝",
    text: "如來滅度後，若讀誦寫經，歡喜如信樂，其得福無量，超餘福之上。",
    anchorText: "若讀誦寫經，歡喜如信樂",
    note: "如来灭后读诵写经并欢喜信乐，所得福德无量，超过余福。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-024",
    category: "奉經福多",
    text: "其人奉經卷，供養當如是，得福甚眾多，其限不可量。",
    anchorText: "其人奉經卷，供養當如是",
    note: "奉持经卷并如法供养，得福众多不可限量。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-025",
    category: "福如虛空",
    text: "譬如虛空界，其限不可得，十方之無量，其福比如是。",
    anchorText: "譬如虛空界，其限不可得",
    note: "以虚空和十方无量为喻，赞叹供养奉经者福德广大。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-026",
    category: "功德難限",
    text: "假使如是像，持殊勝經者，其人功德品，不可得限量。",
    anchorText: "持殊勝經者，其人功德品",
    note: "持此殊胜经者，其功德不可限量。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-027",
    category: "敬奉法師",
    text: "設使人見此，如是像法師，當持此經卷，奉敬加供養。",
    anchorText: "如是像法師，當持此經卷",
    note: "见持经法师，应持此经卷并恭敬供养。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-028",
    category: "當成佛道",
    text: "當覺成佛，所在供養，為饒利益，諸天世間。",
    anchorText: "當覺成佛，所在供養",
    note: "经文令见者思惟此持经者当觉成佛，利益诸天世间。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-029",
    category: "常演如來經",
    text: "臥在床榻，若著衣服，而常講演，斯如來經。",
    anchorText: "而常講演，斯如來經",
    note: "持经法师无论行住坐卧，常讲演如来经法。",
  },
  {
    sectionTitle: YUFU_SECTION_TITLE,
    id: "t0263-008-030",
    category: "所在即尊",
    text: "所有土地，則為佛身，於彼經行。佛聖於中，如坐座上，覺了所在，遊居之處。",
    anchorText: "所有土地，則為佛身",
    note: "偈末赞叹持经讲演所在之处，如佛圣在中，显示经法所在即应尊重。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-031",
    category: "展轉勸化",
    text: "如來滅度後其有聞是所說經者，若比丘、比丘尼、清信士、清信女，男子女人、大小眷屬，聞已勸助，於眾會中宣轉為人說，",
    anchorText: "如來滅度後其有聞是所說經者",
    note: "本品先明佛灭后闻此经者应随喜劝助，并在众会中转为人说。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-032",
    category: "轉相勸化",
    text: "以是因緣所興方便，使五道人有五蓋者通得相見，各以所聞轉相勸化，聽我所說勸助之福，所聞法師經法功德。",
    anchorText: "各以所聞轉相勸化",
    note: "经文将展转相传、互相劝化，归入劝助之福与闻法功德。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-033",
    category: "大施難量",
    text: "彌勒答曰：「甚多不可貲計，乃能安慰無量眾生，供足所乏加復立志，於無著證。」",
    anchorText: "甚多不可貲計，乃能安慰無量眾生",
    note: "弥勒先承认广施并令众生立志证果的福德不可计量，为下文比较随喜闻经功德作铺垫。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-034",
    category: "一句勝施",
    text: "其聞是經一句一偈，勸助代喜，福過彼人所布施上。",
    anchorText: "其聞是經一句一偈，勸助代喜",
    note: "佛明说闻此经一句一偈并随喜劝助，其福超过前述广大布施。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-035",
    category: "功德難喻",
    text: "一句一頌勸助功德，不可稱限，百倍千倍萬倍億倍，巨億萬倍億百千劫，不可計量無以為喻；",
    anchorText: "一句一頌勸助功德，不可稱限",
    note: "对一句一颂随喜劝助的功德，经文以百千万亿倍乃至不可喻说明其难量。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-036",
    category: "耳聽代喜",
    text: "何況目見於此經典，耳聽代喜德難計會。",
    anchorText: "目見於此經典，耳聽代喜德難計會",
    note: "亲见经典、耳听并随喜，其德更难计算。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-037",
    category: "聞法福祐",
    text: "一時得聞此經法者，若再反聞所在專精，現在生處所獲福祐，常得自然無數珍寶，宮殿精舍床榻坐具，象馬車乘安雅無量，",
    anchorText: "一時得聞此經法者",
    note: "得闻此经法并专精再闻，现生所得福祐具足珍宝、宫殿、坐具与车乘等安乐资具。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-038",
    category: "天王擁護",
    text: "說經進止若住若坐，息心天王就擁護之，不遭罪患，釋梵四天翼佐營衛，轉輪聖王近師子座。",
    anchorText: "息心天王就擁護之，不遭罪患",
    note: "说经者行住坐卧得天王拥护，不遭罪患，并有释梵四天护卫。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-039",
    category: "暫聞得益",
    text: "若得斯須暫聽聞者，則解罪福善惡報應，便得德本當獲總持，與諸菩薩世世相隨，",
    anchorText: "若得斯須暫聽聞者",
    note: "即使短暂听闻，也能了知罪福善恶报应，得德本并当获总持，与菩萨世世相随。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-040",
    category: "智慧香潔",
    text: "在在所生聰明智慧，億百千世體常香潔，不墮惡趣不與賊害，兵刃共會無有邪心，",
    anchorText: "在在所生聰明智慧",
    note: "听闻此经者在诸生处聪明智慧、身常香洁，并远离恶趣、贼害与兵刃恶心。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-041",
    category: "身相端嚴",
    text: "面色光潤生賢善家，見者歡喜無憎惡者，不盲不聾鼻不偏戾，亦不塞齆不瘖不瘂，",
    anchorText: "面色光潤生賢善家",
    note: "经文列举听闻者生贤善家、面色光润、见者欢喜，并离诸根缺损。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-042",
    category: "辯慧見佛",
    text: "身體完具姿顏端正，色如桃花人所愛敬，心性仁賢口言辯慧，疾逮禪定如來法教，欲覲諸佛如願即見世尊正覺，當學此經。",
    anchorText: "心性仁賢口言辯慧",
    note: "听闻此经者身相端正、言辞辩慧，能速得禅定法教，并如愿见佛。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-043",
    category: "一聞獲福",
    text: "且觀其德，若有一人，一反聞名勸助代喜，乃獲此福。何況有人，專精聽受供養思惟，而復具足為人說者！",
    anchorText: "一反聞名勸助代喜，乃獲此福",
    note: "佛总结：一闻经名随喜劝助尚获此福，何况专精听受、供养思惟并为人具说。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-044",
    category: "一頌隨喜",
    text: "最後若有，值是經卷，假使逮得，一頌之說，聽采其誼，心喜勸助，其人功德，不可限量。",
    anchorText: "值是經卷，假使逮得，一頌之說",
    note: "偈颂重申末后值遇此经、听一颂而欢喜劝助，功德不可限量。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-045",
    category: "勝過大施",
    text: "若聞一偈，代是勸助，所得功德，出彼無量。",
    anchorText: "若聞一偈，代是勸助",
    note: "闻一偈并代为劝助，所得功德超过前述广大布施无量。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-046",
    category: "一頌難限",
    text: "各各所施，一一分別，一頌之德，難計難限。",
    anchorText: "一頌之德，難計難限",
    note: "即便逐一分别布施功德，也不能计量一颂随喜之德。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-047",
    category: "聞法難值",
    text: "假使有人，來至眾會，一反聞經，歡喜踊躍，從億百千，諸姟劫數，是法難值，亦難曉了。",
    anchorText: "一反聞經，歡喜踊躍",
    note: "一到众会闻经欢喜，已显此法亿百千劫难值难了。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-048",
    category: "聞經果報",
    text: "須臾得聞，於斯經卷，且當聽是，所獲果報，在在所由，無有大病。",
    anchorText: "須臾得聞，於斯經卷",
    note: "偈中列明须臾闻此经卷所得果报，首先是在在所生无有大病。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-049",
    category: "壽命長遠",
    text: "所立巧便，壽命常長，未曾生盲，目亦不冥。",
    anchorText: "所立巧便，壽命常長",
    note: "随喜闻经果报中，包含寿命常长、眼目不盲不冥。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-050",
    category: "眾人愛敬",
    text: "常為眾人，所見愛敬，口氣芬馥，無有臭穢。形體常香，如青蓮華，其薰流布，無所不周。",
    anchorText: "常為眾人，所見愛敬",
    note: "闻经果报还包括众人爱敬、口气芬馥、形体常香。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-051",
    category: "安隱寶乘",
    text: "其人儀體，獲致安隱，殊妙車馬，則用躬迎。",
    anchorText: "其人儀體，獲致安隱",
    note: "偈颂说明到处听经者得安隐，并有殊妙车马迎接。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-052",
    category: "獲諸珍寶",
    text: "若復乘于，賢善象車，所在遊得，若干種寶。常復獲逮，上妙瓔珞，數百千人，悉共發意。",
    anchorText: "所在遊得，若干種寶",
    note: "经文以车乘、珍宝、璎珞等说明闻经随喜者的福报庄严。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-053",
    category: "清淨教誨",
    text: "住造其所，所說法果，則為講斯，清淨教誨。",
    anchorText: "所說法果，則為講斯",
    note: "得闻随喜者所到之处能讲说此清净教诲。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-054",
    category: "天帝梵座",
    text: "清淨法故，所建鮮明，得為天帝，梵天床座。",
    anchorText: "清淨法故，所建鮮明",
    note: "偈中以天帝、梵天座等果报，赞叹清净法所成福德。",
  },
  {
    sectionTitle: QUANZHU_SECTION_TITLE,
    id: "t0263-008-055",
    category: "轉輪說法",
    text: "速疾逮致，轉輪聖王，長處眾會，敷演經誼。",
    anchorText: "速疾逮致，轉輪聖王",
    note: "本品以速得转轮圣王、常处众会敷演经义作结，显示闻经劝助的法果。",
  },
];
