import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const TANFASHI_SECTION_TITLE = "歎法師品第十八";

export const T0263_JUAN_8_TANFASHI_REMAINDER_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-073",
    category: "舌根功德",
    text: "其有持是經典，讀誦書寫，當獲奇異舌根千二百功德，舌根具足分別諸味，若得甘美，變為天上自然飲食，設服酢澀鹹苦，化成天饌，咨味無量。",
    anchorText: "其有持是經典，讀誦書寫",
    note: "持经、读诵、书写者得千二百舌根功德，能分别诸味，诸味化为天馔。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-074",
    category: "說法和雅",
    text: "若入眾會講授法要，蒸庶欣載，欽仰典則；若入諍怒，德音柔軟，談誼辯慧，清白知節，慈愍通徹，眾人歡和，感味餘響。",
    anchorText: "若入眾會講授法要",
    note: "舌根清净者入众讲法，音声柔软、辩慧清白，令大众欢和钦仰。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-075",
    category: "天人往觀",
    text: "其從聞經，言論美妙，天人往造，釋梵四王、清淨天身、諸天玉女，思僥往見。",
    anchorText: "其從聞經，言論美妙",
    note: "从闻此经而得言论美妙，天人、释梵四王等皆欲往见。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-076",
    category: "聽受供侍",
    text: "悉欲往觀，思盡形壽，稽首歸命，供養奉侍，聽受經法。",
    anchorText: "悉欲往觀，思盡形壽",
    note: "人王臣民、居士眷属等皆愿往观，归命供养，听受经法。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-077",
    category: "佛慧深要",
    text: "言誨和淑，猶如世尊如來所歎，面見思察，逮佛明慧深妙之要，曉了如此，自然而聞。",
    anchorText: "言誨和淑，猶如世尊如來所歎",
    note: "其言教和雅如佛所赞，能逮佛明慧深妙之要。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-078",
    category: "音聲殊妙",
    text: "音聲殊妙，語言和雅，聽受奇異，意歡喜悅。在眾會者，莫不欽敬，又當演出，深奧音響。",
    anchorText: "音聲殊妙，語言和雅",
    note: "偈中赞叹持经者音声殊妙、语言和雅，听者欢喜，众会钦敬。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-079",
    category: "供養經卷",
    text: "其有聽聞，所說經法，覩察報應，清淨億千。即生歡喜，曉了尊上，供養經卷，不可計量。",
    anchorText: "其有聽聞，所說經法",
    note: "听闻其所说经法者，见报应而生欢喜，晓了尊上，供养经卷不可计量。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-080",
    category: "普受恭敬",
    text: "諸天龍神，蛟阿須倫，常懷欽敬，欲得見之。謙肅恭遜，咨問經典，其人名德，獲致如是。",
    anchorText: "諸天龍神，蛟阿須倫",
    note: "诸天龙神等常怀钦敬，欲见持经法师并咨问经典。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-081",
    category: "遍告經法",
    text: "於是世界，發意之頃，皆以音聞，能遍告之。其響柔軟，微妙殊特，深邃儒雅，而有限節。",
    anchorText: "發意之頃，皆以音聞",
    note: "持经法师发意之顷，音声能遍告此世界，柔软微妙而有节。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-082",
    category: "護法欣然",
    text: "見所在處，僉然護之，察所講法，悉用欣然。",
    anchorText: "見所在處，僉然護之",
    note: "偈末说诸佛声闻见其所在，皆护持并欣然观察所讲之法。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-083",
    category: "身行功德",
    text: "菩薩大士，若聞是經，持讀誦寫者，逮得身行八百功德，肌色澤光，猛勇響餼，猶如琉璃，淨妙無垢。",
    anchorText: "若聞是經，持讀誦寫者",
    note: "闻此经并持读诵写者，得八百身行功德，身色光泽如琉璃无垢。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-084",
    category: "眾生禮敬",
    text: "所當作為人民欽效，容止可宗，進退致益，彼己無易，三千大千世界眾生稽首為禮，",
    anchorText: "所當作為人民欽效",
    note: "身行清净者所作被人民钦效，三千大千世界众生稽首为礼。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-085",
    category: "威德普見",
    text: "普佛國土群萌好醜，鮮色惡色，生趣善惡，鐵圍、大鐵圍，小山、大山，人所居處，下至無可大地獄中，上至三十三天，自以威德普悉見之。",
    anchorText: "普佛國土群萌好醜",
    note: "由身行清净威德，普见佛国土众生色相、生趣善恶乃至上下诸处。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-086",
    category: "觀諸聖眾",
    text: "於此世界，聲聞、緣覺、菩薩、如來，所可遊居，講說經法，以己威光，都皆觀之。所以者何？身行清淨之所致也。",
    anchorText: "聲聞、緣覺、菩薩、如來",
    note: "身行清净者能以威光观见声闻、缘觉、菩萨、如来游居说法之处。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-087",
    category: "清淨愛敬",
    text: "彼人己身，所行清淨，譬如琉璃，而無瑕疵，為一切人，所見愛敬。",
    anchorText: "彼人己身，所行清淨",
    note: "偈中以琉璃无瑕比喻其身行清净，为一切人所爱敬。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-088",
    category: "明鏡見世",
    text: "其有持此，微妙經卷，猶如明鏡，見其面像，見世形類，亦復如是。",
    anchorText: "其有持此，微妙經卷",
    note: "持此微妙经卷者，身清净如明镜，能见世间形类。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-089",
    category: "俗身覺了",
    text: "其身清淨，亦復如是，悉覩見于，一切世間。以俗之身，覺了如茲，斯人尚未，獲成聖道。",
    anchorText: "其身清淨，亦復如是",
    note: "经文说明其虽尚未成圣道，却以俗身因清净功德觉了世间。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-090",
    category: "意根清淨",
    text: "菩薩大士，如來滅度後，若持斯經，諷讀解說，得千二百意根清淨德，其人則以清淨意根，靡不貫暢。",
    anchorText: "若持斯經，諷讀解說",
    note: "如来灭后持此经、讽读解说者，得千二百意根清净德。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-091",
    category: "聞頌廣解",
    text: "聞一頌者，所究彌廣，多所達了。以弘覺了，便能一月講說經法，四月一年綜練所歷，憶念不忘。",
    anchorText: "聞一頌者，所究彌廣",
    note: "意根清净者闻一颂便广有所达，并能长期讲说、综练、忆念不忘。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-092",
    category: "以法分別",
    text: "凡俗所為，販賣賈作，語言音聲，以法皆覩，次第分別，不失其緒。",
    anchorText: "凡俗所為，販賣賈作",
    note: "对凡俗事与语言音声，都能依法观察、次第分别而不失其绪。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-093",
    category: "知心善惡",
    text: "三千大千世界諸六趣生，皆知其心所念善惡、如應不應，中為沙門聖、非聖者，普見不應。",
    anchorText: "三千大千世界諸六趣生",
    note: "意根清净者知三千大千世界六趣众生心念善恶与相应不相应。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-094",
    category: "自然說法",
    text: "意志清淨，不復思惟，自然分別說法誼趣，言皆至誠，有至講者，皆亦承說，如來所詔，一切剖析，往古最勝經卷。",
    anchorText: "意志清淨，不復思惟",
    note: "意志清净者自然分别法义，言皆至诚，能承如来教诏剖析经典。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-095",
    category: "一頌明理",
    text: "若聞一頌，能奉持者，解無央數，明哲誼理。",
    anchorText: "若聞一頌，能奉持者",
    note: "偈中明说闻一颂而能奉持，即能解无央数义理。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-096",
    category: "悉知眾念",
    text: "六道之中，所有黎元，是等思想，若干種念。持是經者，各各異意，一時之間，悉覩知之。",
    anchorText: "六道之中，所有黎元",
    note: "持经者以意根清净，能于一时之间悉知六道众生种种念想。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-097",
    category: "聽聞受誦",
    text: "諸佛大聖，百福德相，一切悉為，世間說法。登時所講，普等聽聞，所說清淨，即能受誦。",
    anchorText: "諸佛大聖，百福德相",
    note: "能普等听闻诸佛大圣为世间说法，并受诵清净所说。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-098",
    category: "眾會無畏",
    text: "有常所演，經典之要，得眾會中，無所畏憚。",
    anchorText: "有常所演，經典之要",
    note: "常演经典要义者，在众会中无所畏惮。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-099",
    category: "安住正法",
    text: "其能受持，安住正法，巧便意宜，則知所應。",
    anchorText: "其能受持，安住正法",
    note: "本品以受持、安住正法、善知方便所应作结，显示意根明达的法用。",
  },
];
