import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const JINGFU_JINGWANG_SECTION_TITLE = "淨復淨王品第二十五";

export const T0263_JUAN_10_JINGFU_JINGWANG_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-037",
    category: "菩薩德行",
    text: "又其二子皆得神足，輕舉能飛智慧具足，功德備悉聖達巍巍，行菩薩業夙夜精進，未曾懈廢，勤心專精六度無極，善權四等所濟無限，悉遵通達三十有七道品之法，普暢道義，所周旋業，進逮離垢三昧定矣。",
    anchorText: "又其二子皆得神足",
    note: "本品先赞二太子具足神足智慧、精进菩萨行，是后文化导父母眷属的功德基础。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-038",
    category: "廣宣要典",
    text: "今日如來，為天上天下一切眾生，廣宣要典《正法華經》，故當奉覲聽《正法華》。",
    anchorText: "為天上天下一切眾生，廣宣要典",
    note: "二太子劝母往诣佛所，明示如来为一切众生广宣《正法华经》，故应奉觐听受。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-039",
    category: "經道化俗",
    text: "我等身，本是法王子，當以經道化于濁俗反偽向真，爾乃佛子也。",
    anchorText: "當以經道化于濁俗反偽向真",
    note: "经文借二太子发愿，指出以经道能化导浊俗、反伪向真。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-040",
    category: "慈愍父母",
    text: "汝真孝子，為其父母修大慈愍，各顯神足覩之欣然心中開解，便聽子等俱詣佛所稽首受業。",
    anchorText: "為其父母修大慈愍",
    note: "离垢施后赞二子为父母修大慈愍，以神足令父母心开解而许其见佛受业。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-041",
    category: "神足開化",
    text: "其二太子現若干變而顯神足，以用開化於其父母。",
    anchorText: "現若干變而顯神足",
    note: "本品明确说明二太子所现神足变化，是为了开化父母。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-042",
    category: "見變發心",
    text: "于時父王，覩其二子神足變化威德若斯，欣然踊躍善心生焉，躬身叉手向二子曰：『汝等師主所受誰乎？』",
    anchorText: "覩其二子神足變化威德若斯",
    note: "净复净王见二子神变威德，心生欢喜善心，进而追问师主、趋向佛法。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-043",
    category: "出家精學",
    text: "唯母聽我等，出家為沙門，如來甚難遇，曼時當精學。所云難得值，猶如靈瑞華，難遇復越彼，閑靜不可得。",
    anchorText: "如來甚難遇，曼時當精學",
    note: "二太子以偈劝请出家，赞如来难遇、闲静难得，应及时精进修学。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-044",
    category: "出家功德",
    text: "二親當知佛興難值，猶靈瑞華，亦如如意最上明珠，佛亦復然，不可再遇，是故我等來生此土，心念出家功德第一。",
    anchorText: "心念出家功德第一",
    note: "二太子再劝父母，同赞佛兴难值，并明说心念出家功德第一。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-045",
    category: "見佛福慶",
    text: "若覩如來福慶無量，人命難得佛世難值，離於八難，得閑靜難，猶死更生。",
    anchorText: "若覩如來福慶無量",
    note: "父王皇后回应二子，承认见如来福庆无量，人身、佛世、离八难与得闲静皆难。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-046",
    category: "道器啟受",
    text: "爾時淨復淨王宮內，八萬四千宮人婇女，宿命德本應得啟受是《正法華》經典，本是道器。",
    anchorText: "宿命德本應得啟受是《正法華》經典",
    note: "佛说明宫内八万四千人以宿命德本，应得启受《正法华》经典，原是道器。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-047",
    category: "三昧德本",
    text: "離垢藏太子，無央數億百千姟劫，往昔宿命曾以奉行棄於眾生一切惡趣三昧正定。",
    anchorText: "曾以奉行棄於眾生一切惡趣三昧正定",
    note: "经文说明离垢藏太子久远宿命曾奉行能弃众生一切恶趣的三昧正定。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-048",
    category: "化入正法",
    text: "時淨復淨王，見二太子所見神足，化入如來、至真之法，以得超越，展轉相成多所度脫，一切盲冥咸入道明。",
    anchorText: "化入如來、至真之法",
    note: "净复净王见神足而化入如来法，得以超越，并展转成就、多所度脱。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-049",
    category: "應病與藥",
    text: "時佛見淨復淨王，與大眷屬自投歸命，因其本行觀宿所緣，而為說法，應病與藥各得開解，欣然踊躍善心生焉。",
    anchorText: "應病與藥各得開解",
    note: "佛为净复净王及眷属随其本缘说法，应病与药，使各得开解、善心生起。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-050",
    category: "諷誦奉行",
    text: "已作沙門，八萬四千歲奉修道業，思惟觀察是《正法華》經典之要，諷誦奉行，如佛所教無所違失。",
    anchorText: "思惟觀察是《正法華》經典之要",
    note: "净复净王眷属出家后长期奉修道业，思惟观察《正法华》要义并讽诵奉行。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-051",
    category: "勤修得定",
    text: "於是淨復淨王，遵奉勤修《正法華經》，與其眷屬竟八萬四千歲，逮眾德本嚴淨三昧正定。",
    anchorText: "遵奉勤修《正法華經》",
    note: "本品直接说明净复净王与眷属遵奉勤修《正法华经》，最终逮得众德本严净三昧。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-052",
    category: "善師化導",
    text: "其二子者則是聖師，化導吾家蒙其恩德，獲現神足顯揚變化，而緣是見所化神變，心得開解退俗入道，奉佛法訓度眾穢厄，順從法律堅住無極，得奉如來啟受經法，乃為至聖無蓋善師。",
    anchorText: "其二子者則是聖師",
    note: "净复净王称二子为圣师，因其化导而心开解、退俗入道、奉佛法训、启受经法。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-053",
    category: "學經善師",
    text: "若族姓子及族姓女，學是經典，所生之處周旋終始，易得善師顯世尊教，得立無上正真之道，開化導示度脫一切，是為微妙無極之業，展轉相教展轉相成，得至聖諦無極之處，值佛道法王因遇善師，得見如來啟受經法，由勸助恩，王今寧見此二太子",
    anchorText: "若族姓子及族姓女，學是經典",
    note: "佛明确指出学此经典者，所生之处易得善师，得立无上正真道，展转教化成就。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-054",
    category: "持經化邪",
    text: "是諸族姓子，前世已曾供養奉事六十五億百千兆姟江河沙等如來、至真，而復授持是《正法華經》，愍傷眾生沒在邪冥九十六種不能自濟，故開化之令住正見修行精進求佛大道。",
    anchorText: "而復授持是《正法華經》",
    note: "佛说明二太子前世供佛并授持《正法华经》，愍念众生沉没邪冥，故开化令住正见、求佛大道。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-055",
    category: "佛教功德",
    text: "至未曾有，如來、至真之教，弘慈無極，不可思議功德具足，敷演道義施設法禁，令無罪釁，長塗之難皆得無患。",
    anchorText: "如來、至真之教，弘慈無極",
    note: "净复净王赞叹如来教法具不可思议功德，能令远离罪咎与长途诸难。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-056",
    category: "授記成佛",
    text: "是王於今是我學世現比丘像，於將來世當得作佛，名曰種帝王如來、至真、等正覺、明行成為、善逝、世間解、無上士、道法御、天人師，為佛、世尊，其佛土曰廣普，劫曰超王。",
    anchorText: "於將來世當得作佛",
    note: "佛为净复净王授记，说明其将来当得作佛，号种帝王如来。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-057",
    category: "菩薩宿德",
    text: "藥王菩薩、超藥菩薩，功德巍巍無限若斯，在無央數億百千姟諸如來所，殖眾德本，是二正士道德備悉，不可思議。",
    anchorText: "功德巍巍無限若斯",
    note: "佛揭示二太子即药王、超药菩萨，并赞其功德、道德与宿植德本不可思议。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-058",
    category: "聞名禮敬",
    text: "若有聞此二正士名執持懷抱，一切眾人皆當禮敬，如是學士，天上世間皆歸仰之。",
    anchorText: "聞此二正士名執持懷抱",
    note: "经文明确说闻药王、超药二正士名并执持怀抱者，为众人礼敬、天上世间归仰。",
  },
  {
    sectionTitle: JINGFU_JINGWANG_SECTION_TITLE,
    id: "t0263-010-059",
    category: "聞品得益",
    text: "佛說是往古宿世本所行時，八萬四千人遠塵離垢諸法眼淨。",
    anchorText: "八萬四千人遠塵離垢諸法眼淨",
    note: "本品结尾明说佛宣说此宿世本行时，八万四千人远尘离垢、得法眼净。",
  },
];
