import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const RULAIXIANSHOU_SECTION_TITLE = "如來現壽品第十五";

export const T0263_JUAN_7_RULAIXIANSHOU_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-073",
    category: "信佛誠諦",
    text: "諸族姓子，悉當信佛誠諦至教，勿得猶豫。",
    anchorText: "悉當信佛誠諦至教，勿得猶豫",
    note: "本品开端三劝大众信受佛真实教诏，作为听闻如来寿量法门的根本态度。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-074",
    category: "善思受教",
    text: "諦聽諦聽！善思念之。",
    anchorText: "諦聽諦聽！善思念之",
    note: "佛令大众谛听善思，提示本品所说法义深要，须以恭敬心领受。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-075",
    category: "久成正覺",
    text: "又吾在昔，從無數億百千那術姟劫以來，已成至真等正覺矣。",
    anchorText: "從無數億百千那術姟劫以來，已成至真等正覺矣",
    note: "本品揭示如来久远成佛，超越大众以为近成佛道的理解。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-076",
    category: "佛慧難量",
    text: "諸佛世界甚多無量不可思議，非心所及，假使一切聲聞、緣覺處賢聖慧，不能思惟知其數者，唯有世尊大聖之慧，乃能知耳，餘無能及。",
    anchorText: "諸佛世界甚多無量不可思議，非心所及",
    note: "以不可思议佛土数量显发世尊智慧所知广大，非声闻缘觉所能测度。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-077",
    category: "壽量無邊",
    text: "吾逮無上正真道成最正覺已來，其劫之限，過於爾所塵數之劫。",
    anchorText: "吾逮無上正真道成最正覺已來，其劫之限",
    note: "佛以微尘譬喻说明成佛以来劫数过彼尘数，显示如来寿量久远。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-078",
    category: "善權示現",
    text: "諸族姓子，吾以善權方便，演說經典，現無央數種種瑞應。",
    anchorText: "吾以善權方便，演說經典，現無央數種種瑞應",
    note: "如来以善权方便演说经典、示现瑞应，皆为适应众生而施设。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-079",
    category: "隨根說法",
    text: "又如來悉知一切群萌，往來進止諸原根本，悉觀其心而隨示現，各為名號，亦不滅度而說泥洹，順諸眾生瑕穢善惡，則為解演若干種法。",
    anchorText: "悉觀其心而隨示現，各為名號",
    note: "佛知众生根性差别，随心示现并解演种种法门。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-080",
    category: "為化眾生",
    text: "又如來成佛已來甚久，故佛說言，得佛未久。所以者何？欲化眾生故。",
    anchorText: "得佛未久。所以者何？欲化眾生故",
    note: "经文明说如来示现近成佛道，是为教化众生的善权方便。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-081",
    category: "佛語不虛",
    text: "以故如來諸所講演，皆實至誠非是虛妄。",
    anchorText: "如來諸所講演，皆實至誠非是虛妄",
    note: "本品直接宣明如来所说皆真实诚谛，不是虚妄。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-082",
    category: "殖眾德本",
    text: "眾生苦惱不可稱限，行若干種志性各異，思想諸念各各差別，欲令眾生殖眾德本，故為分別說若干法。",
    anchorText: "欲令眾生殖眾德本，故為分別說若干法",
    note: "佛因众生苦恼、志性各异，为令众生种植德本而分别说法。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-083",
    category: "常住不滅",
    text: "成平等覺已來大久，壽命無量常住不滅度。",
    anchorText: "壽命無量常住不滅度",
    note: "如来寿命无量、常住不灭，是本品最核心的法义。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-084",
    category: "難值精進",
    text: "如來善權告諸比丘，勤苦作行乃得佛道，誠諦不虛。",
    anchorText: "勤苦作行乃得佛道，誠諦不虛",
    note: "佛以善权令众生生难值想，策发勤苦修行求佛道。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-085",
    category: "見佛發心",
    text: "言法難值、如來難遇聞見，是已怪之難及興難遭想，悲喜孜孜知佛希有，便多發意，樂在閑居而行精進。",
    anchorText: "悲喜孜孜知佛希有，便多發意",
    note: "众生知法难值、如来难遇，因而多发道意，乐于闲居精进。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-086",
    category: "歡喜植德",
    text: "這不見佛而懷渴仰，見如來已，歡喜稽首造眾德本，其不滅度者教令滅度，開化黎庶。",
    anchorText: "見如來已，歡喜稽首造眾德本",
    note: "经文说明众生见佛欢喜稽首，由此造众德本、蒙佛开化。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-087",
    category: "法藥除病",
    text: "假使諸子時服此藥，其毒消滅病得瘳除，身體安隱氣力康強。",
    anchorText: "其毒消滅病得瘳除，身體安隱氣力康強",
    note: "医子譬喻中，以服药除毒病喻受佛法药而离三毒苦患。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-088",
    category: "廣說經法",
    text: "父聞來還，謂佛如來行大悲哀，見三界人，或流五趣不能自出，故現世間，廣說經法開化黎庶。",
    anchorText: "故現世間，廣說經法開化黎庶",
    note: "佛以大悲现世，广说经法开化众生，使其得以出离五趣流转。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-089",
    category: "發心不退",
    text: "服藥病愈，謂發無上正真道意，立不退轉無所從生，或得聲聞、緣覺乘，不至究竟。",
    anchorText: "發無上正真道意，立不退轉無所從生",
    note: "佛解释譬喻，服法药病愈即发无上道意，安立不退转与无生法。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-090",
    category: "留經後世",
    text: "見父年老留藥教子捨之去者，謂諸黎庶疑受道教，故現滅度，留諸經法以教後世，四輩弟子諷誦學問，思佛功德發大道意，或得羅漢或得緣覺，佛見如是復還出世，一切眾生皆是吾子，諸族姓子，如來行權非徒虛妄。",
    anchorText: "留諸經法以教後世，四輩弟子諷誦學問",
    note: "如来示灭而留经法教后世，令四辈弟子讽诵学问、思佛功德、发大道意。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-091",
    category: "常說經法",
    text: "得佛已來，至尊大道，常講說經，未曾休懈，勸助發起，無數菩薩，皆建立之，於佛道慧。",
    anchorText: "常講說經，未曾休懈，勸助發起",
    note: "偈颂赞叹如来久远以来常讲说经，劝发无数菩萨建立佛慧。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-092",
    category: "導利眾生",
    text: "無數億劫，開道眾生，億千姟數，不可思議，而為示現，立于滅度，以教化誼，導利眾生。",
    anchorText: "開道眾生，億千姟數，不可思議",
    note: "如来于无数亿劫开导不可思议众生，以示现灭度而导利群生。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-093",
    category: "方便演法",
    text: "用權方便，而現滅度，故為眾人，演斯法典。",
    anchorText: "用權方便，而現滅度，故為眾人，演斯法典",
    note: "本品以偈重申：佛现灭度是权方便，为众人演说此法典。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-094",
    category: "顯大佛道",
    text: "若復見佛，歡喜踊躍。假使質直，說至誠言，眾生之類，朽棄身體，然後如來，合集眾音，能自示現，顯大佛道。",
    anchorText: "若復見佛，歡喜踊躍",
    note: "众生复见佛则欢喜踊跃，如来示现为显发大佛道。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-095",
    category: "現壽宣道",
    text: "比丘欲知，佛權方便，數數堪忍，現壽於世，及與異人，眷屬圍繞，因而宣揚，於尊佛道。",
    anchorText: "現壽於世，及與異人，眷屬圍繞",
    note: "偈颂点明本品题义：佛以权方便现寿于世，宣扬尊贵佛道。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-096",
    category: "分別經典",
    text: "望想飢虛，欲得見佛，然後乃為，分別經典。",
    anchorText: "欲得見佛，然後乃為，分別經典",
    note: "众生渴仰见佛，如来乃为分别经典，令其得入法义。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-097",
    category: "佛土安隱",
    text: "當斯之時，吾此佛土，具足微妙，柔軟安雅，歌舞戲笑，無量安隱，講堂精舍，樓閣室宅，校飾莊嚴，皆以七寶，藥草樹木，華實茂好，自然雨華，心華眾色，以散於佛，及弟子上。",
    anchorText: "吾此佛土，具足微妙，柔軟安雅",
    note: "偈中显示如来常住佛土具足微妙、柔软安雅、无量安隐。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-098",
    category: "顯揚清淨",
    text: "假使人民，柔軟中和，其時佛興，出于人間。已見世尊，經法所詔，則為顯揚，清淨誼理。",
    anchorText: "已見世尊，經法所詔，則為顯揚，清淨誼理",
    note: "柔软中和者得见佛兴于世，闻经法教诏而显扬清净义理。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-099",
    category: "棄疑信受",
    text: "智慧明者，無得狐疑，棄捐猶豫，勿懷結滯。",
    anchorText: "無得狐疑，棄捐猶豫，勿懷結滯",
    note: "本品劝有智慧者舍弃疑惑结滞，信受如来寿量真实义。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-100",
    category: "療治眾病",
    text: "世吼療治，眾生之病。開導癡騃，令離愚冥，而現泥洹，亦不滅度。",
    anchorText: "世吼療治，眾生之病",
    note: "偈颂以佛为世间大医，疗治众生之病，开导愚冥而不实灭。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-101",
    category: "應時教化",
    text: "如來所詔，常以知時，為其眾生，而行智慧。",
    anchorText: "如來所詔，常以知時",
    note: "如来知时而为众生行智慧，显示说法教化的应机性。",
  },
  {
    sectionTitle: RULAIXIANSHOU_SECTION_TITLE,
    id: "t0263-007-102",
    category: "聞說獲益",
    text: "世尊說是如來壽限時，則無央數不可思議眾生，皆獲利誼解脫至道。",
    anchorText: "無央數不可思議眾生，皆獲利誼解脫至道",
    note: "本品结尾明说佛说如来寿限时，无量众生获得法益、解脱至道。",
  },
];
