import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const XINLE_SECTION_TITLE = "信樂品第四";

export const T0263_JUAN_3_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0263-003-001",
    category: "聞法歡喜",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "聽演大法，得未曾有，本所未聞；而見世尊授舍利弗決，當得無上正真之道，驚喜踊躍咸從坐起",
    anchorText: "聽演大法，得未曾有，本所未聞",
    note: "须菩提等闻大法并见舍利弗授记，生起未曾有的欢喜踊跃。",
  },
  {
    id: "t0263-003-002",
    category: "聽法無厭",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "如來所講我等靖聽，次第坐定諸來大眾，不敢危疲無所患厭。",
    anchorText: "如來所講我等靖聽",
    note: "声闻大众安住听受如来所讲，无疲厌心。",
  },
  {
    id: "t0263-003-003",
    category: "發大意",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "爾乃誨我以奇特誼，樂於等一，則發大意於無上正真道。",
    anchorText: "誨我以奇特誼",
    note: "如来以奇特义教诲，使其乐于一乘而发无上正真道意。",
  },
  {
    id: "t0263-003-004",
    category: "得大利",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "而今大聖授聲聞決當成正覺，心用愕然怪未曾有，余得大利各當奉事，乃獲逮聞如是品經。",
    anchorText: "余得大利各當奉事",
    note: "闻声闻授记成佛并得闻此品，经文明说为得大利。",
  },
  {
    id: "t0263-003-005",
    category: "值法如寶",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "從過去佛常聞斯法，故初值遇，則我祿厚喻獲妙寶",
    anchorText: "從過去佛常聞斯法",
    note: "经文以获得妙宝譬喻值遇此法。",
  },
  {
    id: "t0263-003-006",
    category: "宿福得藏",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "余何宿福得領室藏？",
    anchorText: "何宿福得領室藏",
    note: "穷子领受宝藏的譬喻，表达得此法藏源于宿福。",
  },
  {
    id: "t0263-003-007",
    category: "如來度脫",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "大富長者則譬如來，諸學士者則謂佛子，勉濟吾等三界勤苦，如富長者還執其子度脫生死。",
    anchorText: "大富長者則譬如來",
    note: "本品明以长者喻如来，救济佛子三界勤苦、度脱生死。",
  },
  {
    id: "t0263-003-008",
    category: "除蓋精進",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "有無央數聖眾之寶，以五神通除五陰蓋，常修精進在彼道教，志于滅度謂為妙印。",
    anchorText: "以五神通除五陰蓋",
    note: "以圣众之宝譬佛法资财，能除五阴盖并令精进修道。",
  },
  {
    id: "t0263-003-009",
    category: "法寶施與",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "此如來法珍寶之藏，於今世尊以權方便，觀于本際慧寶帑藏，蠲除饑𩚛授大妙印。",
    anchorText: "如來法珍寶之藏",
    note: "如来以方便开示法宝之藏，蠲除贫乏而授大妙印。",
  },
  {
    id: "t0263-003-010",
    category: "菩薩慧義",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "世尊為我等示現菩薩大士慧誼，余黨奉行為眾說法，當顯如來聖明大德，咸使暢入隨時之誼。",
    anchorText: "示現菩薩大士慧誼",
    note: "如来示现菩萨智慧义，使众人奉行说法、显发如来大德。",
  },
  {
    id: "t0263-003-011",
    category: "善權方便",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "世雄大通善權方便，知我志操不解深法，為現聲聞，畏三界法及生老死，色聲香味細滑之事",
    anchorText: "世雄大通善權方便",
    note: "佛以善权方便，随声闻怖畏生死的根机而示现教法。",
  },
  {
    id: "t0263-003-012",
    category: "佛子大慧",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "今乃自知成佛真子，無上孫息為佛所矜，施以大慧。",
    anchorText: "成佛真子，無上孫息",
    note: "声闻自知为佛真子，蒙佛哀矜而施以大慧。",
  },
  {
    id: "t0263-003-013",
    category: "甘露法",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "世尊興為二事，為諸菩薩現甘露法，為諸下劣志願小者，轉復勸進入微妙誼。",
    anchorText: "為諸菩薩現甘露法",
    note: "世尊为菩萨现甘露法，也劝小志者入微妙义。",
  },
  {
    id: "t0263-003-014",
    category: "獲大珍寶",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "今如來尊現諸通慧，我等以獲大聖珍寶，佛則為父我則為子，父子同體焉得差別。",
    anchorText: "我等以獲大聖珍寶",
    note: "闻法后自觉获得大圣珍宝，并明白佛子同体之义。",
  },
  {
    id: "t0263-003-015",
    category: "一乘授記",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "佛權方便說三乘耳，尚無有二豈當有三？是諸聲聞皆當成佛，我等悅豫不能自勝。",
    anchorText: "佛權方便說三乘耳",
    note: "本品直显三乘为方便，究竟无二无三，声闻皆当成佛。",
  },
  {
    id: "t0263-003-016",
    category: "聞法悲喜",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "我等今日，逮聞斯音，怪之愕然，得未曾有，由是之故，心用悲喜。",
    anchorText: "逮聞斯音，怪之愕然",
    note: "大迦叶偈中赞今日闻佛音声，得未曾有而悲喜交集。",
  },
  {
    id: "t0263-003-017",
    category: "法寶賜與",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "尊妙珍寶，為大積聚，一處合集，以賜我等。",
    anchorText: "尊妙珍寶，為大積聚",
    note: "以尊妙珍宝譬佛所赐大法。",
  },
  {
    id: "t0263-003-018",
    category: "安隱成佛",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "大雄導師，教化我等，覩見下劣，樂喜小乘，度脫我輩，使得安隱，便復授決，當成佛道。",
    anchorText: "度脫我輩，使得安隱",
    note: "佛教化小乘根机者，使其安隐并授记成佛。",
  },
  {
    id: "t0263-003-019",
    category: "大道奉行",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "最勝諸子，則便奉行，尊上大道，所當起立，視眾眼目，當於世間，得成佛道，而為聖尊",
    anchorText: "最勝諸子，則便奉行",
    note: "佛子奉行尊上大道，最终在世间成佛为圣尊。",
  },
  {
    id: "t0263-003-020",
    category: "講法利眾",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "將養擁護，於此佛法，講說分別，最勝慧誼。則為感動，一切眾生",
    anchorText: "講說分別，最勝慧誼",
    note: "拥护佛法、讲说分别最胜智慧义，能感动一切众生。",
  },
  {
    id: "t0263-003-021",
    category: "精進解脫",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "今乃究竟，具足最勝，得無為限，當捨陰蓋，長夜精進，修理空誼，解脫三界，勤苦之惱。",
    anchorText: "長夜精進，修理空誼",
    note: "经文劝长夜精进修空义，舍阴盖、解脱三界苦恼。",
  },
  {
    id: "t0263-003-022",
    category: "願佛道者",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "最勝所演，經身之慧，假使有人，願等佛道，為是等故，加賜法事",
    anchorText: "假使有人，願等佛道",
    note: "佛为愿求佛道者加赐法事，显示经身智慧。",
  },
  {
    id: "t0263-003-023",
    category: "令得利義",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "有大導師，周旋世間，普悉觀察，如此輩相。諸恐懼者，令得利誼，求索勸助，令我信樂。",
    anchorText: "諸恐懼者，令得利誼",
    note: "大导师观察众生根相，令恐惧者得利益义并生信乐。",
  },
  {
    id: "t0263-003-024",
    category: "法施方便",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "大聖導師，所興希有，分別宣暢，善權方便。諸子之黨，志樂下劣，修行調定，而以法施。",
    anchorText: "分別宣暢，善權方便",
    note: "佛以希有善权方便，对志乐下劣者施以法施。",
  },
  {
    id: "t0263-003-025",
    category: "獲道得寶",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "我等今日，致得百千，未曾有法，如貧得財。於佛教化，獲道得寶，第一清淨，無復諸漏。",
    anchorText: "致得百千，未曾有法",
    note: "闻佛教化如贫得财，获道得宝，第一清净无漏。",
  },
  {
    id: "t0263-003-026",
    category: "聽佛道音",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "我等今日，乃為聲聞，還得聽省，上尊佛道，當復見揚，聖覺音聲，以故獲聽，超度恐懼。",
    anchorText: "還得聽省，上尊佛道",
    note: "声闻今日得以听省上尊佛道，闻圣觉音声而超度恐惧。",
  },
  {
    id: "t0263-003-027",
    category: "頂受具願",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "今日無著，燒罪度岸，修行為業，踊躍歡喜。吾等歸聖，以頂受之，所願具足，如江河沙。",
    anchorText: "燒罪度岸，修行為業",
    note: "偈中以烧罪度岸、顶受佛法、所愿具足赞叹闻法受持之益。",
  },
  {
    id: "t0263-003-028",
    category: "隨根開化",
    sectionTitle: XINLE_SECTION_TITLE,
    text: "如來皆覩，眾人性行，他人心念。一切群萌，以若干法，而致墮落。以法示現，此尊佛道。",
    anchorText: "如來皆覩，眾人性行",
    note: "如来洞见众生性行心念，随其所堕以法示现尊佛道。",
  },
];
