import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const MIAOYIN_SECTION_TITLE = "妙音菩薩品第二十四";
const DHARANI_SECTION_TITLE = "陀羅尼品第二十六";
const MIAOZHUANGYAN_SECTION_TITLE = "妙莊嚴王本事品第二十七";

export const T0262_JUAN_7_MIAOYIN_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0262-007-017",
    category: "久植德本",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "妙音。久已植眾德本。供養親近無量百千萬億諸佛。而悉成就甚深智慧。",
    anchorText: "久已植眾德本",
    note: "妙音菩薩久植德本、供養親近無量諸佛，成就甚深智慧。",
  },
  {
    id: "t0262-007-018",
    category: "諸大三昧",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "得妙幢相三昧。法華三昧。淨德三昧。宿王戲三昧。無緣三昧。智印三昧。解一切眾生語言三昧。集一切功德三昧。清淨三昧。神通遊戲三昧。慧炬三昧。莊嚴王三昧。淨光明三昧。淨藏三昧。不共三昧。日旋三昧。得如是等百千萬億恆河沙等諸大三昧。",
    anchorText: "得妙幢相三昧",
    note: "本品列舉妙音菩薩所得法華三昧、集一切功德三昧等無量三昧。",
  },
  {
    id: "t0262-007-019",
    category: "禮佛聽經",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "我當往詣娑婆世界。禮拜親近供養釋迦牟尼佛。及見文殊師利法王子菩薩。藥王菩薩。勇施菩薩。宿王華菩薩。上行意菩薩。莊嚴王菩薩。藥上菩薩。",
    anchorText: "禮拜親近供養釋迦牟尼佛",
    note: "妙音菩薩發願來娑婆，為禮拜親近供養釋迦牟尼佛並見諸大菩薩。",
  },
  {
    id: "t0262-007-020",
    category: "勿輕娑婆",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "是故汝往。莫輕彼國。若佛菩薩及國土。生下劣想。",
    anchorText: "莫輕彼國",
    note: "淨華宿王智佛告誡妙音勿輕娑婆國土、佛與菩薩，含有敬法敬土的勸修義。",
  },
  {
    id: "t0262-007-021",
    category: "如來力用",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "世尊。我今詣娑婆世界。皆是如來之力。如來神通遊戲。如來功德智慧莊嚴。",
    anchorText: "皆是如來之力",
    note: "妙音菩薩明說往詣娑婆皆依如來之力、神通遊戲與功德智慧莊嚴。",
  },
  {
    id: "t0262-007-022",
    category: "三昧現瑞",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "於是妙音菩薩。不起於座。身不動搖。而入三昧。以三昧力。於耆闍崛山。去法座不遠。化作八萬四千眾寶蓮華。",
    anchorText: "不起於座。身不動搖。而入三昧",
    note: "妙音菩薩不起於座而入三昧，以三昧力於靈鷲山化現眾寶蓮華。",
  },
  {
    id: "t0262-007-023",
    category: "供養聽經",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "是妙音菩薩摩訶薩。欲從淨華宿王智佛國。與八萬四千菩薩圍繞。而來至此娑婆世界。供養親近禮拜於我。亦欲供養聽法華經。",
    anchorText: "亦欲供養聽法華經",
    note: "佛明說妙音菩薩來娑婆，是為供養親近禮拜佛，也為供養聽《法華經》。",
  },
  {
    id: "t0262-007-024",
    category: "勤修三昧",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "世尊。是菩薩種何善本。修何功德。而能有是大神通力。行何三昧。願為我等說是三昧名字。我等亦欲勤修行之。",
    anchorText: "我等亦欲勤修行之",
    note: "文殊因見瑞相請問三昧名字，明說大眾亦欲勤修此三昧。",
  },
  {
    id: "t0262-007-025",
    category: "供佛聞法",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "善哉善哉。汝能為供養釋迦牟尼佛。及聽法華經。并見文殊師利等故來至此。",
    anchorText: "汝能為供養釋迦牟尼佛",
    note: "多寶佛讚妙音菩薩為供養釋迦牟尼佛、聽法華經並見文殊等而來。",
  },
  {
    id: "t0262-007-026",
    category: "供養果報",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "妙音菩薩於萬二千歲。以十萬種伎樂。供養雲雷音王佛。并奉上八萬四千七寶鉢。以是因緣果報。今生淨華宿王智佛國。有是神力。",
    anchorText: "以是因緣果報",
    note: "佛明示妙音菩薩昔日以伎樂、寶鉢供佛，因緣果報今生佛國並具神力。",
  },
  {
    id: "t0262-007-027",
    category: "供佛善根",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "華德。是妙音菩薩。已曾供養親近無量諸佛。久植德本。又值恆河沙等百千萬億那由他佛。",
    anchorText: "已曾供養親近無量諸佛",
    note: "佛再次說明妙音菩薩已曾供養親近無量諸佛，久植德本。",
  },
  {
    id: "t0262-007-028",
    category: "現身說經",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "而是菩薩。現種種身。處處為諸眾生說是經典。",
    anchorText: "現種種身。處處為諸眾生說是經典",
    note: "本品總說妙音菩薩能現種種身，處處為眾生說此經典。",
  },
  {
    id: "t0262-007-029",
    category: "救濟眾難",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "或現天龍。夜叉。乾闥婆。阿修羅。迦樓羅。緊那羅。摩睺羅伽。人非人等身而說是經。諸有地獄。餓鬼。畜生。及眾難處。皆能救濟。",
    anchorText: "諸有地獄。餓鬼。畜生。及眾難處。皆能救濟",
    note: "妙音菩薩隨類現身說經，地獄、餓鬼、畜生及眾難處皆能救濟。",
  },
  {
    id: "t0262-007-030",
    category: "救護娑婆",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "華德。是妙音菩薩。能救護娑婆世界諸眾生者。",
    anchorText: "能救護娑婆世界諸眾生",
    note: "佛明說妙音菩薩能救護娑婆世界諸眾生。",
  },
  {
    id: "t0262-007-031",
    category: "智慧明照",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "是菩薩以若干智慧。明照娑婆世界。令一切眾生。各得所知。",
    anchorText: "明照娑婆世界",
    note: "妙音菩薩以若干智慧明照娑婆世界，令一切眾生各得所知。",
  },
  {
    id: "t0262-007-032",
    category: "隨類度生",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "如是種種。隨所應度而為現形。乃至應以滅度而得度者。示現滅度。",
    anchorText: "隨所應度而為現形",
    note: "佛總結妙音菩薩隨所應度而現形，乃至示現滅度以度眾生。",
  },
  {
    id: "t0262-007-033",
    category: "三昧饒益",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "善男子。其三昧名現一切色身。妙音菩薩住是三昧中。能如是饒益無量眾生。",
    anchorText: "能如是饒益無量眾生",
    note: "佛說妙音菩薩住現一切色身三昧，能如是饒益無量眾生。",
  },
  {
    id: "t0262-007-034",
    category: "聞品得益",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "說是妙音菩薩品時。與妙音菩薩俱來者八萬四千人。皆得現一切色身三昧。此娑婆世界無量菩薩。亦得是三昧及陀羅尼。",
    anchorText: "皆得現一切色身三昧",
    note: "說此品時，俱來八萬四千人及娑婆無量菩薩皆得三昧，並得陀羅尼。",
  },
  {
    id: "t0262-007-035",
    category: "來往饒益",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "世尊。我到娑婆世界。饒益眾生。見釋迦牟尼佛。及見多寶佛塔。禮拜供養。",
    anchorText: "我到娑婆世界。饒益眾生",
    note: "妙音菩薩回本國自述到娑婆世界饒益眾生，並禮拜供養釋迦佛與多寶佛塔。",
  },
  {
    id: "t0262-007-036",
    category: "聞品證法",
    sectionTitle: MIAOYIN_SECTION_TITLE,
    text: "說是妙音菩薩來往品時。四萬二千天子。得無生法忍。華德菩薩。得法華三昧。",
    anchorText: "四萬二千天子。得無生法忍",
    note: "本品結尾明說說此來往品時，四萬二千天子得無生法忍，華德菩薩得法華三昧。",
  },
  {
    id: "t0262-007-037",
    category: "受持功德",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "佛言。若善男子善女人。能於是經。乃至受持一四句偈。讀誦解義。如說修行。功德甚多。",
    anchorText: "能於是經。乃至受持一四句偈",
    note: "佛以供養無量諸佛為比較，明說受持乃至一四句偈、讀誦解義、如說修行，功德甚多。",
  },
  {
    id: "t0262-007-038",
    category: "陀羅尼守護",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊。我今當與說法者陀羅尼咒。以守護之。",
    anchorText: "我今當與說法者陀羅尼咒",
    note: "藥王菩薩發願為說法者說陀羅尼咒，以作守護。",
  },
  {
    id: "t0262-007-039",
    category: "諸佛所說",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊。是陀羅尼神咒。六十二憶恆河沙等諸佛所說。若有侵毀此法師者。則為侵毀是諸佛已。",
    anchorText: "六十二憶恆河沙等諸佛所說",
    note: "藥王菩薩說此陀羅尼為諸佛所說，並警示侵毀法師即同侵毀諸佛。",
  },
  {
    id: "t0262-007-040",
    category: "多所饒益",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "善哉善哉。藥王。汝愍念擁護此法師故。說是陀羅尼。於諸眾生。多所饒益。",
    anchorText: "汝愍念擁護此法師故",
    note: "佛讚藥王菩薩愍念擁護法師而說陀羅尼，於眾生多所饒益。",
  },
  {
    id: "t0262-007-041",
    category: "護持讀誦",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊。我亦為擁護讀誦受持法華經者。說陀羅尼。若此法師得是陀羅尼。若夜叉。若羅剎。若富單那。若吉蔗。若鳩槃荼。若餓鬼等。伺求其短。無能得便。",
    anchorText: "我亦為擁護讀誦受持法華經者",
    note: "勇施菩薩說陀羅尼擁護讀誦受持《法華經》者，使諸鬼神伺求其短不得其便。",
  },
  {
    id: "t0262-007-042",
    category: "擁護無患",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊。以是神咒。擁護法師。我亦自當擁護持是經者。令百由旬內。無諸衰患。",
    anchorText: "我亦自當擁護持是經者",
    note: "毗沙門天王明說以神咒擁護法師，並自當擁護持經者，使百由旬內無諸衰患。",
  },
  {
    id: "t0262-007-043",
    category: "擁護持經",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊。我亦以陀羅尼神咒。擁護持法華經者。",
    anchorText: "擁護持法華經者",
    note: "持國天王亦以陀羅尼神咒擁護持《法華經》者。",
  },
  {
    id: "t0262-007-044",
    category: "除衰患",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊。我等亦欲擁護讀誦受持法華經者。除其衰患。若有伺求法師短者。令不得便。",
    anchorText: "我等亦欲擁護讀誦受持法華經者",
    note: "十羅剎女與鬼子母等發願擁護讀誦受持《法華經》者，除其衰患，令伺求法師短者不得其便。",
  },
  {
    id: "t0262-007-045",
    category: "安隱離患",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "世尊。我等亦當身自擁護受持讀誦修行是經者。令得安隱。離諸衰患。消眾毒藥。",
    anchorText: "身自擁護受持讀誦修行是經者",
    note: "羅剎女等明說親自擁護受持、讀誦、修行此經者，令得安隱、離諸衰患、消眾毒藥。",
  },
  {
    id: "t0262-007-046",
    category: "福不可量",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "善哉善哉。汝等但能擁護受持法華名者。福不可量。何況擁護具足受持。供養經卷。華香瓔珞。末香塗香燒香。旛蓋伎樂。燃種種燈。",
    anchorText: "擁護受持法華名者。福不可量",
    note: "佛讚羅剎女等，即使只擁護受持法華名者，福已不可量，何況擁護具足受持供養經卷者。",
  },
  {
    id: "t0262-007-047",
    category: "聞品證法",
    sectionTitle: DHARANI_SECTION_TITLE,
    text: "說是陀羅尼品時。六萬八千人。得無生法忍。",
    anchorText: "六萬八千人。得無生法忍",
    note: "本品結尾明說，說陀羅尼品時，六萬八千人得無生法忍。",
  },
  {
    id: "t0262-007-048",
    category: "福德智慧",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "是二子有大神力福德智慧。久修菩薩所行之道。所謂檀波羅蜜。尸羅波羅蜜。羼提波羅蜜。毗離耶波羅蜜。禪波羅蜜。般若波羅蜜。方便波羅蜜。慈悲喜捨。乃至三十七品助道法。皆悉明了通達。",
    anchorText: "是二子有大神力福德智慧",
    note: "本品先明淨藏、淨眼二子具大神力、福德智慧，久修菩薩行並通達諸助道法。",
  },
  {
    id: "t0262-007-049",
    category: "諸大三昧",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "又得菩薩淨三昧。日星宿三昧。淨光三昧。淨色三昧。淨照明三昧。長莊嚴三昧。大威德藏三昧。於此三昧。亦悉通達。",
    anchorText: "又得菩薩淨三昧",
    note: "經文明列二子所得諸三昧，並說皆悉通達。",
  },
  {
    id: "t0262-007-050",
    category: "說經愍眾",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "爾時彼佛欲引導妙莊嚴王。及愍念眾生故。說是法華經。",
    anchorText: "欲引導妙莊嚴王",
    note: "雲雷音宿王華智佛為引導妙莊嚴王、愍念眾生而說《法華經》。",
  },
  {
    id: "t0262-007-051",
    category: "聽受法華",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "願母往詣雲雷音宿王華智佛所。我等亦當侍從親近。供養禮拜。所以者何。此佛於一切天人眾中。說法華經。宜應聽受。",
    anchorText: "此佛於一切天人眾中。說法華經",
    note: "二子勸母同往佛所親近供養，理由是佛正在眾中說《法華經》，宜應聽受。",
  },
  {
    id: "t0262-007-052",
    category: "神變淨信",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "現如是等種種神變。令其父王心淨信解。時父見子神力如是。心大歡喜。得未曾有。",
    anchorText: "令其父王心淨信解",
    note: "二子以神變方便化父，使父王心淨信解，歡喜得未曾有。",
  },
  {
    id: "t0262-007-053",
    category: "發菩提心",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "父王今已信解。堪任發阿耨多羅三藐三菩提心。我等為父已作佛事。願母見聽。於彼佛所。出家修道。",
    anchorText: "堪任發阿耨多羅三藐三菩提心",
    note: "二子見父已信解，明說父王堪任發無上菩提心，並請求出家修道。",
  },
  {
    id: "t0262-007-054",
    category: "出家難值",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "願母放我等 出家作沙門 諸佛甚難值 我等隨佛學 如優曇鉢華 值佛復難是 脫諸難亦難 願聽我出家",
    anchorText: "諸佛甚難值",
    note: "偈中以諸佛難值、脫諸難亦難，勸母聽許出家隨佛學。",
  },
  {
    id: "t0262-007-055",
    category: "宿福值法",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "佛難得值。如優曇鉢羅華。又如一眼之龜。值浮木孔。而我等宿福深厚。生值佛法。是故父母當聽我等。令得出家。所以者何。諸佛難值。時亦難遇。",
    anchorText: "而我等宿福深厚。生值佛法",
    note: "二子以佛難值、時難遇為由，並自述宿福深厚而生值佛法。",
  },
  {
    id: "t0262-007-056",
    category: "受持法華",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "彼時妙莊嚴王後宮八萬四千人。皆悉堪任受持是法華經。",
    anchorText: "皆悉堪任受持是法華經",
    note: "本品明說妙莊嚴王後宮八萬四千人皆堪任受持《法華經》。",
  },
  {
    id: "t0262-007-057",
    category: "三昧利益",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "淨眼菩薩。於法華三昧久已通達。淨藏菩薩。已於無量百千萬億劫。通達離諸惡趣三昧。欲令一切眾生離諸惡趣故。其王夫人。得諸佛集三昧。能知諸佛秘密之藏。",
    anchorText: "於法華三昧久已通達",
    note: "本段總說淨眼通達法華三昧、淨藏通達離諸惡趣三昧、夫人知諸佛祕密之藏。",
  },
  {
    id: "t0262-007-058",
    category: "方便化導",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "二子如是以方便力善化其父。令心信解。好樂佛法。",
    anchorText: "以方便力善化其父",
    note: "經文明示二子以方便力善化其父，使其信解並好樂佛法。",
  },
  {
    id: "t0262-007-059",
    category: "聞法歡喜",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "爾時彼佛為王說法。示教利喜。王大歡悅。",
    anchorText: "為王說法。示教利喜",
    note: "雲雷音宿王華智佛為王說法、示教利喜，王因此大歡悅。",
  },
  {
    id: "t0262-007-060",
    category: "授記作佛",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "此王於我法中作比丘。精勤修習助佛道法。當得作佛。號娑羅樹王。國名大光。劫名大高王。其娑羅樹王佛。有無量菩薩眾。及無量聲聞。其國平正。功德如是。",
    anchorText: "精勤修習助佛道法。當得作佛",
    note: "佛為妙莊嚴王授記，明說其出家精勤修習助佛道法，當得作佛。",
  },
  {
    id: "t0262-007-061",
    category: "修行得定",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "王出家已。於八萬四千歲。常勤精進。修行妙法華經。過是已後。得一切淨功德莊嚴三昧。",
    anchorText: "常勤精進。修行妙法華經",
    note: "妙莊嚴王出家後長時精進修行《妙法華經》，後得一切淨功德莊嚴三昧。",
  },
  {
    id: "t0262-007-062",
    category: "善知識饒益",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "此我二子已作佛事。以神通變化。轉我邪心。令得安住於佛法中。得見世尊。此二子者。是我善知識。為欲發起宿世善根饒益我故。來生我家。",
    anchorText: "轉我邪心。令得安住於佛法中",
    note: "妙莊嚴王自述二子作佛事，轉其邪心，使安住佛法、得見世尊。",
  },
  {
    id: "t0262-007-063",
    category: "善知識力",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "若善男子善女人。種善根故。世世得善知識。其善知識。能作佛事。示教利喜。令入阿耨多羅三藐三菩提。",
    anchorText: "種善根故。世世得善知識",
    note: "佛明說種善根故世世得善知識，善知識能作佛事、示教利喜，令入無上菩提。",
  },
  {
    id: "t0262-007-064",
    category: "見佛發心",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "大王當知。善知識者。是大因緣。所謂化導令得見佛。發阿耨多羅三藐三菩提心。",
    anchorText: "善知識者。是大因緣",
    note: "佛進一步總結善知識是大因緣，能化導眾生見佛並發無上菩提心。",
  },
  {
    id: "t0262-007-065",
    category: "受持正見",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "此二子已曾供養六十五百千萬億那由他恆河沙諸佛。親近恭敬。於諸佛所。受持法華經。愍念邪見眾生。令住正見。",
    anchorText: "於諸佛所。受持法華經",
    note: "佛明說二子曾供養親近無量諸佛，於諸佛所受持《法華經》，愍念邪見眾生令住正見。",
  },
  {
    id: "t0262-007-066",
    category: "如來法德",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "世尊。未曾有也。如來之法。具足成就不可思議微妙功德。教誡所行。安隱快善。我從今日。不復自隨心行。不生邪見憍慢瞋恚諸惡之心。",
    anchorText: "如來之法。具足成就不可思議微妙功德",
    note: "妙莊嚴王讚歎如來之法具足不可思議微妙功德，並發願不再隨邪惡之心。",
  },
  {
    id: "t0262-007-067",
    category: "應當禮拜",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "是藥王藥上菩薩。成就如此諸大功德。已於無量百千萬億諸佛所。植眾德本。成就不可思議諸善功德。若有人識是二菩薩名字者。一切世間諸天人民。亦應禮拜。",
    anchorText: "成就如此諸大功德",
    note: "佛總結藥王、藥上菩薩成就諸大功德，聞知其名者，諸天人民亦應禮拜。",
  },
  {
    id: "t0262-007-068",
    category: "聞品證法",
    sectionTitle: MIAOZHUANGYAN_SECTION_TITLE,
    text: "佛說是妙莊嚴王本事品時。八萬四千人遠塵離垢。於諸法中。得法眼淨。",
    anchorText: "八萬四千人遠塵離垢",
    note: "本品結尾明說佛說此品時，八萬四千人遠塵離垢，得法眼淨。",
  },
];
