import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const RULAI_SHENLI_SECTION_TITLE = "如來神力品第二十";

export const T0264_JUAN_6_RULAI_SHENLI_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-006-060",
    category: "弘经供养",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "我等於佛滅後，世尊分身所在國土滅度之處，當廣說此經。所以者何？我等亦自欲得是真淨大法，受持、讀誦、解說、書寫而供養之。",
    anchorText: "我等於佛滅後，世尊分身所在國土滅度之處",
    note: "从地踊出诸菩萨发愿于佛灭后广说此经，并以受持、读诵、解说、书写作为供养。",
  },
  {
    id: "t0264-006-061",
    category: "如来神力示现",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "現大神力，出廣長舌，上至梵世，一切毛孔放於無量無數色光，皆悉遍照十方世界。",
    anchorText: "現大神力，出廣長舌，上至梵世",
    note: "佛于大众前现大神力，放无量色光遍照十方，以显此经付嘱之重。",
  },
  {
    id: "t0264-006-062",
    category: "见佛欢喜",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "以佛神力故，皆見此娑婆世界無量無邊百千萬億眾寶樹下師子座上諸佛；及見釋迦牟尼佛共多寶如來在寶塔中坐師子座；又見無量無邊百千萬億菩薩摩訶薩；及諸四眾恭敬圍遶釋迦牟尼佛。既見是已，皆大歡喜得未曾有。",
    anchorText: "以佛神力故，皆見此娑婆世界",
    note: "十方众生因佛神力见娑婆诸佛、多宝如来、诸菩萨与四众围绕，皆大欢喜。",
  },
  {
    id: "t0264-006-063",
    category: "隨喜供養",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "汝等當深心隨喜，亦當禮拜供養釋迦牟尼佛。",
    anchorText: "汝等當深心隨喜，亦當禮拜供養",
    note: "诸天宣告十方众生，应深心随喜此大乘经，并礼拜供养释迦牟尼佛。",
  },
  {
    id: "t0264-006-064",
    category: "十方一佛土",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "以種種華香、瓔珞、幡蓋及諸嚴身之具，珍寶妙物，皆共遙散娑婆世界，所散諸物從十方來，譬如雲集，變成寶帳，遍覆此間諸佛之上；于時十方世界通達無礙，如一佛土。",
    anchorText: "所散諸物從十方來，譬如雲集",
    note: "十方众生遥散供养，供物云集成宝帐；十方世界通达无碍，如一佛土。",
  },
  {
    id: "t0264-006-065",
    category: "经功德不可尽",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "諸佛神力如是，無量無邊不可思議，若我以是神力，於無量無邊百千萬億阿僧祇劫，為囑累故，說此經功德，猶不能盡；",
    anchorText: "為囑累故，說此經功德，猶不能盡",
    note: "佛明示即使用不可思议神力，历无量劫说此经功德，仍不能穷尽。",
  },
  {
    id: "t0264-006-066",
    category: "经中总摄如来法藏",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "以要言之，如來一切所有之法，如來一切自在神力，如來一切祕要之藏，如來一切甚深之事，皆於此經宣示顯說。",
    anchorText: "如來一切所有之法，如來一切自在神力",
    note: "佛以要言总摄：如来所有法、自在神力、秘要之藏、甚深之事，皆于此经宣示显说。",
  },
  {
    id: "t0264-006-067",
    category: "灭后应修",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "是故汝等，於如來滅後，應一心受持、讀誦、解說、書寫、如說修行。",
    anchorText: "於如來滅後，應一心受持、讀誦、解說",
    note: "佛直接劝嘱灭后应一心受持、读诵、解说、书写并如说修行。",
  },
  {
    id: "t0264-006-068",
    category: "经所在处即道场",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "所在國土，若有受持、讀誦、解說、書寫、如說修行，若經卷所住之處，若於園中，若於林中，若於樹下，若於僧坊，若白衣舍，若在殿堂，若山谷、曠野，是中皆應起塔供養。所以者何？當知是處即是道場，諸佛於此得阿耨多羅三藐三菩提，諸佛於此轉于法輪，諸佛於此而般涅槃。",
    anchorText: "當知是處即是道場",
    note: "凡受持修行此经或经卷所在之处，皆应起塔供养；经文明说其处即是道场。",
  },
  {
    id: "t0264-006-069",
    category: "持经令佛欢喜",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "以佛滅度後，能持是經故，諸佛皆歡喜，現無量神力，囑累是經故，讚美受持者，於無量劫中，猶故不能盡。",
    anchorText: "能持是經故，諸佛皆歡喜",
    note: "偈颂说明灭后能持此经，令诸佛欢喜；诸佛赞美受持者，无量劫不能尽。",
  },
  {
    id: "t0264-006-070",
    category: "持经功德无边",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "是人之功德，無邊無有窮，如十方虛空，不可得邊際。",
    anchorText: "是人之功德，無邊無有窮",
    note: "受持此经者功德无边无穷，如十方虚空不可得边际。",
  },
  {
    id: "t0264-006-071",
    category: "持经见佛",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "能持是經者，則為已見我，亦見多寶佛，及諸分身者，又見我今日，教化諸菩薩。",
    anchorText: "能持是經者，則為已見我",
    note: "偈颂赞叹持经者即为已见释迦、多宝、诸分身佛，并见佛教化诸菩萨。",
  },
  {
    id: "t0264-006-072",
    category: "供养诸佛令欢喜",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "能持是經者，令我及分身，滅度多寶佛，一切皆歡喜。十方現在佛，并過去未來，亦見亦供養，亦令得歡喜。",
    anchorText: "能持是經者，令我及分身",
    note: "持经者令释迦、分身、多宝佛皆欢喜，并能见供养三世诸佛、令佛欢喜。",
  },
  {
    id: "t0264-006-073",
    category: "得诸佛秘要法",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "諸佛坐道場，所得祕要法，能持是經者，不久亦當得。",
    anchorText: "諸佛坐道場，所得祕要法",
    note: "诸佛坐道场所得秘要法，能持此经者不久亦当得。",
  },
  {
    id: "t0264-006-074",
    category: "乐说无碍",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "能持是經者，於諸法之義，名字及言辭，樂說無窮盡，如風於空中，一切無障礙。",
    anchorText: "於諸法之義，名字及言辭，樂說無窮盡",
    note: "持经者于诸法义、名字言辞乐说无尽，如风行空，无有障碍。",
  },
  {
    id: "t0264-006-075",
    category: "灭闇住一乘",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "於如來滅後，如佛所說經，因緣及次第，隨義如實說，如日月光明，能除諸幽冥。斯人行世間，能滅眾生闇，教無量菩薩，畢竟住一乘；",
    anchorText: "如日月光明，能除諸幽冥",
    note: "佛灭后如实宣说此经者，如日月光明除暗，能灭众生暗，教无量菩萨毕竟住一乘。",
  },
  {
    id: "t0264-006-076",
    category: "决定佛道",
    sectionTitle: RULAI_SHENLI_SECTION_TITLE,
    text: "是故有智者，聞此功德利，於我滅度後，應受持斯經，是人於佛道，決定無有疑。",
    anchorText: "聞此功德利，於我滅度後，應受持斯經",
    note: "结偈劝有智者闻此功德利益，佛灭后应受持此经，于佛道决定无疑。",
  },
];
