import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const XUPIN_SECTION_TITLE = "序品第一";
const FANGBIAN_SECTION_TITLE = "方便品第二";

export const T0264_JUAN_1_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-001-001",
    category: "菩薩功德",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "菩薩摩訶薩八萬人，皆於阿耨多羅三藐三菩提不退轉，皆得陀羅尼，樂說辯才，轉不退轉法輪。供養無量百千諸佛，於諸佛所，殖眾德本，常為諸佛之所稱歎。以慈修身，善入佛慧。通達大智到於彼岸。名稱普聞無量世界，能度無數百千眾生。",
    anchorText: "菩薩摩訶薩八萬人，皆於阿耨多羅三藐三菩提不退轉",
    note: "序品开列大会菩萨不退、总持、辩才、供佛植德与度众功德。",
  },
  {
    id: "t0264-001-002",
    category: "法會總讚",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "爾時世尊，四眾圍遶，供養、恭敬、尊重、讚歎，為諸菩薩說大乘經，名《無量義教菩薩法佛所護念》。",
    anchorText: "為諸菩薩說大乘經，名《無量義教菩薩法佛所護念》",
    note: "本品以佛为诸菩萨说大乘经、为佛所护念，显出将入法华的庄严因缘。",
  },
  {
    id: "t0264-001-003",
    category: "佛光顯法",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "爾時佛放眉間白毫相光，照東方萬八千世界靡不周遍，下至阿鼻地獄，上至阿迦膩吒天，於此世界，盡見彼土六趣眾生；又見彼土現在諸佛，及聞諸佛所說經法；并見彼諸比丘、比丘尼、優婆塞、優婆夷諸修行得道者；復見諸菩薩摩訶薩，種種因緣、種種信解、種種相貌行菩薩道；復見諸佛般涅槃者；復見諸佛般涅槃後，以佛舍利起七寶塔。",
    anchorText: "爾時佛放眉間白毫相光，照東方萬八千世界靡不周遍",
    note: "佛光普照，使大众见六趣、诸佛说法、修行得道、菩萨行道与起塔供养等法界景象。",
  },
  {
    id: "t0264-001-004",
    category: "經典利益",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "又覩諸佛，聖主師子；演說經典，微妙第一。其聲清淨，出柔軟音；教諸菩薩，無數億萬。梵音深妙，令人樂聞；各於世界，講說正法。種種因緣，以無量喻；照明佛法，開悟眾生。",
    anchorText: "演說經典，微妙第一",
    note: "偈中赞诸佛演说经典微妙第一，以清净柔软音讲说正法、开悟众生。",
  },
  {
    id: "t0264-001-005",
    category: "離苦入道",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "若人遭苦，厭老病死；為說涅槃，盡諸苦際。",
    anchorText: "若人遭苦，厭老病死；為說涅槃，盡諸苦際",
    note: "经文说明诸佛随众生厌老病死之苦，为说涅槃以尽苦际。",
  },
  {
    id: "t0264-001-006",
    category: "隨機說法",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "若人有福，曾供養佛；志求勝法，為說緣覺。若有佛子，修種種行；求無上慧，為說淨道。",
    anchorText: "若人有福，曾供養佛；志求勝法，為說緣覺",
    note: "本品展现诸佛随众生根机，为求胜法者、求无上慧者分别说法。",
  },
  {
    id: "t0264-001-007",
    category: "聞法受持",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "復見菩薩，智深志固，能問諸佛，聞悉受持。又見佛子，定慧具足，以無量喻，為眾講法，欣樂說法，化諸菩薩，破魔兵眾，而擊法鼓。",
    anchorText: "復見菩薩，智深志固，能問諸佛，聞悉受持",
    note: "偈中赞菩萨闻法悉能受持，并以无量譬喻为众讲法、化诸菩萨。",
  },
  {
    id: "t0264-001-008",
    category: "悲願濟苦",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "又見菩薩，處林放光，濟地獄苦，令入佛道。",
    anchorText: "又見菩薩，處林放光，濟地獄苦，令入佛道",
    note: "经文以菩萨放光济拔地狱苦、令入佛道，显示大乘悲愿。",
  },
  {
    id: "t0264-001-009",
    category: "修行勸勉",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "又見具戒，威儀無缺，淨如寶珠，以求佛道。又見佛子，住忍辱力，增上慢人，惡罵捶打，皆悉能忍，以求佛道。",
    anchorText: "又見具戒，威儀無缺，淨如寶珠，以求佛道",
    note: "本品列举持戒清净与忍辱求佛道，作为读者可见的修行方向。",
  },
  {
    id: "t0264-001-010",
    category: "妙慧求道",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "復見菩薩，觀諸法性，無有一相，猶如虛空；又見佛子，心無所著，以此妙慧，求無上道。",
    anchorText: "復見菩薩，觀諸法性，無有一相，猶如虛空",
    note: "经文赞菩萨观诸法性、心无所著，以妙慧求无上道。",
  },
  {
    id: "t0264-001-011",
    category: "將說大法",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "今佛世尊，欲說大法、雨大法雨、吹大法螺、擊大法鼓、演大法義。諸善男子！我於過去諸佛曾見此瑞，放斯光已即說大法。是故當知，今佛現光亦復如是，欲令眾生咸得聞知一切世間難信之法，故現斯瑞。",
    anchorText: "今佛世尊，欲說大法、雨大法雨、吹大法螺",
    note: "文殊判明放光瑞相，是佛欲令众生闻知一切世间难信之法。",
  },
  {
    id: "t0264-001-012",
    category: "正法功德",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "演說正法，初善、中善、後善，其義深遠其語巧妙，純一無雜，具足清白梵行之相。為求聲聞者，說應四諦法，度生、老、病、死，究竟涅槃；為求辟支佛者，說應十二因緣法；為諸菩薩，說應六波羅蜜，令得阿耨多羅三藐三菩提，成一切種智。",
    anchorText: "演說正法，初善、中善、後善，其義深遠其語巧妙",
    note: "经文赞正法初中后善，并说明三乘根机由法得度、乃至成一切种智。",
  },
  {
    id: "t0264-001-013",
    category: "聽法不倦",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "是時日月燈明佛從三昧起，因妙光菩薩說大乘經，名《妙法蓮華教菩薩法佛所護念》，六十小劫不起于座；時會聽者，亦坐一處六十小劫身心不動，聽佛所說謂如食頃。是時眾中，無有一人若身若心而生懈倦。",
    anchorText: "說大乘經，名《妙法蓮華教菩薩法佛所護念》",
    note: "过去佛说《妙法莲华》六十小劫，听众身心不动、不生懈倦，显经法难得可乐。",
  },
  {
    id: "t0264-001-014",
    category: "弘宣法華",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "佛滅度後，妙光菩薩持《妙法蓮華經》，滿八十小劫，為人演說。日月燈明佛八子，皆師妙光，妙光教化，令其堅固阿耨多羅三藐三菩提；是諸王子，供養無量百千萬億佛已，皆成佛道。",
    anchorText: "妙光菩薩持《妙法蓮華經》，滿八十小劫，為人演說",
    note: "本品明说妙光受持并长期演说《妙法莲华经》，教化王子坚固菩提、次第成佛。",
  },
  {
    id: "t0264-001-015",
    category: "聞法除疑",
    sectionTitle: XUPIN_SECTION_TITLE,
    text: "我見燈明佛，本光瑞如此；以是知今佛，欲說《法華經》。今相如本瑞，是諸佛方便；今佛放光明，助發實相義。諸人今當知，合掌一心待；佛當雨法雨，充足求道者。諸求三乘人，若有疑悔者；佛當為除斷，令盡無有餘。",
    anchorText: "以是知今佛，欲說《法華經》",
    note: "结偈劝大众合掌一心待法，佛当雨法雨、充足求道者并断除疑悔。",
  },
  {
    id: "t0264-001-016",
    category: "佛智甚深",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "爾時世尊從三昧安詳而起，告舍利弗：「諸佛智慧甚深無量，其智慧門難解難入，一切聲聞、辟支佛所不能知。所以者何？佛曾親近百千萬億無數諸佛，盡行諸佛無量道法，勇猛精進名稱普聞，成就甚深未曾有法，隨宜所說意趣難解。",
    anchorText: "諸佛智慧甚深無量，其智慧門難解難入",
    note: "本品开示诸佛智慧与智慧门甚深难入，为法华核心义理作铺垫。",
  },
  {
    id: "t0264-001-017",
    category: "方便引導",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "舍利弗！吾從成佛已來，種種因緣種種譬喻，廣演言教無數方便，引導眾生令離諸著。",
    anchorText: "廣演言教無數方便，引導眾生令離諸著",
    note: "佛以种种因缘譬喻和无数方便，引导众生离诸执著。",
  },
  {
    id: "t0264-001-018",
    category: "巧說悅眾",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "如來能種種分別巧說諸法，言辭柔軟悅可眾心。",
    anchorText: "如來能種種分別巧說諸法",
    note: "经文赞如来善巧分别说法，言辞柔软，能令众心欢悦。",
  },
  {
    id: "t0264-001-019",
    category: "諸法實相",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "佛所成就第一希有難解之法，惟佛與佛乃能究盡諸法實相，所謂諸法，如是相、如是性、如是體、如是力、如是作、如是因、如是緣、如是果、如是報、如是本末究竟等。",
    anchorText: "惟佛與佛乃能究盡諸法實相",
    note: "本品明示惟佛与佛能究尽诸法实相，是读者理解法华深义的关键。",
  },
  {
    id: "t0264-001-020",
    category: "聞法生信",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "舍利弗當知！諸佛語無異。於佛所說法，當生大信力，世尊法久後，要當說真實。",
    anchorText: "於佛所說法，當生大信力",
    note: "佛劝于所说法生大信力，并说明久后要说真实。",
  },
  {
    id: "t0264-001-021",
    category: "離著出苦",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "佛以方便力，示以三乘教，眾生處處著，引之令得出。",
    anchorText: "佛以方便力，示以三乘教",
    note: "三乘教为佛方便，用以引导处处执著的众生出离。",
  },
  {
    id: "t0264-001-022",
    category: "妙法難遇",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "如是妙法，諸佛如來時乃說之，如優曇鉢華時一現耳。",
    anchorText: "如是妙法，諸佛如來時乃說之",
    note: "本品以优昙钵华比喻妙法难遇，显出听闻此法的稀有。",
  },
  {
    id: "t0264-001-023",
    category: "開示悟入",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "諸佛世尊，惟以一大事因緣故出現於世。舍利弗！云何名諸佛世尊惟以一大事因緣故出現於世？諸佛世尊，欲令眾生開佛知見使得清淨故，出現於世；欲示眾生佛知見故，出現於世；欲令眾生悟佛知見故，出現於世；欲令眾生入佛知見道故，出現於世。",
    anchorText: "諸佛世尊，惟以一大事因緣故出現於世",
    note: "经文直接说明诸佛出世，是为令众生开、示、悟、入佛知见。",
  },
  {
    id: "t0264-001-024",
    category: "一佛乘",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "如來但以一佛乘故，為眾生說法，無有餘乘若二若三。",
    anchorText: "如來但以一佛乘故，為眾生說法",
    note: "本品明示如来为众生说法，究竟只为一佛乘。",
  },
  {
    id: "t0264-001-025",
    category: "聞法成智",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "過去諸佛，以無量無數方便，種種因緣、譬喻言辭，而為眾生演說諸法，是法皆為一佛乘故，是諸眾生，從諸佛聞法究竟皆得一切種智。",
    anchorText: "從諸佛聞法究竟皆得一切種智",
    note: "经文明说从诸佛闻法的众生，究竟皆得一切种智。",
  },
  {
    id: "t0264-001-026",
    category: "饒益安樂",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "現在十方無量百千萬億佛土中諸佛世尊，多所饒益安樂眾生，是諸佛亦以無量無數方便，種種因緣、譬喻言辭，而為眾生演說諸法，是法皆為一佛乘故，是諸眾生從佛聞法，究竟皆得一切種智。",
    anchorText: "多所饒益安樂眾生",
    note: "诸佛以方便演说诸法，饶益安乐众生，并令闻法者究竟得一切种智。",
  },
  {
    id: "t0264-001-027",
    category: "受持難得",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "佛滅度後，如是等經受持、讀誦、解其義者，是人難得，若遇餘佛，於此法中便得決了。",
    anchorText: "如是等經受持、讀誦、解其義者，是人難得",
    note: "佛灭后能受持、读诵并理解此类经典者难得，遇佛则能于此法决了。",
  },
  {
    id: "t0264-001-028",
    category: "信解受持",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "舍利弗！汝等當一心信解，受持佛語。諸佛如來言無虛妄，無有餘乘，惟一佛乘。",
    anchorText: "汝等當一心信解，受持佛語",
    note: "经文劝一心信解、受持佛语，并确认诸佛言无虚妄。",
  },
  {
    id: "t0264-001-029",
    category: "令眾歡喜",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "佛悉知是已，以諸緣譬喻，言辭方便力，令一切歡喜。",
    anchorText: "以諸緣譬喻，言辭方便力，令一切歡喜",
    note: "佛知众生心行后，以因缘譬喻和方便言辞令众欢喜。",
  },
  {
    id: "t0264-001-030",
    category: "入佛智慧",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "鈍根樂小法，貪著於生死，於諸無量佛，不行深妙道，眾苦所惱亂，為是說涅槃。我設是方便，令得入佛慧。",
    anchorText: "我設是方便，令得入佛慧",
    note: "佛为受苦众生说涅槃为方便，根本目的在令入佛慧。",
  },
  {
    id: "t0264-001-031",
    category: "決說大乘",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "今正是其時，決定說大乘。我此九部法，隨順眾生說，入大乘為本，以故說是經。",
    anchorText: "今正是其時，決定說大乘",
    note: "本品明说时机已至，决定说大乘，并以入大乘为本。",
  },
  {
    id: "t0264-001-032",
    category: "聞偈成佛",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "有佛子心淨，柔軟亦利根，無量諸佛所，而行深妙道，為此諸佛子，說是大乘經。我記如是人，來世成佛道，以深心念佛，修持淨戒故。此等聞得佛，大喜充遍身，佛知彼心行，故為說大乘。聲聞若菩薩，聞我所說法，乃至於一偈，皆成佛無疑。",
    anchorText: "聲聞若菩薩，聞我所說法，乃至於一偈，皆成佛無疑",
    note: "经文明说声闻、菩萨闻佛所说乃至一偈，皆成佛无疑。",
  },
  {
    id: "t0264-001-033",
    category: "一乘真實",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "十方佛土中，惟有一乘法，無二亦無三，除佛方便說，但以假名字，引導於眾生。說佛智慧故，諸佛出於世，惟此一事實，餘二則非真。",
    anchorText: "十方佛土中，惟有一乘法",
    note: "偈中总明十方佛土惟有一乘，以假名方便引导众生。",
  },
  {
    id: "t0264-001-034",
    category: "大乘度眾",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "佛自住大乘，如其所得法。定慧力莊嚴，以此度眾生，自證無上道，大乘平等法。",
    anchorText: "定慧力莊嚴，以此度眾生",
    note: "佛自住大乘，以定慧力庄严的大乘平等法度众生。",
  },
  {
    id: "t0264-001-035",
    category: "佛本誓願",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "舍利弗當知！我本立誓願，欲令一切眾，如我等無異。如我昔所願，今者已滿足，化一切眾生，皆令入佛道。",
    anchorText: "我本立誓願，欲令一切眾，如我等無異",
    note: "佛本愿是令一切众生如佛无异，并化一切众生入佛道。",
  },
  {
    id: "t0264-001-036",
    category: "盡苦作佛",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "是故舍利弗！我為設方便，說諸盡苦道，示之以涅槃。我雖說涅槃，是亦非真滅，諸法從本來，常自寂滅相。佛子行道已，來世得作佛，我有方便力，開示三乘法。",
    anchorText: "說諸盡苦道，示之以涅槃",
    note: "佛以方便示涅槃尽苦，并指出佛子行道后来世得作佛。",
  },
  {
    id: "t0264-001-037",
    category: "一乘化眾",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "是諸世尊等，皆說一乘法，化無量眾生，令入於佛道。",
    anchorText: "皆說一乘法，化無量眾生",
    note: "诸佛皆说一乘法，化无量众生入于佛道。",
  },
  {
    id: "t0264-001-038",
    category: "修福成佛",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "若有眾生類，值諸過去佛，若聞法布施，或持戒忍辱，精進禪智等，種種修福慧，如是諸人等，皆已成佛道。",
    anchorText: "若聞法布施，或持戒忍辱",
    note: "值佛闻法并修布施、持戒、忍辱、精进、禅智等福慧者，皆已成佛道。",
  },
  {
    id: "t0264-001-039",
    category: "供塔成佛",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "諸佛滅度已，供養舍利者，起萬億種塔，金銀及頗梨，車𤦲與馬瑙，玫瑰瑠璃珠，清淨廣嚴飾，莊校於諸塔；或有起石廟，栴檀及沈水，木櫁并餘材，塼瓦泥土等，若於曠野中，積土成佛廟；乃至童子戲，聚沙為佛塔；如是諸人等，皆已成佛道。",
    anchorText: "乃至童子戲，聚沙為佛塔",
    note: "经文说供养舍利、起塔乃至童子戏聚沙为塔，皆已成佛道。",
  },
  {
    id: "t0264-001-040",
    category: "造像成佛",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "若人為佛故，建立諸形像，刻雕成眾相，皆已成佛道。",
    anchorText: "若人為佛故，建立諸形像",
    note: "为佛建立形像、刻雕众相者，皆已成佛道。",
  },
  {
    id: "t0264-001-041",
    category: "供養成佛",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "若人於塔廟，寶像及畫像，以華香幡蓋，敬心而供養，若使人作樂，擊鼓吹角貝，簫笛琴箜篌，琵琶鐃銅鈸，如是眾妙音，盡持以供養，或以歡喜心，歌唄頌佛德，乃至一小音，皆已成佛道。",
    anchorText: "若人於塔廟，寶像及畫像",
    note: "以香花幡盖、音乐歌呗等供养塔庙与佛像，乃至一小音，皆已成佛道。",
  },
  {
    id: "t0264-001-042",
    category: "禮敬成道",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "若人散亂心，乃至以一華；供養於畫像，漸見無數佛。或有人禮拜，或復但合掌，乃至舉一手，或復小低頭，以此供養像，漸見無量佛，自成無上道，廣度無數眾，入無餘涅槃，如薪盡火滅。",
    anchorText: "或有人禮拜，或復但合掌",
    note: "散乱心以一华供像，乃至礼拜、合掌、举手、低头，渐见诸佛，自成无上道。",
  },
  {
    id: "t0264-001-043",
    category: "稱佛聞法",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "若人散亂心，入於塔廟中，一稱南無佛，皆已成佛道；於諸過去佛，現在或滅度，若有聞是法，皆已成佛道。",
    anchorText: "一稱南無佛，皆已成佛道",
    note: "经文说入塔庙一称南无佛，或闻此法者，皆已成佛道。",
  },
  {
    id: "t0264-001-044",
    category: "聞法成佛",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "若有聞法者，無一不成佛。諸佛本誓願，我所行佛道，普欲令眾生，亦同得此道。",
    anchorText: "若有聞法者，無一不成佛",
    note: "偈中明说闻法者无一不成佛，并显诸佛欲令众生同得佛道的本愿。",
  },
  {
    id: "t0264-001-045",
    category: "安隱歡喜",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "我今亦如是，安隱眾生故，以種種法門，宣示於佛道。我以智慧力，知眾生性欲，方便說諸法，皆令得歡喜。",
    anchorText: "安隱眾生故，以種種法門，宣示於佛道",
    note: "佛为安隐众生，以种种法门宣示佛道，方便说法令众欢喜。",
  },
  {
    id: "t0264-001-046",
    category: "聞法除疑",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "菩薩聞是法，疑網皆已除，千二百羅漢，悉亦當作佛。",
    anchorText: "菩薩聞是法，疑網皆已除",
    note: "菩萨闻法疑网皆除，千二百罗汉亦悉当作佛。",
  },
  {
    id: "t0264-001-047",
    category: "聞法難得",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "諸佛興出世，懸遠值遇難，正使出于世，說是法復難。無量無數劫，聞是法亦難，能聽是法者，斯人亦復難。",
    anchorText: "說是法復難。無量無數劫，聞是法亦難",
    note: "本品反复说明诸佛出世、说此法、闻此法、能听此法皆难。",
  },
  {
    id: "t0264-001-048",
    category: "隨喜供養",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "聞法歡喜讚，乃至發一言，則為已供養，一切三世佛。",
    anchorText: "聞法歡喜讚，乃至發一言",
    note: "闻法欢喜赞叹乃至发一言，即为已供养一切三世佛。",
  },
  {
    id: "t0264-001-049",
    category: "廣讚一乘",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "有慚愧清淨，志求佛道者，當為如是等，廣讚一乘道。",
    anchorText: "有慚愧清淨，志求佛道者",
    note: "对有惭愧清净、志求佛道者，应为其广赞一乘道。",
  },
  {
    id: "t0264-001-050",
    category: "自知作佛",
    sectionTitle: FANGBIAN_SECTION_TITLE,
    text: "汝等既已知，諸佛世之師，隨宜方便事，無復諸疑惑，心生大歡喜，自知當作佛。",
    anchorText: "無復諸疑惑，心生大歡喜，自知當作佛",
    note: "了知诸佛随宜方便后，疑惑尽除，心生大欢喜，自知当作佛。",
  },
];
