import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const TANFASHI_SECTION_TITLE = "歎法師品第十八";

export const T0263_JUAN_8_TANFASHI_PART1_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-056",
    category: "六根功德",
    text: "若族姓子、族姓女，受是經典持讀書寫，當得十眼功德之本八百名稱，千二百耳根，千二百鼻根，千二百舌根，千二百身行，千二百意淨，是為無數百千品德，則能嚴淨六根功祚。",
    anchorText: "受是經典持讀書寫，當得十眼功德之本",
    note: "本品总标受持、读诵、书写此经所得六根清净功德。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-057",
    category: "眼根清淨",
    text: "彼人若令眼根清淨，而以肉眼覩諸所有，滿三千大千世界諸味石蜜叢樹，下至無可大地獄中，上至三十三天，一切普見悉能攝取，故曰肉眼。",
    anchorText: "彼人若令眼根清淨",
    note: "受持此经者眼根清净，以肉眼普见三千大千世界乃至上下诸处。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-058",
    category: "知罪福趣",
    text: "若有眾庶生其中者，皆悉見之，咸曉了知罪福所趣。",
    anchorText: "咸曉了知罪福所趣",
    note: "眼根清净的功德还包括见诸众生，并了知罪福所趣。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-059",
    category: "說法無怯",
    text: "其執此經卷，勇猛處眾會，所說不怯弱，旦聽斯名德。",
    anchorText: "其執此經卷，勇猛處眾會",
    note: "偈中赞持经者在大众中勇猛说法，不生怯弱。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-060",
    category: "肉眼普見",
    text: "彼則以肉眼，而從父母生，覩諸佛世界，普見超神仙。",
    anchorText: "彼則以肉眼，而從父母生",
    note: "虽是父母所生肉眼，因持经功德而能普见诸佛世界。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-061",
    category: "耳根功德",
    text: "若族姓子、族姓女，說是經典，若為異類聲聞乘說者，則便逮得千二百耳名稱，聞三千大千世界周匝，下至無可大地獄，上至三十三天，超外神仙。",
    anchorText: "說是經典，若為異類聲聞乘說者",
    note: "为他宣说此经者得千二百耳根功德，能闻三千大千世界诸声。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-062",
    category: "肉耳普聞",
    text: "三千大千世界所有音聲，內外通徹一切清淨，以肉耳根，悉聞眾生所說聲，尚未得天耳而悉普聞，曉了萌類諸聲，亦不思惟觀察，黎庶本末所由。",
    anchorText: "以肉耳根，悉聞眾生所說聲",
    note: "经文明说持经说法者虽未得天耳，却以清净肉耳普闻众生音声。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-063",
    category: "聞聲無著",
    text: "悉聞一切，群萌音響，於諸音聲，亦無所著。處處悉知，他人表裏，其耳清淨，聰徹如是。",
    anchorText: "悉聞一切，群萌音響",
    note: "耳根清净不只是能闻诸声，也能无所染著，并了知他人表里。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-064",
    category: "學經名德",
    text: "於時法師，功德如是，學斯經卷，名稱若茲。",
    anchorText: "學斯經卷，名稱若茲",
    note: "偈末总结学此经卷者，具足如上耳根功德与名称。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-065",
    category: "鼻根清淨",
    text: "若族姓子、族姓女，有持是經卷分別說者，若復諷讀書著竹帛，得八百功德諸根堅固鼻根清淨，以是鼻根，三千大千世界所有諸香，皆得普聞。",
    anchorText: "有持是經卷分別說者",
    note: "持经、分别解说、讽读书写者，得鼻根清净，普闻三千大千世界诸香。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-066",
    category: "聞香不著",
    text: "其法師者於此間住，所去殊遠不到其前，亦不近邊不往就嗅，悉聞彼香不愛不求，亦不思念亦不乍香，而嗅知氣以一心住，在於眾會，悉分別說如是諸香，心亦不著無所慕求。",
    anchorText: "悉聞彼香不愛不求",
    note: "鼻根清净能远闻诸香，并在分别诸香时不爱不求、心无所著。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-067",
    category: "分別眾香",
    text: "其人鼻根，清淨如是，若干種香，所聞甚多。於是世界，一切所有，諸所可生，香香甚好。",
    anchorText: "其人鼻根，清淨如是",
    note: "偈颂赞持经者鼻根清净，能闻并分别世间若干种香。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-068",
    category: "福應所獲",
    text: "復自識知，身所從來，又亦曉了，誼法科律。採覩其人，安隱苦樂，童男力勢，福應所獲。",
    anchorText: "又亦曉了，誼法科律",
    note: "鼻根功德中，经文还说能了知法义科律、安隐苦乐及福报所获。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-069",
    category: "知宿命本末",
    text: "住已不住，皆能曉了，諸所遠近，無不開達。終沒若生，前世宿命，以鼻嗅之，知斯本末。",
    anchorText: "終沒若生，前世宿命",
    note: "偈中说明鼻根清净能了知远近、生死与前世宿命本末。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-070",
    category: "識諸修行",
    text: "其有菩薩，持是經卷，若有比丘，順安住教，常修精進，靜住經行，若已至誠，諷誦解說，其彼菩薩，皆悉知之。",
    anchorText: "其有菩薩，持是經卷",
    note: "鼻根清净者能识知持经菩萨与比丘精进、经行、讽诵、解说等行。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-071",
    category: "覺了法王",
    text: "其有菩薩，意堅禪定，常自娛樂，諷誦講說，復為他人，講演解法。於時菩薩，以香覺了，安住大人，遊所在方，愍哀行慈，分別說法，在其座中，弟子圍遶，以香識了，法王所在。",
    anchorText: "其有菩薩，意堅禪定",
    note: "经文以菩萨、安住大人、法王所在为例，赞鼻根清净能觉了说法之处。",
  },
  {
    sectionTitle: TANFASHI_SECTION_TITLE,
    id: "t0263-008-072",
    category: "自然瑞應",
    text: "菩薩力勢，如是色像，尚未逮得，天人之鼻，自然得是，本之瑞應，諸天之鼻，無有諸漏。",
    anchorText: "尚未逮得，天人之鼻",
    note: "本段结语说明尚未得天人鼻，已自然得此瑞应，显持经功德殊胜。",
  },
];
