import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const WUBAIDIZI_SECTION_TITLE = "五百弟子授記品第八";

export const T0264_JUAN_4_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0264-004-001",
    category: "聞法歡喜",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "爾時富樓那彌多羅尼子，從佛聞是智慧方便隨宜說法，又聞授諸大弟子阿耨多羅三藐三菩提記，復聞宿世因緣之事，復聞諸佛有大自在神通之力，得未曾有心淨踊躍，",
    anchorText: "從佛聞是智慧方便隨宜說法",
    note: "富楼那闻佛智慧方便、授记、宿世因缘与神通力，心得未曾有而清净踊跃。",
    occurrence: 1,
  },
  {
    id: "t0264-004-002",
    category: "方便拔著",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "世尊甚奇特，所為希有，隨順世間若干種性，以方便知見而為說法，拔出眾生處處貪著，",
    anchorText: "隨順世間若干種性，以方便知見",
    note: "经文赞叹世尊随顺众生根性，以方便知见说法，拔出众生种种贪著。",
    occurrence: 1,
  },
  {
    id: "t0264-004-003",
    category: "說法第一",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "我常稱其於說法人中最為第一，亦常歎其種種功德，精勤護持助宣我法，能於四眾示教利喜，具足解釋佛之正法，而大饒益同梵行者，",
    anchorText: "我常稱其於說法人中最為第一",
    note: "佛称富楼那说法人中第一，护持助宣佛法，示教利喜而饶益同修。",
    occurrence: 1,
  },
  {
    id: "t0264-004-004",
    category: "護法利生",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "而富樓那，以斯方便饒益無量百千眾生，又化無量阿僧祇人，令立阿耨多羅三藐三菩提，為淨佛土故，常作佛事教化眾生。",
    anchorText: "以斯方便饒益無量百千眾生",
    note: "富楼那以方便饶益众生，令无量人立无上菩提，并为净佛土常作佛事。",
    occurrence: 1,
  },
  {
    id: "t0264-004-005",
    category: "未來護法",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "亦於未來護持助宣無量無邊諸佛之法，教化饒益無量眾生，令立阿耨多羅三藐三菩提，為淨佛土故，常勤精進教化眾生，漸漸具足菩薩之道，",
    anchorText: "亦於未來護持助宣無量無邊諸佛之法",
    note: "佛记富楼那未来继续护持宣扬诸佛之法，教化饶益众生，渐具菩萨道。",
    occurrence: 1,
  },
  {
    id: "t0264-004-006",
    category: "授記成佛",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "過無量阿僧祇劫，當於此土得阿耨多羅三藐三菩提，號曰法明如來、應供、正遍知、明行足、善逝、世間解、無上士、調御丈夫、天人師、佛、世尊。",
    anchorText: "當於此土得阿耨多羅三藐三菩提",
    note: "佛为富楼那授记，未来在此土成法明如来。",
    occurrence: 1,
  },
  {
    id: "t0264-004-007",
    category: "淨土莊嚴",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "無諸惡道，亦無女人，一切眾生皆以化生，無有婬欲，得大神通，身出光明，飛行自在，志念堅固，精進智慧，普皆金色，三十二相而自莊嚴。",
    anchorText: "無諸惡道，亦無女人",
    note: "法明如来国土清净，众生化生，具神通光明、坚固志念与智慧庄严。",
    occurrence: 1,
  },
  {
    id: "t0264-004-008",
    category: "法喜禪悅",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "其國眾生常以二食，一者、法喜食，二者、禪悅食。",
    anchorText: "其國眾生常以二食",
    note: "法明如来国中众生以法喜、禅悦为食，显示净土受用清净。",
    occurrence: 1,
  },
  {
    id: "t0264-004-009",
    category: "方便度生",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "佛子所行道，善學方便故，不可得思議。知眾樂小法，而畏於大智，是故諸菩薩，作聲聞緣覺，以無數方便，化諸眾生類，自說是聲聞，去佛道甚遠，度脫無量眾，皆悉得成就，雖小欲懈怠，漸當令作佛。",
    anchorText: "佛子所行道，善學方便故",
    note: "偈颂说明菩萨善学方便，能随众生乐小而示现声闻缘觉，渐令作佛。",
    occurrence: 1,
  },
  {
    id: "t0264-004-010",
    category: "宣護佛法",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "今此富樓那，於昔千億佛，勤修所行道，宣護諸佛法，為求無上慧，而於諸佛所，現居弟子上，多聞有智慧。",
    anchorText: "於昔千億佛，勤修所行道",
    note: "偈颂赞富楼那久远勤修，宣护诸佛法，为求无上慧而多闻有智。",
    occurrence: 1,
  },
  {
    id: "t0264-004-011",
    category: "教住大乘",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "所說無所畏，能令眾歡喜，未曾有疲倦，而以助佛事。已度大神通，具四無礙慧，知眾根利鈍，常說清淨法，演暢如是義，教諸千億眾，令住大乘法，而自淨佛土。",
    anchorText: "所說無所畏，能令眾歡喜",
    note: "富楼那说法无畏，令众欢喜，常说清净法，教千亿众住大乘法。",
    occurrence: 1,
  },
  {
    id: "t0264-004-012",
    category: "成就一切智",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "未來亦供養，無量無數佛，護助宣正法，亦自淨佛土。常以諸方便，說法無所畏，度不可計眾，成就一切智。",
    anchorText: "未來亦供養，無量無數佛",
    note: "偈颂重宣富楼那未来供佛护法，以方便无畏说法，度众成就一切智。",
    occurrence: 1,
  },
  {
    id: "t0264-004-013",
    category: "聲聞授記",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "我等歡喜得未曾有，若世尊各見授記如餘大弟子者，不亦快乎？",
    anchorText: "我等歡喜得未曾有",
    note: "千二百阿罗汉闻法后欢喜，希求如诸大弟子一样得佛授记。",
    occurrence: 1,
  },
  {
    id: "t0264-004-014",
    category: "普明授記",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "其五百阿羅漢，漚樓頻螺迦葉、伽耶迦葉、那提迦葉、迦留陀夷、優陀夷、阿㝹樓馱、離波多、劫賓那、薄拘羅、周陀莎伽陀等，皆當得阿耨多羅三藐三菩提，盡同一號，名曰普明。",
    anchorText: "其五百阿羅漢，漚樓頻螺迦葉",
    note: "佛为五百阿罗汉授记，皆当得无上菩提，同号普明。",
    occurrence: 1,
  },
  {
    id: "t0264-004-015",
    category: "普明淨土",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "常放大光明，具足諸神通，名聞遍十方，一切之所敬。常說無上道，故號為普明；其國土清淨，菩薩皆勇猛，咸昇妙樓閣，遊諸十方國，以無上供具，奉獻於諸佛，作是供養已，心懷大歡喜，須臾還本國，有如是神力。",
    anchorText: "常放大光明，具足諸神通",
    note: "偈颂描写普明如来光明、神通、名闻与净土菩萨供佛欢喜。",
    occurrence: 1,
  },
  {
    id: "t0264-004-016",
    category: "轉次授記",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "其五百比丘，次第當作佛，同號曰普明，轉次而授記。",
    anchorText: "其五百比丘，次第當作佛",
    note: "五百比丘次第作佛，同号普明，并转次授记。",
    occurrence: 1,
  },
  {
    id: "t0264-004-017",
    category: "得記歡喜",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "爾時五百阿羅漢，於佛前得授記已，歡喜踊躍，即從座起到於佛前，頭面禮足，悔過自責：",
    anchorText: "於佛前得授記已，歡喜踊躍",
    note: "五百阿罗汉得授记后欢喜踊跃，并在佛前礼足悔责。",
    occurrence: 1,
  },
  {
    id: "t0264-004-018",
    category: "衣珠譬喻",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "我昔欲令汝得安樂，五欲自恣，於某年日月，以無價寶珠繫汝衣裏，今故現在，而汝不知，勤苦憂惱以求自活，甚為癡也。汝今可以此寶，貿易所須，常可如意，無所乏短。",
    anchorText: "以無價寶珠繫汝衣裏",
    note: "衣里宝珠譬喻说明本有大宝而不自知，若能取用则所须如意无乏。",
    occurrence: 1,
  },
  {
    id: "t0264-004-019",
    category: "覺悟佛慧",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "佛亦如是，為菩薩時教化我等，令發一切智心，而尋廢忘不知不覺，既得阿羅漢道，自謂滅度，資生艱難，得少為足，一切智願猶在不失。今者世尊覺悟我等，作如是言：『諸比丘！汝等所得非究竟滅，我久令汝等種佛善根，以方便故示涅槃相，而汝謂為實得滅度。』",
    anchorText: "佛亦如是，為菩薩時教化我等",
    note: "经文以宝珠譬喻回明佛久已教化令发一切智心，小乘涅槃非究竟灭。",
    occurrence: 1,
  },
  {
    id: "t0264-004-020",
    category: "實是菩薩",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "世尊！我今乃知實是菩薩，得授阿耨多羅三藐三菩提記，以是因緣，甚大歡喜得未曾有。",
    anchorText: "我今乃知實是菩薩",
    note: "五百阿罗汉觉知自身实是菩萨，蒙授无上菩提记而大欢喜。",
    occurrence: 1,
  },
  {
    id: "t0264-004-021",
    category: "安隱授記",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "我等聞無上，安隱授記聲，歡喜未曾有，禮無量智佛。",
    anchorText: "我等聞無上，安隱授記聲",
    note: "偈颂以“无上安隐授记声”赞叹闻佛授记所得欢喜。",
    occurrence: 1,
  },
  {
    id: "t0264-004-022",
    category: "非實滅度",
    sectionTitle: WUBAIDIZI_SECTION_TITLE,
    text: "我等亦如是，世尊於長夜，常愍見教化，令種無上願；我等無智故，不覺亦不知，得少涅槃分，自足不求餘。今佛覺悟我，言非實滅度，得佛無上慧，爾乃為真滅；我今從佛聞，授記莊嚴事，及轉次受決，身心遍歡喜。",
    anchorText: "世尊於長夜，常愍見教化",
    note: "偈颂总结佛长夜愍念教化，令种无上愿，并觉悟众人非究竟灭，得佛慧方为真灭。",
    occurrence: 1,
  },
];
